### ISSUE TITLE
Resolve the search bar related issues

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#1007]
We want to eliminate multiple search bars (as on /organization), perhaps with some sort of dropdown that specifies what is to be searched.  Designer effort required.

Closely related is this issue: #283, which may or may not be solved by the time we take up this epic.

**Comment by danmihaila** [comment]
I think this is done via new features already implemented. @cjhendrix pls reopen if you still think it is an issue
