### ISSUE TITLE
css tweak: from dpi in ddpx?

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#1021]
In chrome console i get:

**Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 1.5), only screen and (min-resolution: 144dpi)*

Any chance to forward to a design specialist to look into it and suggest correction?

**Comment by danmihaila** [comment]
@teodorescuserban can you still reproduce it? can you paste here an url or screenshot. Closing it, please reopen if it is still an issue
