### ISSUE TITLE
How can group names and descriptions be translated?

### ISSUE THREAD

**Issue by davidmegginson** [OCHA-DAP/hdx-ckan#12]
Not sure who should get this one.  Does CKAN have built-in support for providing multilingual versions of group names and descriptions (and other user-generated data)?  Need to experiment and find out.

**Comment by danmihaila** [comment]
@davidmegginson I am assigning you this epic as you were the first contributor. If you still think this is issue will be something intereseting for HDX keep it open and maybe we can add some requirements, otherwise lets close it. thanks

**Comment by davidmegginson** [comment]
If I'm the only one driving it, then we should close it, because I don't provide business requirements to the dev team (at least, not outside HXL).  We can reopen the issue if/when it becomes a priority.
