### ISSUE TITLE
datastore / datapusher issue with maps?

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#1234]
I know you're going to like this bug. :)

After a resource is uploaded to datastore, the map feature of the resource makes chrome or firefox  to go 100% cpu and locks out the current chrome tab. See attached screenshot.

Steps to duplicate:
1. Login to stag ckan
2. Choose any airport
3. Make sure the resource is NOT yet uploaded to datastore (if you see the button named "Data API" on top right then it is already in the datastore)
4. check if the map is working correctly (choose lat and long and hit update)
5. now edit the resource
6. go to "Datastore" tab
7. Hit "Upload" button - after a few seconds yo uwill get confirmation that XX entries have been pushed to datastore
8. switch back to view mode
9. see the map lockout (choose lat and long and hit update)

Assigning CJ to verify and reassign.

![preview-100percent](https://cloud.githubusercontent.com/assets/1542984/4210253/c7f261e8-3873-11e4-9f6d-b5610a8f4fb0.png)

**Comment by cjhendrix** [comment]
This doesn't seem to be happening with the latest datastore code.  Closing unless we see the behavior again.
