### ISSUE TITLE
Add padding to the last dataset from the results page

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#1241]
The last result of the results page seems a bit too close to the footer area: 

![screen shot 2014-09-10 at 12 20 52 pm](https://cloud.githubusercontent.com/assets/953118/4221107/ab360968-3906-11e4-9dbb-9edee5f5e618.png)

It would be nice to add some padding there; probably the same amount from in between results: 

![screen shot 2014-09-10 at 12 23 05 pm](https://cloud.githubusercontent.com/assets/953118/4221116/c7034e08-3906-11e4-96ea-135b01bd64a3.png)

**Comment by cjhendrix** [comment]
Fixed (as best I can tell).  Closing.
