### ISSUE TITLE
Consider changing the "Submit Data" button to "Share Data"

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#1290]
"Share data" sounds more inclusive than submit. 

![screen shot 2014-09-18 at 12 38 01 pm](https://cloud.githubusercontent.com/assets/953118/4323632/2f1bbe98-3f52-11e4-8598-7aebc7768e3c.png)

**Comment by cjhendrix** [comment]
This was done.  Closing.
