### ISSUE TITLE
Dataset Create: Validation does not highlight title

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#1295]
To replicate:

1. Start dataset creation
1. Add Country, Source, and Description (leave title blank)
1. Validation error highlights the URL, but not the Title (see screencap below)
1. Fix the URL only and submit (title is still blank)
1. Dataset is created with URL as the Title also.

Validation should highlight title also.  It is *not* necessary to prevent URL being used as title if a user forces this (unless it's easy).  Users can easily edit the title later.

![image](https://cloud.githubusercontent.com/assets/1654485/4335129/c883c4b2-3ff8-11e4-8edf-0600edad4d7d.png)

**Comment by danmihaila** [comment]
not an issue anymore
