### ISSUE TITLE
Search Page>Filters: Improve search so that acronyms can match Org Names

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#1460]
Typing WFP into the search box on the org filter does not match the org "United Nations World Food Programme . . ."  This epic would be to improve our indexing/searching so that multiple names/spellings/acronyms could be created for an org to make it easier to find.   We may want to consider how multiple language versions of the name would work with this as well.   

Once solved, we could expand this to include Topics, Countries, and Tags.

**Comment by danmihaila** [comment]
@cjhendrix I think this issue can be closed. I tried with WFP and it is working good and also with gfsc .
https://data.hdx.rwlabs.org/organization?q=gfsc#headerSearch
I think we can close this one
