### ISSUE TITLE
Icons from profile dropdown are not being shown

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#1475]
When user is in the indicator page the icons from the profile drop-down are not shown.

![screen shot 2014-10-09 at 11 18 04 am](https://cloud.githubusercontent.com/assets/953118/4616589/500e786e-52f5-11e4-98f7-0741fc9c1679.png)

This issue happens like this: 

1. User navigates to an indicator. 
2. User clicks on his profile image / name.
3. No icons are shown, but a white space is there.

**Comment by cjhendrix** [comment]
Fixed.  Closing.
