### ISSUE TITLE
Linking non-ssl images

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#1494]
Linking http resources ends up in not having the green lock icon on ssl encryption status in the browsers, which would induce a false sense of insecurity on our not-so-techincal users.

Please link as much as possible to https, not http!

For example [HERE](https://data.hdx.rwlabs.org/dataset/ebola-west-africa-ebola-treatment-centres-isolation-wards-hospitals-and-transit-centres/related?__no_cache__=True#), where the image has been linked from [http://docs.hdx.rwlabs.org/...](http://docs.hdx.rwlabs.org/wp-content/uploads/Screen-Shot-2014-10-14-at-9.04.31-AM.png) instead of [https://docs.hdx.rwlabs.org/...](https://docs.hdx.rwlabs.org/wp-content/uploads/Screen-Shot-2014-10-14-at-9.04.31-AM.png)

Assigning to @luiscape just because he did some work on that dataset (please edit the first link above and change http in https for the image).

**Comment by cjhendrix** [comment]
Can this be closed?

**Comment by luiscape** [comment]
Yes, I think so. All images on gallery items that come from HDX should be https.
