### ISSUE TITLE
The CSV preview is broken when the CSV file contains special characters

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#1531]
The original CSV file [is located here](http://test-data.hdx.rwlabs.org/storage/f/2014-10-20T15%3A58%3A23.560Z/testcsvaaaeno.csv). The picture below shows how it is rendered in the preview

![broken preview with special characters](https://cloud.githubusercontent.com/assets/6885303/4708828/ccc713de-589a-11e4-9b5d-4c5f052b08ea.png)

**Comment by cjhendrix** [comment]
archiving this as it will be solved by current work on improving the datapusher (which allows us to not use  dataproxy (at least for user uploaded files).
