### ISSUE TITLE
Large files not uploaded to CKAN

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#1548]
Updated by CJ with actions to close this issue:
* Set file size limit to 100mb
* Provide clear feedback to user when the limit has been exceeded (perhaps one of the standard bootstrap/ckan error messages)
* Edit the resource create template to indicate the file size limitation:
![image](https://cloud.githubusercontent.com/assets/1654485/5438649/2c7ce320-847a-11e4-8ee0-1bbebf1059c3.png)

------------------------------------------
Original issue text follows:

During the past few days I have been trying to upload a large file to CKAN unsuccessfully. The following error appears on the page:

![screen shot 2014-10-21 at 11 01 20 am](https://cloud.githubusercontent.com/assets/953118/4720733/2a2bfaa6-5933-11e4-829c-e6d6fc95f2d4.png)

And the console registers 2 errors: 

```console
Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://data.hdx.rwlabs.org/storage/upload_handle
Failed to load resource: the server responded with a status of 404 (Not Found) https://data.hdx.rwlabs.org/api/storage/metadata/2014-10-21T14:40:22.904Z/140812-uariv-rni-consulta-edades.csv
```

The file has about 500mb. It is an important dataset from our colleagues in Colombia. We could make enough transformations to make the file smaller, but it would be nice to be able to upload that file as is to CKAN.

The file is available [here](http://ec2-54-86-59-119.compute-1.amazonaws.com/owncloud/public.php?service=files&t=5ee0d0c8ec0952a67c13c6b01a974da2&download).

**Comment by cjhendrix** [comment]
Based on discussions on 6-Jan-2015, we will not implement a file size limit for the time being.  No changes needed.   Closing.
