### ISSUE TITLE
Make terminology for files/resources consistent

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#1575]
The edit interface still uses the resource terminology. 

As per discussion in the FAQ gdoc with ST 27-jul-2015, we should standardize on "resource".  Tagging @amcguire62

**Comment by danmihaila** [comment]
dataset page, create/edit . Replace file/s -> resource/s

**Comment by danmihaila** [comment]
I guess this was a bit unclear. We need to use resource everywhere and not files.
So replace all the occurrences of "file"/"files" with "resouce"/"resources"
Moving this to next sprint and ping @mbellotti

**Comment by mbellotti** [comment]
Wait what? I'm sorry I don't understand. We were using resources
everywhere, the only places the word files were used is instructions when
uploading actual files. Changing that would be unnecessary confusing.
