### ISSUE TITLE
Dataset Create Epic: no way to cancel out of adding a second resource without losing new dataset

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#1585]
To replicate:

1. Make a new dataset
1. Add a resource
1. Click "Save and Add Another"
1. Decide you don't need another and try to find the dataset.
1. Dataset appears not to have been saved.

**Comment by danmihaila** [comment]
closing this one as no longer true for our new contribute flow. ping @cjhendrix to be aware
