### ISSUE TITLE
Markdown formatting of tables tags is not fully honoured in dataset description

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#1597]
Tables defined using markdown are not being shown as tables in the dataset.

See https://test-data.hdx.rwlabs.org/dataset/number-of-sands-on-the-beach-aaaeno on staging for an example.

**Comment by danmihaila** [comment]
@takavarasha do you still needs tables?

**Comment by takavarasha** [comment]
This was after a user tried to use the markdown formatting instructions to do tables. I guess we can say in the instructions that tables are not supported.
