### ISSUE TITLE
Changing nose test configuration ini file ( like we did with common-config-ini.txt )

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#1624]
There's a potential for simplifying this like we did with common-congif-ini.txt, we could have a common config that is the same for all developers & servers and just have the environment specifc information needed for running nose tests in hdx-core-test.ini

**Comment by danmihaila** [comment]
@alexandru-m-g i think we can close this one. pls reopen if it is still an issue
