### ISSUE TITLE
Search Results:  searching 'OCHA Kenya' doesn't bring the org page in the feature results

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#1632]

**Comment by danmihaila** [comment]
I am closing this one. OCHA Kenya doesn't exist. If I search for 
OCHA Liberia it is working good
https://data.hdx.rwlabs.org/search?q=+OCHA+Liberia+
<img width="1440" alt="screen shot 2016-04-26 at 14 40 00" src="https://cloud.githubusercontent.com/assets/3865844/14817010/d992d162-0bbc-11e6-9fd4-c7f1bc86f78d.png">

**Comment by danmihaila** [comment]
OCHA Kenya doesn't exist anymore. If I search https://data.hdx.rwlabs.org/search?q=+OCHA+Liberia+ it is working ok
<img width="1440" alt="screen shot 2016-04-26 at 14 40 00" src="https://cloud.githubusercontent.com/assets/3865844/14817059/1aa4866e-0bbd-11e6-9771-fb3605c52437.png">

**Comment by danmihaila** [comment]
<img width="1440" alt="screen shot 2016-04-26 at 14 40 00" src="https://cloud.githubusercontent.com/assets/3865844/14817076/3e844bbe-0bbd-11e6-87c2-a7af40b886d7.png">
