### ISSUE TITLE
Dataset Edit:  Clicking "X" on the success message does not remove the message

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#1653]
![image](https://cloud.githubusercontent.com/assets/1654485/4880838/fb7142d0-6340-11e4-8153-3314b3ea854c.png)

**Comment by mbellotti** [comment]
Have we confirmed this error still exists? So far I have not been able to reproduce it and it's quite old at this point :/

**Comment by cjhendrix** [comment]
I tried to reproduce and couldn't.  Magic fix.  :)  Closing.  Score +1 for HDX.

Unfortunately, I found a new one while testing (#2922). Score +1 for the forces of chaos.  :p
