### ISSUE TITLE
Change dataset names for indicators so they include the source code

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#1771]
1.  Create a script that goes through all existing indicators on CKAN and modifies the dataset's name ( it's the part that also shoes in the URL ) to include the source code
1.  The name will have the following format: [Transformed Indicator Title]___[Source code] 
  *  [Transformed Indicator Title] - remains the same as it is now. It's the indicator title as specified in CPS, transformed to lower case and with spaces translated to "_". We need to make sure all characters are url-encoded.
  *  Separator is: 3 underscores
  *  [Source code] - the source code from CPS
  *  Example: `https://data.hdx.rwlabs.org/dataset/proportion_of_the_population_using_improved_sanitation_facilities___mdgs`
1.  Since the urls of the indicators will be modified we need to talk to @teodorescuserban  and provide him with a mapping of old URLs to the new modified ones

**Comment by alexandru-m-g** [comment]
@cjhendrix @danmihaila 
Nothing for me to do here. Should be done automatically from CPS.

**Comment by danmihaila** [comment]
@alexandru-m-g @cjhendrix - who will do these changes and when?

**Comment by alexandru-m-g** [comment]
As I said, the changes will be done automatically from CPS once the CPS push is enabled.

**Comment by alexandru-m-g** [comment]
@cjhendrix @danmihaila I'm closing this as no longer necessary.
