### ISSUE TITLE
Update ckan, nose test and other scripts to work in docker containers

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#1838]
Scripts for:
 - ckan
 - nose tests
 - cps
  
This is related to https://github.com/OCHA-DAP/hdx-infrastructure/issues/111

**Comment by teodorescuserban** [comment]
only restore left.
but behold, there i saw a bunch of user input dialog lines!!! :(

**Comment by teodorescuserban** [comment]
Will be done today.

**Comment by teodorescuserban** [comment]
Done.
