### ISSUE TITLE
Delete outdated files

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#1873]
This is based on the following issue: https://github.com/OCHA-DAP/hdx-ckan/issues/1721 . 

@danmihaila do we want to make this happen out of CKAN or is this meant as a bash script ?

Right now, both perma links and old type of links still work even after a resource is marked as deleted. This will stop working once we implement this ticket. So we need to have requirements for both.

**Comment by teodorescuserban** [comment]
Please help me clean the filestore! :)
2.4GB that need to be archived hourly.

**Comment by teodorescuserban** [comment]
bumping this issue.
I need to clean the old filestore.
As per discussed with @cjhendrix @amcguire62 and @danmihaila target is 2 weeks from July 30, so let's make it Aug 15.

Changing priority to High.

@danmihaila, @cjhendrix please assign a new milestone.
Thank you

**Comment by danmihaila** [comment]
I don't think we still have an issue with the new CKAN
