### ISSUE TITLE
Docker development environment

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#1876]
Having a developer try to setup a development environment based on docker that's can use the same containers as the ones from the server environment

**Comment by teodorescuserban** [comment]
Any update on that?

**Comment by alexandru-m-g** [comment]
Here is the documentation: https://drive.google.com/folderview?id=0B2Cgmf3EurKoam5MUGJVczBidkk&usp=sharing

**Comment by danmihaila** [comment]
@alexandru-m-g @cjhendrix can we consider this issue completed?

**Comment by danmihaila** [comment]
I am closing it, please reopen and move to 46 if it is the case
