### ISSUE TITLE
Graphic in Colombia page: instead of line (time-series) make it a bar graph.

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#1936]
CJ added current action for this issue:
* Change "Number of IDPs" graph **from** bar graph **to** line graph. 

-----------------Original issue text follows---------------------
I think the graph **Number of people with access constrains** would look better if it was a bar graph instead of a line, time-series: 

![screen shot 2014-12-10 at 12 50 45 pm](https://cloud.githubusercontent.com/assets/953118/5381033/61da09f2-806b-11e4-8cba-532c10734cc7.png)

The reason I think that is that the lines give the impression the indicator changes significantly every month, but in a continuum of time. Bar graphs will help the user compare months as nearly independent measurements, which is influences better consumption of the data in my opinion. 

I chatted with the Data Team about this (including @JavierTeran) and they've approved this suggestion.

**Comment by cjhendrix** [comment]
Still lines on stag. Reopening.
