### ISSUE TITLE
Login page: change spacing on left panel 

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#1981]
The spacing in the left panel is odd.  Change to something like the below: 

![image](https://cloud.githubusercontent.com/assets/1654485/5451121/6d3fa152-850d-11e4-87dd-4485c2f767da.png)

Note, this will stay in backlog for now as we may want to revise this page to align with the Frog design.

**Comment by danmihaila** [comment]
@cjhendrix - should I also change the registration page? check screenshot
![screen shot 2015-01-08 at 16 23 13](https://cloud.githubusercontent.com/assets/3865844/5663699/c9274f90-9752-11e4-90bb-23d16d0eb1a0.png)

**Comment by cjhendrix** [comment]
That one is not as confusing, but yes, why not make them consistent while we are at it.  In the case of registration, I'd just remove the dashed line completely.
