### ISSUE TITLE
Organization List, Member List, Dataset List: sort order is case sensitive

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#1983]
Make it case insensitive.  We did that in the search results a long time ago, but it seems to have come back.  We should probably also do this for the /group as well, even though there aren't any lowercase titles in there yet.

Example: INNAGO is out of order
![image](https://cloud.githubusercontent.com/assets/1654485/5452381/7fee183a-851a-11e4-9d2b-6691e6d0ffd1.png)

**Comment by alexandru-m-g** [comment]
Following page with lists need to be checked:

- [ ] Dataset/Serach lists
- [ ] Member list
- [ ] Organization list
- [ ] Organization list in browse
- [ ] List of datasets when click on a country

**Comment by alexandru-m-g** [comment]
@cjhendrix I was checking the members list ( like this one https://data.hdx.rwlabs.org/organization/members/wfp  ) and to me they seem to be well sorted. Could you please confirm, thanks.

**Comment by cjhendrix** [comment]
Agreed, this looks like it's working well.  I wonder why?  Maybe it isn't in solr?

**Comment by alexandru-m-g** [comment]
It isn't using solr. But neither were the organization pages and those were not working either.
