### ISSUE TITLE
Disable markdown in user profile "About" section

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#1986]
It doesn't display well, and links are not allowed.

![image](https://cloud.githubusercontent.com/assets/1654485/5453246/7b2e3482-8525-11e4-92eb-e09acc140129.png)

**Comment by cjhendrix** [comment]
We also want to remove this from the user profile edit page.  I'll reopen and move to sprint 47.

**Comment by danmihaila** [comment]
@cjhendrix - so, we will remove description for users from create/edit user profile and from displaying it, right?

**Comment by cjhendrix** [comment]
Just remove the "markdown" label so that users won't expect their markdown to render.
