### ISSUE TITLE
"Show more" for dataset description texts adds a weird line break.

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#1990]
When clicking on the `more` button on a dataset description some extra text loads on the page. When the text finishes loading, there is a weird line break introduced to the paragraph. Here are a few screenshots directly from the [Colombia page](https://data.hdx.rwlabs.org/group/col). 

**Before:**
![screen shot 2014-12-16 at 11 32 56 am](https://cloud.githubusercontent.com/assets/953118/5457292/78de448c-8517-11e4-924f-fffd730b5f2b.png)

**After:**
![screen shot 2014-12-16 at 11 34 44 am](https://cloud.githubusercontent.com/assets/953118/5457307/8def7ee0-8517-11e4-9f68-eb898caa1528.png)

**Comment by aalecs** [comment]
Changed plugin so it works in "block mode" all of the time. It won't split the text no more.
I think that a test is costly and if we follow the way to use the plugin now, we shouldn't have any more problems.
