### ISSUE TITLE
Browse Page: topics

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2000]
Based on https://docs.google.com/drawings/d/1hC8IA45gg-nAA5SeAx3YBrmJXrdeV02vKRoWstZ7RMs/edit
Implement the topics section
blocked by #1997 and #1998

**Comment by aalecs** [comment]
Waiting to clear things with the Humanitarian Icons font pack used...

**Comment by aalecs** [comment]
All good, closing issue.
