### ISSUE TITLE
Filestore: size on disk

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2028]
It will be interesting to have an idea how filestore size changed over time.

**Comment by teodorescuserban** [comment]
2.4GB size on disk.

**Comment by teodorescuserban** [comment]
Not sure how do you want me to proceed? Make a way to update us every few hours? Daily?

**Comment by teodorescuserban** [comment]
According to what I talked with @cjhendrix , I will make a munin addon to monitor the filestore size.

**Comment by teodorescuserban** [comment]
now it's 2.5GB (still need a lil time to write that plugin)

**Comment by teodorescuserban** [comment]
2.6GB now.

**Comment by teodorescuserban** [comment]
Jun 25: 5.6GB uncompressed, 4.2GB archive.

tagging @cjhendrix, @amcguire62 and @danmihaila

**Comment by teodorescuserban** [comment]
Bumping this one.
3.2GB on the new filestore.
6.2GB on the old filestore.
