### ISSUE TITLE
User deletion

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2029]
Investigate deletion of users to support reusing the same username/email after deletion.

Original Text:
We need to be able to delete users. There is an API action for this,  `ckan.logic.action.delete.user_delete(context, data_dict)`, so it should be possible. 

Some items to investigate/do:

1. What happens to a dataset/gallery item created by a user when the user is deleted?  I tested this a long time ago and the dataset persisted, but we should confirm how this is working before doing the items below.
1. Add a delete button (for sysadmins only) on each user listed at /user
1. Add a "Delete Account" button on the users setting page 
1. There are some users in the ckan `users` table that have been deleted using ckan-user-delete.sh.  They are no longer visible at /user, but the username still exists and can't be reused.  How can we safely remove those?  On prod, username `joebloggs` is an example.

**Comment by teodorescuserban** [comment]
FYI: paster command to delete user is not working either... it just mark the user as "Deleted" but there's no Trash for users...

**Comment by danmihaila** [comment]
I will write down what I found digging a bit into CKAN documentation and playing with UI, API and paster commands.
1. I tried to delete an user via user interface as sysadmin, via api and via paster command. All the actions had the same result: marking the user as deleted in "user" table and no other actions. When user is deleted, it will not appear in list of users or members, but you can still view its profile (by accessing the url direct). There is no way of "reactivating" the user(at least I didn't find it), but to edit via UI (access direct the url /user/edit/...) and click on update profile button which will mark the user as active.
2. I searched in documentation for a purge option, but I couldn't find anything. We could address this question also on ckan-dev mailing list ( I can do it if it is ok) to ask if there is a "hidden" way to remove an user.
On the other hand, I am not sure we should remove for ever an user. If we remove it for ever, we should also remove everything that is related to its activity and his actions which are recorded and linked to other ckan tables. I don't think it is ok to do it.
We could think of another solution to allow other users to use that email address and username. For example CKAN is using the following strategy when deleting a group:
- it will rename the name by adding a text "DO NOT USE" (or something similar) to the name of the group. We could alter the username and/or email by adding something like admin@hdx.org => admin-DELETED@hdx.org
- another ideea is to use the user id when displaying information about a deleted user. For example if the user has no username and/or email (fields are empty) the information/links that are generated should display the id of that user . It is a common practice in other systems.
Tagging @cjhendrix
