### ISSUE TITLE
Invite user: improve error message if email exists

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2030]
Improve formatting and change text to "That login email address is already in use by user [username]. Please try adding that username to your organization."

I'm guessing that may require a whole new user create function.  If so, we can keep it simple by just changing the error message universally (from invite user or from /user/register) to say "That login email is already in use."

![image](https://cloud.githubusercontent.com/assets/1654485/5548400/4b153740-8b70-11e4-9330-a417c9a600bf.png)

**Comment by mbellotti** [comment]
I've gone one better on this. We'll now check to see if the email belongs to an account already and if it does we add that account as a member.

**Comment by cjhendrix** [comment]
Nice!
