### ISSUE TITLE
Date missing from some datasets (where source = WHO?)

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2033]
So far, it seems to be only affecting indicators from WHO, and all of those.

Examples: 
https://data.hdx.rwlabs.org/dataset/total_number_of_reported_cases_of_cholera
https://data.hdx.rwlabs.org/dataset/total_number_of_suspected_meningitis_deaths_reported

![image](https://cloud.githubusercontent.com/assets/1654485/5568955/358905dc-8f67-11e4-96ff-2cb9aa87fed2.png)

**Comment by danmihaila** [comment]
I checked in CKAN db and there is no date. If I edit, add a date all is good. So, probably a CPS issue.
@alexandru-m-g any thoughts about this?

**Comment by danmihaila** [comment]
This is not a problem related to CKAN db or displaying. The date is missing from db.
We checked the CPS and it has the metadata, we just need a way to push it to HDX CKAN and wait until this issue https://github.com/OCHA-DAP/DAP-System/issues/298 to be completed

**Comment by danmihaila** [comment]
@cjhendrix still an issue?

**Comment by cjhendrix** [comment]
nope. closing.
