### ISSUE TITLE
ckan error emails do not get sent

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#2045]
We have 2 categories of emails that are generated by ckan:

1. user / org related emails (reset password, request new org, etc) - this work ok
1. critical errors+ exceptions from ckan - this fails.

There seem to be a different way to handle those 2 categories in ckan, while the first category is really using the ```smtp.server``` parameter from config .ini file, the second one doesn't care about it and tries to connect to localhost

Quick fix (but ugly): enable another service that will do smtp proxy from container's localhost to the docker host port 25.

**Comment by alexandru-m-g** [comment]
@teodorescuserban after debugging a bit it seems you can put the following parameters in the .ini file for (2):

 *  smtp_server
 *  smtp_username
 *  smtp_password
 *  smtp_use_tls

I think this parameters were introduced by the pylons framework while the other ones ( used in (1) ) were introduced by CKAN.

Please let me know if it works.

**Comment by teodorescuserban** [comment]
I only need smtp_server :)
Thanks, will try and comment here.

**Comment by teodorescuserban** [comment]
:+1: it is working.
imho it looks a bit retarded to have both ```smtp_server``` and ```smtp.server``` in config :)
@alexandru-m-g please make sure you include both of them in common-config-ini.txt
I **will** overwrite it for the containers on prod, stag and maybe dev but helps to have them in there.
Ideally the prod.ini would only have options that overwrite the ones already existing in common-config-ini.txt (just to keep prod.ini as small as possible in all circumstances).

thank you again, @alexandru-m-g , for figuring this one out.
