### ISSUE TITLE
Browse: Map - 

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2047]
Click on Romania from map ( :)  ) - it will redirect to https://dev-data.hdx.rwlabs.org/group/rou which is wrong. it should go to https://dev-data.hdx.rwlabs.org/group/rom
Pinging @aalecs   to comment  tech and to propose how to fix it and and @cjhendrix to be aware of this

**Comment by aalecs** [comment]
The problem is in the metadata we're using with the implementation received from frog. Seems that the ISO3 code for Romania is wrong and others might be affected. 
I'll check this and get back to you.

**Comment by aalecs** [comment]
@danmihaila @cjhendrix I checked all the codes and they are correct on the metadata side. Seems ROU is the correct ISO3 code for Romania (http://en.wikipedia.org/wiki/ISO_3166-1_alpha-3). CJ can you confirm?

**Comment by danmihaila** [comment]
ok. where do we have ROM? in CPS? I think we should try to check&match all our codes

**Comment by aalecs** [comment]
Yeah I think it's in CPS and as a group in CKAN. Quick fix would be to change it in the js metadata so we don't have a non-working redirect.

**Comment by cjhendrix** [comment]
Yes, it should be ROU.

**Comment by danmihaila** [comment]
@cjhendrix - what about the other codes? should we try to check every group/country pair code-name we have?

**Comment by cjhendrix** [comment]
Wouldn't hurt to make a comparison and be sure everything matches ISO 3166-3

**Comment by aalecs** [comment]
I kind of did by checking the countries for which I didn't have any information about the number of indicators/datasets. And "Romania" was the only one with the wrong code. For the rest I assumed that if it found the info, then the code is correct.

**Comment by cjhendrix** [comment]
That sounds like a reasonable test.  We wouldn't know if both the map and HDX had the wrong code, but we probably don't care that much if that's the case.

**Comment by danmihaila** [comment]
it was a bit interesting that yesterday the first country i checked (Romania - i wonder why) had this error. anyway, I will close this issue if @aalecs confirms the code is ok.

**Comment by aalecs** [comment]
So for the code "ROM" are we changing it in HDX? Or should I patch the metadata?

**Comment by cjhendrix** [comment]
All our codes should be ISO 3, so ROU everywhere!

**Comment by danmihaila** [comment]
I am not sure, but maybe we should change CKAN db for group code and probably CPS. 
@aalecs - can you please provide a list of changes? and if you are to busy we can assign this one to someone else

**Comment by cjhendrix** [comment]
It is already ROU in CPS.

**Comment by aalecs** [comment]
I meant the CKAN group, as you can see it's still ROM: http://data.hdx.rwlabs.org/group/rom

**Comment by cjhendrix** [comment]
Yes, we need to change it there, just to be consistent (both in our URLs, but also for anyone using our API).  I'm not worried about permalinks or redirecting.  Just don't want to break any of our own systems.

**Comment by danmihaila** [comment]
I used the interface on dev server to change "rom" to "rou" and now I see that we can access both urls:
https://dev-data.hdx.rwlabs.org/group/rou and https://dev-data.hdx.rwlabs.org/group/rom
Any thoughts?
@cjhendrix @aalecs

**Comment by cjhendrix** [comment]
And neither of them show up at /group

https://dev-data.hdx.rwlabs.org/group?page=9

**Comment by danmihaila** [comment]
so, what I did on dev:
1. edit group/rom to have the url /group/rou. At that moment I had two urls /rom and /rou which displayed the same information and number of datasets. I didn't check /group
2. I edited /rom and deleted it.
3. I checked /rou and I noticed that the group is empty - no datasets, no description.
I assume the UI is not working very well. We might want to patch db. 
So, my conclusion is to assign this issue to a dev which is a bit not loaded to find an easy solution how to migrate from /rom to /rou
@cjhendrix sounds good?

**Comment by cjhendrix** [comment]
Sounds good.  Thanks.

**Comment by teodorescuserban** [comment]
offtopic, 0 data for romania. :)

**Comment by teodorescuserban** [comment]
cps has nothing for ROM, it just displayes an empty response.
it does have something for ROU.
So I guess there was just a miss on ckan side when creating datasets.
We can create manually a ROU dataset  and corresponding resources, I guess.
No db patching required - just data team work.
IMHO.

**Comment by aalecs** [comment]
Did the check on my local machine:
    1. renamed url from /group/rom to /group/rou, by using the interface. And both URLs are working now. And showing the correct data. But if you clicked edit on "/group/rom" you'll see that the url field has "/group/rou"
    2. so I used the api and queried both group id's "rom" and "rou" and I've seen the same information, so it's the same entry, with name="rou" and group_id="rom". 

Can we just edit the url then?

**Comment by cjhendrix** [comment]
It seems a little freaky, but if we can't think of any other way this would cause a problem, I'm ok to leave it for now.  But I wonder what db this continues to live in?

**Comment by teodorescuserban** [comment]
I propose data team creates a new group from scratch.
Copy all resources in there. 
Remove the old group afterwards.

**Comment by danmihaila** [comment]
assigning it to CJ as he did the changes on prod and probably we will close it

**Comment by cjhendrix** [comment]
Done for Romania and East Timor.

**Comment by cjhendrix** [comment]
Reopening pending resolution of #2127.
