### ISSUE TITLE
Download counter:  confirm behavior

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2056]
From my testing, it seems that the download counter is not quite working as we expect.

Can you please verify:
- [x] Are downloads being counted as expected (cj confirmed that they are not, see comment below)
- [x] This dataset has reset to 0 downloads; but in the activity stream I don't see any new files being added.  Perhaps pushing to datastore resets the downloads?  Or even just updating the resource? https://data.hdx.rwlabs.org/dataset/ebola-cases-2014  (cj confirmed that updating the resource updates the count)
- [x] what is the limit on counted downloads from the same user/ip over a given period of time (seems like I remember something about it being one download per resource per user per day)
- [x] are downloads on private datasets counted (cj confirmed that they are counted)

**Comment by cjhendrix** [comment]
I just did some more testing on this.  Replacing the files (uploading a file onto a new resource) resets the counter to 0. 

Here were my steps: 
1. This resource had 5 downloads: https://test-data.hdx.rwlabs.org/dataset/a-private-dataset-for-access-testing
1. I replaced both files with new files (same resources, just uploading new files).  It shouldn't matter, but note that they were completely different files: new filename, different content.
1. Download counter is now 0

**Comment by danmihaila** [comment]
fixed in #2139 . lets check if they are ok.

**Comment by aalecs** [comment]
I tested it out and:
    - downloading resources updates the counter
    - for a resource stored in the FileStore, uploading newer versions doesn't reset the individual resource's counter => number of downloads stays the same
    - changing the url of an external resource or a FileStore resource to an external one will reset the individual's resource counter and affect the global counter inside the dataset

**Comment by cjhendrix** [comment]
Both the data team and I have seen that uploading a new file to an existing resource updates the counter. Maybe you were seeing something in the cache?
