### ISSUE TITLE
Browse page : small tweaks

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2057]
1. Map section: when mouse over Map| Alphabetically A-Z it will display a bigger font
2. Links to be added for Learn more about Humanitarian Exchange Language and Common Hummanitarian Dataset. 
3. Question: should we make the red bar fixed and the content below to be scrolled? I will give a try to this. @cjhendrix  ?
4. Proper case on the Topics.
5. Change Gender Icon to this one: http://img.static.reliefweb.int/sites/reliefweb.int/files/styles/large_icon-130x130/public/topics-icon-gender.png?itok=zPEGYWjS .  I see that it is png, which may cause a problem.  We can discuss.

**Comment by cjhendrix** [comment]
Note:  I added number 4 above.

On number 3, Yes, I think it is worth a try if it's only an hour or 2 of work.   It would look really nice.

**Comment by danmihaila** [comment]
pinging @aalecs

**Comment by aalecs** [comment]
@cjhendrix for number 5: I checked the humanitarian icons set and couldn't find it. So, we can use a png ... but it will be a special case, since the rest are nicely implemented as a font and are added to the page through a css class. We don't have a SVG for it, right?

**Comment by cjhendrix** [comment]
No, we don't.  And we will probably replace it in the future with something better.  So special case is ok for now.

**Comment by aalecs** [comment]
@cjhendrix: question for step2: 
  -  I used "http://docs.hdx.rwlabs.org/hxl/" for HXL link
  -  what link do we put for "Common Hummanitarian Dataset"

**Comment by cjhendrix** [comment]
I think that's covered in the stuff I just added to #2063.  Let me know if not.
