### ISSUE TITLE
Browse page map - change to ReliefWeb MapBox provider

### ISSUE THREAD

**Issue by aalecs** [OCHA-DAP/hdx-ckan#2058]
Current ReliefWeb MapBox provider has no country names at the zoom level that we need. 
We're currently using the provider given by Frog, but that one might be limited on the MapBox free plan and might be easily exceeded.

**Comment by danmihaila** [comment]
pinging @luiscape  as we need a feedback from him

**Comment by cjhendrix** [comment]
Just FYI, this is not a blocker for sprint 46 deploy on 21-Jan.   But it is an improvement that we may want to make.

**Comment by luiscape** [comment]
Hi there folks. We're on it on the Data Team end. @DitaA is the focal-point.

**Comment by cjhendrix** [comment]
I'm going to close this one.  We'll make a new one if any action is needed on the dev side.
