### ISSUE TITLE
Browse: Changes to header text

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2063]
- [x] @ochadataproject to provide new text for first two paragraphs
- [x] remove "watch demo"
- [x] move "show me a cool visualization to left align with the paragraphs above
- [x] link "show me a cool visualization" to https://data.hdx.rwlabs.org/dataset/mobile_cellular_subscriptions_per_100_inhabitants

**Comment by danmihaila** [comment]
assigned to @aalecs

**Comment by cjhendrix** [comment]
Tagging @ochadataproject for text as described in the first item above.

**Comment by ochadataproject** [comment]
see email on this..

**Comment by cjhendrix** [comment]
New header text:

The Humanitarian Data Exchange has two categories of data – curated indicators and user-contributed datasets. We curate about 130 indicators, ensuring they are comparable across countries and have gone through a quality control process. We call this group of indicators the Common Humanitarian Dataset (hyperlink to https://docs.google.com/spreadsheet/pub?key=0AjNYvYpDh-dadFJHdnIwT0hVc0J3QkV6akFqMkVUTkE&single=true&gid=18&output=html). We also have datasets that organizations have shared. You can explore the entire HDX Collection below by location, topic or organization. 

SHOW ME A COOL VISUALIZATION (link) | TAKE A LOOK AT OUR EBOLA & COLOMBIA PAGES. (link)

**Comment by cjhendrix** [comment]
Sorry, have to reopen for a change:  
Please change the link for "Common Humanitarian Dataset" to https://data.hdx.rwlabs.org/dataset?sort=metadata_modified+desc&ext_indicator=1
