### ISSUE TITLE
Review db patch for topic tags

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2064]
There are 5 topics with no datasets: 
humanitarian profile
food and nutrition
water sanitation and hygiene
humanitarian funding
emergency telecommunications

After some brief investigation, it looks like the database patch to convert tags to these new topic tags was not applied or was reverted:

https://docs.google.com/spreadsheets/d/1063fIkazVlMUsBJtxTnWHFS1QgJ0dwWRrzcWW6BYgAc/edit#gid=0

**Comment by danmihaila** [comment]
related to https://github.com/OCHA-DAP/hdx-ckan/issues/1383

**Comment by danmihaila** [comment]
Pinging @teodorescuserban . These are the steps to be done (I will also update the document with checklikst) in this order:
[ ] update_tags_2064.sql  (https://github.com/OCHA-DAP/HDX-CKAN_Setup/blob/master/HDX_CKAN_scripts/sql/update_tags_2064.sql)
[ ] delete_tags_2064.py (https://github.com/OCHA-DAP/HDX-CKAN_Setup/blob/master/HDX_CKAN_scripts/python/delete_tags_2064.py)
[ ] - we will have to manually check if there are any other tags with uppercase:  select * from tag order by name asc;
[ ] Also to run this query:  select a.id, a.name from tag a, tag b where a.id <> b.id and a.name ilike b.name (it should return nothing)

**Comment by cjhendrix** [comment]
The patch doesn't seem to be working on stag.  Reopening.

**Comment by danmihaila** [comment]
we had to change link from tags= to vocab_Topics= in url . After redeploy it should work

**Comment by teodorescuserban** [comment]
Should this be closed?
I believe so.
Pinging @cjhendrix
