### ISSUE TITLE
Browse Page Map: improve counts of indicators by country

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2066]
Currently, the countries all show 0 for the number of indicators:

![image](https://cloud.githubusercontent.com/assets/1654485/5647504/dee8b016-9686-11e4-8a8c-96486aa977ac.png)

Let's find a way to have those counts available.  I don't think this is trivial since this information is not collected anywhere and it would take too long compile it from API queries on load. 

Some ideas (add more!):
* programatically populate CPS (and therefore CKAN with the new push functionality) with all of the countries that appear in a dataset.  
* have a script that periodically uses the cps API to compile the country count for each indicator periodically and store it in a new table somewhere

**Comment by danmihaila** [comment]
@alexandru-m-g - do you have time next week to work on this one? any ideas how to do it?

**Comment by alexandru-m-g** [comment]
Committed a small change and tested: we can easily update the groups/countries list from the api using `hdx_package_update_metadata` api/action. 
Need to talk to @seustachi about doing this via CPS.

**Comment by alexandru-m-g** [comment]
I think this can be closed now as the push of countries was tested and it worked.
