### ISSUE TITLE
Browse Page: Organization tweaks

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2073]
- [x] Add blue bar to the section title
- [ ] Implement the "more" functionality
- [x] Add sort ordering - action drop down not showing
- [ ] Pagination is using a different anchor for section (probably Arty change the sections anchor names) and when u click on a page it will not show the org section

Anything else?  There was something about JS . . .

**Comment by danmihaila** [comment]
I double checked this issue on dev server and I found some issues and one new requirement:
- [ ] move dropdown to the blue bar
- [ ] when i am using the dropdown to sort organizations it is redirecting to /organizations. It should stay on same page /browse
- [ ] pagination is not yet done - Pagination is using a different anchor for section (probably Arty change the sections anchor names) and when u click on a page it will not show the org section
- [ ] More functionality is not yet done
Pinging @mbellotti  and @cjhendrix

**Comment by mbellotti** [comment]
- "Move dropdown to the blue bar"
Not sure what this means... the dropdown is not on the blue bar on the spec I was given (https://docs.google.com/drawings/d/1hC8IA45gg-nAA5SeAx3YBrmJXrdeV02vKRoWstZ7RMs/edit) is there a new mockup I don't have?

- "when i am using the dropdown to sort organizations it is redirecting to /organizations. It should stay on same page /browse"
Yes we discussed this earlier in the week. I said this is what I wanted to do and you gave me the okay to do it. Doing pagination and sorting on the browse page means we're querying the database unnecessarily for information (topics, countries) no one needs. I've changed it to the way you're asking for, but I still think it makes more sense to direct them to the org list.

- "pagination is not yet done - Pagination is using a different anchor for section (probably Arty change the sections anchor names) and when u click on a page it will not show the org section"
Maybe this was a miscommunication, but if something is labeled as for Arty to fix later, I'm not going to touch it. It's fixed now.

**Comment by cjhendrix** [comment]
On the first item, the blue bar request is an adjustment.  It's not on the spec.

**Comment by cjhendrix** [comment]
I hear your concerns about the unneeded queries.  We have to figure out how /browse and /org fit together now that "organization" is no longer in the main nav (as of next deploy), so we want to try keeping people on Browse as much as possible.  But we will have to watch user behavior and evaluate.

**Comment by cjhendrix** [comment]
And one more item:
- [ ] Add a "Show All Organisations" link to the blue bar that links to /organization

**Comment by danmihaila** [comment]
And please don't forget about the counter.


Dan Mihaila
