### ISSUE TITLE
Minor CSS issue on organization pages

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2083]
When the name of the organization is too long, the buttons on the right hand of the page seem to move out of place. Here is a screenshot of that area: 

![screen shot 2015-01-09 at 12 10 07 pm](https://cloud.githubusercontent.com/assets/953118/5683765/96265aea-97f8-11e4-9aa5-050371a71479.png)

**Comment by cjhendrix** [comment]
I just barely beat you to it with #2081.   ;) Closing this one.

**Comment by luiscape** [comment]
Ha, nice.
