### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2084]
Where we have help resources to offer, we will have a standard help icon which will provide context-relevant help to users by pointing them to a section of the FAQ, a screencast, or the "contact us" page.

The help icon can appear on the main content panel as shown here:
![image](https://cloud.githubusercontent.com/assets/1654485/5702882/0c8be4a8-9a5f-11e4-92a7-2717be1f8f3d.png)

In the future, we may also put a smaller version of it next to specific page elements.

The icon svg is here: https://drive.google.com/file/d/0Bx1KWNTx8Ij3MExLOTNjN3paeWM/view?usp=sharing

Please add the help icon with the specified links in the associated popup as listed below. Each of the help icons listed below will open a popup in our standard style with two links:
* a link to the relevant section of the screencast page (add fragment identifiers as necessary for the sections.  The screencasts are here: http://docs.hdx.rwlabs.org/screencasts/
* this link: [Contact us](http://docs.hdx.rwlabs.org/get-involved/)

List of pages to add help icon and popup to:
- [x] Register Page: LInks to: "Creating a new user" (register screencast) + "Contact us"
- [x] My Organizations.  For users with 1..* orgs, the button will be below the other two buttons.  Links to:
"Requesting a new organization" (creating an org screencast) + "Join an organization" + "Contact us"
- [x] Preselect Page (https://data.hdx.rwlabs.org/dataset/preselect): Links to "Submitting Data" + Contact us"
- [x] Create Dataset Page. Place the button in the top right corner of the gray panel, aligned with "Tell us some details about your dataset".  Links to: Links to "Submitting Data" (submitting data screencast) + Contact us"
- [x] Create Resource Page. Place the button in the top right corner of the gray panel, aligned with "Select how you'd like to share the data".  Links to: Links to "Submitting Data" (submitting data screencast) + "Updating a resource" (updating a resource screencast)" + "Contact us"
- [x] Resource Edit List ( example .../resources/[dataset name]). Place the button just to the right of the "View dataset" button.  Links to: Links to "Submitting Data" (submitting data screencast) + "Updating a resource" (updating a resource screencast)" + "Contact us"
- [x] Edit Resource Page (.../dataset/[dataset name]/resource_edit/[resource_id]).  Add button to the right of the "All Resources" button. Links to: Links to "Submitting Data" (submitting data screencast) + "Updating a resource" (updating a resource screencast)" + "Contact us"

**Comment by mbellotti** [comment]
@cjhendrix Since Resource Edit and Resource Create share the same template the help box is already on the page for Resource Edit, although in a slightly different position than the one specified. Do you want me to have the templates position it differently depending on which page is loaded or is it fine where it is?

**Comment by cjhendrix** [comment]
Can you send me screenshots?

**Comment by cjhendrix** [comment]
the positioning and menu you show here looks good to me.  I'm assuming the position of the icon relative to the "2. Select how you'd like to share the data" will be the same on resource create? 

![image](https://cloud.githubusercontent.com/assets/1654485/5940518/ad46d5c0-a70b-11e4-886b-5407f80345cc.png)

**Comment by cjhendrix** [comment]
Reopening:  

The help menu is bold and the line breaks are odd for the My Orgs page: 

![image](https://cloud.githubusercontent.com/assets/1654485/6022750/60ed098e-abbf-11e4-9ded-67473a9bc434.png)
