### ISSUE TITLE
New Nav and homepage

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2089]
@aalecs has implemented the new nav, which has implications for the home page.  We want to make it work more like the rest of our pages to minimize maintenance (though it is not massive to maintain a separate homepage). Please compare the options below and let me know which one is preferred or if you have other ideas.  A couple of notes:
*  We need to consider these in the context of different screen sizes.  These look ok on my laptop screen, which is pretty much bottom of the barrel these days. It's still too tall to see the footer without scrolling and we may want to address that in the future.   Just simply tightening up the vertical spacing won't be enough to do it.
* The background map doesn't scroll (same behavior as our non-home pages), which is a nice effect.

**10% Opacity**  The header, footer, and "pane" in the middle all scroll together, over the fixed backgroud map. 
![image](https://cloud.githubusercontent.com/assets/1654485/5718846/701af668-9b12-11e4-99f5-5c6d19a11c84.png)

**20% Opacity**  The header, footer, and "pane" in the middle all scroll together, over the fixed backgroud map. 
![image](https://cloud.githubusercontent.com/assets/1654485/5719032/46c20afc-9b14-11e4-906b-acbf158c3dc8.png)

**New Nav Full Width** This one is the approach on the current home page, but a *little* extra work to maintain.
![image](https://cloud.githubusercontent.com/assets/1654485/5718915/ffca5fec-9b12-11e4-944c-303f02160da7.png)

**Default** If we did nothing, this is what the new nav would look like on the home page.
![image](https://cloud.githubusercontent.com/assets/1654485/5718944/57fc0738-9b13-11e4-8460-94502e509e09.png)

**Comment by cjhendrix** [comment]
Based on feedback from @ochadataproject, homepage header will be new nav *minus search bar*: 
![sc3](https://cloud.githubusercontent.com/assets/1654485/5758645/57caa0ca-9cc7-11e4-9492-67a6b9a61da7.png)

Homepage footer will be same as previous version (what is currently on production).

We will have a redesign of the homepage at some point soon . . .

**Comment by aalecs** [comment]
Header - full width + hidden search box
Footer - changed to full width version from production
Background - fixed to main content and not to body - avoid scrolling issue on smaller screens
