### ISSUE TITLE
Search and Dataset List Pages:  Move the filter button

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2096]
Move the filter button on /search and /dataset so that it apears as part of the search input in main nav:
https://cloud.githubusercontent.com/assets/1654485/5780030/a25eaeb6-9da7-11e4-9e5e-bdca79e549ab.png

When open, the filter button remains in the same place but has a "-" added to indicate that it can be closed.  SVGs will be linked below shortly.

* Open filter button: https://drive.google.com/file/d/0Bx1KWNTx8Ij3SW42UEFNaTdFQXc/view?usp=sharing
* Close filter button: https://drive.google.com/file/d/0Bx1KWNTx8Ij3NzdEXzFmRlJZZU0/view?usp=sharing

Let me know if these SVGs cause any problem.  They are filled black, but I can easily change that.

**Comment by cjhendrix** [comment]
Design proposals:

On hovers says "Filter results":
![image](https://cloud.githubusercontent.com/assets/1654485/5779896/d0d4c01a-9da6-11e4-9fce-b314fced4b46.png)

Alternatively

**Comment by alexandru-m-g** [comment]
Changed the color in this commit: 
https://github.com/OCHA-DAP/hdx-ckan/commit/fb090444136368b1d3f214e60fede0a61b37d116

The color is now blue, like below
![snapshot2](https://cloud.githubusercontent.com/assets/6586348/5909793/759463b8-a5bc-11e4-9608-c638352dfe62.png)

@cjhendrix I also tried with the red of the "share data" button. What do you think ?
![snapshot1](https://cloud.githubusercontent.com/assets/6586348/5909788/61ec5104-a5bc-11e4-9e1d-9e52908b5153.png)

**Comment by cjhendrix** [comment]
Let's go with the blue.  I feel like it implies "something to do here" whereas the red implies "take action now!"
