### ISSUE TITLE
Research WFP API

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2098]
Plan 8 hours for research into what kind of data can be retrieved from WFP VAM's api to support the WFP org page.   Work in conjunction with @SimonbJohnson

**Comment by mbellotti** [comment]
Note: speak to @amcguire62 for details about this

**Comment by mbellotti** [comment]
Backlog this for now? Turns out they haven't finished developing the API :)

**Comment by cjhendrix** [comment]
I'll kick it over to sprint 48.  But it isn't yet clear if we will be using their API or just using the Food Consumption Score data from CPS.  Tagging @amcguire62 @SimonbJohnson 

Also, note that if we are using CPS for this, we will need to add some stuff to the CPS API to support subnational.  @alexandru-m-g and I investigated this a bit yesterday.

**Comment by amcguire62** [comment]
My view on this is that it looks now like we will be taking data from the WFP api - if that is the case then i would suggest it goes straight into the datastore and Simon works from that as the source and the Frog visual as the design. I may be wrong on this but i have a suspicion this is going to be easier to build. Happy to get on a call to go over the issues.

**Comment by cjhendrix** [comment]
If it's going to come from their API, couldn't we just call it from there directly (to avoid the need to synchronize it to the datastore)?
