### ISSUE TITLE
Default Country Page: controller

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2102]
Annotated (very annotated) design is here: 
https://docs.google.com/drawings/d/1qOBKZ7IO7zkEMHh2g3ZiAynh5PiAbO-_-SL4rd9uO_M/edit
Implement the controller that is populating the sections with data

**Comment by alexandru-m-g** [comment]
This commit is related to this task: https://github.com/OCHA-DAP/hdx-ckan/commit/41561d990ea4a38cb9d6d90da61657dbb088c1f5
