### ISSUE TITLE
Default Country Page: continuous browsing

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2109]
Blocked by #2102 and #2103 
Annotated (very annotated) design is here: 
https://docs.google.com/drawings/d/1qOBKZ7IO7zkEMHh2g3ZiAynh5PiAbO-_-SL4rd9uO_M/edit
Implement the continuous browsing section:
- [ ] explore
- [ ] supporting topics
- [ ] followers
- [ ] related websites

**Comment by alexandru-m-g** [comment]
@mbellotti I committed and merged on dev a version of the controller that fetches the data for:
  *  followers - c.cont_browsing['followers']
  *  related websites - c.cont_browsing['websites']
  *  topics ( these are just DUMMY topics for now as I want to try and fetch them together with the datasets for the central section ) - c.cont_browsing['topics']

Each of the above is a list of dicts of the following format: {'name': 'item name', 'url': 'item url'}. Same format as on the dataset/indicator page.

**Comment by alexandru-m-g** [comment]
Just a note that now the topics are the real thing, not dummy anymore.

**Comment by mbellotti** [comment]
Finalizing this today. Some questions for @cjhendrix:

- On the mockup "related websites" is "contributors" ... should I change the copy or is it supposed to be "related websites"?
- With Supporting Datasets taken out there's a significant amount of empty space on the right side. Should I center the content? Add a placeholder for Supporting Datasets?

![screen shot 2015-01-28 at 12 48 50 pm](https://cloud.githubusercontent.com/assets/489152/5943338/15b95896-a6ec-11e4-8b3b-5c5c7edaa695.png)

**Comment by mbellotti** [comment]
Can't do this via percentages (at least not nicely making the boxes wider doesn't make them prettier), but here are two options using empty placeholders to better distribute spacing:

centered:
![screen shot 2015-01-28 at 1 56 25 pm](https://cloud.githubusercontent.com/assets/489152/5944542/d1ab634c-a6f5-11e4-9dce-f005e3e3ddd0.png)

But I actually prefer this, keep the browse section aligned to the left, while the other boxes are centered in relation to the make content block:
![screen shot 2015-01-28 at 1 55 28 pm](https://cloud.githubusercontent.com/assets/489152/5944561/fc36700c-a6f5-11e4-8a2a-611fbdee23ee.png)

**Comment by alexandru-m-g** [comment]
There is a bubble on the bottom right side of the mockup page. That's where I saw the "Related websites" name

**Comment by cjhendrix** [comment]
I agree with your preference Marianne.  A couple of other small items: 
- [ ] Could we put the "Explore Colombia . . ." bit on a single line, stretching across the space to the "supporting topics" box?
- [ ] We should remove the link from "Colombia" since it can really only go to the page that is already on.  I would have sworn that was in the annotated design, but it isn't.

**Comment by mbellotti** [comment]
1 - Sure, I think I can do that.
2 - Not true! The Colombia link searches datasets for the term "Colombia" which means it can pull up datasets that mention Colombia but are not sorted into the Colombia group. While we might not want this to happen, the reality is user generated content doesn't always end up so neatly organized.

**Comment by cjhendrix** [comment]
Ok, you convinced me.  I think that's a reasonable approach. It will make these mis-grouped datasets easier for data team to find (if the counts don't match, we know we have a problem).
