### ISSUE TITLE
Search snippet & Dataset Create/Edit: add subnational stuff

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2115]
The subnational icon will appear in the search snippet if the dataset is flagged as subnational in the package_extra (this part is covered in #2101). 

We will need to add this to the create/edit dataset pages.  (Design TBD, bug CJ)

**Comment by mbellotti** [comment]
@cjhendrix I assume you have some preferred copy for the help text to this field?

**Comment by cjhendrix** [comment]
The exact wording may depend on how you implement the flag in the UI.  Could you send me a screenshot or let's discuss over a screenshare.

**Comment by cjhendrix** [comment]
Ok, based on the screen cap you sent me, let's do the following: 

- [ ] move the subnational section up to just after description
- [ ] change section title from "Data Features:" to **Dataset contains sub-national data** and then the check box.  Remove "Subnational regions included".
- [ ] box is checked by default for new datasets
- [ ] help text = "Leave this box checked if the values in your dataset apply to one or more locations *within* a country.  For example, if your dataset is disaggregated by district, province, city, town or other locations within a country or countries, then it contains sub-national data.  If the each value in your dataset apply to a whole country, it does not contain sub-national data."

**Comment by mbellotti** [comment]
I had to trim the help text a bit because it was more characters than what will fit in the help box. The alternative is making the box larger and ending up with a huge empty space between the checkbox and the next field.

**Comment by cjhendrix** [comment]
Ok.  What text did you use?  I may see it on dev before you see this.
