### ISSUE TITLE
Test dataset/resource saving

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2118]
Make a test for being sure we save everything from the create dataset/resource form.

**Comment by danmihaila** [comment]
@mbellotti I think we have nosetests, but can you please confirm?

**Comment by mbellotti** [comment]
I believe we have for everything we've modified https://github.com/OCHA-DAP/hdx-ckan/tree/dev/ckanext-hdx_package/ckanext/hdx_package/tests/test_actions

CKAN core covers the rest.

**Comment by danmihaila** [comment]
I see in our test only the update resource metadata. @mbellotti can you point to the ckan core test for resource create, update, delete ? I think @cjhendrix is right to include in our running test just to be sure it is working well.

**Comment by alexandru-m-g** [comment]
As discussed in the previous spar call I added unit tests for the changed resource create/update
