### ISSUE TITLE
ckanext-sitemap and ckanext-hdx_theme are missing top level __init__.py

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#2119]
we need this to be able to run ckan in production mode.

**Comment by danmihaila** [comment]
Ping @mbellotti

**Comment by mbellotti** [comment]
Wow that's weird. Okay, easy enough to fix.

**Comment by mbellotti** [comment]
Oh wait... looks like @teodorescuserban already pushed a fix for this?

**Comment by teodorescuserban** [comment]
Yes I did.
