### ISSUE TITLE
Login Page: Add a button for "Forgot username"

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2125]
Add an additional button above "forgot password" for "forgot username" which links to /user.

**Comment by danmihaila** [comment]
ping @yumiendo : is this related to onboarding? do we need it?

**Comment by yumiendo** [comment]
How have we dealt with someone who forgot username before the new onboarding?
do we have a page like "forgot password"(https://data.hdx.rwlabs.org/user/reset) for username?

**Comment by danmihaila** [comment]
@yumiendo  I don't remember to have this feature.
In this case do we want this new feature? Basically right now we can login with username or email, in my opinion it doesn't make sense to have it.
Assigned to @cjhendrix for comments too

**Comment by cjhendrix** [comment]
We have this.  But it leads to an old (old) style page https://data.hdx.rwlabs.org/user/reset

**Comment by danmihaila** [comment]
I think there are 2 different things:
- forgot password
- forgot username/email
  Forgot password is CKAN default which I think should be included in onboarding. I think we don't need forgot username/email feature.

**Comment by danmihaila** [comment]
assigned to @yumiendo for comments

**Comment by yumiendo** [comment]
Im ok with just having "forgot password?" option for now.
if we see too many users get stuck with forgetting username/email address...then we'll come back to this feature.
