### ISSUE TITLE
Romania and East Timor not tagged on indicators

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2144]
This might be just a glitch because of the order we have been fixing the various problems that came up with this yesterday.   No need to fix on stag as long as it will work on prod.   Not a blocker for prod either.

**Comment by danmihaila** [comment]
Ping @aalecs and @alexandru-m-g

**Comment by alexandru-m-g** [comment]
@danmihaila @cjhendrix , this is ok now, right ? 
So I'm closing it.
