### ISSUE TITLE
Update terms of service

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2147]
Create item number 12 on the terms of service page.

The text is:

`12. The designations employed and the presentation of material on this website do not imply the expression of any opinion whatsoever on the part of the Secretariat of the United Nations concerning the legal status of any country, territory, city or area or of its authorities, or concerning the delimitation of its frontiers or boundaries.`

![image](https://cloud.githubusercontent.com/assets/1654485/5819297/f3699876-a0bc-11e4-9742-31af1ffbc1f0.png)

**Comment by danmihaila** [comment]
assigned to me

**Comment by cjhendrix** [comment]
Made small change to text just now ("map" to "website" in the first line).
