### ISSUE TITLE
Browse Page Map: Update geojson for 3 countries: rou, som, tls

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2156]
The unrecognized nation of Somaliland is recognized in our map, but shouldn't be.  Also, Romania and East Timor lost their geojson when we fixed their codes. 

![image](https://cloud.githubusercontent.com/assets/1654485/5825905/17c02d66-a0ef-11e4-8591-81eaa7cd54a7.png)

**Comment by cjhendrix** [comment]
Geojson files for 3 countrys (somalia, romania, and east timor) are here: https://drive.google.com/folderview?id=0Bx1KWNTx8Ij3fkFNeTNLNDQzU2VQV2ZfVEtGMEQwNURpd2xNNTY3OHR1Tkl2TUFxRlpMTm8&usp=sharing

In the cases of rou and tls, there is currently no geometry.  In the case of som, the existing geometry needs to be replaced.

**Comment by alexandru-m-g** [comment]
@cjhendrix made the groups form show all fields and updated the geojson for the 4 countries: ssd, som, rou, tls

**Comment by cjhendrix** [comment]
Cool.  Sadly, I forgot that Marianne had an issue to remove the geojson field in this sprint and she closed it yesterday.  :(  I've asked Dan not to merge that one.  We'll keep the field for now.
