### ISSUE TITLE
Topic page: clicking  on the indicators tab loads wrong search (topic filter is dropped)

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2163]
To replicate:

1. On browse page, click a topic that has indicators (most of them do)
1. On the resulting /search page, click on the "Indicators [xx]" tab
![image](https://cloud.githubusercontent.com/assets/1654485/5834213/7721ba92-a15b-11e4-8090-74f5eb7a78e8.png)
1. The URL loaded search no longer has the topic filter.  In the above example, it loads https://data.hdx.rwlabs.org/search?sort=metadata_modified+desc&ext_indicator=1&_show_filters=false

The "show all indicators" link has the same problem.  And the Datasets tab and "show all datasets" link behave the same way.

**Comment by alexandru-m-g** [comment]
This was fixed and merged.
