### ISSUE TITLE
on indicator page meta data - reduce txt (see location xxx countries) using same approach click "more ...."

### ISSUE THREAD

**Issue by amcguire62** [OCHA-DAP/hdx-ckan#2167]
Display the same number of lines as for methodology and license before showing the "more" link.

![screenshot 2015-01-21 at 1 12 08 pm](https://cloud.githubusercontent.com/assets/1962335/5836562/59cf43a6-a16f-11e4-9d01-1e183d17dab9.png)

**Comment by cjhendrix** [comment]
Will schedule this for sprint 48. I thought we might want to.  But one nice consequence of these longer lists are that that draw the user down to the continuous browsing bar.  So far we are getting less than 1% of clicks on busy dataset pages in the CB bar, so drawing some traffic down there might not be a bad idea.  Tagging @ochadataproject for consideration.

**Comment by ochadataproject** [comment]
Hi good feedback on CB. Once the download works we can promote the CB
feature more. But let's add more to the list of locations in be metadata.
Thanks
