### ISSUE TITLE
Filtering datasets by clicking on a tag in a dataset does not work for some tags

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#2171]
1. Open the following dataset: https://data.hdx.rwlabs.org/dataset/humanitarian-needs-overview-classification-tool
2. On the Tags field, click on the "Humanitarian Profile" tag. 
3. The result contains no results when we expect at least one result

**Comment by cjhendrix** [comment]
Beat you to it:  #2154, which we will be working on in sprint 48.  Thanks for raising it though.

Closing this one.
