### ISSUE TITLE
JSON resource that does not preview, why?

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2176]
We need to understand if this is a limitation of our setup or something about their API, then decide how to handle it.

Preview not working:
https://data.hdx.rwlabs.org/dataset/standard-cluster-names-and-codes
(there is also a problem with the CSV preview, but that's on them, so ignore the CSV)

Preview working:
https://data.hdx.rwlabs.org/dataset/worldwide-ushahidis

**Comment by alexandru-m-g** [comment]
Cannot reproduce right now.
