### ISSUE TITLE
Share button title for /group/col and /ebola

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2186]
Change title of share button popup menu from "Share dataset" to "Share"
- [ ] /group/col
- [ ] /ebola

![image](https://cloud.githubusercontent.com/assets/1654485/5900098/1358cd30-a565-11e4-921c-337dc078e762.png)

**Comment by alexandru-m-g** [comment]
@cjhendrix I believe this was done as part of the previous sprint.
