### ISSUE TITLE
Default Country Page: Graph colors

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2188]
I pulled the colors out of the frog design.  I'm not sure how this will look, but please assign these colors to the bars in the graphs, in the order shown here:

![image](https://cloud.githubusercontent.com/assets/1654485/5902951/09e170b2-a57f-11e4-83a5-dbb69b4310c4.png)

**Comment by alexandru-m-g** [comment]
This commit contains also the change of colors: https://github.com/OCHA-DAP/hdx-ckan/commit/00080e2eeaf2bf61c31d01abbc4f94bdf1e54444
