### ISSUE TITLE
Country --> Location

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2190]
We need to change the terminology from "country" to "location" throughout the site. 

Here are the locations to make the change: 
- [ ] Home page (two locations)
![image](https://cloud.githubusercontent.com/assets/1654485/5903122/281da162-a580-11e4-84af-222247b7b691.png)
- [ ] /data
![image](https://cloud.githubusercontent.com/assets/1654485/5903167/6a50480a-a580-11e4-805f-f1b55eb7dda0.png)
- [ ] Create Dataset (5 places)
![image](https://cloud.githubusercontent.com/assets/1654485/5915839/c7291b9e-a60a-11e4-8896-43dd7f358aec.png)
- [ ] Edit Dataset (3 places)
![image](https://cloud.githubusercontent.com/assets/1654485/5903345/79c2988c-a581-11e4-9736-6068c335568f.png)
- [ ] My Countries
![image](https://cloud.githubusercontent.com/assets/1654485/5903971/37cbff3c-a585-11e4-9937-a8065f6b937e.png)
- [ ] /group (4 places)
![image](https://cloud.githubusercontent.com/assets/1654485/5904035/c676627c-a585-11e4-8b52-ac8e17da04d7.png)
- [ ] Default Country Page (2 places; this may have already been done in sprint 47).  In the case of "Country Overview", just change it to "Overview"
![image](https://cloud.githubusercontent.com/assets/1654485/5904004/8600e67c-a585-11e4-9bce-2258e6212058.png)
- [ ] Org view page 
![image](https://cloud.githubusercontent.com/assets/1654485/5937589/7bca6dc8-a6f1-11e4-8de1-91b55d569976.png)
- [ ] Old country page (if we decide to keep it in addition to the new default country page)
![image](https://cloud.githubusercontent.com/assets/1654485/5937627/f3545246-a6f1-11e4-8958-9a58fa62d632.png)

**Comment by danmihaila** [comment]
pinging @cjhendrix about "Default Country Page (2 places; this may have already been done in sprint 47). In the case of "Country Overview", just change it to "Overview" "
I don't see the text "Country Overview" or "Overview". Was a requirement?

**Comment by cjhendrix** [comment]
Overview is there, just above the summary numbers block.

**Comment by danmihaila** [comment]
@cjhendrix - you are right (I can swear it was not there when I tested :) ). Colombia page doesn't have it.
