### ISSUE TITLE
Dataset View: change color of background map based on an org's specified color (if available)

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2195]
I'm open to ideas about how we do this.  Here is the requirement:

If a dataset belongs to an org using the customizable org page (as opposed to the default org page), the background map should the organization's chosen color (specified on org create/edit), if a logo is available for that org. You can see an example in the screencap below.

In the long term, here is what I think this implies: 

- [ ] changing the dataset view template to use the org's color if the org is using the customizable org page.  

![image](https://cloud.githubusercontent.com/assets/1654485/5939124/5ec656a0-a701-11e4-9582-0f9904bf3a91.png)

**Comment by danmihaila** [comment]
@cjhendrix is this still an issue?

**Comment by cjhendrix** [comment]
Long since done.  :)
