### ISSUE TITLE
WFP page: topline numbers section

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2201]
Implement the topline numbers section.

Design is here: 
https://docs.google.com/drawings/d/1PE5sAfD7Iii0Gfvp106ipqkamR37iLAwdgfXGfBROek/edit

Blocked by #2199 and #2200

**Comment by cjhendrix** [comment]
@alexandru-m-g The datastore is available, though the contents are still a work in progress. 

Hi CJ, we've created the DataStore for the WFP topline figures: https://data.hdx.rwlabs.org/dataset/wfp-topline-figures/resource/7329f8c7-2112-499a-8b93-d6da0331d092

**Comment by alexandru-m-g** [comment]
@cjhendrix @luiscape I see units that are different from what we used before ( which was count,ratio,million ). Can we discuss this ?

**Comment by alexandru-m-g** [comment]
I've connected the controller to the snippet in the template but it looks bad until we figure out the units.

**Comment by luiscape** [comment]
@alexandru-m-g Yes, let's discuss this. Can you ping me on Skype tomorrow? Also @JavierTeran should be in that conversation.

**Comment by alexandru-m-g** [comment]
Ok, just a recap of what we are using so far - with examples: 

| Type | Sample Value |
| --- | :-: |
| count | 22,495 |
| million | 3.1 million |
| dollars | $ 12,371 |
| dollars_million | $ 69.7 million |
| ratio | 54.2 % |
| per100k | 26.4 per 100k |

**Comment by luiscape** [comment]
Google Doc and DataStore have been updated. 

https://data.hdx.rwlabs.org/dataset/wfp-topline-figures/resource/7329f8c7-2112-499a-8b93-d6da0331d092

Closing issue.
