### ISSUE TITLE
WFP page: datasets, indicators

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2202]
Implement the section that is displaying the list of datasets, indicators, activities and filters. For now they should look like the results from the /search page.

The filters can work as they do on the current org page, but if we have time, we could improve on that, I think.  

Design is here:  https://docs.google.com/drawings/d/1PE5sAfD7Iii0Gfvp106ipqkamR37iLAwdgfXGfBROek/edit

Blocked by #2199 and #2200

**Comment by alexandru-m-g** [comment]
@cjhendrix is there a way to reset the filters ? I might've missed it.

**Comment by alexandru-m-g** [comment]
Now I see that in the org page ( /organization/org_code ) for each filter group there's a "Clear all". Do we want to go the same way here ?

**Comment by cjhendrix** [comment]
I guess so for now.  It's probably easier to stick with them as they are right?
