### ISSUE TITLE
Epic:  COD Preview

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2206]
ITOS now has a geodata service built around the Mali CODs (administrative boundary polygons).  

For each of Mali's 4 admin boundary layers, the COD service can deliver these formats:
* geojson (filestore)
* KMZ (filestore)
* WMS (url)
* WFS (url)
* Shapefile (filestore)
* Geodatabase (filestore)
* WKT (filestore)

In the future, we hope also to provide xls, csv.

We will have a single ckan dataset with a resource for each of the above. 

We want to create a specialized preview for these data so that users can get some idea of what they will get when downloading.   You can sort of think of it like the Indicator View Page, where we have a specialized graph preview of the data.   With these COD datasets, we will also know the structure.  Essentially, they are curated datasets, but they are curated by ITOS rather than CPS.  

Originally, we had talked about having the preview button open a specialized version of the recline map preview.  However I think that will be complicated since the preview button relies on the file type and there is no unique file type for CODs. I'm open to other ideas about how we do this, but my default proposal is this: 

- [ ] implement a flag on a dataset that indicates "CODService" (in the same way that we flag "indicator".  For the moment, we can just set that in the db, but in the future, we should allow sysadmins to see it in the dataset create/edit interface.
- [ ] For any dataset with the "CODService" flag, we display a leaflet map preview at the top of the dataset view page which displays the OSM baselayer + 4 Mali WFS layers.  

At the moment, the various resources mentioned above are in several separate datasets.  The links are below for reference:

 https://data.hdx.rwlabs.org/dataset/mali-cod-admin-boundaries-gdb-10-1
https://data.hdx.rwlabs.org/dataset/mali-cod-admin-boundaries-geojson
https://data.hdx.rwlabs.org/dataset/mali-cod-admin-boundaries-kmz
https://data.hdx.rwlabs.org/dataset/mali-cod-admin-boundaries-map-service
https://data.hdx.rwlabs.org/dataset/mali-cod-admin-boundaries-wkt
https://data.hdx.rwlabs.org/dataset/mali-cod-admin-boundaries-shapefile
https://data.hdx.rwlabs.org/dataset/mali-cod-admin-boundaries-pcode-wfs-service

**Comment by cjhendrix** [comment]
Moving to sprint 50.

**Comment by cjhendrix** [comment]
Archiving this, since it has changed significantly.

**Comment by danmihaila** [comment]
closing it but ping @cjhendrix as we had a big progress on COD migration
