### ISSUE TITLE
WPF page: activities tab

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2215]
Implement the activity stream tab in section that is displaying the list of datasets, indicators, activities and filters. 

Design is here:  https://docs.google.com/drawings/d/1PE5sAfD7Iii0Gfvp106ipqkamR37iLAwdgfXGfBROek/edit

Blocked by #2199 and #2200

**Comment by alexandru-m-g** [comment]
@danmihaila don't forget to remove the pagination and search box from the activities tab
