### ISSUE TITLE
Remove geojson from group create/edit

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2216]

**Comment by cjhendrix** [comment]
@mbellotti @alexandru-m-g @danmihaila So as it turns out, just yesterday Alex was trying to solve the problem of updating the geodata for some problem countries and he wanted to make the geojson field work again.  

Marianne, I completely forgot that this was a current issue, otherwise I would have pinged you not to work on it.  Sorry for that.

For now let's keep the geojson (and RW and HR.info) fields working on the edit/create group pages.  

Closing this one.

**Comment by mbellotti** [comment]
hahah okay... then I have to go revert a commit :)

**Comment by danmihaila** [comment]
reopening this issue as it is was not reverted.
pinging @mbellotti - please fix it today as it needs to go to prod tomorrow.

**Comment by mbellotti** [comment]
That's super weird then what the hell did I roll back before? O.o

**Comment by danmihaila** [comment]
closing this issue
