### ISSUE TITLE
Issue with subnational flag

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#2218]
*  When editing an existing dataset ( which was not subnational ) in the dataset edit form the subnational checkbox appeared "checked"
*  After editing a dataset, making sure that the subnational checkbox is "checked" and saving it, the "subnational" field value of the dataset is an empty string ('') - checked via the API

Question, does this flag show anywhere on the dataset view page ?
This is related to #2115 .

**Comment by mbellotti** [comment]
Okay, yeah. Made some minor changes to the display after CJ's feedback.
Didn't think it would effect the behavior but obviously it did. Will fix
and have a PR for you before Monday

On Sat, Jan 31, 2015 at 9:59 AM, Alexandru Gartner <notifications@github.com

**Comment by alexandru-m-g** [comment]
Thanks for the fix. 
There's one wrinkle left here: according to #2115, for new datasets, the checkbox needs to be checked by default ( in accordance with the help text ).
