### ISSUE TITLE
Dataset View Page: Make dataset icons visible on this page

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2227]
I think we should make the comparable, quality checked, subnational, and popular icons visible on the dataset page.   

Gallery is excluded from display here because it is visible (and large) on the page. 

![image](https://cloud.githubusercontent.com/assets/1654485/6103925/238ca94e-b049-11e4-9232-ff5ee888ce99.png)

**Comment by cjhendrix** [comment]
@ochadataproject Please have a look at the design above (icons next to the dataset name) and comment.

**Comment by ochadataproject** [comment]
Hi I'm not sure we need the icons on the dataset page. Did a user ask for
it? Will can you to discuss.

**Comment by cjhendrix** [comment]
It just seemed weird to me that you can see that a dataset is subnational and quality assured when you are searching, but not once you are on the page.  I found it a bit disorienting.  

Note that it is in the product backlog, not a high priority.

**Comment by ochadataproject** [comment]
Yes I looked at it more. You're right. What happens if the data set title
is long do these go on the second line? Is there any overlap with what's in
the metadata fields down the page? I don't think so.

**Comment by danmihaila** [comment]
@yumiendo and @cjhendrix what do you think about the proposal? should we implement or close this issue?

**Comment by cjhendrix** [comment]
I recommend we implement.    To answer Sarah's question, yes, I think they would break to a second line, and we should make sure they break all together (we wouldn't want the first icon at the end of the first line and the others on the second line, for example)/

**Comment by yumiendo** [comment]
I agree. I'd say add as a row below the title.

**Comment by danmihaila** [comment]
@yumiendo can you please provide a quick mockup?

**Comment by danmihaila** [comment]
pinging @yumiendo for a mockup :)

**Comment by cjhendrix** [comment]
Can I suggest we don't do the icons on a second line (unless it breaks that way).  For most of our (non-inidcator) datasets, we have a lot of spaciness in the top section already.   It's Yumi's call, but I'd suggest having a look at datasets (not indicators) with and without geopreview as well as with and without the org logo to get a feel for the different situations in which the icons will occur.

**Comment by yumiendo** [comment]
After looking at various cases - I think icons on the same row as actions (share, edit, delete etc) is the safest location for them.

different cases below....

<img width="1406" alt="screen shot 2015-09-08 at 5 29 40 pm" src="https://cloud.githubusercontent.com/assets/8006323/9747808/fd2966ce-564d-11e5-8fc6-f9e5b6ef292b.png">
<img width="1409" alt="screen shot 2015-09-08 at 5 28 06 pm" src="https://cloud.githubusercontent.com/assets/8006323/9747806/fd28f3b0-564d-11e5-8a22-c93056b7c4e5.png">
<img width="1394" alt="screen shot 2015-09-08 at 5 21 02 pm" src="https://cloud.githubusercontent.com/assets/8006323/9747805/fd278106-564d-11e5-8290-e85f2bd08a4d.png">
<img width="1419" alt="screen shot 2015-09-08 at 5 15 05 pm" src="https://cloud.githubusercontent.com/assets/8006323/9747807/fd29256a-564d-11e5-85d7-c3dc839b1dff.png">
<img width="1420" alt="screen shot 2015-09-08 at 5 13 12 pm" src="https://cloud.githubusercontent.com/assets/8006323/9747809/fd2b8558-564d-11e5-9c3a-989a88e79ebc.png">

dan - i know this is a separate issue but on the "Json repository" example - the margin above the description is smaller than the the above "gallery". can we match to margin above "gallery"?

**Comment by cjhendrix** [comment]
Looks good to me.   Makes the buttons look less misaligned when there are icons to show.  @yumiendo Could handle #1593 the same way?

**Comment by yumiendo** [comment]
I isolated the private icon from other icons because its more important to the owner. 
please see the treatment here https://github.com/OCHA-DAP/hdx-ckan/issues/1593

**Comment by danmihaila** [comment]
I think we can close this one @cjhendrix
