### ISSUE TITLE
Dataset Create: adjust subnational help box higher

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2230]
![image](https://cloud.githubusercontent.com/assets/1654485/6018881/c5822f98-ab9a-11e4-8842-7c85c47929b6.png)

**Comment by mbellotti** [comment]
@cjhendrix do you want this aligned with the top of the field like all the others, or further up?

The reason why it's doing this is because the css expects the label to be on a separate line from the input field (in this case a checkbox).
