### ISSUE TITLE
Add/edit gallery item: remove location list

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2232]
Gallery list page (which is loaded after creating/editing a gallery item) shows a list of all groups, followers, tags and share.  This should be removed. Let's simply show the dataset title at the top of this panel (where "HDX" is shown in the screencap below).

![image](https://cloud.githubusercontent.com/assets/1654485/6021317/349ee4ec-abb5-11e4-90bf-a8ec1b2f79f2.png)

**Comment by danmihaila** [comment]
This needs a bit of refactoring and cleaning also in the center of the page
![screen shot 2015-08-27 at 16 38 52](https://cloud.githubusercontent.com/assets/3865844/9521909/32684f1c-4cda-11e5-9605-170cc4ae4097.png)
