### ISSUE TITLE
Search result snippet: issue with icon movement on hover

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2233]
In Chrome, not FF: 

When hovering over the "comparable indicator" icon in a search result, the icon to the right of it jumps a few pixels to the left. The new position is maintained until the page is refreshed.  In the screencap below, the first result has had this behavior triggered, but the second one has not.  Note the misalignment in the quality icons. 

![efe20c3705609a7a87245fd95c89e9f7](https://cloud.githubusercontent.com/assets/953118/6070468/a8c8b216-ad5a-11e4-8a9c-a4174092a673.gif)

Luis notes that it's happening on a MAC in Chrome + Safari + Firefox, and provides this useful gif to show the problem. 

![image](https://cloud.githubusercontent.com/assets/1654485/6021452/363708a6-abb6-11e4-93af-af8cf50cb139.png)

**Comment by danmihaila** [comment]
I can not reproduce it anymore, closing it
