### ISSUE TITLE
Search Result Snippet: adding a gallery item to an indicator does not result in the gallery icon being displayed

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2234]
Tested on two datasets on stag:

1. Search for an indicator with no gallery items
1. Add a fake gallery item
1. Search for that indicator
1. Note that gallery icon is not displayed.

Also, the indicator show here: https://test-data.hdx.rwlabs.org/search?q=drinking+water  
does have a gallery item, but the icon is not shown.

**Comment by alexandru-m-g** [comment]
Fixed
