### ISSUE TITLE
Default Country Page: Add source/data/date information to overview numbers

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2239]
![image](https://cloud.githubusercontent.com/assets/1654485/6037947/16d66ed6-ac59-11e4-91c6-954a1ef1326e.png)

**Note**: white backgrounds around the source/data/date line are just me being a lazy designer.  Background should be the default for that row of the table

Here are the elements of how I made the screencap above.  Feel free to use a different CSS approach!
- [ ] tr.indicator: height: 63px
- [ ] td.name font-weight: 700
- [ ] td.name vertical-align: top
- [ ] td.name padding-top: 12px
- [ ] td.name width: enough for the HDI rank name to be on one line (I faked this one)
- [ ] style and content for the source/data link/date is the same as for the graphs

**Comment by alexandru-m-g** [comment]
This is on prod in the meantime. Closing
