### ISSUE TITLE
inexistent country code makes ckan cough and then he faints

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#2265]
https://data.hdx.rwlabs.org/group/xxx?sort=metadata_modified+desc leads to internal server error.

Replace **xxx** with any inexistent is country code to get the same result.

Please prepend a check that would throw at least a 404 if not something smarter.

**Comment by danmihaila** [comment]
@teodorescuserban I think we have a 404 now. can you check and close this one?

**Comment by teodorescuserban** [comment]
Yep. Works ok now.
Closing.
