### ISSUE TITLE
at least one country have no polygon

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#2266]
rou have no polygon attached.

when going to https://data.hdx.rwlabs.org/group/rou?sort=metadata_modified+desc the map zooms out on a multiworld level. no polygon in sight.

**Comment by luiscape** [comment]
Maybe the problem is caused by a confusion of using `ROU` instead of the [deprecated](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) `ROM`?

**Comment by cjhendrix** [comment]
We had a few geojson problems that were fixed in #2156.   Closing this one.
