### ISSUE TITLE
A part of tooltip of the `Country Overview` section is misplaced

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2268]
The little triangle of the tooltip of the **country overview** section (country pages) covers the text in some cases. This tooltip is the one that shows the unit type of indicators within that area. 

Apparently the behavior is being caused when the text takes two lines instead of one. Here is a gif:

![46526d5976584513edb825616ac96232](https://cloud.githubusercontent.com/assets/953118/6070518/124ec4f0-ad5b-11e4-8fbf-5c39b1313d60.gif)

**Comment by cjhendrix** [comment]
I beat you to it with #2238.  But I'm stealing your animated gif to add to that one.   :)
