### ISSUE TITLE
Google Analytics tracking code of blog and CKAN should be the same.

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2269]
Currently, the GA tracking code of CKAN is `UA-48221887-3` and of the blog is `UA-48221887-2`. Both sites should use the same tracking code -- likely the CKAN one (`UA-48221887-3`).

**Comment by danmihaila** [comment]
@luiscape can you double check now? if they are not the same lets change the blog
pinging @amcguire62 to be aware

**Comment by luiscape** [comment]
Tracking codes still seem to be different. See here: 
- **blog**: http://docs.hdx.rwlabs.org/ (see page source). 
- **ckan**: https://goo.gl/f2vZgq

**Comment by danmihaila** [comment]
@luiscape can we change the blog entry?

**Comment by luiscape** [comment]
@danmihaila should I change it? I can. Serban has to lift the the write permissions of the blog.

**Comment by danmihaila** [comment]
@teodorescuserban @luiscape can you coordinate?

**Comment by luiscape** [comment]
@teodorescuserban Ping me on Skype / Slack. This should be a quick (i.e. > 15 mins) fix.

**Comment by teodorescuserban** [comment]
Please make sure you double check what exactly is the code we need to change.
Is it the blog one or the ckan one?

Please note the only difference is the last digit.

I can change the blog GA code in 20 seconds but let's make surte there is no impact in the GA history

**Comment by teodorescuserban** [comment]
After a talk with @luiscape , I changed the blog GA code.
While at it I also updated the blog and the plugins.
Closing.

**Comment by danmihaila** [comment]
@luiscape can you please test this on staging and put here a comment if everything is ok? thanks
