### ISSUE TITLE
Register site with Google Webmaster Tools

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2270]
I am not sure we are registered on Google's Webmaster Tools. I believe it would increase our SEO considerably by making our pages more "findable" for Google -- and other search engines. 

This issue is for registration of our site with Google Webmaster Tools.

**Comment by amcguire62** [comment]
@danmihaila i think this is an easy thing to do - could we put it down for August during quiet period?

**Comment by danmihaila** [comment]
@luiscape @amcguire62 lets find a time to chat about this one

**Comment by luiscape** [comment]
@danmihaila @amcguire62 Except for Monday and Tuesday morning, I am available anytime next week.

**Comment by danmihaila** [comment]
closing this one as we probably are going to move to mixpanel
