### ISSUE TITLE
Dataproxy?  CSV/XLS previews not working for some files and the files seem ok

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2271]
https://data.hdx.rwlabs.org/dataset/kenya-income-gini-coefficient-per-county 
https://data.hdx.rwlabs.org/dataset/number-of-security-incidents-in-ethiopia
https://data.hdx.rwlabs.org/dataset/ebola-cases-2014  (csv working, but not xls)

**Comment by teodorescuserban** [comment]
fixed.
