### ISSUE TITLE
Lots of errors related to solr search

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#2273]
Devs should be getting lots of errors similar to this:
Subject: **WebApp Error: <class 'ckan.lib.search.common.SearchError'>: SOLR returned an error running query:**

The urls are multiple but have /group in common. Below an example:
**http://data.hdx.rwlabs.org/group/world?groups=world&organization=international-displacement-monitoring-centre-idmc&_tags_more=true&_tags_limit=0**

**Comment by cjhendrix** [comment]
Searching for that org and group=world works.  

However just trying to load group/world does not work (returns server error).  But loading the edit page: /group/edit/world does work.  Strange.

**Comment by danmihaila** [comment]
done in sprint 48

**Comment by danmihaila** [comment]
@teodorescuserban do we have other errors related to SOLR?

**Comment by teodorescuserban** [comment]
We still have on prod.
The commit above is tagged for v0.7.0.
It seems fixed on stag v0.7.0stag.
I will confirm it is solved on prod as well after deployment (hopefully tomorrow).

Thank you, @mbellotti
