### ISSUE TITLE
Refactoring web components (html/css/less)

### ISSUE THREAD

**Issue by aalecs** [OCHA-DAP/hdx-ckan#2283]
There are some components that can be used for building blocks in new pages eg.: dataset lists, dropdowns, toplines, etc. These components should be refactored so that they are more maintainable and easier to use when building new pages.
This is a starting point in theming them or making them embeddable.

**Comment by danmihaila** [comment]
@aalecs - an estimate for this? and maybe you can provide a list of components and we can set a priority for these.
