### ISSUE TITLE
Add a "quality checked" flag so we can use it as a search filter

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2284]
Quality checked is currently just applied to any dataset that is an indicator coming out of CPS.  However we have other quality checked datasets (mostly in datastore or CODs coming from ITOS).  

We want to allow sysadmins to set a "quality checked" flag which then:
- shows the quality checked icon in the search result snippet
- can be used as a search facet (separate issue)

for this issue:
- [x] set the flag on any dataset that is currently flagged as an indicator (let's talk about how to handle future indicators)
- [x] on dataset create/edit expose the flag to sysadmins as a checkbox just below the subnational checkbox

**Comment by cjhendrix** [comment]
Currently a user with edit rights can modify this flag via API even if they are not sysadmin.  Reopening so we can fix that.

**Comment by danmihaila** [comment]
We fixed some of the issues here:
- the checkbox was not really saving that value
- not working well for sysadmin
- the icon was showing on most of the existing datasets
- by default the checkbox was checked

We also improved so the checkbox will not be overwritten by an editor .
