### ISSUE TITLE
Writing more nose tests for the controllers of the country and browse pages

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#2286]
We should create more tests for the new controllers that have been created. 
Also, refactoring some of their inner functions to have no side-effects would make them easier to test and maintain in the future.

This should generally increase stability for these pages.

**Comment by alexandru-m-g** [comment]
Estimate 1 day

**Comment by danmihaila** [comment]
@alexandru-m-g Can we close this one?

**Comment by alexandru-m-g** [comment]
@danmihaila I've created nose tests for the browse controller. We can move this to the next Sprint to also add tests for the country controller ( especially with the new country controller changes ).

**Comment by danmihaila** [comment]
@alexandru-m-g :+1:
