### ISSUE TITLE
Location Page: change to activity stream

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2288]
- [ ] remove the activity stream
- [ ] reformat the search result to look similar to /group/col (full width, blue bar).  However, on the Colombia page, we only have datasets, so to blend the to use this approach:

![image](https://cloud.githubusercontent.com/assets/1654485/6149459/5e4607d0-b209-11e4-9ade-e12b82692f4c.png)

**Comment by cjhendrix** [comment]
@ochadataproject Please take a look at the design above.  I don't think we want to make it exactly like Colombia since their page doesn't distinguish between datasets and indicators.  In fact, now that we have  the indicators tagged with locations, we may want to (later) update the colombia page to match the style proposed above.

**Comment by danmihaila** [comment]
CB background is smaller than pagination background at bottom of the page.
reassign to myself
