### ISSUE TITLE
Improving the way in which a dev docker environment is created

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#2290]
- [x] automating some steps by using `fig`
- [x] find a better way of dealing with the prod vs dev config files (.ini)
- [x] better integration with the IDE
- [ ] how to restore a snashot from production in case of a crises (added by dan)

**Comment by alexandru-m-g** [comment]
Estimate: 1 day

**Comment by danmihaila** [comment]
@alexandru-m-g  ping

**Comment by alexandru-m-g** [comment]
@danmihaila not sure what I should answer to "ping"

**Comment by danmihaila** [comment]
@alexandru-m-g @cjhendrix 
We should address this issue as soon as possible (I think we have space in Sprint 51) as we face several issues with docker configurations/creation, etc.

**Comment by alexandru-m-g** [comment]
I created a new document for using docker-compose ( formerly known as fig )
https://docs.google.com/document/d/1dxPkLVrIzyq82gPUzf4_gPU55_io0ZQLbxk5mOFwdqo

**Comment by danmihaila** [comment]
@alexandru-m-g is this completed? maybe we should give a try and use it to set Simon's computer...
