### ISSUE TITLE
Org create/edit: changes to support customizable org pages

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2298]
- [ ] Add a checkbox for "Use custom organization page" (visible only to sysadmins).  If this is checked, then some additional fields become visible on org create/edit.  These fields will be visible only to sysadmins for now.

Functions that are visible if "Use custom organization page" is checked.
- [ ] Upload logo (as in default ckan) - it will be marked as not required/mandatory field
- [ ] Set "Highlight color".  This provides a color picker for defining the color that is used for the background map, and dataset list tabs.  Defaults to HDX green.
- [ ] Configure topline numbers functionality: field for pasting a link to the datastore that contains the topline numbers (assumed to be in the standard format)

A question:  how could we use this approach to integrate a custom visualization which may  be present for some pages (WFP), but not others?

**Comment by alexandru-m-g** [comment]
@mbellotti @cjhendrix @danmihaila I think there's some discussion here on how we go about storing the logo and the additional metadata ( especially since I guess there will be more to come ).

**Comment by danmihaila** [comment]
Just a short story:
1. for  topline numbers will have 2 fields: one for dataset name and one for resource name.
2. we will store the settings in one field similar to geojson, and it will have a json format (logo url, highlight color, datastore information)
TODO:
@aalecs suggested to store less files, more discussions needed here.
