### ISSUE TITLE
Change to terms of service: UNCS stuff

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2307]
Replace point 12 of our terms of service with the following text:

"12. The designations employed and the presentation of material on this website do not imply the expression of any opinion whatsoever on the part of the Secretariat of the United Nations concerning the legal status of any country, territory, city or area or of its authorities, or concerning the delimitation of its frontiers or boundaries.  Data used to represent international boundaries in HDX provided by the UN Cartographic Section except where noted otherwise."

**Comment by cjhendrix** [comment]
@ochadataproject Please have a look at the text above.  It is identical to the existing text except the last sentence which is new.

**Comment by ochadataproject** [comment]
Not sure about the word unofficial before data. What does that mean if we
are also saying it's from UNCS?

**Comment by cjhendrix** [comment]
Ok, removed "unofficial".  I was just trying to re-state the point that the boundaries do not imply endorsement, but it's not really necessary.
