### ISSUE TITLE
Remove the CKAN base styling in the new pages

### ISSUE THREAD

**Issue by aalecs** [OCHA-DAP/hdx-ckan#2313]
We're still including the CKAN base styling in our newly created pages which have a new design and don't really depend on it anymore.
- remove lite-main.css & test - 1 day
- remove additional leftover classes in html - 1 day

**Comment by danmihaila** [comment]
@aalecs is this still an issue?

**Comment by aalecs** [comment]
@danmihaila  I did check what are the results of removing the CKAN default classes and these are the places where the UI breaks:
- datasets page 
  - stying for breadcrumbs
  - datasets labels (zippedshapefile, etc)
  - order by - wrong position
  - some distance in indicator preview between description and labels - might be caused by labels not rendering
- header - search box not vertically aligned 
- organisation - left side filters - styling for items needs fixing
             - search box needs to be redone + order by positioned
- dataset - files icons are missing
        - preview/update/dwd/share buttons for files are overlapping
        - missing "hot" icon
        - metadata table needs restyling
- sysadmin settings - need list restyling + round user icons
                  - config menu messed up
- user profile page - datasets spacings
- dashboard - newsfeed styling
- user settings - restyle whole form
- dataset edit - form restyling
             - resource edit whole list restyling 
             - resource edit/add restyle form
- organization edit - restyle
- location edit - restyle

We don't have time for this in this sprint, should we move it for next sprint?

**Comment by danmihaila** [comment]
I am not sure how I can test this one @aalecs I see many changes and probably will have some problems soon :)
