### ISSUE TITLE
Checking authorization for current_package_list_with_resources

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#2317]
The current_package_list_with_resources allows unauth access.

This is related to: https://github.com/ckan/ckan/issues/1507

**Comment by cjhendrix** [comment]
@takavarasha Let us know how important this api call is for you so we know how to prioritize it.

**Comment by takavarasha** [comment]
It is not that important. The major advantage is that it allows for a more efficient iteration through all packages.

**Comment by alexandru-m-g** [comment]
Maybe package_search could do the same thing ?
