### ISSUE TITLE
Track activity on private datasets

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2320]
See #2134 for discussion.

This enhancement implies that activity done to a dataset while private will become public if the dataset is made public.

**Comment by danmihaila** [comment]
@cjhendrix what to do about this one? is this a question ?

**Comment by cjhendrix** [comment]
I think it is still an issue.   And may affect the COD migration (see https://github.com/OCHA-DAP/cod-migration/issues/66)
