### ISSUE TITLE
Permalinks. How many types we want?

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#2322]
Hi. Currently the implementation of permalinks has been done in hdx-ckan (I talked with @alexandru-m-g  about this). Is there any reason why we keep the two ebola permalinks on nginx side?

I am proposing to just let google people know about the new URLs style and stop updating the old permalinks.

The reason: there are changes in the methodology and location of these links, making my permalink script whine about it. This usually happens on Friday evening :)

Today, I am the proud owner of 864 emails saying "file not found" :)
Not that I am upset, but this keeps me from focusing on real issues that may arise.

Please note that at this time I don't care where the resources are pulled from or the URL publishing it.

Tagging @alexandru-m-g and @luiscape for comments.
Tagging @cjhendrix for assigning priorities and milestone.

**Comment by teodorescuserban** [comment]
I changed my script to stop checking for the filestore real path (since it is no longer available in the URL path), making it usable again. 

I would rather just disable it altogether though.

**Comment by teodorescuserban** [comment]
No luck.

I will disable the script.

@luiscape , please tell google people to use the new URLs, because my script cannot operate in the new ckan permalink type (the script is making a symlink on a real file under a filestore but from now on the script cannot see what the real filestore is - theres not such info in the db anymore).

This is happening only for `f48a3cf9-110e-4892-bedf-d4c1d725a7d1` , `ebola-data-db-format.csv`

**Comment by cjhendrix** [comment]
Is there some outstanding action here for the dev team?  If not, let's close.
