### ISSUE TITLE
WFP Page: first review on dev branch

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2324]
Based on https://docs.google.com/drawings/d/1PE5sAfD7Iii0Gfvp106ipqkamR37iLAwdgfXGfBROek/edit
- [x] EDIT & MEMBERS - reverse order
- [x] Edit (org admin + sysadmin only) & Members  Visible only to members of the org (check annotated page)
- [x] "Data" - is a link to "https://data.hdx.rwlabs.org/organization/wfp"
- [x] pagination - there is a space between numbers which looks ugly (in FF and Chrome)

**Comment by cjhendrix** [comment]
Just confirming the above.  Thx @danmihaila

**Comment by alexandru-m-g** [comment]
@danmihaila @cjhendrix 3rd point is not a bug - check https://data.hdx.rwlabs.org/dataset/wfp-topline-figures/resource/7329f8c7-2112-499a-8b93-d6da0331d092

**Comment by cjhendrix** [comment]
Ah, yes, I get it.

**Comment by danmihaila** [comment]
@aalecs can we have the space between buttons "members"&"edit" similar to "follow"&"visit website" ?

**Comment by danmihaila** [comment]
@alexandru-m-g : this task needs a review.
initial req: Edit (org admin + sysadmin only) & Members Visible only to members of the org (check annotated page)

Currently:
-Members are visible if the user is logged in (and not if it is member of the org)
-Edit is ok.
pinging also @cjhendrix

**Comment by alexandru-m-g** [comment]
@danmihaila @cjhendrix 
The current implementation keeps the rules existing in HDX ( on the old org page ). Check for example: https://test-data.hdx.rwlabs.org/organization/wfp while logged in but not a member. Even if I were to hide the button current permissions allow a logged in user to see the members list.

You still want me to change this ?

**Comment by cjhendrix** [comment]
The annotated design does propose a change, but on second thought, I think it's fine to leave it as it is.  At least for now.  Sorry for the confusion.

**Comment by cjhendrix** [comment]
In case that wasn't totally clear, let's leave it as it is on staging now (members button is visible to logged in users regardless of membership in the org).

**Comment by danmihaila** [comment]
understand, so this item is ok.
we still have ongoing: the space between buttons "members"&"edit" similar to "follow"&"visit website" ? @aalecs will deal with it today.
