### ISSUE TITLE
Enable resource proxy

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2331]
Links to remote CSVs cannot be previewed, however this seems possible using the Resource Proxy:  http://docs.ckan.org/en/1117-start-new-test-suite/data-viewer.html#viewing-remote-resources-the-resource-proxy

**Comment by teodorescuserban** [comment]
It is working... At least for some.
Can you paste an axample url?

This works: https://data.hdx.rwlabs.org/dataset/ourairports-zwe/resource/16f7a1b9-1223-47ff-9e79-5abaf02dfda2

**Comment by cjhendrix** [comment]
In this one: https://test-data.hdx.rwlabs.org/dataset/evd-cases-by-district
CKAN seems to recognize that it is a csv (note the icon for the resource), even though the format is set to "link to csv".    However, preview is not available.  Changing the resource type to csv shows the preview button the returns an error from the remote server.  

Probably this isn't about resource proxy, but some other complexity of how their server is delivering the data?

**Comment by teodorescuserban** [comment]
Most likely.

**Comment by cjhendrix** [comment]
Ok, so we can't preview this because of how the source server delivers the file.  Archiving for now.

**Comment by khanh78** [comment]
Hello,

is anyone can help me to configure reource_proxy ?
do I need only add in ckan_plugin = resource_proxy ?

Thanks for your helps
