### ISSUE TITLE
Warn a user if a pcoded dataset contains admin units from different levels

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2337]
If a dataset returns admin units from more than one level, warn the user:

"This dataset contains p-codes from multiple levels.  The map that is drawn may not appear as you expect.  For best results, separate data from different administrative levels into separate files."

**Comment by danmihaila** [comment]
@cjhendrix we should close this one

**Comment by cjhendrix** [comment]
Agreed.
