### ISSUE TITLE
Pagination looks weird on /organization page

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#2344]
Check this link https://test-data.hdx.rwlabs.org/organization/hdx?sort=metadata_modified+desc or this one https://test-data.hdx.rwlabs.org/organization

Pagination looks weird:
![snapshot1](https://cloud.githubusercontent.com/assets/6586348/6258464/626c0c6a-b7d1-11e4-8d20-a79741814d8e.png)

**Comment by alexandru-m-g** [comment]
@danmihaila @cjhendrix do we need to fix this before going to prod ?

**Comment by cjhendrix** [comment]
No, I don't think it's a production blocker.

**Comment by cjhendrix** [comment]
I made a duplicate issue with some more locations where this is occuring.  #2365. Closing this one.
