### ISSUE TITLE
WFP page: after clicking the follow button, hover state is retained

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2346]
After an initial click,the follow button changes to the lighter gray hover state style.  It remains that way through subsequent clicks.  Interestingly, if the OS focus is moved to another application, the style reverts to normal.

![image](https://cloud.githubusercontent.com/assets/1654485/6263639/9cd9c556-b81a-11e4-9737-55223b6aacf9.png)

**Comment by danmihaila** [comment]
@cjhendrix I can not reproduce it anymore. closing it, please reopen if it is valid
