### ISSUE TITLE
Some files downloaded from a dataset do not have an extension

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#2357]
Sometimes the file that is downloaded from a dataset does not have a file extension. This occurs in those cases where Name field of the resource does not contain the file extension. Because this issue has the potential to make the downloaded data very difficult for a user to make use of, we fix the problem when we encountered it. However, the following steps will reproduce the problem:
1. On any resource, remove the extension from the Name of the resource
2. Save the resource and then click on the download link
The downloaded file will not have a file extension associated with it.

From cj:
We need to separate the file name of the download from the title of the resource.  But we need to think about how that will work if data is generated from the datastore for download (rather than the filestore).

**Comment by takavarasha** [comment]
This bug makes any affected download potentially unusable by the average user. May I suggest that the priority be set to high for this one

**Comment by cjhendrix** [comment]
@amcguire62 Ok for high priority sprint 50 for this one?

**Comment by amcguire62** [comment]
can i ask how often it happens - do we know?

**Comment by danmihaila** [comment]
I think it is everytime we don't keep the name(title) of files similar with
the filename. From what I remember it is not complicated to fix it.
Basically:
1. if the name contains the extension such as adm1_.zip_, adm0_.xls_ we
should do nothing and just leave it like this
2. if name doesn't contain the extension we should concatenate the format
(if exists!) with the name and return the file to the user for download.
There is a chance that user removes the extension from name and don't add a
format to the resource, this means the system will act as it is doing now.
​

**Comment by danmihaila** [comment]
ping @takavarasha about my last comment to agree on this. :)
