### ISSUE TITLE
DataStore / resource IDs for visualizations deprecated.

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2358]
Last week two accidents happened that led to the deletion of two resources. Those resources were feeding into visualizations on the [Ebola page](https://data.hdx.rwlabs.org/ebola) and the [Colombia page](https://data.hdx.rwlabs.org/group/col).

On the Ebola page, the resource with id [f48a3cf9-110e-4892-bedf-d4c1d725a7d1](https://data.hdx.rwlabs.org/api/action/resource_show?id=f48a3cf9-110e-4892-bedf-d4c1d725a7d1)  (ebola-data-db-format.csv) was mysteriously deleted while I was editing a different resource (ebola-data-db-format.xls). That deletion caused the sparklines for cases and figures to disappear. 

CKAN apparently doesn't "delete" resources from its database. By inserting data directly on the DataStore of the deleted resource, I updated the ebola deaths and cases figures to their latest. However, that means that the sparklines are now currently pulling data from a different resource than the one available to the general public.

The same issue happened on the Colombia page. The visual "Number of Internally Displaced People" was pulling data from a resource that was accidentally deleted by a member of the Data Team, making the visual disappear. I proceeded to do the same I did with the Ebola cases figure. 

**SUGGESTED ACTIONS:**
1. Update the Ebola deaths and cases sparklines code to pull data from the resource ID [c59b5722-ca4b-41ca-a446-472d6d824d01](https://data.hdx.rwlabs.org/dataset/ebola-cases-2014/resource/c59b5722-ca4b-41ca-a446-472d6d824d01) instead of f48a3cf9-110e-4892-bedf-d4c1d725a7d1.
2. Update the Colombia "Number of Internally Displaced People" to pull data from the new resource id [1f56da93-6622-477f-9b55-b109def3f248](https://data.hdx.rwlabs.org/dataset/idps-data-by-year/resource/1f56da93-6622-477f-9b55-b109def3f248) instead of the old one.

It could be also useful to have a discussion about how our visualizations depend on the DataStore and how DataStore tables can be fragile to those kind of accidental errors. 

I'm pinging @teodorescuserban, @alexandru-m-g, @aalecs, @cjhendrix, @amcguire62, and @danmihaila so you are all aware.

**Comment by alexandru-m-g** [comment]
@luiscape thanks for mentioning this. The way we were going about this is that a datastore should be defined by: dataset name + resources name ( exactly for such cases where resources might get deleted ). Apparently there's still some places that are directly using the resource ID and we should change that in the scope of this issue.

Sounds ok ?

**Comment by luiscape** [comment]
@alexandru-m-g That sounds like a great plan! The visualizations I mentioned above failed when the resources were deleted, so I'm not sure if the solution you outlined has been implemented in those cases. I think it should work ...

**Comment by luiscape** [comment]
@alexandru-m-g I just checked today and the problem still persists. The DataStore scripts I'm running update the datastores for the resource `ebola-data-db-format.csv` of https://data.hdx.rwlabs.org/dataset/ebola-cases-2014. However, the sparklines on the Ebola page pull data from a different, deleted resource / DataStore.

Right now I'm running two scripts: (1) to update the DataStore from the current resource and (2) to update the DataStore from the deleted resource. 

Please advise on what to do.

**Comment by alexandru-m-g** [comment]
@luiscape will deal with it as part of the next Sprint. Is that ok ?

**Comment by luiscape** [comment]
@alexandru-m-g Sounds great. Thank you!

**Comment by alexandru-m-g** [comment]
After discussing with @luiscape @cjhendrix :
-  we're switching to use datastore IDs ( both in UI and config ) for charts and top line numbers
-  there still exists an issue in case a datastore ( that is used on the ebola or colombia page) gets deleted
-  in the future there should be a way to change the datastore ID from the UI for all charts / top line nums
-  in the meantime that "hardcoded" datastore IDs are in common-config and they can be overwritten in prod.ini:

```
## Chart / Top line num source settings

# Ebola page
hdx.ebola.datastore.top_line_num = a02903a9-022b-4047-bbb5-45127b591c85
hdx.ebola.datastore.cases = c59b5722-ca4b-41ca-a446-472d6d824d01
hdx.ebola.datastore.appeal = 93b92803-f9fa-45f4-bf72-73a8ab1d8922

# Columbia page
hdx.colombia.datastore.top_line_num = f78fe6f8-c363-4988-a847-b7c1c81ca233
hdx.colombia.datastore.displaced = 1f56da93-6622-477f-9b55-b109def3f248
hdx.colombia.datastore.access_constraints = 9e69d499-0b2b-4da6-9c61-10e453a57504
```
