### ISSUE TITLE
Dataset View: Add update function to resource

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2360]
Add update function as described here: https://drive.google.com/file/d/0B-1-N0EKs6IBZURrRkNObWNlRXc/view

**Comment by alexandru-m-g** [comment]
@cjhendrix @danmihaila 
I think it's a bit unclear what should happen with the so called "unnecessary fields" from the frog slideshow ( notes & format ) when a new version is uploaded ( or link is changed ). 
Keeping the old values might not be a good idea as  the new version ( of the file ) might be a different format.

Maybe we should just have an "edit" button that takes the user to the "resource edit" page.

**Comment by danmihaila** [comment]
My advice is also to have "Edit" button that will redirect user to "resource edit" page.
I agree with @alexandru-m-g that if we have "excel" file with "xls" format and we upload a "csv" file as an update the user will not be able to change that format.
I also agree, that the update/edit button is very useful and save a lot of clicks.
Pinging also @amcguire62 and @ochadataproject about this issue
