### ISSUE TITLE
Custom Org Page: improvements to filters for long lists

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2362]
- [ ] Add a text entry field to each filter to allow searching through long lists. 
- [ ] Place long lists in a scrollable box.

**Comment by danmihaila** [comment]
@cjhendrix I think we already have this feature. can we close this one?
![screen shot 2015-08-27 at 16 10 16](https://cloud.githubusercontent.com/assets/3865844/9521215/2a730986-4cd6-11e5-82fc-5f8b4c45f24c.png)

**Comment by cjhendrix** [comment]
No, we don't have it yet, but the functionality you screencapped is what I am suggesting we add to custom org.

![image](https://cloud.githubusercontent.com/assets/1654485/9576496/717e03da-4fd8-11e5-908f-959f37130b41.png)

**Comment by danmihaila** [comment]
I misread the title. Assigned @yumiendo for more comments
