### ISSUE TITLE
Pagination styling has changed on some legacy pages

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2365]
On some of the pages that are still on the old design, the pagination controls have gotten squeezed. 

![image](https://cloud.githubusercontent.com/assets/1654485/6372249/a4f70ebc-bcfa-11e4-9f1c-0fa2f6367d3b.png)

This is happening (at least) on 
- Organization view page
- My datasets
- /user
- /organization

**Comment by danmihaila** [comment]
i think this is fixed, closing it
