### ISSUE TITLE
User menu dropdown icons not always visible

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2366]
Compare user menu dropdown on home page to any other page:

![image](https://cloud.githubusercontent.com/assets/1654485/6373774/c8612946-bd04-11e4-932e-7082f019e1a3.png)

**Comment by cjhendrix** [comment]
So it looks like our solution was to eliminate them everywhere?

**Comment by danmihaila** [comment]
I think the new design didn't contain those icons. On home page it was the initial code from CKAN

**Comment by cjhendrix** [comment]
got it. Thanks.
