### ISSUE TITLE
Add an "Are you sure" modal to the "make it public/private" links on the the dataset view page

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#2370]
![image](https://cloud.githubusercontent.com/assets/6885303/6377120/17983ac8-bcf0-11e4-85e6-4061aa5ae429.png)

**Comment by cjhendrix** [comment]
Proposed text:  

**Make it private:**  _Are you sure?  This dataset will only be visible to members of the owning organization and will not be visible in search results._

**Make it public:** _Are you sure? This dataset will be visible to all users of HDX._
