### ISSUE TITLE
Test the datastore retrival of large datasets for a visualisation

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2379]
We want to test simon's wfp viz queries (or similar) against a 1 million row dataset.  

We could use the data below as a template (though I think there are far less than 1 million rows).  We could fake some data if needed. 

Here is the link to download the “Food Prices” datasets:
For the “West Africa” Countries: http://vam.wfp.org/sites/data/FoodPrices_OMD_24-02-2015.xlsx (updated)
For the “East Africa” Countries: http://vam.wfp.org/sites/data/Food%20Prices_OMN_19-02-2015.xlsx (new)

Please note:
This dataset still requires some further cleaning.
**This dataset should be used only for “Development” and not for “Production”.**

**Comment by SimonbJohnson** [comment]
The kind of queries I am thinking about are averaging prices by country for the last three months across all products.

**Comment by alexandru-m-g** [comment]
Here are some results from my datastore retrieval tests:
-  The following request to the "datastore_search_sql" endpoint takes  on my laptop around 2 minutes to complete for a datastore_table with 2 500 rows and limit 250 000. Without the limit I imagine it would take around 50 mins (There would be 2 500 x 2 500 rows in the response). 
  -  curl -G localhost:5000/api/action/datastore_search_sql --data-urlencode "sql=SELECT a.\* from datastore_table a, datastore_table b limit 250000" 
-  accessing the "datastore_search" endpoint with a limit of 250 000 takes also about 2 mins ( for a table of around 500 000 rows )
  -  curl "http://localhost/api/action/datastore_search?resource_id=resource_id&limit=250000"
-  there's no way to set a hard limit that cannot be overwritten by the user for the number of results returned by a query to the datastore

So, a user with bad intentions could achieve a denial of service. 

Advices from the CKAN mailing list suggest the following:
-  have nginx limit the request rate (total and from a single IP) to the datastore api
-  make CKAN use less memory by making sure response strings can be garbage collected. We would need to merge this work https://github.com/ckan/ckan/pull/2262
-  make sure that our server can deal with the max number of requests set (so worst case the site is blocked, but the servers won't go down)

**Comment by alexandru-m-g** [comment]
More info can be found here: https://docs.google.com/document/d/15ibzZZ8sI5eT8HbQM-MnFphjysrLTkwwaOFQj_FmpJI

**Comment by danmihaila** [comment]
Excellent @alexandru-m-g 
Pinging @amcguire62 and @cjhendrix to have also a look over this doc

**Comment by alexandru-m-g** [comment]
Pinging @SimonbJohnson and @luiscape as well. Please check the above google doc.

**Comment by luiscape** [comment]
Got it. I'll take a look at the document.
