### ISSUE TITLE
Local install of ogr2ogr on our servers

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2382]
We will use this as the method for converting geodata (at least for now).   If this looks complicated, we should reconsider since we may eventually want to use geoserver (or similar) to do this job.

**Comment by danmihaila** [comment]
ping @aalecs also because he might have an idea as he digged into this

**Comment by aalecs** [comment]
I also created some scripts to deploy the ogre docker ... they are on the OCHA-DAP/ogre repository. We can chat when you want to start on this ;)

**Comment by danmihaila** [comment]
@teodorescuserban @aalecs lets have a chat this week in preparation for next week deploy to prod

**Comment by danmihaila** [comment]
@teodorescuserban what is the status of this issue?

**Comment by teodorescuserban** [comment]
made the initial image.
please pull it by typing `docker pull teodorescuserban/hdx-ogre`
let me know if ogre need to automatically start as a service (now you just enter the created container and type in `ogre -p 3000`).

**Comment by teodorescuserban** [comment]
Done.
Closing.
Please reopen if there's any issue with the container.
