### ISSUE TITLE
Finalize geodata preview

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2384]
In Liverpool, we added a geodata preview component to datasets that have "zipped shapefile" resources.  This issue covers finalizing that interface including: 
- [x] Checkboxes instead of radio buttons for layers
- [x] adjustments to design of template (cj to review)
- [x] fix the /tmp file problem (dan)
- [x] if a resource contains geojson and it is marked with "geojson" display it on the map (dan)

What else?

**Comment by danmihaila** [comment]
@cjhendrix @aalecs added 2 more subtasks
