### ISSUE TITLE
Datastores identified by resource id

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2391]

**Comment by mbellotti** [comment]
Change topline number customization so that user enters resource ID instead of name, ask @alexandru-m-g if there are other areas where this pops up

**Comment by alexandru-m-g** [comment]
@mbellotti Also for the vizualization data, no  ?

**Comment by mbellotti** [comment]
Viz already use resource id ;)

**Comment by alexandru-m-g** [comment]
Cool. Wasn't sure. I know that before there was also input box for datasets name. This is not needed anymore.
