### ISSUE TITLE
Geo-preview: resources/datasets created via API don't trigger the generation of geojson

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2396]
@luiscape can you link the script you are using to create datasets via API?

**Comment by luiscape** [comment]
Hi @danmihaila, the script to create datasets is available [here](https://github.com/luiscape/hdxscraper-unosat/blob/master/code/create-datasets.py). It loads dataset metadata from a file called [datasets.json](https://github.com/luiscape/hdxscraper-unosat/blob/master/data/datasets.json) and resources data from a file called [resources.json](https://github.com/luiscape/hdxscraper-unosat/blob/master/data/resources.json).

**Comment by luiscape** [comment]
@danmihaila Any updates on this issue?

**Comment by danmihaila** [comment]
@luiscape we didn't work on this as it was not on our top priority list. Pinging @amcguire62 and @cjhendrix

**Comment by luiscape** [comment]
Sounds good.

**Comment by danmihaila** [comment]
closing this one and will create another issue

**Comment by danmihaila** [comment]
moved to https://github.com/OCHA-DAP/hdx-ckan/issues/2999
