### ISSUE TITLE
Geo-preview: check files with multiple layers or big sizes

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2397]
Actions:
- [ ] Handle files with multiple geo data sets in a zip (common for shapefiles). 
- [ ] We probably need to set a limit on how big a file we store as geojson so as not to kill the browser.  We'll have to figure out later how to communicate that to the user.

From @cjhendrix :
For this one: https://test-data.hdx.rwlabs.org/dataset/geodata-of-standing-waters-in-tarind-muhammed-panah-area-punjab-province-pakistan. It has multiple shapefiles in one zip, which is not working on staging.

**Comment by cjhendrix** [comment]
I'm going to close this one since it needs to be updated a bit for the new vector tiles geo preview.  I'll make a new issue.
