### ISSUE TITLE
Custom org page: merge WFP controller & template with custom org pages

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2399]
There should be only one controller and template that display a custom org page based on the flag that a sysadmin is set in org page admin.
Basically, we should bring the work from WFP to the custom org page controller&template

**Comment by alexandru-m-g** [comment]
If i'm not mistaking, this is the way it works now ( unless you go to /alpha ). So not sure it needs to be high priority.

**Comment by alexandru-m-g** [comment]
@mbellotti  please note I did a commit here #2347 on the wfp controller. The last commit is the one that matters.

**Comment by mbellotti** [comment]
Cool. Thanks for letting me know :)
