### ISSUE TITLE
Epic: Geo Preview on Prod

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2401]
Things that need to be done to get geo preview to prod: 
1. Handle failed transformations, probably by simply not showing the preview.  Ideally we would communicate this to the creator so they know that something has gone wrong, but that's probably not MVP
2. Handle file types better.  User's shouldn't need to know magic words like "zipped shapefile" to get their data to be used for geo preview.   Add a flag in the resource create/edit flow for users to indicate "This resource contains geographic data."  Default would be unchecked.  
3. Handle large files intelligently.  We need to not try to push large geojson files to the browser, but we probably need to let people know why.  Some sort of "this geographic dataset was too large to preview" message instead of the map perhaps?  In addition, we could try to display only the bounding box of the data on the map with the message.
4.  For resources that are external links, we will need to update the previews periodically (daily?) and somehow alert us when something goes wrong.
5. Handle zip files with multiple shapefiles in them. 
6. Handle shapefiles with bad data.  Example:
   - 3 bad points that can't be drawn by qgis and appear to prevent leaflet from drawing.  Converted geojson has coordinate values so large (1x10^380) it kills the browser: http://ebolageonode.org/geoserver/wfs?format_options=charset%3AUTF-8&typename=geonode%3Asle_heal_pt_unmeer_ebolacarefacilities&outputFormat=SHAPE-ZIP&version=1.0.0&service=WFS&request=GetFeature&filter=%3CFilter%3E%3CPropertyIsEqualTo%3E%3CPropertyName%3EType%3C%2FPropertyName%3E%3CLiteral%3EETU%3C%2FLiteral%3E%3C%2FPropertyIsEqualTo%3E%3C%2FFilter%3E

**Comment by cjhendrix** [comment]
@ochadataproject Items 1, 2, & 3 above have some UI implications.  I don't think they probably need Yumi's input, but please add her to the issue if you want her to work on it.

**Comment by amcguire62** [comment]
CJ in terms of MVP - which of those have to be done

for example this one

"
1. Handle file types better. User's shouldn't need to know magic words
   like "zipped shapefile" to get their data to be used for geo preview. Add a
   flag in the resource create/edit flow for users to indicate "This resource
   contains geographic data." Default would be unchecked."

we could for example put in a help notice for this one - it would not stop
us going to production (IMO)

On Fri, Mar 6, 2015 at 3:01 PM, cjhendrix notifications@github.com wrote:

> Things that need to be done to get geo preview to prod:
> 1. Handle failed transformations, probably by simply not showing the
>    preview. Ideally we would communicate this to the creator so they know that
>    something has gone wrong, but that's probably not MVP
> 2. Handle file types better. User's shouldn't need to know magic words
>    like "zipped shapefile" to get their data to be used for geo preview. Add a
>    flag in the resource create/edit flow for users to indicate "This resource
>    contains geographic data." Default would be unchecked.
>    1. Handle large files intelligently. We need to not try to push large
>       geojson files to the browser, but we probably need to let people know why.
>       Some sort of "this geographic dataset was too large to preview" message
>       instead of the map perhaps? In addition, we could try to display only the
>       bounding box of the data on the map with the message.
> 3. For resources that are external links, we will need to update the
>    previews periodically (daily?) and somehow alert us when something goes
>    wrong.
> 4. Handle zip files with multiple shapefiles in them.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCHA-DAP/hdx-ckan/issues/2401.

## 

Aidan
ScraperWiki.com - A Gigaom
http://gigaom.com/2014/01/28/the-structure-data-awards-honoring-the-best-data-startups-of-2013/
Structure
Data Award Winner 2014

**Comment by cjhendrix** [comment]
I consider all of these mvp.  

What you propose above would mess with users' ability to search by file type.

**Comment by cjhendrix** [comment]
OBE.  Closing.
