### ISSUE TITLE
Custom org page: small issues in admin interface

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2412]
When edit an organization there is 
1. another link "Edit" that appears
2. a mispelled  "Use custom organization page::" -> "Use custom organization page:"
Check screenshot
![screen shot 2015-03-10 at 14 58 31](https://cloud.githubusercontent.com/assets/3865844/6575323/73c17c2e-c736-11e4-80a5-70a80ba3abdf.png)
@mbellotti please note that this is tested local only, not on dev or stag so it might be fixed on your local version

**Comment by mbellotti** [comment]
Sorry I should have asked this before, but what should be there instead of the Edit link?

**Comment by danmihaila** [comment]
I saw that on our regular org page edit (prod) the link is visible and it looks ok. Probably we have a problem with our style.
I don't see any reason to keep that "Edit" link. Can you please hide it together with the horizontal line?
