### ISSUE TITLE
Custom org page: template updates - new mockups

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2419]
Update the custom org page templates based on this wireframes:
https://drive.google.com/drive/#folders/0B16fOsnmtif0ZGdaa3ZTT3ZqZ00/0B16fOsnmtif0YVZNcmJzRGY5NWc/0Bw5omaSZ5BTHTEg1a0NLRElXU1k/0Bx1KWNTx8Ij3MHFVRjluX3NqQ3c/0B4J8rDnUw80gNXpiQ3NtbU1BQVk/0B24NBcgmV490NUdHYmNTWW8tTWc/0B24NBcgmV490dmlzMDVxN253WHc

Subtasks:
- [x] check the full template against specifications: https://drive.google.com/drive/#folders/0B16fOsnmtif0ZGdaa3ZTT3ZqZ00/0B16fOsnmtif0YVZNcmJzRGY5NWc/0Bw5omaSZ5BTHTEg1a0NLRElXU1k/0Bx1KWNTx8Ij3MHFVRjluX3NqQ3c/0B4J8rDnUw80gNXpiQ3NtbU1BQVk/0B24NBcgmV490NUdHYmNTWW8tTWc/0B24NBcgmV490dmlzMDVxN253WHc/0B24NBcgmV490fkhocnlEdkpsZDRYVzJDYzBydWNia0lleVNZZzNwSl9hcFJoZlVSSTNlOTA
- [x] organization header : description (more/less), buttons (share, etc): https://docs.google.com/file/d/0B24NBcgmV490UmZVMFNabEZzeEk/edit
- [x] organization logo: https://docs.google.com/file/d/0B24NBcgmV490UmZVMFNabEZzeEk/edit
- [ ] scrolling logo https://docs.google.com/file/d/0B24NBcgmV490eWpUWFNkamFUTGc/edit . When you mouse over the logo will also display the name of the organization and "Share link": https://docs.google.com/file/d/0B24NBcgmV490TWU5Ri10blpXeTQ/edit . Check also the specs for logo.

**Comment by aalecs** [comment]
Still need to: 
- include number of members and followers
- user the smaller log (once it's ready) 
- hide members link when user not logged in

**Comment by alexandru-m-g** [comment]
Committed change to 1st point above: "include number of members and followers"
