### ISSUE TITLE
Custom location page: Controller and template

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2422]
Controller and template should be similar with Colombia page and copy from there as a general one that will work for custom locations

**Comment by alexandru-m-g** [comment]
@danmihaila @cjhendrix 
The Colombia page shows the dataset search results with no tabs ( basically the "All" tab ). Do we keep it like this or move to the 3-tab solution ?

**Comment by danmihaila** [comment]
@alexandru-m-g the custom location page should be identical with Colombia page. :) So, yes - no tabs

**Comment by cjhendrix** [comment]
@amcguire62 Included that in his list of specs to Sarah and there was no complaint, so as Dan said, no tabs.  Just for the record, I don't like it.  ;)

But to clarify one thing:  the Colombia page dosn't have the "ALL" tab, it has only the "DATASETS" tab, which is how it should be for Mali.

**Comment by alexandru-m-g** [comment]
@cjhendrix you're right: just datasets
