### ISSUE TITLE
Custom org page: dataset view add logo

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2423]
The datasets that belongs to a custom org page should display the logo of the organization as it specified here:
https://docs.google.com/file/d/0B24NBcgmV490dWFYdFpzV05tR3M/edit

**Comment by alexandru-m-g** [comment]
@cjhendrix @danmihaila 

A few things are unclear to me. The link is to a simple template but real life examples are a bit more complicated. Uploading screenshots below:

![a](https://cloud.githubusercontent.com/assets/6586348/6739766/b6e3d110-ce83-11e4-8f29-896d3cde076f.png)
![b](https://cloud.githubusercontent.com/assets/6586348/6739765/b6e2acfe-ce83-11e4-96a0-057930ddf25e.png)
-  Do we move all 4 buttons to the left under the title ( and the description for normal datasets ) ? Even for indicators ?
-  The color of the box wrapping the logo is always blue  ?
-  The size of the logo seems to be fixed. So I'll stretch the image uploaded by the user to fit the exact size ?
-  The logo will appear in the same place even for indicators ( meaning over the chart ), right ?

**Comment by cjhendrix** [comment]
@yumiendo Can you help us with Alex's questions above.  These become blockers for Alex early next week.  I don't think mockups are needed, just  a discussion between you guys about how to handle it.

Tagging @amcguire62

**Comment by yumiendo** [comment]
@alexandru-m-g 
my answers below: (just clarified with extended team...)

Do we move all 4 buttons to the left under the title ( and the description for normal datasets ) ? Even for indicators ?

> yes, please move the buttons to align left. 
> - For now we will just have dataset pages with org logo (logo links to the org page) and no indicators will have org logo(as of now). 
> - Also, we'd need to wrap the description (quickly did the admin view here: https://drive.google.com/file/d/0B24NBcgmV490d1dTa2d3VnpraUE/view?usp=sharing)

The color of the box wrapping the logo is always blue ?

> there are two scenarios - there is a spec for logo treatment here(the size for org's logo on dataset page isnt included in this document but the two scenarios are the same: https://drive.google.com/file/d/0B24NBcgmV490LXByQTZLd0lHZmM/view?usp=sharing)
> 1. org's logo is made of multiple colors (background color will be gray-ish white with a stroke)
> 2. org's logo is made of one color (background is the org color. ie. blue, orange, red etc. and place white version of the logo on top) if you are working on specific case and confusing - pls feel free to ask. 

The size of the logo seems to be fixed. So I'll stretch the image uploaded by the user to fit the exact size ?

> logo area is fixed. depending on the logo shape (is it more vertical or horizontal) the maximum width or height should be applied. (so proportionally scale up until it either hits height or width.) 

The logo will appear in the same place even for indicators ( meaning over the chart ), right ?

> No, it will just be dataset pages for now. 

Thanks ! let me know if you have any more question.

**Comment by alexandru-m-g** [comment]
@yumiendo thanks for the reply.

Just a comment/question on the color of the box wrapping of the logo:
1.  on the custom org pages the logo is uploaded/updated by the user 
2.  there's no easy way to know if the logo the user has uploaded has 1 color or multiple 
3.  on the other hand, the same user also selects a base color for the page ( that is used for the background of the custom org page ) - that color could be used also for the logo wrapper color
4.  alternatively to (3), we could allow the user to select another color specifically for the logo wrapper ( and if needed this selection could be limited )

**Comment by danmihaila** [comment]
I think we should go with two options:
1. gray-ish white with a stroke - default option in admin custom org (checkbox unchecked)
2. same color as background color picked by user (checkbox checked)
@yumiendo @cjhendrix please confirm

**Comment by cjhendrix** [comment]
Sounds reasonable to me, but it's @yumiendo who has to make the call.

**Comment by yumiendo** [comment]
Hi everyone, sounds like we have a solution :+1: 
thanks @alexandru-m-g for the suggestions + Im ok with @danmihaila 's suggestion of the above 1/2 options.
