### ISSUE TITLE
Custom location page: admin - "topline configuration"

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2426]
This is section that will customize the "topline" from custom location page.
Required fields:
- [ ] resourceID
- [ ]

**Comment by danmihaila** [comment]
@alexandru-m-g or @aalecs please help with the other required fields for this section.

**Comment by alexandru-m-g** [comment]
For now we have a standard structure for the table that contains the topline numbers. If we keep the structure the same we probably don't need more configuration options for now.
