### ISSUE TITLE
Custom location page: admin - "Charts configuration"

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2427]
There will be two sections: "Chart 1 Configuration" and "Chart 2 Configuration". We should give the option to user to add multiple sources for one chart. For example if we want to display a double line chart on the same chart: one line is coming from one resource and the second line will come from a second resource.
Chart X Configuration fields:
- [ ] Title
- [ ] Description
- [ ] Visualization type (dropdown with predefined vizualizations) - check this issue #2428 
- [ ] Title X axis (the text to be displayed on X axis)
- [ ] Title Y axis (the text to be displayed on Y axis)

To specify the SOURCE there will be at least 3 fields:
- [ ] ResourceID (the datastore table that contains data)
- [ ] X axis source (the column from datastore table which will be displayed on X axis)
- [ ] Y axis source (the column from datastore table which will be displayed on Y axis)
- [ ] Source Title/Description

User will also have an icon "+" and it is clicked it will add another subsection SOURCE (with three fields: resource ID, time column, values column). We will limit to three subsections SOURCE for the moment.
User will also have an icon "-" which will remove a subsection SOURCE
All fields, except Visualization type, are text edit boxes.

**Comment by danmihaila** [comment]
We agreed to have 2 static "source" sections in this sprint.

**Comment by mbellotti** [comment]
Source Title/Description will be pulled from the resource metadata since there's no reason to duplicate it here.

**Comment by alexandru-m-g** [comment]
For the resources that are used to build the charts we need both the resource_id and the **dataset_id** in order to create the link back to the dataset. Didn't know about this requirement before.

**Comment by danmihaila** [comment]
lets have a call about this. In my opinion we should avoid to have too many fields in admin interface. In our case I will try to remove the dataset_id from map config too.
Pinging @mbellotti @cjhendrix

**Comment by cjhendrix** [comment]
Happy to have a call if needed.  But remember that ugly and complicated is ok since the audience is the data team.  We can try to improve the usability later.  Of course people will likely complain (I've made a couple of org pages and found it to be cumbersome), but the guidance on that has been clear.

**Comment by danmihaila** [comment]
ok. So, we should add the dataset_id as well?
I am ok if we have time. :)

**Comment by danmihaila** [comment]
Created https://github.com/OCHA-DAP/hdx-ckan/issues/2568 based on these comments and I will close this issue.
