### ISSUE TITLE
problem with less compilation on dev server

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#2429]

**Comment by alexandru-m-g** [comment]
- there was a problem with the rights for these 2 folders: 
  -  /srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/public/css/generated
  -  /srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/less/tmp

**Comment by teodorescuserban** [comment]
Fixed in the newest version of hdx-ckan docker image.
