### ISSUE TITLE
Prod HOTFIX: about page is not aligned

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2435]
About page is not well aligned.
![screen shot 2015-03-16 at 12 27 33](https://cloud.githubusercontent.com/assets/3865844/6664395/e94c5c7a-cbd7-11e4-8013-555e63d37a3e.png)

**Comment by cjhendrix** [comment]
Weird.  Not sure how that would have gotten changed.  I'll take a look at it.

**Comment by cjhendrix** [comment]
I thought this was in wordpress, but it isn't. We'll have to assign it to someone else.

**Comment by danmihaila** [comment]
it's something with bootstrap, header, etc.
I was thinking of @aalecs if he has time today
