### ISSUE TITLE
Create/Edit Org Page: default colors for main nav

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2440]
Set the default LESS values (when creating a new org) for the main nav so that it matches the default HDX main nav.

**Comment by danmihaila** [comment]
@cjhendrix is this still an issue?
@aalecs can you confirm if we are using the same color as HDX main nav?

**Comment by danmihaila** [comment]
ping @cjhendrix

**Comment by cjhendrix** [comment]
It's done.  Closing.
