### ISSUE TITLE
Create/Edit Org Page: 3W map settings

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2441]
Currently, the user would need to know cryptic values for X, Y and zoom level to get the map to display.  We need to understand how these setting work (from @SimonbJohnson ) and figure out a way to make it easy for the data team to configure the map.

**Comment by SimonbJohnson** [comment]
@cjhendrix I'm planning to create a new version of the widget that is integrated with leaflet.  These settings would then not need to be used as the library can zoom to geojson extent.

**Comment by danmihaila** [comment]
@SimonbJohnson any update on this issue?

**Comment by danmihaila** [comment]
I played a bit with numbers for SNGO and it looks almost good. I am closing this issue as it is duplicated by https://github.com/OCHA-DAP/hdx-ckan/issues/2578
