### ISSUE TITLE
Custom Org Page: some pages producing 500 errors

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2442]
Some orgs return 500 errors with tagged to use the custom org page template, while others do not (even though neither have any of the custom fields configured).  On staging (at the moment: 

https://test-data.hdx.rwlabs.org/org/innago  returns a 500 error
while 
https://test-data.hdx.rwlabs.org/org/acaps loads the page.

**Comment by danmihaila** [comment]
I also see that when it is custom, the url is changed to /org/

**Comment by mbellotti** [comment]
Alex is going to take this one since he can reproduce it :)

**Comment by alexandru-m-g** [comment]
The problem was related to pagination. So the reason why it was hard to reproduce: it was only appearing on custom org pages which had enough datasets to make pagination necessary.

**Comment by danmihaila** [comment]
nice! excellent @alexandru-m-g
