### ISSUE TITLE
Custom org page: error with tabs

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2453]
Screenshot attached. If you click on tabs of the datasets list you will go to the url https://test-data.hdx.rwlabs.org/organization/custom_org_read?ext_indicator=1&id=custom-sngo#datasets-section
and get a 404 error page.
![screen shot 2015-03-17 at 12 27 31](https://cloud.githubusercontent.com/assets/3865844/6685292/2233a2e0-cca1-11e4-829d-e1493c686d05.png)
We should fix this before going to prod tomorrow

**Comment by alexandru-m-g** [comment]
This was mostly related to the switch of custom pages to the "/organization" url
