### ISSUE TITLE
Epic: better alignment between staging and production

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2456]
We seem to be bumping into the differences between staging and production more frequently.  The latest instance is that it is difficult to test the custom org page since the filestore is not actually on staging.

Should we start copying the filestore over as well as the ckan db?  What other differences are there that we might be able to tighten up?

More broadly, do we need to consider having both a staging and a test server?

**Comment by danmihaila** [comment]
I think we already have this one, @teodorescuserban is doing the copy of filestore. closing it
