### ISSUE TITLE
Preview of dataset on staging fails, dowloads lose extension

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2457]
1. create a new dataset on staging
2. add a csv file
3. try to preview (fails saying the file could not be retrieved from filestore)
4. try to download (file extension is lost)

I think this must be related to a recent change.

**Comment by teodorescuserban** [comment]
fixed. related to reenabling basic http auth on stag.

**Comment by danmihaila** [comment]
fixing also the csv extension
