### ISSUE TITLE
Custom Org Page: 3W visualization to use CSV for non-geo data

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2464]
@mbellotti @SimonbJohnson Please confirm if this is correct:

Currently, a 3W visualization must point to a json file of of the 3w data.  CSV files (or any other format) will not work.  We need to support at least CSV.

**Comment by mbellotti** [comment]
No, CSV files will work if the Datapusher is enabled. The input has to be in JSON, there's no getting around that. If what's the filestore is already in json you can run the visualization from that. If it's CSV (or a spreadsheet) you need to push it into the datastore, which means you either convert the CSV to JSON yourself and use the api or we re-enable the datapusher. cc @alexandru-m-g

**Comment by cjhendrix** [comment]
Good clarification.  Thanks.   Not that I think we should do this, but couldn't we also run the csv through data proxy to convert it on demand?

**Comment by cjhendrix** [comment]
Datastore enabled.  Closing.
