### ISSUE TITLE
Dataset View Page: breadcrumb should not say "indicators" unless the dataset is an indicator

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2467]
Use our existing indicator flag to modify the breadcrumb.  For non-indicators the breadcrumb should be 

`HOME / DATASETS / FOO`

For inidicators:
`HOME / INDICATORS / FOO`

![image](https://cloud.githubusercontent.com/assets/1654485/6707146/60c5fbd4-cd64-11e4-8552-2c03b9a861b1.png)

**Comment by danmihaila** [comment]
@mbellotti 
We got some errors for nosetests after merge. I think one test is related to this issue, and other to the other changes you did.
Pls check log below
++++++++++++++++++++++++++++++++++++++++++++++++++++
Running tests for plugin ckanext-hdx_search

# 

ERROR: ckanext.hdx_search.tests.test_pages.test_breadcrumbs.TestBreadcrumbs.test_breadcrumb_on_dataset_page
UndefinedError: 'last_user' is undefined
-------------------- >> begin captured logging << --------------------
ckan.lib.uploader: CRITICAL: Please specify a ckan.storage_path in your config
                        for your uploads
--------------------- >> end captured logging << ---------------------

# 

ERROR: ckanext.hdx_search.tests.test_pages.test_breadcrumbs.TestBreadcrumbs.test_breadcrumb_on_search_page
 File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 372, in getattr
   return getattr(obj, attribute)
UndefinedError: 'last_user' is undefined

# 

ERROR: ckanext.hdx_search.tests.test_search_results.test_search_results.TestHDXSearchResults.test_hdx_search_results
   return getattr(obj, attribute)
UndefinedError: 'last_user' is undefined

---

Ran 8 tests in 23.020s

FAILED (errors=3)
++++++++++++++++++++++++++++++++++++++++++++++++++++
Running tests for plugin ckanext-hdx_theme

# 

ERROR: test_search_page.TestSearchPage.test_active_tab
 File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 372, in getattr
   return getattr(obj, attribute)
UndefinedError: 'last_user' is undefined

---

Ran 12 tests in 35.175s

FAILED (errors=1)

**Comment by mbellotti** [comment]
....that's weird. I didn't touch that part of the code O.o

**Comment by danmihaila** [comment]
Maybe from another issue you changed. Can you please check?

**Comment by mbellotti** [comment]
No, that's what I mean. It's not this issue it's #2490 but even then I didn't touch the piece of code that is erring here and the nosetests are passing when I run them locally.
