### ISSUE TITLE
geo-preview: geo transformation via ogre not triggered for private datasets

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2468]
1. Create a private dataset
2. add a resource (zipped shapefile)
3. check dataset - no geo-preview
4. make dataset public
5. save again the resource (not need to reupload it)
6. check dataset - geo-preview is enabled

**Comment by teodorescuserban** [comment]
See the dataproxy issues on the same topic.
Basically the ckan api call to ogre need to pass user's api key and ogre needs to pass that back to ckan so that the private dataset may be accessed.
More details +mbellotti

**Comment by danmihaila** [comment]
@alexandru-m-g you should check this feature also when doing the new GIS module. Closing this issue
