### ISSUE TITLE
Prod server: /dataset is loading with low speed

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2477]
Check this url:https://data.hdx.rwlabs.org/dataset?res_format=zipped+shapefile
It takes 5-6 seconds to load. can we improve it?

**Comment by teodorescuserban** [comment]
3-4 seconds on my notebook.

I see a spike in ckan and solr activity When I load that page. (45% ckan, 28% solr).

**Comment by danmihaila** [comment]
I see a bit of improvement. Soon, we might want to get into some tests with custom pages.
