### ISSUE TITLE
A dataset is wrong

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#2478]
Steps
1. Navigate to https://data.hdx.rwlabs.org/dataset/ebola-treatment-centers/resource/e8a9fa59-5068-4d2d-855e-788c63d061e8
2. Go to map, choose lat and long.
3. Observe the marker on the equator, in the middle of the ocean :)

tagging @cjhendrix and @danmihaila

**Comment by teodorescuserban** [comment]
Also, the URL displayed in the page is wrong (the hostname is `data.` instead of `data.hdx.rwlabs.org`. See below:

![issue-with-hostname-url](https://cloud.githubusercontent.com/assets/1542984/6751613/9cf386ca-cf0e-11e4-8498-0683bb249584.png)

**Comment by teodorescuserban** [comment]
the url issue was my making. Fixed.
The data is still wrong.

**Comment by cjhendrix** [comment]
The 0,0 coordinates are in the dataset.  They are probably using that for locations that they don't know.  It's bad practice, but not uncommon in the GIS world.  Closing.  Please reopen if I've misunderstood.
