### ISSUE TITLE
Custom Organizations: JS Image Uploader not working correctly

### ISSUE THREAD

**Issue by mbellotti** [OCHA-DAP/hdx-ckan#2481]
I've been going around in circles on this and I can't figure it out. CKAN's default image upload module is not setting the value of the input box to the image to upload, therefore nothing is sent back to the server.

Reproducing:
- Open up Inspector in Chrome, find image-upload.min.js in the fanstatic/base bundle, unminified via Chrome pretty print {} set a breakpoint for line 1601
  ![screen shot 2015-03-22 at 7 04 07 pm](https://cloud.githubusercontent.com/assets/489152/6771998/b5cc11f8-d0c6-11e4-8dcd-2fd213dab7d9.png)
- Select Upload, pick any image file
- Examine the contents of this.input in the console.

**Comment by mbellotti** [comment]
@aalecs Any ideas?

**Comment by aalecs** [comment]
After we discussed yesterday I checked on staging as well by uploading a small gif in the organisation edit page.
If you inspect the remove button that appears after the file select control disappears you can see the <input type"file"...> that holds the file being uploaded and if you remove it's opacity and increase it's width you'll see it in the page and with the file name selected. At this point it's up to the form to submit the data to the controller.

**Comment by mbellotti** [comment]
And yet when I replace ckan's file uploader with a normal HTML file input (no js module) the upload works. This is what I see trying to upload an image to staging, where is the file?

![screen shot 2015-03-24 at 7 36 22 pm](https://cloud.githubusercontent.com/assets/489152/6817086/94d36304-d272-11e4-8d3d-8c9dcf03df57.png)

**Comment by danmihaila** [comment]
@mbellotti is this still an issue? I guess not. Can we close it?

**Comment by reubano** [comment]
I'm having an issue with [OCHA Somalia](https://data.hdx.rwlabs.org/organization/ocha-somalia). The image shows up fine in the editor

![window 2015-06-30 at 05 29 13](https://cloud.githubusercontent.com/assets/157864/8422811/1a57bb48-1ee9-11e5-9798-40e981a1d538.png)

But, once you view the org page... it tries to fetch the google docs hosted image from ckan

![window 2015-06-30 at 05 28 32](https://cloud.githubusercontent.com/assets/157864/8422819/34f67caa-1ee9-11e5-9f8c-fd44a2f0091f.png)

`https://data.hdx.rwlabs.org/image/https%3A//docs.google.com/uc%3Fid%3D0B01Bdplw4VkCZC1vQWxJVlVGZWM%26export%3Ddownload"`

**Comment by danmihaila** [comment]
@reubano we are not using it as external link, but instead as local storage of the files.
If this is a request we could modify the code, so we could display external links but I am not sure how it will handle the SSL and https. I guess we should just upload the files using the uploader for the moment.

**Comment by reubano** [comment]
@danmihaila I'm not sure I'm following you. Under 'Custom Styles' you have the option to upload logos or provide links. Are you saying it won't work if you provide a link?

**Comment by danmihaila** [comment]
yes, it looks it doesn't work with links. Basically we need to upload files for the moment

**Comment by reubano** [comment]
Ok, has this always been the case or did a recent change break the link feature?

**Comment by danmihaila** [comment]
This was the default behaviour we had

**Comment by danmihaila** [comment]
@mbellotti can we close this issue?

**Comment by mbellotti** [comment]
Yup!

**Comment by danmihaila** [comment]
closing it
