### ISSUE TITLE
Dataset View: methodology has been clipped for some indicators

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2482]
I've seen this for many indicators in a random sample.  In the edit view, you can see that the string has been truncated with ". . ." appended.
https://data.hdx.rwlabs.org/dataset/cerf_total_allocations
https://data.hdx.rwlabs.org/dataset/cross-appeal_amount_received_by_un_agencies
https://data.hdx.rwlabs.org/dataset/antenatal_care_coverage_-_at_least_four_visits_in_the_three_years_preceding_the_study_urban
https://data.hdx.rwlabs.org/dataset/proportion_of_the_population_using_improved_drinking_water_sources
https://data.hdx.rwlabs.org/dataset/population_undernourished_percentage

However, it's not true for all long methodologies: 
https://data.hdx.rwlabs.org/dataset/number-of-disasters-in-reliefweb

**Comment by cjhendrix** [comment]
The data is clipped in the edit view as well, so it looks like we may have modified the methodologies somewhere along the line.

**Comment by alexandru-m-g** [comment]
It's weird, I took the first dataset from above as an example:
1.  I took the entire description from CPS and edited the dataset and pasted the methodology. Saved it and it showed correctly
2.  I checked and via the hdx_package_metadata_update() API call methodology isn't yet allowed to be updated ( so it doesn't seem like it was updated like this )
3.  I anyway tested an update via the API (hdx_package_metadata_update) for another field which is updateable. It was updated successfully. 

@cjhendrix  In any case, in the future this field should be updated from CPS so the methodology should be overwritten with the correct one at some point, no ?

**Comment by cjhendrix** [comment]
Yes, that's right.  So when we pull the metadata from ckan, we won't pull this field and instead rely on what is already in CPS.   

I think this may have happened when we were working on the ". . . more" functionality.  I remember a couple of weird things happening similar to this.
