### ISSUE TITLE
Download link not working for indicators on preview page

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2484]
For these 3 randomly selected indicators, the download links **on the preview page** are not working. 

https://data.hdx.rwlabs.org/dataset/total-number-of-children-with-fever-who-received-treatment-with-antimalarial
https://data.hdx.rwlabs.org/dataset/erf_total_allocations
https://data.hdx.rwlabs.org/dataset/number_of_reports_in_reliefweb

The links on the dataset page (manage.hdx.rwlabs.org/ . . .)  are working.  But the links on the preview page (data.hdx.rwlabs.org/.../resource_download/...) are not working.   

Also note that the preview of the txt files isn't working.

**Comment by teodorescuserban** [comment]
The is in cps. I was under impression that permalink would only kick in for
files filestore.

Lun, 23 mar. 2015, 12:27, cjhendrix notifications@github.com a scris:

**Comment by alexandru-m-g** [comment]
This is related to #2367
