### ISSUE TITLE
Search result Snippet: change indicators to display data_source instead of org

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2490]
Currently, the search result snipped for indicators displays the owning Org which is always HDX.  As a stopgap, the data team added the actual data source to the dataset description.  As part of CPS taking over the metadata, we want to clean that up.  
- [ ] change the search result snippet to display the contents of the data_source instead of organization but **only for indicator datasets**

The removal of the source string from the description field will be handled separately (by pushing updated descriptions from CPS). 

![image](https://cloud.githubusercontent.com/assets/1654485/6804178/95f366c0-d23c-11e4-9542-7757ffd673f6.png)

**Comment by danmihaila** [comment]
so, "HDX" will be replaced by "World Bank"

**Comment by danmihaila** [comment]
The list of datasets and indicators is missing the date (last update and probably the user)
