### ISSUE TITLE
Dataset Create/Edit: allow user to drag/drop to reorder resources

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2506]

**Comment by danmihaila** [comment]
We could think about this when we upgrade to 2.3 version

**Comment by mbellotti** [comment]
So this feature is not on the dataset page itself, but in a tab under resource edit. You have to click Manage. Then click the resources tab, then click the button the reorder resources.

It's not clear to me whether we want to keep this UX or put the feature somewhere else? Should be easy to just add another button next to "Add New Resource" @yumiendo

**Comment by danmihaila** [comment]
moving this issue to sprint 67 as will probably be part of a design/mockups from @yumiendo 
this is the default ckan core:
![image1](https://cloud.githubusercontent.com/assets/3865844/9991900/ddb8d602-6076-11e5-8955-c831d0ef7779.JPG)
Assigned to @yumiendo for more comments and ideas if there will be part of the big refactor of contribute flow.

**Comment by danmihaila** [comment]
this is done in our new contribute flow
