### ISSUE TITLE
Custom org page: Visualization title not linked with field set in admin

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2533]
The Visualization title not linked with the field set in admin.

**Comment by danmihaila** [comment]
This is not working, reopening
![screen shot 2015-04-03 at 15 14 01](https://cloud.githubusercontent.com/assets/3865844/6982002/32f74174-da14-11e4-880a-e2087f9ca0a6.png)

**Comment by danmihaila** [comment]
moved to sprint 52

**Comment by mbellotti** [comment]
Okay, this is connected the fact that we do not have configuration values for WFP's visualization (it's hard coded somewhere), so the data the controller delivers is just a placeholder. I've updated it to include title and description.

**Comment by danmihaila** [comment]
@mbellotti you are right, WFP has not visualization title. From what I know "WFP visualization" is not using any configuration field that we have for other orgs (e.g SNGO)
pinging @cjhendrix and @SimonbJohnson to be compared with 
https://test-data.hdx.rwlabs.org/organization/somalia-ngo-consortium?sort=metadata_modified+desc
vizualization title is "Vizualization title...a very long title....".

**Comment by danmihaila** [comment]
~~I retested on STAG server and it looks that vizualization title for WFP is displayed, but it is covered by visualization itself. So basically, we should consider making the WFP smaller and allow the title to be visible.~~
~~as it is an integration issue and not confi anymore I would assign this issue to @aalecs.~~
~~@mbellotti are  you ok with this?~~

**Comment by danmihaila** [comment]
@mbellotti I merged the PRs, but I don't see any title for WFP visualization. I think we need to chat about this issue, i assume it is minor but we need to clear it :)

**Comment by mbellotti** [comment]
The fix was not on that PR. It's on my image_uploads branch.

**Comment by danmihaila** [comment]
@mbellotti pls check my commit as well. i needed to work on another issue. thanks

**Comment by mbellotti** [comment]
Yeah that should work, but I don't understand why you did it. Was this a blocker for someone?

**Comment by danmihaila** [comment]
we discussed on chat about this issue. @mbellotti can adjust my commit when she will push her changes. keeping this one closed
