### ISSUE TITLE
Custom Loc Admin Page: question about resources

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2534]
Why does the map config need both dataset id and resource id while the chart config only needs resource id?

**Comment by danmihaila** [comment]
@mbellotti or @alexandru-m-g pls reply to this question and we could close it.
Right now, for "Data url" we are using a different field.

**Comment by danmihaila** [comment]
closing this one. We will review the full admin fields and check what we still needs
