### ISSUE TITLE
Custom location page: 

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2538]
Under "Map Configuration" > "Map Labels/Values" add two fields:
- "Values Column"
- "Threshold"

**Comment by aalecs** [comment]
@mbellotti Please also add a field call "Title Column" in the "Map Boundaries" sub-section of the "Map Config" section

**Comment by mbellotti** [comment]
Okay :)

**Comment by danmihaila** [comment]
:+1: :)

**Comment by danmihaila** [comment]
@mbellotti any update on this issue?
