### ISSUE TITLE
Location page (custom and default):  show edit button for sysadmins

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2540]
#### Description

Add it in the same position as for dataset view
#### Nosetest
- load a location
- check if Edit appears for a regular user, gues or sysadmin
- load a custom location
- check if Edit appears for a regular user, gues or sysadmin

![image](https://cloud.githubusercontent.com/assets/1654485/6914502/8a8ea9bc-d78b-11e4-8d0b-b465e9ae5512.png)

**Comment by danmihaila** [comment]
I think we should follow the line and add it where we currently have "share", "follow" buttons.
"Edit" button will appear for locations only for sysadmins.

**Comment by danmihaila** [comment]
@aalecs Issue is fixed, but I added the NoseTest description. Please work on nosetest as well.
I would also add if you have time test for the other buttons, when checking "edit" we could also check "share", "follow", etc.. thanks!

**Comment by danmihaila** [comment]
moving it to Sprint 56. @alexandru-m-g pls support @aalecs with nosetests in IDE

**Comment by danmihaila** [comment]
@aalecs pls add a nosetest for this one and lets close it

**Comment by danmihaila** [comment]
@aalecs  reopening this one and moving to sprint 65 for nosetests
