### ISSUE TITLE
Custom org page: disable scroll over the map for WFP 

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2550]

**Comment by SimonbJohnson** [comment]
@danmihaila To clarify, do you want to disable scroll zoom behaviour on the map?

**Comment by danmihaila** [comment]
@SimonbJohnson I think we should just disable the zoom over the map based on scroll. We did the same for 
https://data.hdx.rwlabs.org/ebola
and for https://data.hdx.rwlabs.org/group/col
in order to be able to scroll down the page when the page is long
Ping @cjhendrix too

**Comment by amcguire62** [comment]
Simon just checking are you ok with this ticket

**Comment by danmihaila** [comment]
I will reopen this issue for the moment :)

**Comment by SimonbJohnson** [comment]
@danmihaila @aalecs Done for my version on github

https://github.com/SimonbJohnson/WFP-food-price

**Comment by danmihaila** [comment]
this is done, closing it
