### ISSUE TITLE
Custom Loc: ignore 2nd chart if no resource id given`

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2553]
We need a quick way for the data team to indicate that the custom loc page should not have a second graph (when # of toplines = 4).  Seems like an easy way to do that would be to just not configure the 2nd graph and have the controller ignore it. .

**Comment by alexandru-m-g** [comment]
@cjhendrix if you prefer, I can simply ignore on the controller the configuration for the 2nd chart in case the num of toplines <= 4 ?

**Comment by danmihaila** [comment]
I think it is a good idea. lets be sure that in template we hide the full section for 2nd chart, not only the chart.

**Comment by cjhendrix** [comment]
@alexandru-m-g That's fine.  It may confuse users who wonder where their second chart is, but we can add something to the help bubbles.

**Comment by alexandru-m-g** [comment]
@cjhendrix just let me know what the preferred way is. I can just as easily check if all the config fields for the 2nd chart are filled and only display the 2nd graph in case all of them are.

**Comment by cjhendrix** [comment]
I think your idea is good.  Have a think about what threshold to use.  In other words, at what point are there enough toplines that the page looks better with a second chart.

**Comment by alexandru-m-g** [comment]
This is related to #2562 

@cjhendrix I don't think there's a correct answer to "at what point are there enough toplines that the page looks better with a second chart". 
For example, with 5  top lines and 1 chart there is alot of white space on the right side. On the other hand with 2 charts there would be alot of space on the left.
Maybe we should just allow 3 or 6 top lines.
