### ISSUE TITLE
Custom Org Admin Page: Change default value for custom styling to our standard main nav style

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2557]
Use this less code as default:

@hdxLogoUrl: "@{imagePath}/homepage-new/logo-beta.svg";
@headerUserBackgroundColor: @darkGrayColor;
@headerNavBackgroundColor: @whiteColor;
@headerNavBorderColor: @lightGrayColor;
@headerNavSearchBorderColor: @grayColor;
@toolbarBackgroundColor: @extraLightGrayColor;

Alternatively, we may want to hide this field since the decision was made to not allow customization of the main nav.

(do not remove the functionality :) )

**Comment by danmihaila** [comment]
Another idea could be to move this to a expandable/collapsable section called : advanced configurations. We might need it...

**Comment by cjhendrix** [comment]
that works for me too, but I wouldn't recommend investing too much time in it yet.  I'm sure we'll do a massive overhaul on this interface eventually.

**Comment by cjhendrix** [comment]
Noted that the default values are different from above, but the header that results is correct.  Marking as tested.
