### ISSUE TITLE
Unauthorized log out page: python unicode "u" visible in interface

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2558]
To get here, try to access something that the current user is not authorized to do (via URL).

![image](https://cloud.githubusercontent.com/assets/1654485/9576256/67b3ab2c-4fd6-11e5-8200-b776a289e689.png)

**Comment by danmihaila** [comment]
@cjhendrix I am not sure I understand this issue. Can you please provide more details?

**Comment by danmihaila** [comment]
ping @cjhendrix for more information. I think this should be closed...

**Comment by cjhendrix** [comment]
Sorry, wrong screenshot.  Fixed above. 

It's still an issue.
