### ISSUE TITLE
Custom Loc and Custom Org: embed functionality

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2559]
- [x] embed preview not loading in modal
- [x] remove the "option" radio buttons (since we aren't using them)

**Comment by danmihaila** [comment]
@cjhendrix @SimonbJohnson 
I am not sure if we the requirement is to remove this button. If no, after you click on "embed" button there is no way to return the the initial state (hide the options and display again the button).
pls advice what how to proceed
![screen shot 2015-04-03 at 14 23 43](https://cloud.githubusercontent.com/assets/3865844/6981609/31c71966-da0d-11e4-845e-6ff620e98dbb.png)
![screen shot 2015-04-03 at 14 23 38](https://cloud.githubusercontent.com/assets/3865844/6981610/353d6898-da0d-11e4-8940-1b7c1e40924e.png)

**Comment by cjhendrix** [comment]
~~Looks like the radio buttons I was talking about are gone.  Ignore the second item in the list above.~~

**Comment by danmihaila** [comment]
closed via https://github.com/OCHA-DAP/hdx-ckan/commit/135634de23aa966080d694e8cbc3770abeebad42

**Comment by danmihaila** [comment]
"Embed data" link -> "Embed" link
"Embed" button - removed
