### ISSUE TITLE
Custom Org Page

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2561]
Admin button needs some padding between itself and the logo.

![image](https://cloud.githubusercontent.com/assets/1654485/6937659/3e260dc2-d85d-11e4-9031-d48983d0268d.png)

**Comment by danmihaila** [comment]
this is done according to the mockups. Pinging @yumiendo to get her feedback on this.

**Comment by yumiendo** [comment]
this only appears for admin users? am i right?

**Comment by danmihaila** [comment]
yes. The users who has rights to edit.

**Comment by danmihaila** [comment]
@aalecs could we add a small padding and close this one?

**Comment by aalecs** [comment]
Decreased the bottom margin on the button so that larger logos can fit. Beware that on deploy we need to regenerate all the custom css in order for this to work.
