### ISSUE TITLE
Custom location page: map and chart not working

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2562]
1. If user is not logged in the map (for mali) is not working as well as the second chart. Probably related to private/public resources.
2. if one configuration is missing (map, chart, topline numbers) we should hide the whole section including header, loading icons, etc

**Comment by alexandru-m-g** [comment]
Map was not working before the boundries resource that was configured for the map was both deleted and private. Configured correct one and it works now.
