### ISSUE TITLE
Custom location page: check http and https

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2563]
Check with @teodorescuserban the https to be valid

**Comment by alexandru-m-g** [comment]
@danmihaila @aalecs can someone point me on how to replicate the problem for custom locations ?

**Comment by danmihaila** [comment]
@alexandru-m-g  pls check https://test-data.hdx.rwlabs.org/organization/wfp
![screen shot 2015-04-03 at 13 58 32](https://cloud.githubusercontent.com/assets/3865844/6981460/71fdcaaa-da0a-11e4-8149-bccb052079f8.png)

**Comment by alexandru-m-g** [comment]
@danmihaila that's for custom orgs not locations

**Comment by danmihaila** [comment]
I couldn't reproduce anymore for locations: we should check colombia & mali. If they are ok, we can close this issue.
sorry for confusion
