### ISSUE TITLE
Custom org page: check http and https

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2564]
Check with @teodorescuserban the https to be valid

**Comment by alexandru-m-g** [comment]
@danmihaila @aalecs can someone point me on how to replicate the problem for custom locations ?

I've committed a fix for custom org, will test it once it's on dev or stag.

**Comment by alexandru-m-g** [comment]
I've committed a fix for custom org, will test it once it's on dev or stag.

@teodorescuserban : There is a new 'hdx.orgmap.url' setting in common config that can be overwritten to change how the tiles are fetched.
