### ISSUE TITLE
Custom org page: Admin - visualization type

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2567]
When editing an organization there are 2 values for visualization type: 3w and wfp. If we save wfp as value, the value is saved but in edit form is not shown this value.

**Comment by mbellotti** [comment]
I fixed this, but I don't have configuration values for the WFP visualization, so at this point it is just an empty template.

**Comment by danmihaila** [comment]
For WFP there is no fields to be configured yet. Probably @SimonbJohnson or @aalecs will say if we have any field to be added.

**Comment by SimonbJohnson** [comment]
No fields needed for the WFP Viz at this moment.
