### ISSUE TITLE
Custom org page: Admin - after save got error 500

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2569]
Edit one existing organization (non custom). Sometimes when you save without changing anything -> error 500.
I also tested when edit an organization, check the checkbox "custom org" and save -> error 500
Ping @mbellotti @alexandru-m-g  - is this related to failed nosetests ?

**Comment by danmihaila** [comment]
It looks like this is a blocker. After redeploy on stag, the wfp page is not working anymore...

**Comment by alexandru-m-g** [comment]
Yes, seems to be related to nose test failing.

**Comment by danmihaila** [comment]
1. Go to https://test-data.hdx.rwlabs.org/organization/american-red-cross
2. edit
3. don't change anything just click on "save" and it will go to 500 error page
   I guess we are missing couple of imports...
   ![screen shot 2015-04-01 at 18 13 46](https://cloud.githubusercontent.com/assets/3865844/6944119/e56b9006-d89a-11e4-97a5-2e3a930a1a55.png)

I attached a screenshot

**Comment by danmihaila** [comment]
I have to reopen this issue again. 
I removed the description, clicked saved and got again error 500 (try https://test-data.hdx.rwlabs.org/organization/edit/american-red-cross)
I think some references are missing here (check screenshot) at lines 222, 230, 235.
![screen shot 2015-04-03 at 14 42 33](https://cloud.githubusercontent.com/assets/3865844/6981771/f51177b6-da0f-11e4-942d-edb6d07255bd.png)

**Comment by danmihaila** [comment]
Still not working, but using a different behaviour I am getting the same error:
1. Go to https://test-data.hdx.rwlabs.org/organization/american-red-cross
2. click on edit
3. check the checkbox with custom and don't fill any field
4. save organization
5. error 
![screen shot 2015-04-16 at 12 53 06](https://cloud.githubusercontent.com/assets/3865844/7178446/8ae8c204-e437-11e4-8051-345ebc339f53.png)
