### ISSUE TITLE
Custom org page: Sticky logo adjustments

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2571]
- [x] sticky logo - a few things. 1. WFP logo doesn’t seem to have the padding around the logo. 2. please center the logo (its aligned left) 3. we are using bg color here so the logo should be in white and bg should be transparent. @yumiendo to send png
- [x] sticky logo - please add request membership / follow on hover (white box)
- [x] sticky logo - bg disappears once you click on share. is there a way to keep the bg? 
- [x] sticky logo - z-index needs to be adjusted so when it scrolls by the map controls it is in the front of "+/-"

**Comment by cjhendrix** [comment]
Dev team advises 3rd item is significant effort.  We will skip this one for now, but @yumiendo @ochadataproject @amcguire62 let us know if we should do it.

**Comment by alexandru-m-g** [comment]
https://drive.google.com/drive/u/0/#folders/0B16fOsnmtif0ZGdaa3ZTT3ZqZ00/0B16fOsnmtif0YVZNcmJzRGY5NWc/0Bw5omaSZ5BTHTEg1a0NLRElXU1k/0Bx1KWNTx8Ij3MHFVRjluX3NqQ3c/0B4J8rDnUw80gNXpiQ3NtbU1BQVk/0B24NBcgmV490NUdHYmNTWW8tTWc/0B24NBcgmV490dmlzMDVxN253WHc/0B24NBcgmV490fkhocnlEdkpsZDRYVzJDYzBydWNia0lleVNZZzNwSl9hcFJoZlVSSTNlOTA

**Comment by alexandru-m-g** [comment]
@yumiendo @cjhendrix @danmihaila 
The "Request Membership" link is kinda hard to fit inside the white hover box which needs to be (300-75) px x 75 px.  
![rq1](https://cloud.githubusercontent.com/assets/6586348/7003774/d15c65e6-dc68-11e4-8d92-6dc4e4f42714.png)
![rq2](https://cloud.githubusercontent.com/assets/6586348/7003814/b64be33e-dc69-11e4-8d54-4003bb6e1a78.png)

Please advise.

**Comment by yumiendo** [comment]
Hi alex, thank you for sharing the options. 
two things -
1. please add "|" between links. so "SHARE  |  UNFOLLOW  |  REQUEST MEMBERSHIP"
2. now that the above links will be somewhat long and we need to stretch the bg white, the type size needs to be adjusted so it looks proportional to the bg white box.
the revised spec is below:
![screen shot 2015-04-06 at 11 49 37 am](https://cloud.githubusercontent.com/assets/8006323/7006846/5243f6f4-dc52-11e4-9cbb-080b54a3cabb.png)

**Comment by yumiendo** [comment]
also @cjhendrix
by 3rd item you meant, "sticky logo - bg disappears once you click on share. is there a way to keep the bg" is significant effort?

**Comment by alexandru-m-g** [comment]
@yumiendo @cjhendrix 
No worries about 3rd item. All above points are committed _except_ the latest specs from today.
