### ISSUE TITLE
Custom org page: Interactive data

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2574]
- [x] Interactive data - "WFP collected food prices" should link to the dataset (waiting for a confirmation)
- [x] Interactive data - there is a lot of space after the title/description (above the map). can we bring up the map ? *screenshot attached.

**Comment by danmihaila** [comment]
@SimonbJohnson in the interactive data(check screenshot) there is the text "Click a country to..." which is currently displayed on a row and make the vizualization a bit big. Can we remove it? if not, can we move it somewhere else?
keeping @cjhendrix and @yumiendo into the loop
![screen shot 2015-04-03 at 15 14 01](https://cloud.githubusercontent.com/assets/3865844/6982014/4ebcd18a-da14-11e4-89ff-b2b110086909.png)

**Comment by danmihaila** [comment]
First item will be done via: https://github.com/OCHA-DAP/hdx-ckan/issues/2598

**Comment by danmihaila** [comment]
"Embed data" link -> "Embed" link
"Embed" button - removed

**Comment by SimonbJohnson** [comment]
@danmihaila @cjhendrix 

Has this been tested as an embed?  The header is used differently in the embedded version as it also holds the navigation.  When I tried to recreate on mine there wasn't enough space.

![embedheader](https://cloud.githubusercontent.com/assets/2110742/7118129/ff80db5a-e1f4-11e4-939e-fc7f0243f837.png)

**Comment by danmihaila** [comment]
nope, we didn't have the latest code. 
I think we should use them a bit different as there a lot of space that Yumi and Sarah wants to get rid of it in the initial visualization.
@SimonbJohnson can we think of another solution maybe?

**Comment by danmihaila** [comment]
I made a temporary fix, but I think we should find a proper one
