### ISSUE TITLE
Custom org page: Embed improvements

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2575]
- [x] Embed data - not working for me right now but if loading takes time - we should consider adding a loading gif. 
- [x] Embed data - in modal, the header should read “embed data“
- [ ] 2nd “embed" below the map - looks out of place + repeated. can we consolidate with the first one?

**Comment by aalecs** [comment]
2nd "embed" we can fix when we integrate Simon's latest version of the script

**Comment by danmihaila** [comment]
i think this is done, closing it
