### ISSUE TITLE
Custom org page: 3w vizualization (SNGO)

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2578]
- [ ] Interactive Data - the map looks cut off and tucked away. Can we center it? 
- [ ] Interactive Data - Add an option to see all data, not just Top 15. We can add "Top 15 | See all” toggle. Toggle can be default to Top 15 but click on "See all" opens a new tab. 
- [ ] Interactive Data - Please add this interactive data as a gallery item on the dataset page.(data team could do this)
  Assigned to @SimonbJohnson as it is related to the vizualization

**Comment by danmihaila** [comment]
@SimonbJohnson any update on this one?

**Comment by SimonbJohnson** [comment]
@amcguire62 wanted me to focus my time on wfp viz for now.  @amcguire62 is that still the case?
Same with https://github.com/OCHA-DAP/hdx-ckan/issues/2441

**Comment by amcguire62** [comment]
yes it remains wfp ...@danmihaila can anyone else look at this?

**Comment by danmihaila** [comment]
I played a bit with numbers for SNGO and it looks almost good. 
Moving this task to Sprint 53 and assign it to @aalecs for handover. Tomorrow meeting with Simon will help future integration&development

**Comment by SimonbJohnson** [comment]
I've updated the 3W visualisation to now use a leaflet map and auto zoom to extent of the geometry.  This way the embedded versions should never cut off the map.  Due this the x,y and zoom are no longer needed in the configuration file.

Code: https://github.com/SimonbJohnson/HDX-3W
Demo: http://simonbjohnson.github.io/HDX-3W/

**Comment by danmihaila** [comment]
ok. closing this one
