### ISSUE TITLE
Custom location page: chart with multiple sources

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2582]
We have to implement the feature to display data from at least two sources in the same chart

**Comment by cjhendrix** [comment]
For testing, we want to show this data alongside the IDPs data that is already there in the first chart.
https://data.hdx.rwlabs.org/dataset/evolution-of-malian-refugees-since-september-2012/resource/bdc01eb9-ed81-4887-bb64-f4317bf4221e

**Comment by danmihaila** [comment]
i think it is done, closing it
