### ISSUE TITLE
Custom Loc Page: Chart date format

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2585]
Compare the date formats on production and stag:
![image](https://cloud.githubusercontent.com/assets/1654485/6940104/ae8ba50c-d873-11e4-8e3e-a7aa4f14be2a.png)

The format on production (left) is preferred.  However I know we have to consider what approach can be most flexible for other datasets with dates at different timescales.  Maybe we have to include this in the configuration?

**Comment by aalecs** [comment]
@cjhendrix I wasn't able to reproduce the issue, but I looked into the code and why it could have happened.

If the date field coming from the datastore has the type "text" instead of "timestamp", then we're not formatting the field. 
Right now the format is in this style: "Jan 14, 2015".
