### ISSUE TITLE
Custom location page: format dates for chart

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2594]
if it is a string: display like this
otherwise display it: Oct 01, 2014

**Comment by danmihaila** [comment]
@cjhendrix - we don't find the resource for chart 2 for Mali. Can you point us to it?

**Comment by cjhendrix** [comment]
It's in the control doc.  ;)

But you also need to know what variables to use.  See the comments in the doc for that info.
