### ISSUE TITLE
Custom Org Page: Adjustments to main title area

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2597]
- [x] Allow Org Name and and Description to be wider.  Leave same white space on left and right sides of the logo box. 
- [x] keep buttons bottom aligned with logo box
- [x] allow two lines of description, then "more" functionality

![image](https://cloud.githubusercontent.com/assets/1654485/6944806/0bf6466c-d896-11e4-97ad-3ae285582cb0.png)

**Comment by cjhendrix** [comment]
Note "Visit Website" not to be changed (not sure if that's in another issue somewhere), but Yumi agreed it wouldn't look good with longer Org Names).

**Comment by danmihaila** [comment]
I will take this one as I have another one linked to it

**Comment by danmihaila** [comment]
@cjhendrix  in the initial design there were 3 lines for description. I am attaching a screenshot with 3 lines which I think it looks good.
pls advis
![screen shot 2015-04-02 at 15 56 40](https://cloud.githubusercontent.com/assets/3865844/6964358/fe6de048-d950-11e4-9f8e-0949ade24250.png)
e

**Comment by danmihaila** [comment]
@cjhendrix I tested with 3 lines as it is in the initial design and it looks ok. what do you think?
![screen shot 2015-04-02 at 16 26 13](https://cloud.githubusercontent.com/assets/3865844/6964776/18c145d0-d955-11e4-8448-6fc8536ce6e1.png)

**Comment by cjhendrix** [comment]
Agreed!
