### ISSUE TITLE
Custom Org Page: Vizualization title changes

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2598]
- [ ] add data link (same style as /group/col on prod)
- [ ] change viz title to black text  

![image](https://cloud.githubusercontent.com/assets/1654485/6945113/b70c05c2-d897-11e4-8989-69155e5beb3b.png)

**Comment by danmihaila** [comment]
after a call with @cjhendrix we decided to make item 1. similar with custom location page:
description -> data link url and used as link for "data"
