### ISSUE TITLE
Dataset Create: odd bit of text showing in bottom left

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2599]
![image](https://cloud.githubusercontent.com/assets/1654485/6961775/91a26d0c-d92e-11e4-88fe-a84de10920dc.png)

**Comment by mbellotti** [comment]
@cjhendrix Where exactly is this? (What part of the dataset create process I mean) I can't seem to find the text myself either locally or on staging :/

**Comment by cjhendrix** [comment]
Sorry, should have specified if it was stag or prod.  I don't see it on either now, so it's another magic fix. Closing.
