### ISSUE TITLE
Custom org page: admin menu is always displayed

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2607]
Admin menu should be displayed only for users that have the right to see it.
![screen shot 2015-04-02 at 18 04 19](https://cloud.githubusercontent.com/assets/3865844/6966587/dc860868-d962-11e4-8023-17f2bdc39430.png)

**Comment by alexandru-m-g** [comment]
So I implemented the following (based on auth functions): 
- if the user has no role in the org then he doesn't see the menu at all
- if the user is an editor of the org he will see the menu with 1 entry ( Add Dataset )
- if the user is an admin of the org he will see the menu and all 3 entries
