### ISSUE TITLE
Show Resource Size

### ISSUE THREAD

**Issue by pjdufour** [OCHA-DAP/hdx-ckan#2612]
Show users the "human readable size" (4 MB, 200 KB, etc.) of a resource in the UI somewhere.  For the API, the size could just be in bytes/kilobytes.  This is useful information to know before you download a large file through the UI or automatically.

**Comment by mbellotti** [comment]
Investigate if CKAN stores this already and report back

**Comment by cjhendrix** [comment]
Serban has found that CKAN does have an extra for this.  We are populating it for the resources created in the COD migration in hopes that we can soon add it to the interface.

**Comment by danmihaila** [comment]
@cjhendrix 
I think it is a standard column in resource and not in extras, please double check

**Comment by cjhendrix** [comment]
Yes, that's possible.  Point is, we're populating it for the COD migration and we have users and Sarah asking to display it.   But in to make it work we would need to capture that info when datasets are uploaded via interface or api.

**Comment by danmihaila** [comment]
"an interesting issue for August vacation period I see".... :)

**Comment by yumiendo** [comment]
Hi all, I want to clean up and update the data & file section of the dataset page but until that happens....
below is the interim solution to display the file size.
<img width="1407" alt="screen shot 2015-10-01 at 6 43 42 pm" src="https://cloud.githubusercontent.com/assets/8006323/10235426/5f512d40-686a-11e5-9823-4d2b1e174d32.png">

**Comment by danmihaila** [comment]
right now it is displaying a number and not in brackets
https://test-data.hdx.rwlabs.org/dataset/yemen-administrative-boundaries-settlements
it is not done according to mockups. reopening it and assigning it @alexandru-m-g

**Comment by alexandru-m-g** [comment]
Committed a fix for the formatting.

@danmihaila , @cjhendrix  Please note that this doesn't really mean that file sizes will start appearing. The file size is not stored by default in CKAN and getting this information and storing it when a user uploads a file doesn't seem to be trivial. So this only works for resources that for some reason ( API ) have the size info.

**Comment by teodorescuserban** [comment]
@alexandru-m-g the resource table has a size column...
but indeed, get/set might be a bit complicated.

**Comment by alexandru-m-g** [comment]
@teodorescuserban indeed the size column is there and you can populate it via the API. But it's a bit more complex to populate that field when a user uploads a resource via the UI ( from what I've seen this doesn't happen even in CKAN 2.4 )

**Comment by teodorescuserban** [comment]
I'm sure you can make a clean nice patch back to the core :)

În Joi, 5 nov. 2015 la 01:42, Alexandru Gartner notifications@github.com
a scris:
