### ISSUE TITLE
Custom org page , Custom Location page : Admin - remove items from header

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2635]
@cjhendrix what do you think?
Check screenshots as well:
Custom org page: 
- [ ] remove horizontal line
- [ ] remove "View Organization" link

Custom location page: 
- [ ] remove horizontal line
- [ ] remove "View" link
- [ ] remove tabs "Edit" and "Members"

![screen shot 2015-04-10 at 00 31 38](https://cloud.githubusercontent.com/assets/3865844/7077470/9d45b31c-df19-11e4-8808-da6c5aaa02c0.png)
![screen shot 2015-04-10 at 00 31 32](https://cloud.githubusercontent.com/assets/3865844/7077471/9d546ab0-df19-11e4-95fd-6edaa9f5a5ea.png)

**Comment by mbellotti** [comment]
Just a quick clarification here: Do you want these removed JUST for custom org/location or for default org/location as well?

**Comment by danmihaila** [comment]
Do you see a problem for non-custom ones?

**Comment by mbellotti** [comment]
To be honest I don't really understand what the problem is for custom ones LOL, but my point is custom and non-custom use exactly the same form so removing these elements just for custom locations/orgs is going to be tricky.

**Comment by danmihaila** [comment]
Ok. Lets remove for all. I thought vice-versa, that it is a problem to remove for all.
