### ISSUE TITLE
Develop script for migrating CODs to HDX

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2641]
The specification (still a work in progress) is here: 

https://docs.google.com/spreadsheets/d/1eJatDiBAeKDAfTi7y2WV-xVYS_qVYxmUuWIoAxI2lrY/edit#gid=1742481065

I believe there is enough there to build it.  There will no doubt be some adjustments once we start testing it, however.

**Comment by teodorescuserban** [comment]
I began to work on this when @cjhendrix came in Buch.

**Comment by cjhendrix** [comment]
Moving some notes over from #2649, which I will close.  Sorry, I had completely forgotten about this info:

From Luis:

---

The script to "register" datasets on HDX can be found here:
https://github.com/luiscape/hdxscraper-unosat/blob/master/code/create-datasets.py
It can also create resources and gallery items. 

It uses three JSON files as input:
Datasets.json: https://github.com/luiscape/hdxscraper-unosat/blob/master/data/datasets.json
Gallery.json: https://github.com/luiscape/hdxscraper-unosat/blob/master/data/gallery.json
Resources.json: https://github.com/luiscape/hdxscraper-unosat/blob/master/data/resources.json
There were constrains about creating all of those things at once, that is why I decide to separate them. 

PS: Take care with the script before running it. It has the potential of deleting a lot of things accidentally!

---

**Comment by teodorescuserban** [comment]
for status see: 
https://github.com/OCHA-DAP/cod-migration/issues/
