### ISSUE TITLE
Add another units configuration to the topline numbers for "million-dollars"

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2647]
The units keywords the the topline #s currently does not handle the combination of large numbers and dollars.  Hence, this topline becomes too long: 

![image](https://cloud.githubusercontent.com/assets/1654485/7115837/630f5d9e-e1ec-11e4-99fb-2a48eb9e116e.png)

Add a new configuration "million-dollars" that triggers both formatting actions.  While you're at it, you might add "billion-dollars" and "thousand-dollars".

**Comment by alexandru-m-g** [comment]
We currently support:  'ratio',  'per100k', 'million', 'dollars_million', 'count', 'dollars'

**Comment by danmihaila** [comment]
it is enough for the moment according to @cjhendrix and chat we had. closing it
