### ISSUE TITLE
COD Migration Script

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2649]
Just putting some notes here.  More to come.
From Luis:

---

The script to "register" datasets on HDX can be found here:
https://github.com/luiscape/hdxscraper-unosat/blob/master/code/create-datasets.py
It can also create resources and gallery items. 

It uses three JSON files as input:
Datasets.json: https://github.com/luiscape/hdxscraper-unosat/blob/master/data/datasets.json
Gallery.json: https://github.com/luiscape/hdxscraper-unosat/blob/master/data/gallery.json
Resources.json: https://github.com/luiscape/hdxscraper-unosat/blob/master/data/resources.json
There were constrains about creating all of those things at once, that is why I decide to separate them. 

PS: Take care with the script before running it. It has the potential of deleting a lot of things accidentally!

---

**Comment by teodorescuserban** [comment]
What is the relationship of this issue with #2641  ?

**Comment by cjhendrix** [comment]
Duplicate of #2641.  Closing.
