### ISSUE TITLE
Custom Org Page: Sticky logo doesn't handle long names well

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2650]
Org name is fine at the top of the page (I tested 2 and 3 line names):
![image](https://cloud.githubusercontent.com/assets/1654485/7117017/4c3d80f0-e1f6-11e4-9ac2-e275bf8cb59a.png)

But the sticky logo doesn't like long names:
![image](https://cloud.githubusercontent.com/assets/1654485/7117034/63564bfa-e1f6-11e4-89c2-dd0f6629c16a.png)

**Comment by danmihaila** [comment]
it should allow title on 2 lines and trim it after that.
