### ISSUE TITLE
Embed: scroll bar lingers after changing size of embed

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2651]
1. Embed the wfp map
2. change the size
3. change it back to 800x500
4. extra scroll bar maintained

![image](https://cloud.githubusercontent.com/assets/1654485/7117747/1c8fc066-e1fb-11e4-9ebf-e2403e26766e.png)

**Comment by aalecs** [comment]
@cjhendrix I can't seem to reproduce the problem. I tested in Safari/Chrome/FF. Can you still reproduce it?

**Comment by cjhendrix** [comment]
Just tested again now.  I still see the problem in chrome, but now I don't have to change size.  It appears immediately on clicking embed. 

![image](https://cloud.githubusercontent.com/assets/1654485/7335949/c1addc1e-ebe1-11e4-9fe6-f5eb83ae7c0c.png)

**Comment by danmihaila** [comment]
I see it in FF too @aalecs

**Comment by aalecs** [comment]
@danmihaila - I can't seem to reproduce. Can you check your browser's console for errors, please? I tested local on my laptop + on staging in Chrome/FF/Safari.

**Comment by danmihaila** [comment]
I think I found the cause, fixing it
