### ISSUE TITLE
Custom org page: Admin : SNGO title is not saved

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2655]
I am trying to update the title of the SNGO visualization and it is not saving...
pinging @mbellotti

**Comment by cjhendrix** [comment]
Same for the "Data Link URL".

**Comment by cjhendrix** [comment]
Same for the chart title as well (compare title of Mali chart 1 vs what is saved in the admin page).

**Comment by danmihaila** [comment]
@mbellotti I think this is related with latest commit. On Friday it was working. 
We need to fix this one today.

**Comment by mbellotti** [comment]
@cjhendrix I can't reproduce this issue with charts in custom countries :/ It works fine on staging.

**Comment by cjhendrix** [comment]
Seems to be working now.  Magic.

**Comment by mbellotti** [comment]
:dancer:

**Comment by danmihaila** [comment]
@cjhendrix we redeployed the fixes pushed by @mbellotti . now it looks good. closing this one
