### ISSUE TITLE
Custom location page: tweaks about Topline numbers &charts

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2656]
0-3 toplines -> topline sections off, charts off
4 toplines -> 1 chart on
5-7 toplines -> 4 toplines on, 1 chart on
8 toplines -> 2 charts on
ping @cjhendrix 

![custom-location](https://cloud.githubusercontent.com/assets/3865844/7133195/6712e750-e299-11e4-8cc8-9e00cfcbe86f.png)

**Comment by cjhendrix** [comment]
Seems sensible to me.  @yumiendo ?

**Comment by danmihaila** [comment]
About topline numbers:
keep text only on 2 lines and if it is longer lets trim it and add "...". When moving mouse over text it will display a default browser hint with full text.
@alexandru-m-g what do you think, is it doable?

**Comment by cjhendrix** [comment]
Note the the "source - data - date" line on a topline number can be > 1 line, and changes the height.

![image](https://cloud.githubusercontent.com/assets/1654485/7134647/0f9f223a-e29f-11e4-92ca-7a9d74059540.png)

**Comment by alexandru-m-g** [comment]
@danmihaila  @cjhendrix 
For now I'm only focusing on the design changes requested in Yumi's template. 
We already have a logic in place for when to show the 2nd chart implemented in #2553. I would suggest we do any logic changes in the next Sprint.

**Comment by yumiendo** [comment]
Does this mean top line number can be "in-between" numbers (ie. 3, 5, etc) ?? Can we suggest to data team that ideally we stick to 4 or 8?

**Comment by danmihaila** [comment]
@yumiendo @cjhendrix @alexandru-m-g pls note I created another issue for next sprint to address maybe a rewrite of these 2 sections in order to support these cases:
https://github.com/OCHA-DAP/hdx-ckan/issues/2662

**Comment by alexandru-m-g** [comment]
We have Yumi's changes now so I'm closing this ticket . We still have #2662 open.
