### ISSUE TITLE
Continous integration: Maintenance scripts, automatic testing

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2660]
The desired scenario:
- when a dev is creating a Pull Request (PR) the server should try to redeploy that branch and run nosetests
- when a PR is merged into dev - the dev server should automatically redeploy and run nosetests.

Ping @alexandru-m-g to fill more details here
@teodorescuserban to be aware as it might be a task for him

**Comment by alexandru-m-g** [comment]
I think we should spend some time investigating jenkins and travis for automating the tasks mentioned above.

**Comment by teodorescuserban** [comment]
Agree.
Care to have a short talk tomorrow?

Mar, 14 apr. 2015, 13:38, Alexandru Gartner notifications@github.com a
scris:

**Comment by danmihaila** [comment]
moved to sprint 57
