### ISSUE TITLE
Custom Loc & Custom Org: Allow configuration of series names in charts

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2661]
We probably need to allow the user to configure the name to be shown each series in the charts.  

![image](https://cloud.githubusercontent.com/assets/1654485/7134735/07fb47a6-e2a0-11e4-822d-fcba0337c19b.png)

**Comment by danmihaila** [comment]
@cjhendrix this is the name of resource. This is how we decided to display, make it easier to configure. Can you check that if you change the name of resource the text is changing here?

**Comment by alexandru-m-g** [comment]
@danmihaila Won't this affect the name of the file when you download it ?

**Comment by danmihaila** [comment]
@alexandru-m-g the filename that will be downloaded will be: Name.format

**Comment by danmihaila** [comment]
This is the CKAN way I think. If there is name it will be return as name of the file...If you think we should display the initial filename, we can create a git issue for it.
Ping @cjhendrix

**Comment by cjhendrix** [comment]
I think we just want to add another configuration element on the admin page for "Series Name", with help text "The series name is shown in the legend of the chart."  But maybe I'm missing something?

**Comment by danmihaila** [comment]
We tried to avoid having too many fields in the admin configuration. This was a reason @mbellotti proposed to use the name of the resources. For me it makes sense as we display information from that resource. But in case Data Team wants to have another field in admin form, we can add it (maybe Sprint 53 or next Sprint).

**Comment by danmihaila** [comment]
I think this is done. closing it
