### ISSUE TITLE
Different base map on WFP page than on other country pages

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2667]
The [WFP organization page](https://test-data.hdx.rwlabs.org/organization/wfp) seems to use the default OSM base map while [other country pages](https://test-data.hdx.rwlabs.org/group/mli) use a custom-made version that uses MapBox. I think the latter looks much better; and would suggest changing the WFP base map to use the map on MapBox instead of OSM. 

**Base map A.**
![screen shot 2015-04-14 at 10 12 37 am](https://cloud.githubusercontent.com/assets/953118/7138510/d3170ebe-e28e-11e4-8d37-660cf40a2b1c.png)

**Base map B.**
![screen shot 2015-04-14 at 10 12 44 am](https://cloud.githubusercontent.com/assets/953118/7138514/d690c882-e28e-11e4-8562-329ec78cf065.png)

Base map B looks much better in my opinion.

**Comment by danmihaila** [comment]
assigned to Arty. it should not be a big change in code.
@aalecs pls add it to sprint estimation doc

**Comment by aalecs** [comment]
Basemap is configurable with config option: hdx.orgmap.url ... we can ask Serban to change it on prod/stag/dev.

**Comment by alexandru-m-g** [comment]
@aalecs correct me if I'm wrong but as I saw the mapbox basemap needs 2 layers ( basemap + labels ). So just changing the config might not be enough or did I miss something ?

**Comment by aalecs** [comment]
Right on Alex :)

**Comment by danmihaila** [comment]
@aalecs can you implement it?

**Comment by aalecs** [comment]
I changed the base map, please take a look and see if everyone likes the new appearance.

**Comment by luiscape** [comment]
It looks nice, in my opinion. But I am puzzled about the blue. Maybe it should have the orange tone we have in the "Share Data" button ... ? I defer this to someone else though.
