### ISSUE TITLE
Custom org page: Save as image feature

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2673]
Implement Save as image feature as described here:
https://drive.google.com/drive/u/0/folders/0B16fOsnmtif0ZGdaa3ZTT3ZqZ00/0B16fOsnmtif0YVZNcmJzRGY5NWc/0Bw5omaSZ5BTHTEg1a0NLRElXU1k/0Bx1KWNTx8Ij3MHFVRjluX3NqQ3c/0B4J8rDnUw80gNXpiQ3NtbU1BQVk/0B24NBcgmV490NUdHYmNTWW8tTWc/0B24NBcgmV490dmlzMDVxN253WHc/0B24NBcgmV490fkhocnlEdkpsZDRYVzJDYzBydWNia0lleVNZZzNwSl9hcFJoZlVSSTNlOTA

**Comment by aalecs** [comment]
Right now we can nicely implement this feature just for the WFP page/visualisation because it's the only one that was designed to be embeddable at any point and it has state exports. The rest of the visualisations can only be exported at the initial state.

**Comment by danmihaila** [comment]
closing this until we get more requirements or requests to implement this
