### ISSUE TITLE
Custom location page: Colombia page - map bug

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2679]
When moving mouse over districts, the name of district is "undefined". I played a bit with json file, replacing some strange chars, but I still didn't fix it. 
Mali is working good.
I am not sure if it is from data source or code.
Ping @aalecs and @cjhendrix . I think first we should change data and later check code.

**Comment by alexandru-m-g** [comment]
Talked to @danmihaila and I'll look into this so assigning this to me.
