### ISSUE TITLE
Custom org page: adjust template

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2687]
From Yumi:
(all country pages) add some space between the lines of key figure and the chart (so they don’t look like they are affiliated)

![spacing](https://cloud.githubusercontent.com/assets/3865844/7199059/46ac72f2-e4fa-11e4-8c25-80d6e00d431c.jpg)

**Comment by danmihaila** [comment]
assigned to @aalecs

**Comment by alexandru-m-g** [comment]
This is actually related to #2662
