### ISSUE TITLE
The Colombia org page map contains an unexpected hole

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2719]
The Colombia country page contains a map. 

![screen shot 2015-04-23 at 10 49 12 am](https://cloud.githubusercontent.com/assets/953118/7300216/ea994dc4-e9a8-11e4-9b44-040b8e8cc216.png)

The hole matches the state of Antioquia. The problem is likely happening because all the p-codes from that state start with a leading "0". If the visualization is taking those p-codes as integers, it is probably eliminating the leading "0".

A fix may include treating those p-codes as strings.

**Comment by alexandru-m-g** [comment]
Hi @luiscape . Thanks for mentioning this. You were right, they were treated as integers. Changed to string and the hole disappeared.

**Comment by luiscape** [comment]
Nice!
