### ISSUE TITLE
Clarify meaning of the "popular" icon

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2721]
On hover, the popular icon displays something like "XX views" (default ckan).  A user (PD) has asked for clarification on what that means and it's been asked before as well.

We should say something like "XX recent views" or "XX views in the last XX days"

**Comment by danmihaila** [comment]
@aalecs @alexandru-m-g @mbellotti 
I think someone worked on something similar. Can you comment with more details about how it is working right now?
