### ISSUE TITLE
Custom org page: SNGO tweaks

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2724]
For interactive map can we add transparency on the green/gray polygons (for admin level) like WFP visualization map? 
1. opacity of green on the map (we can make it like the blue polygon on WFP, only on hover it becomes 100%) 
2. name of the admin level on hover (screen attached, I’m hoping this data is available)
3. "Reset filters” button changed to a smaller link on the same line as “Who” “What” “Where”. (comp attached)
4. use 2 colors for bar charts and map - pls use #add974 for active, and can keep the inactive as is #cccccc

![2](https://cloud.githubusercontent.com/assets/3865844/7318023/105f67c2-ea90-11e4-8436-ef81e28dc844.png)

**Comment by aalecs** [comment]
1. When configuring the 3W please set all the colours to #add974 and this will work just fine

**Comment by aalecs** [comment]
For 3. I also changed the info box displaying the number of selected items ... please check the before and the after screenshots containing explanations:
![var1](https://cloud.githubusercontent.com/assets/5638491/7536668/7d5fc104-f59a-11e4-98ae-1bbf859e5a9b.png)
![var2](https://cloud.githubusercontent.com/assets/5638491/7536671/81d38c98-f59a-11e4-9e3f-a87ec64a003f.png)

**Comment by aalecs** [comment]
@danmihaila - please check last comment and reopen if necessary :)

**Comment by danmihaila** [comment]
it is perfect from my point of view! thanks, @aalecs
