### ISSUE TITLE
Custom org page: SNGO visualization not working well on mobile

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2725]
(NGO consortium - interactive map) the visualization does not display correctly on mobile

**Comment by aalecs** [comment]
Seems to be ok now - tested out both views: HDX page and embedded widget

![2015-05-22 12 55 13](https://cloud.githubusercontent.com/assets/5638491/7768270/1484a3dc-0082-11e5-9c14-84d1ace6313e.png)
![2015-05-22 12 55 48](https://cloud.githubusercontent.com/assets/5638491/7768271/14cfaf94-0082-11e5-876a-6a19b01090bd.png)
