### ISSUE TITLE
Custom location page: chart labels

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2732]
We currently don't display the vertical/horizontal labels even if we store them in admin.
Do we want them displayed?
@cjhendrix @yumiendo 
Check screenshot as it is now on a common org page vs https://data.hdx.rwlabs.org/group/col
![screen shot 2015-04-24 at 16 58 13](https://cloud.githubusercontent.com/assets/3865844/7320158/558f3c6a-eaa3-11e4-80c2-36cb2ca52f87.png)

**Comment by cjhendrix** [comment]
As long as the chart title is good, the Y axis shouldn't need a label, but of course we can't always count on users giving a good title.  With the default loc pages, it was more important to have it because the indicator titles do not always make the units clear. It's not really my call, but I think it's ok either way.

**Comment by yumiendo** [comment]
Hmm who’s in charge of giving chart titles? I won’t be concerned if its done by data team but if anyone can give a title - we perhaps should have the Y axis title.

**Comment by danmihaila** [comment]
It is data team and it is a field set in admin. We just don't display it...Assigned to @aalecs

**Comment by danmihaila** [comment]
I redeployed this on stag and still not showing labels on vertical
@aalecs pls check https://test-data.hdx.rwlabs.org/group/mli

**Comment by danmihaila** [comment]
Still an issue. Moving it to Sprint 55

**Comment by aalecs** [comment]
@danmihaila - from your comment I understood we should remove the legend for the Oy axis: "It is data team and it is a field set in admin. **We just don't display it**".
Please describe what's the desired behaviour :smiley:

**Comment by danmihaila** [comment]
@aalecs  sorry, my bad :)
I wanted to say that we have everything in place, but we don't display it in javascript.
We should display it! :)
