### ISSUE TITLE
Custom Org Page: Somalian-NGO-3W

### ISSUE THREAD

**Issue by SimonbJohnson** [OCHA-DAP/hdx-ckan#2739]
The embed preview is not working.  Error about loading http file over https

![custom-org-page-3w-error](https://cloud.githubusercontent.com/assets/2110742/7334179/2060da80-eb84-11e4-9aa0-8736ee6ce839.png)

**Comment by danmihaila** [comment]
I think this issue is smaller. See screenshot
![screen shot 2015-05-11 at 15 58 29](https://cloud.githubusercontent.com/assets/3865844/7565195/9d85b14c-f7f6-11e4-9186-6f38d0f15c17.png)

**Comment by danmihaila** [comment]
@aalecs can you check if this is still an issue and close it?
