### ISSUE TITLE
Make it possible to sort the results in My Datasets

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2748]
The site is getting big now.  Users with lots of datasets need some tools to help them find stuff, especially private or deleted datasets.  Sorting would help.  Filtering by private or deleted would be even better.

**Comment by danmihaila** [comment]
@mbellotti is it going to be moved to Sprint 56 ?

**Comment by mbellotti** [comment]
It can be closed.

**Comment by danmihaila** [comment]
@cjhendrix it looks that we now have the sorting feature in place.
We could add filters as well, but we should check if dashboard (datasets, organizations, etc) is going to be changed or it is intensively used to implement such a feature. 
what do you think?
