### ISSUE TITLE
Invite to Org: deleted users can be invited to an org via email

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2754]
We should not allow deleted users to be invited to an org (by email).

**Comment by danmihaila** [comment]
I think this issue need more information about how to handle different situations.

**Comment by mbellotti** [comment]
Should we have HDX email the deleted user to let them know someone wants them to come back? :)

**Comment by danmihaila** [comment]
the functionality is working ok, user can not be invited. But there is a redirect to a login page and I think we should remain on same alert message displaying the error message. In case there is no placeholder for message we can ask @yumiendo to help.
Moving this one to sprint 65
![screen shot 2015-09-10 at 12 00 40](https://cloud.githubusercontent.com/assets/3865844/9784419/c6f8367c-57b3-11e5-9e53-9dd2ba58d083.png)
