### ISSUE TITLE
User Profile:  Mark a deleted user as such and make their page visible only to sysadmins

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2755]
#### Description

Currently deleted users are still visible at their link.  For example: https://data.hdx.rwlabs.org/user/cj-test-2  but there's no easy way to see that he is deleted. 
- [ ] add a "deleted" flag somewhere (similar to what we do for datasets)
- [ ] make the profile pages invisible to anyone other than sysadmins
#### Nosetest
- mark a user as deleted
- check as guest or regular user if user page is loading 
- check as sysadmin if page loads and display a message/icon with "deleted"

**Comment by mbellotti** [comment]
Do you also want to give the sysadmin the ability to restore a deleted user?

**Comment by cjhendrix** [comment]
Good idea. But not essential.  We could always add that later if their is a demand.

**Comment by mbellotti** [comment]
Please test this one carefully. Because of the way routes are structured I had to reproduce all of the ones that started with /user/ in the plugin file. Otherwise these routes will 404. I'm pretty sure I got them all and tested it pretty aggressively beyond the nosetest, but still, double check that login, registration, editing, etc are working as expected.

**Comment by aalecs** [comment]
@mbellotti - I see that in your nose test you comment out 2 other tests and there is no commit message about that, can you please tell why those two tests were disabled? 
Also I don't seem to find the part where you're testing out these two points, maybe I'm wrong:  
- check as guest or regular user if user page is loading
- check as sysadmin if page loads and display a message/icon with "deleted"

**Comment by mbellotti** [comment]
I commented them out because they are part of email validation, which is
now disabled.

I missed point 1, but point 2 is definitely covered.
