### ISSUE TITLE
Organization Redirect Link

### ISSUE THREAD

**Issue by pjdufour** [OCHA-DAP/hdx-ckan#2761]
Since https://data.hdx.rwlabs.org is already a long domain, it would be useful to have a redirect so users can have shorter stable links to organizations.  This could be an automatic client side redirect, like url shortner services.

For example, given the "OCHA Nepal" organization

```
https://data.hdx.rwlabs.org/organization/ocha-nepal
```

The following would redirect there:

```
https://data.hdx.rwlabs.org/org/ocha-nepal
```

or even better

```
https://data.hdx.rwlabs.org/o/ocha-nepal
```

**Comment by danmihaila** [comment]
I am not sure we should duplicate the url format. I assume soon we will have a shorter url and we will have to review most of the url like /group /organization /user . Basically this is the default url from CKAN

**Comment by danmihaila** [comment]
closing this one. we will migrate to a shorter url.
