### ISSUE TITLE
Dataset edit: show all lines of resource description when editing.  

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2764]
Show all lines of the resource description on the resource list page. This makes it easier to manage descriptions for datasets with many resources.   I don't have a great example of this at my fingertips, but you get the idea from this one: https://data.hdx.rwlabs.org/dataset/resources/administrative-boundaries-cod.  This remains low priority.

**Comment by danmihaila** [comment]
@cjhendrix can you please provide more details? When editing a dataset>resource list has implemented the "... more" option. do we want to remove this?

**Comment by danmihaila** [comment]
ping @cjhendrix  for more comments about this

**Comment by cjhendrix** [comment]
Sorry, that issue wasn't very clear.   I've updated the description.

**Comment by danmihaila** [comment]
I saw there are couple of resources with long description which make difficult to read. assigned to @yumiendo to give us an idea what should be the best approach:
- display the whole description
- display more lines and keep the more/less functionality
- keep like it is now

**Comment by cjhendrix** [comment]
The use case here is for when a user is setting up a dataset with many resources.  Often you want to copy/paste between resources since some of the description text will be the same.  It's a pain to have to click all the "more" buttons every after each edit when this page is reloaded.    Again, low priority, but useful to contributors.

**Comment by yumiendo** [comment]
agree with cj. 
I think at the dataset level (edit mode) - it'd be nicer to see all info exposed. 

so the best approach would be:
- display the whole description 

...until we can introduce a new contribute flow via empty dataset page (cj's idea).

**Comment by danmihaila** [comment]
ok. Adding this issue for next sprint.
