### ISSUE TITLE
WFP Visualisation: Bar chart x value wrong on some bars 

### ISSUE THREAD

**Issue by SimonbJohnson** [OCHA-DAP/hdx-ckan#2772]
Choose India->Rice->zoom in on time extent and some bars appear on the far left.

![hdx-wfp-bug](https://cloud.githubusercontent.com/assets/2110742/7374097/41cfad5e-edc8-11e4-8fe5-9959faa4370b.png)

Could be a result of the key not being found when the x value is selected.

**Comment by SimonbJohnson** [comment]
I think it is because the new keys were generated to have ellipses on the long values.  The transformation function uses old keys with out ellipses

**Comment by SimonbJohnson** [comment]
Code to be integrated:
https://github.com/SimonbJohnson/WFP-food-price/commit/5be2cd8a63d9835d5626057304a9ad6167a9bf7d
https://github.com/SimonbJohnson/WFP-food-price/commit/b558fdfbc0bcbecef0763f153bfc9731f20b69ed

**Comment by danmihaila** [comment]
this is done and redeployed. @SimonbJohnson pls reopen if it is still an issue
