### ISSUE TITLE
Geo Preview: adding a geojson file results in server error

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2788]
To replicate:  
1. Add a geojson resource
2. Make sure format = geojson
3. 500 error returned. 
4. Check dataset and new resource is there, but no preview.

Here is a very small geojson you can use.  It's valid (draws on geojson.io).

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -38.935546875,
              71.80827136550005
            ],
            [
              -40.84716796875,
              71.21607526596131
            ],
            [
              -39.7705078125,
              70.60531901924371
            ],
            [
              -37.11181640625,
              70.51024068514326
            ],
            [
              -36.1669921875,
              71.20899878425502
            ],
            [
              -37.001953125,
              71.85622888185527
            ],
            [
              -38.935546875,
              71.80827136550005
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -39.17724609375,
              71.43417616304582
            ],
            [
              -39.17724609375,
              71.58747326430792
            ],
            [
              -38.7158203125,
              71.58747326430792
            ],
            [
              -38.7158203125,
              71.43417616304582
            ],
            [
              -39.17724609375,
              71.43417616304582
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -38.16650390625,
              71.42717893107371
            ],
            [
              -38.16650390625,
              71.60134862675986
            ],
            [
              -37.529296875,
              71.60134862675986
            ],
            [
              -37.529296875,
              71.42717893107371
            ],
            [
              -38.16650390625,
              71.42717893107371
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -39.90234375,
              70.95969716686398
            ],
            [
              -39.90234375,
              71.13098770917023
            ],
            [
              -37.1337890625,
              71.13098770917023
            ],
            [
              -37.1337890625,
              70.95969716686398
            ],
            [
              -39.90234375,
              70.95969716686398
            ]
          ]
        ]
      }
    }
  ]
}

**Comment by danmihaila** [comment]
it is indeed a problem with this as bug.
If you want to make it work, make the dataset first public and it will skip that error.

**Comment by cjhendrix** [comment]
Got it.  We can work around it with public for now.  We don't need to invest too much into this since we are about to replace it.  If we could easily eliminate the 500, it would be good.

**Comment by danmihaila** [comment]
i think this is done. @cjhendrix pls reopen if you still see the error
