### ISSUE TITLE
Search results: provide a way to turn off pagination

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2790]
We've talked about this a long time ago, but if we are going to redo search, let's consider offering a "show all" button in alongside pagination. This would support the common (I think) practice of searching a page with the browser's ctrl+f rather than the keyword search functionality.   It's irritating to have to do ctrl+f on multiple pages when looking for a particular term.  Many users will have the ctrl+f habit from searching on other pages.

**Comment by danmihaila** [comment]
We have right now the option 25|50|100 on /organization page which could be implemented on /search page. 
@yumiendo  @cjhendrix is this something we want to implement?

**Comment by cjhendrix** [comment]
I don't see it on /organization?  Maybe not on stag yet?  But if Yumi and Sarah are happy with how it looks there, it makes sense to implement on all search results, I think.

**Comment by danmihaila** [comment]
assigned to @yumiendo for comments

**Comment by yumiendo** [comment]
I personally like "show all" but I was flagged that it's going to run into loading issue(esp for search results). so we're using "show 25|50|100"
<img width="1229" alt="screen shot 2015-08-31 at 12 41 04 pm" src="https://cloud.githubusercontent.com/assets/8006323/9583959/2dd30e6a-4fdc-11e5-8e1b-af7d0dfa3744.png">

This would definitely be a nice feature for search results. 
<img width="1402" alt="screen shot 2015-08-31 at 12 53 28 pm" src="https://cloud.githubusercontent.com/assets/8006323/9584193/ca6ed7a8-4fdd-11e5-8826-52f8178bb38c.png">

**Comment by danmihaila** [comment]
@cjhendrix @yumiendo - where do we want to have this new feature:
- [ ] /search 
- [ ] /dataset
  I also wanted to raise the issue that on custom org page 
- we have pagination
- we don't 25|50|100
- we have a search bar
  Do we want to show the list of datasets in a common way?
  ![screen shot 2015-09-01 at 12 11 30](https://cloud.githubusercontent.com/assets/3865844/9600260/c4577030-50a2-11e5-8382-0ba7025a81cc.png)
