### ISSUE TITLE
Custom org page: WFP visualization issue

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2810]
From our users:
On WFP visualization, after you select a country check the series.
On-mouse over on the last series, you start not seeing the date and the price.

**Comment by danmihaila** [comment]
Another issue
 Go to https://test-data.hdx.rwlabs.org/widget/WFP?type=WFP&amp;data_link_url=%23&amp;embedded=True&amp;
Click on Senegal (but it happens on all countries)
Click on a commodity, Sorghum i.e.
Click and pan the mouse over the timeline (first chart on top) to select a custom period
Move the mouse over the admin units column chart on the bottom and you'll see numbers floating over the chart

**Comment by danmihaila** [comment]
Second issue is done. Only the initial one is on

**Comment by aalecs** [comment]
@danmihaila - I changed the text position so that it doesn't exceed the container limits - other solutions didn't work.
Please check it out and reopen if needed.

**Comment by cjhendrix** [comment]
First one tested.  I don't quite understand the 2nd one, but I don't see anything weird in that area other that the already-documented #2885
