### ISSUE TITLE
Custom org page: 3w visualization

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2821]
There is no need to use
Map posinioning (X Value)
Map posinioning (Y Value)
Zoom level
@aalecs please confirm

**Comment by aalecs** [comment]
Only one way to find out ... kidding!
Yes they don't seem to be used anymore since we're zooming to the poly boundaries.

**Comment by danmihaila** [comment]
@aalecs then lets remove them from admin interface :)
can you work on this one?
