### ISSUE TITLE
Add new/Edit Dataset: tags search not working

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2831]
#### Description

When add new or edit dataset, at field "Tag" will not display the options for tags. Autocomplete and search not working.
#### Nosetest
- create/edit dataset
- check how the dropdown for tag is working (what action is using) and use it in test to see full list of tags.
- check list of tags retrieved based on typed letters

**Comment by mbellotti** [comment]
Can't reproduce this on staging or dev :/

**Comment by danmihaila** [comment]
I reproduced it on stag and on prod. When I first tested I couldn't see any result, but digging a bit it looks that it displays like only 1 result or none. 
Check screenshots below
![screen shot 2015-05-13 at 10 57 56](https://cloud.githubusercontent.com/assets/3865844/7606176/2c5f76aa-f95f-11e4-841b-35602b6ca1b5.png)
![screen shot 2015-05-13 at 10 57 49](https://cloud.githubusercontent.com/assets/3865844/7606177/2c619822-f95f-11e4-8af7-a75adbc95bfd.png)

**Comment by mbellotti** [comment]
Oh, I see what you mean. So the problem isn't that it isn't working but that it isn't displaying a enough suggestions?

**Comment by danmihaila** [comment]
yes. Initially I thought it is not working at all because couldn't find some terms i was looking for.

**Comment by danmihaila** [comment]
@mbellotti - reopening this issue as there is no nosetest committed.

**Comment by cjhendrix** [comment]
Tested and working.  But I still see some odd behavior:

Typing "refuge" returns "refugee", but not "refugees" even though both are (unfortunately) tags.   

Maybe this is a limitation of how the matching algorithm is working and we have to live with it, but it would be nice to know.

**Comment by mbellotti** [comment]
CJ, are you sure they are both active tags? A while back you asked me to
change the functionality of the autocomplete to remove tags that have no
datasets assigned to them.

**Comment by cjhendrix** [comment]
Good thought, but no dice.  They are both tags in use (you can filter by each on /dataset) and get a non-overlapping list of datasets.
