### ISSUE TITLE
indicator preview: txt preview not working

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2835]
Indicator preview txt file is not working

https://data.hdx.rwlabs.org/dataset/people_killed_in_disasters/resource/e685f791-2957-4818-a4bd-d64f60f5bb8d

**Comment by cjhendrix** [comment]
Funny, the above one is working for me (stag and prod).  Maybe something you did while investigating the issue?

I tested a few others and confirm that they aren't working (on stag 0.9.0):
https://test-data.hdx.rwlabs.org/dataset/children_under_five_mortality_rate_per_1000_live_births/resource/8cb9e373-eb4e-4a29-a4dd-86105f8bb844
https://test-data.hdx.rwlabs.org/dataset/prevalence_of_hiv_total_of_population_aged_15-49/resource/22d353d1-8cfa-4db0-9d1c-38731a753fe5
https://test-data.hdx.rwlabs.org/dataset/percentage_of_population_residing_in_urban_areas_by_major_area_region_and_country_1950-2050/resource/56cc3dcc-4325-4f38-b640-35df018c5a51

**Comment by danmihaila** [comment]
this has to do with removing /hdx/ from indicator url
@teodorescuserban lets discuss about this and fix it. I am not sure if we have to push any indicators to ckan db

**Comment by teodorescuserban** [comment]
Sorry, I kinda missed that. 
If you will link the files from cps over https this will not happen.

**Comment by cjhendrix** [comment]
I think this is still happening for all of our indicators.  Reopening.

**Comment by teodorescuserban** [comment]
What plugin should be enable and is not?
prod.ini inherit all plugins from common-config.ini.txt

What view should I create?

tagging @cjhendrix and @alexandru-m-g 

```
There are no views created for this resource yet.

 Not seeing the views you were expecting? Click here for more information.

Here are some reasons you may not be seeing expected views:

No view has been created that is suitable for this resource
The site administrators may not have enabled the relevant view plugins
If a view requires the DataStore, the DataStore plugin may not be enabled, or the data may not have been pushed to the DataStore, or the DataStore hasn't finished processing the data yet
```

**Comment by teodorescuserban** [comment]
Bumping this.
@alexandru-m-g ?

**Comment by alexandru-m-g** [comment]
@teodorescuserban I'm looking into this. More info later :)

**Comment by alexandru-m-g** [comment]
@teodorescuserban 
Although the text_view plugin was enabled there were 2 issues:
1.  there were no default views in common config so the default views - views that are added by default to a resource if no specific views are selected - were `image_view recline_view`. The following configuration entry solved this: `ckan.views.default_views = image_view recline_view text_view`
2.  that fixed the problem for txt file that were uploaded to CKAN. But for remote txt files the text_view plugin also needed the `resource_proxy` plugin in order to bypass the same origin policy

**Comment by teodorescuserban** [comment]
Ok. So what are the next steps, @alexandru-m-g ?
Youmake changes to common-config on next deployment?
Should I change anything in prod.ini?

**Comment by alexandru-m-g** [comment]
@teodorescuserban There's no need to change anything in prod.ini. I've made the changes in common-config.

One thing I forgot to mention though. We should re-run the following command when the new code is deployed: `paster views create recline_view text_view -c /srv/prod.ini`

**Comment by teodorescuserban** [comment]
Ok.
Just let me know when the code will be deployed.

În Lun, 24 aug. 2015 la 12:53, Alexandru Gartner notifications@github.com
a scris:

**Comment by teodorescuserban** [comment]
tested on stag.
thank you @alexandru-m-g 
Closing.
