### ISSUE TITLE
Gis Preview: 3. Show  map preview in dataset view

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#2849]
- [ ]  Check if there's any layer available
- [ ]  Display any feedback ( errors, timeouts, etc) that might've appeared during the PostGIS import process 
- [ ]  Use Leaflet Vector Tiles support to display .pbf files coming from the spatial server

https://www.mindmup.com/#m:cg10B2Cgmf3EurKoSWVIQS1oMUlMeEU

**Comment by aalecs** [comment]
@alexandru-m-g - We need a custom endpoint in PGrestAPI through which we can get the bounding box for the shapes in a resource. eg: 

``` SQL
gis=# SELECT ST_Extent(wkb_geometry) FROM "raw_fts_input_463ec953c6313bd3049efe1a80b36e2b";
                           st_extent
---------------------------------------------------------------
 BOX(-12.239236906 10.141371344,4.24467035900005 24.999511983)
(1 row)
```

**Comment by alexandru-m-g** [comment]
I think you can run custom SQL commands in PgrestAPI/ spatial server. There is a UI for writing them so i think you can call it from API without code changes.

**Comment by aalecs** [comment]
@alexandru-m-g: Yeah I've seen the UI, but it allows only selecting existing columns from what I've checked. When I do aggregations like "ST_Extent(wkb_geometry)" it can't find that column :)
