### ISSUE TITLE
Create a more elegant way of storing and editing focus countries

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#285]
The information on which countries are "focus countries" should probably be stored in the database for easy access, and to make it possible for sysadmins to change the list in the interface.

This is related to #183

**Comment by danmihaila** [comment]
@alexandru-m-g @cjhendrix as https://github.com/OCHA-DAP/hdx-ckan/issues/183 is closed, I think we could also close this one. Anyway, moving it to epics.

**Comment by cjhendrix** [comment]
I think the locations dropdown will disappear from the homepage soon, so we can close this as OBE.
