### ISSUE TITLE
Custom Org Pages: Consider making the Join Column case-insensitive for 3W dashboard viz

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#2866]
Currently, the Join Column appears to be a case-sensitive field. It also appears that the value entered by the user is forced to upper case on save. This may cause a hard to diagnose issue when the Data Type is set to "Datastore (via datapusher)" if the name of the Join Column in the datastore is not uppercase. It is likely that the column names in a datastore will be lowercase because using lowecase column names is a workaround for a known bug in the datastore that requires column names to be lowercase for sql based queries to work. @luiscape 

![image](https://cloud.githubusercontent.com/assets/6885303/7634704/a3d5b9ee-fa2a-11e4-96ca-231a3702325b.png)

**Comment by danmihaila** [comment]
@alexandru-m-g and @cjhendrix any comments on this one?

**Comment by alexandru-m-g** [comment]
1.  If the name of the field is actually forced to upper-case when saving that's definitely a bug
2.  As far as I see we have many datastore tables that have column names that include both upper and lower case letters: https://data.hdx.rwlabs.org/dataset/json-repository/resource/fb37281c-f0d1-43bd-a13d-b9cc9044dc47 , https://data.hdx.rwlabs.org/dataset/json-repository/resource/515c2575-0d94-4e54-8a5c-dc943a92e18a . So it does **not** seem like we should force this form field to lower-case.

**Comment by luiscape** [comment]
@alexandru-m-g as of point **2**, you are right there are fields with upper cases. However, those field, for some reason, are not "queriable" using the SQL interface. Examples as follow:
- If you search for value=284, you will get the following JSON:

``` json
  "result": {
  "records": [
    {
      "ADMIN1_PCO": "ML003",
      "_full_text": "'ml003':1 'sikasso':2",
      "CODE_INSTA": 3,
      "value": 284,
      "month": "2014-12-01T00:00:00",
      "REGION_NAM": "Sikasso",
      "_id": 3
    }
  ],
  "fields": [...],
  "sql": "select * from "515c2575-0d94-4e54-8a5c-dc943a92e18a" where value=284"
}
```

**Query URL:** https://data.hdx.rwlabs.org/api/action/datastore_search_sql?sql=SELECT%20*%20FROM%20%22515c2575-0d94-4e54-8a5c-dc943a92e18a%22%20WHERE%20value=284
- If you search for ADMIN1_PCO="ML003", you will get an error:

``` json
"error": {
    "info": {
        "params": [{}],
        "statement": ["select * from "515c2575-0d94-4e54-8a5c-dc943a92e18a" where ADMIN1_PCO="ML003""],
        "orig": ["column "admin1_pco" does not existLINE 1: ...from "515c2575-0d94-4e54-8a5c-dc943a92e18a" where ADMIN1_PCO..."]
    },
    "query": ["(ProgrammingError) column "admin1_pco" does not existLINE 1: ...from  "515c2575-0d94-4e54-8a5c-dc943a92e18a" where ADMIN1_PCO...'select * from "515c2575-0d94-4e54-8a5c-dc943a92e18a" where ADMIN1_PCO="ML003"' {}"],
    "__type": "Validation Error"
}
```

**Query URL:** https://data.hdx.rwlabs.org/api/action/datastore_search_sql?sql=select%20*%20from%20%22515c2575-0d94-4e54-8a5c-dc943a92e18a%22%20where%20ADMIN1_PCO=%22ML003%22

Please note that on the `"orig"` field the column name has been converted to lower case, "admin1_pco". That problem doesn't happen if the column is **already** lower case. So, basically, in the cases in which those columns need to be queried via SQL, **it is necessary** to convert them to lower case.

Please let me know if I am wrong.

**Comment by alexandru-m-g** [comment]
@luiscape I was not suggesting that the problem doesn't exist. Was simply suggesting that if we want to remain consistent than we should have everywhere the fields in lower case: in the datastore, in the forms and everywhere else that they might be used

I've slightly modified your query above and this seems to work for me: https://data.hdx.rwlabs.org/api/action/datastore_search_sql?sql=select%20*%20from%20%22515c2575-0d94-4e54-8a5c-dc943a92e18a%22%20where%20%22ADMIN1_PCO%22=%27ML003%27 . Didn't try with others

**Comment by luiscape** [comment]
@alexandru-m-g Got it, that make sense. Great with the query above! I really hadn't thought of that. Thanks for the comments.
