### ISSUE TITLE
Currency code undefined when navigating backwards  

### ISSUE THREAD

**Issue by reubano** [OCHA-DAP/hdx-ckan#2867]
https://data.hdx.rwlabs.org/organization/wfp
click a country -> click a commodity -> click a region
then at the top click the commodity link to go back to the national average
you will notice that the currency code gets replaced with 'Undefined'
e.g., Price of Maize in undefined per 100 KG in United Republic of Tanzania

re #2203

**Comment by danmihaila** [comment]
this is done
