### ISSUE TITLE
Permalinks on staging point to production

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2877]
Permalinks on staging point to resources on productions. Here's a printscreen:

![screen shot 2015-05-16 at 3 53 51 pm](https://cloud.githubusercontent.com/assets/953118/7667752/e94531fc-fbe3-11e4-9b03-2cb23a98a322.png)

Please note the API query on the URL bar and the permalink result field.

**Comment by danmihaila** [comment]
This is ok as it is saved in db. In case we want stag, we edit&save resources. I think we should close this one

**Comment by teodorescuserban** [comment]
+1.

Luis was not aware we redeployed stag with latest prod db.

Sâm, 16 mai 2015, 23:34, danmihaila notifications@github.com a scris:

**Comment by luiscape** [comment]
Got it. I thought it was a bug. :-)

**Comment by danmihaila** [comment]
ok. closing it
