### ISSUE TITLE
Dataset view: External links should open in a new tab

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2882]
Dataset view > download button
When clicking and if it is an external link it should open in a new tab.

**Comment by mbellotti** [comment]
This question came up in our meeting today: is this just external links for resources or ALL external links throughout the site?

**Comment by mbellotti** [comment]
We're still waiting for clarification on this, correct?

**Comment by mbellotti** [comment]
Actually, this is a little hacky, but we might be able to solve this problem with a small javascript on the bottom of the base template: https://github.com/OCHA-DAP/hdx-ckan/blob/accd79ee91623bc088beb5454ea9fa64cd195c7a/ckanext-hdx_theme/ckanext/hdx_theme/templates/base.html#L137

**Comment by danmihaila** [comment]
The link from description are working, I am still testing this issue. But I have to reopen because the "download" (k.ro) is not working if you check this resource:
https://test-data.hdx.rwlabs.org/dataset/fakexxxiso-admin-level-3-boundaries
ping @mbellotti

**Comment by mbellotti** [comment]
Hey Dan, I don't see a download link on the page you shared so can you be a bit more specific?

**Comment by danmihaila** [comment]
It is the arrow near update, preview, etc. basically is the icon that will direct you to link www.k.ro

Dan Mihaila

**Comment by danmihaila** [comment]
@mbellotti this is still an issue. We also have a bug on prod with links from header which open in new tabs.
Pls check this screenshot from staging : https://test-data.hdx.rwlabs.org/dataset/json-repository  > "test dan" resource
![screen shot 2015-06-16 at 14 09 09](https://cloud.githubusercontent.com/assets/3865844/8181754/77a66384-1431-11e5-95d2-a9f7114627c8.png)
This issue become more and more complicated and I guess it should have been a bit simple to fix. Lets fix it as we need to redeploy tomorrow prod! :)

**Comment by mbellotti** [comment]
Trying this approach:
- see if we can extend tracking.js and have it load instead of the core tracking.js
- only open resources that are uploaded as links, not file uploads.

**Comment by danmihaila** [comment]
moving to Sprint 59

**Comment by mbellotti** [comment]
I'll test this a bit more throughout today but assuming we are satisfied with just download links opening up in new window/tabs and only if they are not files we're hosting then this should be ready to go?

**Comment by danmihaila** [comment]
@mbellotti can you make a pull request to "dev" branch too? We will need to deploy this to prod before going to 2.3.

**Comment by mbellotti** [comment]
Okay, I should be able to have that done by today :)
