### ISSUE TITLE
WFP Visualization:  small display glitch when hovering over regions

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2885]
![image](https://cloud.githubusercontent.com/assets/1654485/7727690/b4786302-ff0a-11e4-9ddf-594afc664747.png)
![image](https://cloud.githubusercontent.com/assets/1654485/7727697/bef95cd2-ff0a-11e4-8a52-ae3843eea87f.png)

**Comment by danmihaila** [comment]
@cjhendrix this is the best solution we could get based on @aalecs comment on https://github.com/OCHA-DAP/hdx-ckan/issues/2810
I think @SimonbJohnson could help here fixing this as it is quite customization.

**Comment by danmihaila** [comment]
assigned to @SimonbJohnson to work on it when he is back

**Comment by SimonbJohnson** [comment]
@aalecs Missing an equals in the if statement

https://github.com/SimonbJohnson/WFP-food-price/commit/7fe184ba11e523f300fb4e478d54bf0de809b832

**Comment by danmihaila** [comment]
@aalecs can you please check if we merged the last change from Simon and close this one?
