### ISSUE TITLE
Email validation module: when logging out and log in back error

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2886]
1.
I logged out as hdx and logged local.
I have this error:
File '/srv/ckan/ckanext-hdx_users/ckanext/hdx_users/controllers/mail_validation_controller.py', line 362 in logged_in
  if g.openid_enabled:
NameError: global name 'g' is not defined
2. I checked the same py file and I see at line 125: send_mail(name, email, org, reason)
which is "unresolved reference..."

Please fix this ASAP as i need to work on other issues local as logged user.

**Comment by teodorescuserban** [comment]
You might not have a proper env. 
Can your local ckan connect to the specified smtp server (default localhost port 25)?

**Comment by danmihaila** [comment]
I think it is related to a python import. i was just trying to login. Marianne is looking into this.

**Comment by mbellotti** [comment]
Marianne fixed this yesterday actually, before Dan noticed it LOL. :p

**Comment by teodorescuserban** [comment]
:)

**Comment by mbellotti** [comment]
Tacked the fix on to the end of this commit https://github.com/OCHA-DAP/hdx-ckan/commit/0160b10c11234f18a5327c860f34141c2c940a77 ... so... no worries

**Comment by mbellotti** [comment]
I've also cleaned up the imports as well. They were a bit wonky, copy and paste fails again.

**Comment by danmihaila** [comment]
@mbellotti this is still an issue. I tried local and I couldn't logged in back. WIth email validation module on i was getting no err, i removed it from common-config and i am getting this one

The form contains invalid entries:

```
Login failed. Bad username or password. (Or if using OpenID, it hasn't been associated with a user account.)
```

**Comment by danmihaila** [comment]
after reimport db, I don't see anymore the error. closing this one
