### ISSUE TITLE
Custom org page: javascript alert

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2891]
@mbellotti we still have this error since https://github.com/OCHA-DAP/hdx-ckan/issues/2438 and was noticed today by @reubano in our demo
A. Javascript Alert
I tried to reproduce it:
1. I edited wfp org
2. add logos
3. add vizualization type (wfp and not 3w as selected by default)

I got this alert: check screenshot
![screen shot 2015-04-02 at 14 04 01](https://cloud.githubusercontent.com/assets/3865844/6963458/62584232-d948-11e4-97d4-9af64a8473a4.png)

**Comment by mbellotti** [comment]
What browser was this in?

**Comment by danmihaila** [comment]
Firefox

**Comment by mbellotti** [comment]
This is such a bizarre and incredibly anal FF issue. It's the search form at the top of the page that's to blame, but only in FF and only if you interact with one of the javascript elements on the form (image upload, visualization select, probably also visualization color picker). If you just interact with the HTML elements on the form in FF you will not see this message >.>
