### ISSUE TITLE
CKAN 2.3: upgrade research

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2900]
We need a research to answer to couple of question:
1. What are the best steps to upgrade from 2.2.1 (HDX version) to 2.3? (from sources, etc)
2. Do we need to upgrade first to 2.2.2 ?
3. What are the main changes from 2.3 we don't have yet implemented?
4. What extensions/customizations from HDX are not compatbile with 2.3?
5. If we changed some core methods (or ask to be changed) - do we see these changes in 2.3?

**Comment by alexandru-m-g** [comment]
@mbellotti I've checked out the _hdx_ckan_2_3_ branch. I think there is an issue cause for the files from our extension I don't see the GIT history anymore. I see only 1 commit: the last one.

See attached screenshot:
![git_history](https://cloud.githubusercontent.com/assets/6586348/8167377/9334847c-13a6-11e5-86fe-582eb0f86ec5.png)

**Comment by mbellotti** [comment]
I talked to Dan about this already, it's because the CKAN installer (or in
this case updater) overwrites the git directory completely. Didn't realize
this until after. Not sure what to do about this to be honest, but open to
suggestions

On Mon, Jun 15, 2015 at 2:36 PM, Alexandru Gartner <notifications@github.com

**Comment by alexandru-m-g** [comment]
My suggestion would be to look at what that script does and see why it overrides the git folder. I think it's important cause otherwise we're loosing valuable information.

**Comment by alexandru-m-g** [comment]
Or is there a way to first checkout the ckan core code, then run the update script and then merge our code over it ?

**Comment by mbellotti** [comment]
Wouldn't it be easier to just use git rebase to combine dev and
hdx_ckan_2_3 when the time comes?

On Mon, Jun 15, 2015 at 3:12 PM, Alexandru Gartner <notifications@github.com

**Comment by danmihaila** [comment]
I think we need to find a solution to have at least our history from git. It will help to track bugs, issues or old issues, etc

**Comment by mbellotti** [comment]
Yeah, but this is no big deal... Git is magical like that. I went ahead and
fixed this, check the branch now and make the history is as it should be.
