### ISSUE TITLE
Update to new reCAPTCHA

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2910]
Announced at Google I/O, Google just updated its reCAPTCHA. Now, instead of an actual captcha that requires image interpretation by an user, it displays a simple check-box that reads "I'm not a robot.". Here's a screen shot:

![screen shot 2015-05-29 at 11 16 08 am](https://cloud.githubusercontent.com/assets/953118/7885824/2669a5e4-05f4-11e5-824a-e1165fb987b5.png)

I think that would be a lovely update.

@amcguire62 

Here's more info: https://www.google.com/recaptcha/intro/index.html

**Comment by danmihaila** [comment]
we have this one in onboarding, closing this issue.
thanks @luiscape for mentioning it
