### ISSUE TITLE
Extra character in error message

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2911]
Change "Password1" to "Password"
![image](https://cloud.githubusercontent.com/assets/1654485/7886006/5ed85320-0627-11e5-93a5-0327e3513f9f.png)

**Comment by danmihaila** [comment]
@cjhendrix i think this is the old registration module and we can close this one. can u confirm and close it pls?

**Comment by cjhendrix** [comment]
I did this the other day and didn't notice it.  Closing.
