### ISSUE TITLE
Adjust the default zoom of the Nepal Earthquake page to show more idp sites

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#2919]
Adjust the default zoom level of the map on the Nepal Earthquake page to show more clusters of idp sites. There is a cluster of IDP sites around Gorkha that is only visible after the user clicks on the zoom out button twice.

Desired Zoom
![image](https://cloud.githubusercontent.com/assets/6885303/7992510/f5be4d80-0acd-11e5-89e7-ab7703e5c9ba.png)

Current Zoom
![image](https://cloud.githubusercontent.com/assets/6885303/7992475/ac153608-0acd-11e5-8641-993a8c8e4510.png)

**Comment by danmihaila** [comment]
@takavarasha is this still an issue or we can close it?

**Comment by takavarasha** [comment]
Please close this
