### ISSUE TITLE
Browse Page:  Section links (scrollTo links) not working

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2921]
On FF and Chrome the links aren't working.  Looks like maybe the anchors got dropped?

![image](https://cloud.githubusercontent.com/assets/1654485/8006177/9c3c3a1e-0b91-11e5-9d2e-40dec7337062.png)

**Comment by mbellotti** [comment]
I'm not able to reproduce this issue in either FF or Chrome on either local or production. Gremlins?
