### ISSUE TITLE
Dataset Edit: confirmation for delete dataset is missing the white background div

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2922]
On STAG and PROD; Chrome and FF:
1. Edit a dataset
2. Click delete
3. receive confirmation page as shown below:
   ![image](https://cloud.githubusercontent.com/assets/1654485/8030453/51035234-0dc7-11e5-850b-013ef170d299.png)

**Comment by danmihaila** [comment]
duplicated by https://github.com/OCHA-DAP/hdx-ckan/issues/3394, closing this one
