### ISSUE TITLE
Geopreview not working for "long" dataset names

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2926]
@alexandru-m-g knows about this one

**Comment by cjhendrix** [comment]
Just tested it here and it seems to be ok: http://feature-data.hdx.rwlabs.org/dataset/geotest15-which-has-a-long-name-for-testing-the-bug-with-not-getting-geopreview-on-long-names

**Comment by teodorescuserban** [comment]
might be related to max size for resource name in postgis or along the way,
because the actual table made for a resource is datasetname_resourceID

În Vin, 26 iun. 2015 la 12:53, cjhendrix notifications@github.com a scris:

**Comment by alexandru-m-g** [comment]
The table name in postgis should have the following name: first 10 characters from datasetname + a hash string that has always the same length

https://bitbucket.org/agartner/gisrestlayer/src/a31be6ade273f1153cdc8fb698675a5c5a7df29b/api/import_api.py?at=master#cl-186

**Comment by alexandru-m-g** [comment]
This cannot be reproduced and  the way the table names are created have been anyway changed in the meantime.
