### ISSUE TITLE
Remove ogc_fid attribute from shape info

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2932]
The ogc_fid attribute is added by our backend (postgis or maybe spatial server?).  We shouldn't display that to end users.  Ideally, we should prevent it from being sent with the vector tiles at all (unless it is needed for client side rendering). 

![image](https://cloud.githubusercontent.com/assets/1654485/8079327/027cba4e-0f64-11e5-974a-d31199266e51.png)

**Comment by alexandru-m-g** [comment]
This was done
