### ISSUE TITLE
Geo preview dependency on formats is restrictive

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2934]
As an interim solution (until we can figure out the interface), could we have the geo preview generation be triggered on all new/updated resources with extension = .zip or geojson or json?

**Comment by cjhendrix** [comment]
Of course that means we would be sending (eventually) failure messages to any user trying to upload a zipfile with something other than a shapefile in it.  So maybe not such a great suggestion.

**Comment by yumiendo** [comment]
I had an idea to include small FAQ on the "submit data" page - where we could include questions like "Can I preview my geo data?" and we'll list formats thats previewable. let me know your thoughts

**Comment by cjhendrix** [comment]
yes.  That could work as a quick solution. It implies the user has uploaded a zip, wondered why it isn't previewing, checks the faq, and sees that they have to use the magic "zipped shapefile" words.

**Comment by yumiendo** [comment]
I can provide a comp for this but I'd need someone to compile the FAQ - when would you need the comp by & who would be able to compile FAQ??

**Comment by teodorescuserban** [comment]
But we want users to upload simple zip files? The web server is compressing the file on the fly on download so there should be no reason to upload a simple zip file.

**Comment by cjhendrix** [comment]
Yes, but they still might do it.  :)  Tagging @amcguire62 for Yumi's questions about tasking and timing.  I can write the FAQ material, but it's not clear to me if we are considering this a block or not for going to production with geo preview, so I'm not sure about timing.

**Comment by cjhendrix** [comment]
Pinging @amcguire62.  

I propose that for the first iteration, we just stick with having geo preview triggered when the file format is set to one of the magic words.  We can add a link to the help button that links directly to some explanatory text in the FAQ, which I will write (but we have to get the FAQ up first.)

**Comment by amcguire62** [comment]
i agree

**Comment by cjhendrix** [comment]
We did the faq and help text changes.  Closing.  There is another issue for implementing something in the api/interface to disable geopreview.
