### ISSUE TITLE
Unable to upload files above about 1MB to feature or test

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2935]
In testing the geo preview, I am unable to upload a 4.5MB file.  

1) create a dataset
2) select a 4.5MB or larger file to upload. you can find one [here](https://www.dropbox.com/sh/3aqdloh27yynwmp/AACCZF1hT01FqV0n0wlyJ_ica?dl=0)
3) upload spinner disappears and no further action happens on the page (name field is not populated)

This is not a problem on prod.

Although not directly related to geo preview, I am labeling it as such since it blocks testing of Geo Preview.

**Comment by cjhendrix** [comment]
I reverted to testing with pure text files (ignoring geo for the moment).  
On feature-data and on stag:
800kb uploads
1600kb fails

In the latter case, I see the chrome upload status bar (it got to 7%), then it disappears and the spinner disappers.  No further updates occur on the page.

the .txt files I was using are [here](https://www.dropbox.com/sh/3aqdloh27yynwmp/AACCZF1hT01FqV0n0wlyJ_ica?dl=0)

**Comment by teodorescuserban** [comment]
@cjhendrix tested while I was watching the logs. No error were thrown, however, the small file succeeded while the bigger file failed.

It failed repeatedly on the POST request to /storage/upload_handle (pending then timing out with 502 status message). I was pretty sure it has to have something with the containers config but it doesn't.

@aalecs please try to identify the latest changes around that area - who did it, why etc.

**Comment by mbellotti** [comment]
So just to clarify, we are seeing this issue on production but not on staging?

**Comment by teodorescuserban** [comment]
Production is ok. Feature and test are not.

**Comment by mbellotti** [comment]
Oh okay, because @cjhendrix said "This is not a problem on stag." so I'm not sure which server I should use to diagnose the issue?

**Comment by cjhendrix** [comment]
My bad.  

The problem is on feature and test (stag).  Production is ok.

**Comment by mbellotti** [comment]
Honestly, the best way to fix this is by using a file upload plugin that chunks larger files. The problem is most likely that production has more resources than staging. There's always going to be some point where the file is too large and the request times out. https://github.com/ckan/ckan/issues/2368

**Comment by cjhendrix** [comment]
@teodorescuserban Before working on a plugin, could we test Marianne's hypothesis by giving feature more resources?

**Comment by teodorescuserban** [comment]
Only by shutting down stag and demo will feature get more resources.
But not significantly more. 

Staging VM is slower and on slower hard drives. Dev is even slower.

Only prod is the real thing. What I would suggest is to have a separate set of containers on prod to test out this feature :)

I will only start the containers when we test, on a convenient time (less visitors etc) so prod itself wont be impacted.

Feedbacks?

**Comment by teodorescuserban** [comment]
Prod tests completed successfully.
See attached screenshots.

![upload 32 mb - bmon](https://cloud.githubusercontent.com/assets/1542984/8128323/7894caa2-1106-11e5-809b-5156bd18921a.png)
+++++++++++++++++++++++++++++++++
![upload 32 mb - chrome timing](https://cloud.githubusercontent.com/assets/1542984/8128324/7895d0aa-1106-11e5-99a5-8351195de1ec.png)
+++++++++++++++++++++++++++++++++
![upload 32 mb - ckan reply filesize](https://cloud.githubusercontent.com/assets/1542984/8128325/7896e544-1106-11e5-9923-0a8c0f0120b6.png)

**Comment by teodorescuserban** [comment]
Conclusions:
- stag is slower (as stated previously).
- careful on migration to the new provider (tagging @amcguire62) - this test should be included in the load testing.

**Comment by teodorescuserban** [comment]
@alexandru-m-g please see my previous comment about upload_handle

**Comment by alexandru-m-g** [comment]
I did a bit of testing on staging while connecting directly to ckan ( not through nginx ):
- I uploaded a 5 MB file in 17s - worked
- I uploaded an 8 MB file in 27.44s - worked
- I uploadded a 12 MB file  - failed (no response) after 30.4s

That makes me think there's something in CKAN that times out after 30s ( and on prod since there are more resources we don't hit this timeout ). 
@teodorescuserban: I found the following things in Gunicorn, maybe it is related ( especially the **graceful_timeout**):

```
timeout

-t INT, --timeout INT
30
Workers silent for more than this many seconds are killed and restarted.

Generally set to thirty seconds. Only set this noticeably higher if you’re sure of the repercussions for sync workers. For the non sync workers it just means that the worker process is still communicating and is not tied to the length of time required to handle a single request.

graceful_timeout

--graceful-timeout INT
30
Timeout for graceful workers restart.

Generally set to thirty seconds. How max time worker can handle request after got restart signal. If the time is up worker will be force killed.
```

**Comment by teodorescuserban** [comment]
Please note:
1. the timeout comes from the fact that the call to `upload_handle` is remaining pending (never responded)
2. the resources we all think about are cpu and ram - staging is having both. The only thing that should slow down stag comparing to prod is the hard discs speed - but we are talking about 20-30 MB not 30 GB :)

Gunicorn is timing out because ckan does not respond to `upload_handle`

Nginx is more optimistic than gunicorn because of an old issue (nginx timing out before gunicorn) from our repo.

**Comment by alexandru-m-g** [comment]
@teodorescuserban for an 8 MB file CKAN staging answers in 27s. That's not ideal but it works. For a 12MB it clearly takes more than 30s so Gunicorn kills the thread. Can't we try increasing the 2 Gunicorn timeouts on staging ? 

Why prod does the job quicker, that's an interesting question. Surely related to hard disk speeds as well. Maybe it would be worth investigating after we switch to the newer and simpler CKAN file storage system.

**Comment by teodorescuserban** [comment]
Yes, an interesting question, but again, the file is not transferred until call to upload_handle completes.
That should be a fast call.
Can I call you on hangouts?

**Comment by alexandru-m-g** [comment]
Yes. Just call me on hangouts if you want.

**Comment by danmihaila** [comment]
@alexandru-m-g @teodorescuserban @cjhendrix what is the status of this issue?
should we move it sprint 59? who is going to work on this one?

**Comment by cjhendrix** [comment]
A good file for testing (>200MB): https://www.dropbox.com/s/e0x0ya180t8x3to/Africa_adm2_multipoly_GADM.geojson?dl=0

**Comment by reubano** [comment]
Related to #2406

**Comment by danmihaila** [comment]
I think this is done, but moving to 61 to be more tested
ping @cjhendrix @teodorescuserban

**Comment by reubano** [comment]
Related to #3104?

**Comment by danmihaila** [comment]
@reubano can you test it again now on staging server please?

**Comment by cjhendrix** [comment]
I think we're good on this one.  Closing.
