### ISSUE TITLE
WFP Custom Org Page: South Sudan and Sudan data not visible on the the map

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#2938]
The adm0_id for South Sudan [70001] and Sudan [40764] which are coming from the datastore do not match the ADMO_CODE for South Sudan [74] and Sudan [6] in the geojson variable in data/un_world_topo.js file. Additionally, the geojson does not have a polygon for State of Palestine [adm0_id=999].

**Comment by SimonbJohnson** [comment]
@aalecs Here's the new topojson https://github.com/SimonbJohnson/WFP-food-price/blob/master/data/un_world_topo.js

Will hopefully get the chance to set up docker on my mac this week are you able to handle this in the mean time?

**Comment by takavarasha** [comment]
@aalecs, any update on this. Pinging @amcguire62  who is also interested in this

**Comment by danmihaila** [comment]
@takavarasha dev team is focusing this sprint on upgrade to 2.3. What is the priority of this issue? I am thinking that if @SimonbJohnson is setting HDX CKAN local, he could change the code and maybe doing a hotfix on prod if the priority is very high.

**Comment by takavarasha** [comment]
@amcguire62 asked about this and asked me to follow up. I am sure he will comment soon on priority.

**Comment by amcguire62** [comment]
@danmihaila please ping it over to Simon, hopefully he is operational now.

**Comment by danmihaila** [comment]
This is done and deployed on prod.
https://data.hdx.rwlabs.org/organization/wfp
 closing it
