### ISSUE TITLE
CSS issue with the deleting dataset confirmation page

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2939]
After clicking on "Delete" on a dataset page, I am directed to a confirmation page that asks me to confirm if I really want to do that. When I got there I saw this page that had some broken CSS: 

![screen shot 2015-06-11 at 12 45 49 pm](https://cloud.githubusercontent.com/assets/953118/8112915/e58f3800-1038-11e5-8155-56ae78bbc527.png)

**Comment by teodorescuserban** [comment]
+1

**Comment by cjhendrix** [comment]
duplicate of #2922   :p
