### ISSUE TITLE
CKAN 2.3: ckanext-hdx_org_group

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2944]
Check this document:
https://docs.google.com/document/d/1D6kdWctMio8FyqmsqGt4BonIMatETQppQu_n-98eY4M/edit#
- [ ] HDX CKAN plugin: hdx_org_group
- [ ] HDX CKAN plugin: hdx_group 

Questions:
- do we need both plugins?
- I know that CKAN core fixed some problems regarding organizations vs groups. Are we still having a problem?

**Comment by alexandru-m-g** [comment]
@danmihaila Please be more specific regarding which "org vs group" problem you are referring to.

**Comment by alexandru-m-g** [comment]
The hdx_group plugin only contains the schema changes that are specific to the group entity.
