### ISSUE TITLE
CKAN 2.3: ckanext-hdx_search

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2946]
Check this document:
https://docs.google.com/document/d/1D6kdWctMio8FyqmsqGt4BonIMatETQppQu_n-98eY4M/edit#
- [ ] HDX CKAN plugin: hdx_search

A new search will come in place in the next sprint. Until then lets comment what we currently have and be prepared for next changes that will improve our search.
I think this task should go together with SOLR task

**Comment by alexandru-m-g** [comment]
This commit should be in this issue: https://github.com/OCHA-DAP/hdx-ckan/commit/56c131436aea919e4bfaaa46c8c4cc7543ee94e6
