### ISSUE TITLE
CKAN 2.3: SOLR

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2951]
Check this document:
https://docs.google.com/document/d/1D6kdWctMio8FyqmsqGt4BonIMatETQppQu_n-98eY4M/edit#
- [ ] Check HDX SOLR schema with schema from 2.3
- [ ] Make a report about the changes.
- [ ] any impact over the new search changes we want to do?

**Comment by alexandru-m-g** [comment]
This ticket is completed by this commit.The schema was updated to the 2.3 version: https://github.com/OCHA-DAP/hdx-ckan/commit/716c5ee8340b55bb83e5e45b38e5aeecba81f715

**Comment by teodorescuserban** [comment]
Wasn't this ticket referring to solr schema inside the solr container?

**Comment by alexandru-m-g** [comment]
It was referring to needed changes in the solr schema in general. So yes, any changes need to be reflected in the solr container, which already happened on the testing server that runs 2.3.
