### ISSUE TITLE
Map on custom org 3w viz not reset when the Reset All button is clicked

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#2960]
![ocha afghanistan - humanitarian data exchange](https://cloud.githubusercontent.com/assets/6885303/8209340/70393488-14da-11e5-9cc7-cca7a3a0eae3.png)

**Comment by danmihaila** [comment]
I think the reset is about resetting the selection and not the position of the map.
Maybe we should take into consideration to reset map position

**Comment by danmihaila** [comment]
@takavarasha closing this one
