### ISSUE TITLE
Trying to have a correct GIT history in the upgrade branch to 2.3 

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#2962]
I have created a new branch for the 2.3 upgrade: https://github.com/OCHA-DAP/hdx-ckan/tree/history_2_3_upgrade

I've had problems with the following CKAN CORE files while merging. I've mainly took the version from ckan 2.3 since we shouldn't modify ckan core: 
- [ ]   datastore/plugin.py ( @teodorescuserban we will need to double check this, it's related to #1837 )
- [x]   ckan/logic/auth/validators.py ( @mbellotti , can you check this pls ?  Note that I've added back the user_email_validator() otherwise CKAN wouldn't start: https://github.com/OCHA-DAP/hdx-ckan/commit/b31f27a3ab26e6bae691ac9cda39afc4be20a73a )
- [x]   ckan/logic/action/get.py  ( @mbellotti , can you check this pls ? )
- [x]   ckan/controllers/related.py  ( @mbellotti , can you check this pls ? )
- [x]   ckan/controllers/package.py  ( @danmihaila  , can you check this pls ? I think it's just formatting but double-check )
- [x]   ckan/controllers/group.py  ( @mbellotti , can you check this pls ? )
- [ ]   generally the translation files where showing conflicts, have no idea why ( I took the latest version from core ckan 2.3)

Also, @mbellotti I don't know if you're initial upgrade commit ( https://github.com/OCHA-DAP/hdx-ckan/commit/eae55fba13922fd5499f2d9a402c84314b434d20 ) had some other changes except the code changes from ckan core 2.3. Can you please check, thanks.

**Comment by mbellotti** [comment]
https://github.com/OCHA-DAP/hdx-ckan/commit/eae55fba13922fd5499f2d9a402c84314b434d20 Looks good to me. There are a couple other changes related to user_email_validator in schema.py (https://github.com/OCHA-DAP/hdx-ckan/commit/eae55fba13922fd5499f2d9a402c84314b434d20#diff-e4189be2bde0fc4cd4cfbfc28f3227fbL29) and (https://github.com/OCHA-DAP/hdx-ckan/commit/eae55fba13922fd5499f2d9a402c84314b434d20#diff-e4189be2bde0fc4cd4cfbfc28f3227fbL406). Those need to be restored and we should really revisit the issue of pushing this back into core.

Related.py was a change accepted back into CKAN so... no worries there :)

Don't see anything with the other files but double checking now.

**Comment by alexandru-m-g** [comment]
@mbellotti Could you please open a PR towards this branch with any other user_email_validator - related changes that need to be in 2.3 ?

**Comment by mbellotti** [comment]
Okay get.py was another core update that was eventually accepted: https://github.com/ckan/ckan/issues/2001

group.py is a little weird because this (https://github.com/OCHA-DAP/hdx-ckan/commit/eae55fba13922fd5499f2d9a402c84314b434d20#diff-379752379d1d722bcb76beff6e0ebef8L148) looks like something we might have added and pushed back into core but it is not labelled as such and I can't find any record of it :/ It's not a huge concern since we are overriding this part in our org_group controller anyway.

**Comment by teodorescuserban** [comment]
@alex fine by me as long as it wont err on nosetests.
I recall you did some changes on that replicates upstream ckan behaviour.

Lun, 22 iun. 2015, 19:32, mbellotti notifications@github.com a scris:

**Comment by alexandru-m-g** [comment]
@danmihaila @mbellotti The last 3 paths (ckan/controllers/related.py, ckan/controllers/pacakge.py, ckan/controllers/group.py ) were wrong in my description above, I changed them:

**Comment by danmihaila** [comment]
@alexandru-m-g @mbellotti 
- [x] ckan/controllers/package.py ( can you check this pls ? I think it's just formatting but double-check )

mine is ok, only an automatic format - no need to bring changes
