### ISSUE TITLE
Add to the list of file formats that trigger geo preview

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2967]
Here is the current list of formats that should trigger geo preview creation:
- zipped shapefile
- shapefile
- kml
- kmz
- geojson
- gml

**Comment by danmihaila** [comment]
I think we should have all the formats supported to trigger or only one "general".

Dan Mihaila

**Comment by cjhendrix** [comment]
That would mess with the ability to filter by format.  Also, in the future, we may want to trigger completely different geo preview processes for formats like WMS.

**Comment by danmihaila** [comment]
I agree. Then I think we should have a full list of formats such as:
- kml
- geojson
- zipped shapefile??

Dan Mihaila

**Comment by cjhendrix** [comment]
Updated the list in the issue description above.

**Comment by cjhendrix** [comment]
downgrading this to medium after our discussion the other day.

**Comment by cjhendrix** [comment]
downgrading this to medium after our recent discussion

**Comment by alexandru-m-g** [comment]
KML support was added.
