### ISSUE TITLE
New window opening when clicking on the "Reset all" link of the 3W visualization

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2969]
When exploring the 3W component visualization an user can filter the data by clicking on the map or on the bars. However, when the user wants to "reset" the visualization by clicking on "Reset all", it opens a new window as it the link had a `target=_blank` parameter set. 

This issue is happening on `Firefox 38.0.5` on Mac Yosemite 10.10.3 (14D136). Other users have reported the same issue with Firefox as well (@reubano + Moses). 

![screen shot 2015-06-23 at 2 50 41 pm](https://cloud.githubusercontent.com/assets/953118/8314468/bd4b9996-19b7-11e5-9a63-23a6c12019f6.png)

**Comment by danmihaila** [comment]
Related to #2942 , ping @mbellotti

**Comment by mbellotti** [comment]
Okay I suggest we comment out this script and table this issue. I can
modify tracking.js to open a new window for downloads, will that work for
now?

**Comment by danmihaila** [comment]
@mbellotti can you please revert your changes? We will need to revert&hotfix production and to bring the fix to 2.3 branch too.

**Comment by alexandru-m-g** [comment]
I suggest investing a bit of time to see if it's possible to fix this without modifying core ckan

**Comment by mbellotti** [comment]
We never modified ckan core for this.

On Wed, Jun 24, 2015 at 5:43 PM, Alexandru Gartner <notifications@github.com

**Comment by alexandru-m-g** [comment]
I mean tracking.js. isn't it part of core ckan?

**Comment by mbellotti** [comment]
Ah! Sorry I assumed you were talking about the revert.

On Wed, Jun 24, 2015 at 5:45 PM, Alexandru Gartner <notifications@github.com
