### ISSUE TITLE
Geo-preview: triggering geo transformation

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2999]
- [ ] resources/datasets created via API 
- [ ] resource/datasets created via HDX UI (we need to bring changes from geo branch to 2.3 upgrade branch)

**Comment by alexandru-m-g** [comment]
I think we should move the logic that triggers the "gis layer creation" process from the controller to the _resource_create_ & _resource_update_ actions. 
Also, we need to make sure that even in case a new resource is created, its ID is sent to the GIS layer.
