### ISSUE TITLE
Trying to download private resource does not return 401 (Unauthorized)

### ISSUE THREAD

**Issue by davidmegginson** [OCHA-DAP/hdx-ckan#3009]
When I attempt to download a private (at the time of writing) resource like http://data.hdx.rwlabs.org/dataset/beneficiary-target/resource_download/600672e7-9421-4bcb-b1c8-835b77be7d3c (at the time of download), the app returns a 303 (see other) redirect, then a 302 (found) redirect, then a 200 (ok) status with the HTML login page. 

This provides a good interactive user experience via the browser, but is poor for any RESTful software trying to access the resource, where it would expect a 401 Unauthorized response.  I'm running into this problem with the HXL Proxy now, and I expect other RESTful apps using HDX-hosted resources will have a similar problem in the future.

**Comment by danmihaila** [comment]
this is interesting. We might do these changes in there is a strong recommendation to do it after our upgrade to 2.3 and migration to new servers.
Thanks @davidmegginson for rising this concerns

**Comment by davidmegginson** [comment]
It actually turns out that there is no documented way to download a private resource from the FileStore non-interactively — there's no API call where you can provide your CKAN API key, for example. That may become a separate issue for some of the HXL pilots (not the Guinea one, yet).

**Comment by reubano** [comment]
I'm having this same issue. Requests returns a 200 but if you look at the [history](http://docs.python-requests.org/en/latest/user/quickstart/#redirection-and-history) you see the 401s.

**Comment by reubano** [comment]
@davidmegginson there is no api call to download a resource whether it is public OR private. Best you can do via the api is get the resource object which contains the `url`, and then use `requests` to fetch.

**Comment by teodorescuserban** [comment]
@reubano are you sure there are 401s in requests history? I would think there are 301s.

**Comment by reubano** [comment]
@teodorescuserban you may be right. i don't have the ipython window open now. I recall seeing `x-ckan-api` and `squid` unauthorized errors.

**Comment by teodorescuserban** [comment]
squid unauthorized will appear if you try to acess anything on http instead of https.

**Comment by teodorescuserban** [comment]
Update: please try to add the following header to your call:
X-CKAN-API-Key: 'your_real_api_key'
If your user has access to that dataset, you should be able to access it through the api.
Closing. 
Please feel free to reopen.
