### ISSUE TITLE
Filestore downloads do not support CORS

### ISSUE THREAD

**Issue by davidmegginson** [OCHA-DAP/hdx-ckan#3010]
Public data files downloadable from HDX should support CORS, so that browser-based visualisations hosted on other domains can use them without resorting to hacks like a JSONP proxy.  This means simply adding one HTTP header to all public files downloaded from the Filestore:

```
Access-Control-Allow-Origin: *
```

This change will make a big difference in the usability of HDX-hosted data by web developers.  More details here: https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

**Comment by reubano** [comment]
View https://github.com/jfinkels/flask-restless/issues/223 for more info

**Comment by teodorescuserban** [comment]
Fixed.
