### ISSUE TITLE
Search Results: when filtering by "zipped shapefile" and ordering by "last modified" no datasets are shown

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3014]
On prod:
1. go to /dataset
2. filter by format = "zipped shapefile"
3. sort by "last modified"

I wasn't able find this with different combinations of format at sort.  My bet is that the space in "zipped shapefile" is choking something.

![image](https://cloud.githubusercontent.com/assets/1654485/8472677/8ec87a10-20a3-11e5-9fe0-fc4cfdb6478a.png)

**Comment by danmihaila** [comment]
good catch. it looks to be a bug about tags with at least two words. if you try this url it will work
https://data.hdx.rwlabs.org/dataset?sort=title_case_insensitive+desc&res_format=zipped%20shapefile
or 
"https://data.hdx.rwlabs.org/dataset?sort=title_case_insensitive+desc&res_format=zipped shapefile"

**Comment by danmihaila** [comment]
assigned to @mbellotti as she fixed something similar

**Comment by danmihaila** [comment]
related to #3285
