### ISSUE TITLE
Default organizatoin page: change or remove the "updated" date

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3021]
![image](https://cloud.githubusercontent.com/assets/1654485/8501218/b290cec4-21a3-11e5-89b2-5dd21077a221.png)
This currently displays the most recent date of update to a dataset belonging to the org.  

Preferred behavior: display "Joined on" with the created date.

**Comment by danmihaila** [comment]
I think we should check if it is the latest change on organization entity or dataset belonging the org.
@cjhendrix and @amcguire62 do we have any plans to change the default org page template?

**Comment by cjhendrix** [comment]
I haven't heard of any plans. @amcguire62 ?
