### ISSUE TITLE
Search result snippet: use dataset_date instead of metadata_modified

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3022]
The user gave an example of a dataset from 2010 which shows 2015 in the search result snippet because that's when the dataset was added to HDX.  This is confusing to users. 

Things to consider when considering how to solve this:
1. dataset date is not a required field and will not always be present
2. sort behavior needs to remain sensible
3. currently ckan is unaware of updates to remote resources (#2804)

**Comment by cjhendrix** [comment]
Maybe we should just show both the dates:  
- Date metadata modified
- Dataset date

It won't be as pretty, but I think both of those dates would be useful to users.

**Comment by danmihaila** [comment]
@yumiendo - can we chat about issue and how to display both dates? You can check this url: 
https://data.hdx.rwlabs.org/organization/acaps

**Comment by yumiendo** [comment]
@danmihaila - im not seeing the relevant page to this issue (the link you pasted) am I missing something?
 
maybe we could do something like the comp (attached) - After "meta data" header, we include "last updated MM-DD-YEAR"
![screen-shot-2015-07-13-at-9 13 46-am](https://cloud.githubusercontent.com/assets/8006323/8650147/a279e172-293e-11e5-8c4e-9f9760e34a5b.png)

**Comment by danmihaila** [comment]
@yumiendo sorry about link only with private datasets :)
check for example: https://data.hdx.rwlabs.org/organization/brcmapsteam list of datasets

**Comment by danmihaila** [comment]
assigned to @yumiendo for comments

**Comment by yumiendo** [comment]
im noticing that not all but a lot of datasets do have dataset date in either title / description / file name and im not sure repeating dates are necessarily good solution.

Would it be more obvious if we put "last updated:" in front of "Month-DD, YEAR"?  (screen attached below)

Ive also noticed that the date stamp in the search result is reflecting activity...(looks like there is no distinction between meta data update or dataset update?) 
<img width="1174" alt="screen shot 2015-08-31 at 12 02 56 pm" src="https://cloud.githubusercontent.com/assets/8006323/9583239/29a1286c-4fd8-11e5-8748-41e8751054d5.png">

**Comment by danmihaila** [comment]
@yumiendo I think there are 2 types of dates as CJ commented:
- metadata date - automatically set in database when a dataset is changed
- dataset date - user has to fill this field in admin form
  I am not sure I understand your comment.
  Basically, we need to decide how to display both dates in case they exists. I also noticed that there are users asking about dataset date which is important.

**Comment by cjhendrix** [comment]
Regarding @yumiendo 's suggestion:  "last updated" is confusing  because it isn't clear if we are saying when the ckan record was updated (such as fixing a type in the description) or when the actual data file (as in a new weekly version of an XLXS of ebola cases) is updated.  Users care more about the latter than the former.

**Comment by cjhendrix** [comment]
@yumiendo  We probably should resolve this one as part of the #3555 work.  Happy to discuss.

**Comment by yumiendo** [comment]
hi all - as per earlier call, comp attached.
<img width="1200" alt="screen shot 2015-09-28 at 7 32 34 pm" src="https://cloud.githubusercontent.com/assets/8006323/10167410/67927a48-6696-11e5-86bc-b3ded933113c.png">

**Comment by danmihaila** [comment]
@mbellotti when solving this issue please check last comment from Yumi with comp attached. this is the final requirement

**Comment by danmihaila** [comment]
I have local this error: File '/srv/ckan/ckanext-hdx_theme/ckanext/hdx_theme/helpers/helpers.py', line 142 in get_dataset_date_format
  dt = datetime.datetime.strptime(d, '%m/%d/%Y')
File '/usr/lib/python2.7/_strptime.py', line 325 in _strptime
  (data_string, format))
ValueError: time data '' does not match format '%m/%d/%Y'

**Comment by yumiendo** [comment]
Can be add a break after the org name, before the dates? 
before & after below:
BEFORE
<img width="1196" alt="screen shot 2015-11-02 at 11 19 22 am" src="https://cloud.githubusercontent.com/assets/8006323/10886685/46d4e7de-8151-11e5-8adf-58f3592d9ce4.png">

AFTER
<img width="1198" alt="screen shot 2015-11-02 at 11 18 52 am copy" src="https://cloud.githubusercontent.com/assets/8006323/10886720/7ab34f14-8151-11e5-994f-217fad9c620e.png">

**Comment by danmihaila** [comment]
ok, will do it
