### ISSUE TITLE
Add a "search within" box to the crisis and custom location pages

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3030]
Add the search box similar to what appears on the custom org pages.

![image](https://cloud.githubusercontent.com/assets/1654485/8541629/edb16c72-248f-11e5-8bef-79764df54282.png)

**Comment by danmihaila** [comment]
this will be done in #3555

**Comment by danmihaila** [comment]
this is done, closing this one
