### ISSUE TITLE
Email validation: login error (Typo)

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3031]
@mbellotti I think it is a typo in code. please check error below:
ckanext.hdx_users.controllers.mail_validation_controller:343 in logged_in

AttributeError: 'ValidationController' object has no attribute '_sane_came_from'

Can you fix it as it is a blocker?

**Comment by danmihaila** [comment]
another one in mail_validation_controller: 131-133 (numbers might be different): 
def request(...)
...
                    send_mail(name, email, org, reason)
                    h.flash_success(_('We will check your request and we will send you an email!'))
                    h.redirect_to('/')
...
"send_mail" shows an error

**Comment by mbellotti** [comment]
It's not a typo but that's strange because it's a problem I specifically
remember fixing last Sprint.... maybe it got lost when we redid the git
branch? O.o

**Comment by danmihaila** [comment]
closing this one
