### ISSUE TITLE
"Share from Google Drive" button

### ISSUE THREAD

**Issue by davidmegginson** [OCHA-DAP/hdx-ckan#3037]
I propose that we add a "Share from Google Drive" button that uses the Drive API to create a selector where the user can choose a Google Sheet to share, and we can automatically create the proper CSV/Excel download URLs for the HDX resource.

**Comment by teodorescuserban** [comment]
Please note that it looks like Gdocs API  (not sure if Drive API it's the same) it can suddenly change and csv downloads wont work. And then it might change back in a couple of hours. This happened to me more than once.
