### ISSUE TITLE
Custom org page not using appropriate resource url

### ISSUE THREAD

**Issue by reubano** [OCHA-DAP/hdx-ckan#3044]
When uploading resources to the filestore via ckan api, the download url is set to the dataset id as opposed to the dataset name, i.e., `http://<remote>/dataset/e66dbc70-17fe-4230-b9d6-855d192fc05c/resource/<resource_id>/download/<file_name>` vs `http://<remote>/dataset/json-repository/resource/<resource_id>/download/<file_name>`. This breaks the 3w viz as it expects the json file to be available at the later.

**Comment by reubano** [comment]
I'd suggest not hard-coding in the url, and instead using something like this:

```
import ckanapi

ckan = ckanapi('url)
resource = ckan.action.resource_show(id='resource_id')
# sometimes there is a `perma_link` 
# url = resource.get('perma_link') or resource.get('url')
url = resource.get('url')
```

This could be implemented in [before_map()](https://github.com/OCHA-DAP/hdx-ckan/blob/cc32773424d4f642630f651b3014628a248a30a6/ckanext-hdx_package/ckanext/hdx_package/plugin.py#L75).

**Comment by cjhendrix** [comment]
this might be 2.3.  Labeling as such and putting into sprint cadidates.

**Comment by reubano** [comment]
I'm guessing it's hardcoded since the [http api](https://test-data.hdx.rwlabs.org/api/action/resource_show?id=c393a6a2-aa66-4f33-94cc-ce7d32fcdd27) shows the correct url of `http://test-data.hdx.rwlabs.org/dataset/e66dbc70-17fe-4230-b9d6-855d192fc05c/resource/c393a6a2-aa66-4f33-94cc-ce7d32fcdd27/download/maliadmnbndaAdm1Gov.geojson`.

**Comment by danmihaila** [comment]
all our custom pages are broken right now, we are working to fix it. tnx!

**Comment by danmihaila** [comment]
I think this is done, now. closing it. @reubano if you can still reproduce it reopen this issue
