### ISSUE TITLE
Copy the HR.info terms of use to a page on HDX

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3055]
Copy the main content from here: http://www.humanitarianresponse.info/en/applications/data/page/terms-use
to a page on HDX.  I suggest /about/license/legacy_hrinfo  @amcguire62 ?

Our page should contain the following:

```
Some datasets migrated from the COD/FOD Registry formerly on HumanitarianResponse.info have a legacy license that is reproduced below for convenience.  The original location of this license is [here](http://www.humanitarianresponse.info/en/applications/data/page/terms-use).
```

Following that introduction, reproduce the contents of the HR.info page from
 "Terms of Use"  down to " . . . duly authorized representative."

**Comment by cjhendrix** [comment]
URL confirmed by @amcguire62

**Comment by teodorescuserban** [comment]
tagging @cjhendrix please confirm it looks alright.

**Comment by cjhendrix** [comment]
Looks great.  Thanks!  Maybe @amcguire62 should have a look also.

**Comment by danmihaila** [comment]
beer?

**Comment by teodorescuserban** [comment]
On me, BUT at my place :P

În Joi, 6 aug. 2015 la 17:45, danmihaila notifications@github.com a scris:
