### ISSUE TITLE
Org member list: icons not well aligned

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3066]
<img width="627" alt="screen shot 2015-07-13 at 13 25 59" src="https://cloud.githubusercontent.com/assets/3865844/8647673/bed85a5a-2962-11e5-81ab-e53f99d314ad.png">
Trash button and edit are not well aligned

**Comment by alexandru-m-g** [comment]
This commit is also related to this ticket ( wrong comment in commit):
https://github.com/OCHA-DAP/hdx-ckan/commit/69b4c4f88dfa1c74054c3c461123b0bd916ee00b
