### ISSUE TITLE
Org add member modal not working

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3067]
- [ ] modal is not working
- [ ] check if add/edit/remove member is working for different roles of users

**Comment by alexandru-m-g** [comment]
This commit is also related to this ticket ( wrong comment in commit):
https://github.com/OCHA-DAP/hdx-ckan/commit/69b4c4f88dfa1c74054c3c461123b0bd916ee00b

**Comment by cjhendrix** [comment]
Reopening.  The edit button (for a specific org member) works the first time, but not afterward.  
1. go to the member list page for an org
2. edit some member
3. success message is displayed
4. click an edit button - nothing happens
5. refresh
6. try to edit again, it works
