### ISSUE TITLE
Default Org Page:  Dataset filter counts are confusing

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3069]
The numbers beside each facet are hard to understand.  In the example below
- beside "FORMATS" it says 13, but only 12 are displayed
- beside TAGs it says 1571, but INNAGO only has 67 datasets and listing all the tags shows only a couple dozen, not 1571. 

![image](https://cloud.githubusercontent.com/assets/1654485/8648653/a502cdae-2962-11e5-9349-f63e4bc526cd.png)

**Comment by danmihaila** [comment]
right now the big number is the total of tags. it was a bug in displaying that one, I hope it is ok now
