### ISSUE TITLE
Location default page: not working

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3070]
- [ ] Going to https://test-data.hdx.rwlabs.org/group/abw is not loading the map, giving script errors.
  Also check browser console for errors that need to be fixed
- [ ] check header for Datasets and alignments on page

**Comment by cjhendrix** [comment]
Ok, my part is done.  :p  And fixed on prod as well.

**Comment by danmihaila** [comment]
@cjhendrix , can you also check other locations during your tests or UATs? (random picking maybe...) thanks
