### ISSUE TITLE
Create a router to send a test email

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#3074]
Needed to test the email functionality.
Ask me fo details.
Thank you.

**Comment by teodorescuserban** [comment]
tagging @alexandru-m-g : lets discuss :)

**Comment by danmihaila** [comment]
@teodorescuserban having the monitor of external services implemented by @alexandru-m-g i think we can close this one

**Comment by alexandru-m-g** [comment]
@danmihaila  for now the monitor verifies HTTP services ( so not the email service ). Will need to talk to @teodorescuserban to see how to best test the email service.

**Comment by teodorescuserban** [comment]
As per discussed today:

@alexandru-m-g will do a service check by testing the ip/port pair of `smtp.server` and `smtp_server` is open.
@alexandru-m-g will subsequently provide a button on the health check to generated some kind of "print test page" by email (possibly sending it to the email address of the sysadmin that is clicking on it).

also tagging @danmihaila and @cjhendrix

**Comment by danmihaila** [comment]
any updates on this one @teodorescuserban  and @alexandru-m-g ?

**Comment by teodorescuserban** [comment]
not relevant anymore
