### ISSUE TITLE
Search Results: Accented characters are sorted after Z

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3076]
Accented characters are sorted after Z alphabetically.  They should be sorted with their "base" character.  

Something like
a
æ
å
ä
ã
â
á
à
b
c
ç
d
e
é
ê
ë
f
g
h
i
ì
í
î
ï 
and so on.  Someone out there must have figured out a logical way to do this. There are some characters for which it isn't clear where they go, like ß

**Comment by mbellotti** [comment]
This is a problem in core https://github.com/ckan/ckan/issues/1676 Although they seem to not want to do anything about it. I've made the change he suggested to our search extension. The solr index will have to be rebuilt in order to see the effect (@teodorescuserban)

**Comment by cjhendrix** [comment]
tested with this one  https://test-data.hdx.rwlabs.org/dataset/a-test-of-accented-character-sorting. Working.

**Comment by cjhendrix** [comment]
but the character "Í" is still sorting after z.  https://test-data.hdx.rwlabs.org/dataset?sort=title_case_insensitive+desc
