### ISSUE TITLE
Search Results: changing sort type from a middle page keeps the same page number

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3078]
I'm not sure if this is the desired behavior or not.  @yumiendo ?  Seems like it might be more logical to load page 1 of the new sort. 
1. From page 3 of a search result https://test-data.hdx.rwlabs.org/dataset?sort=title_case_insensitive+desc&page=3
2. Change the sort type 
3. Loads page 3 of the new sort: https://test-data.hdx.rwlabs.org/dataset?sort=title_case_insensitive+desc&page=3

**Comment by yumiendo** [comment]
mmm I agree. sort should override the page #. so in this scenario once user used the sort - it should refresh the view to page 1.

**Comment by cjhendrix** [comment]
Thanks Yumi.  Then it's settled, and in the backlog. Not a high priority, I think, but ready to be worked on when someone has time.

**Comment by danmihaila** [comment]
I agree with this.
