### ISSUE TITLE
Downloading:  behavior of download button different in different places

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3079]
Download a csv file from the dataset page and again from the preview page.  
1. When downloading from the dataset page, a new empty browser tab is opened (in chrome).  
2. When downloading from the preview page, no new tab is opened.

If possible, we should make the dataset page download button behave the same way as the preview download button.

**Comment by cjhendrix** [comment]
This seems to have come back.

**Comment by mbellotti** [comment]
@cjhendrix while I was fixing this I noticed that web browsers like Chrome will disable the opening of a new window automatically-- thereby making it appear to an uneducated user that the download itself is broken. Are we sure we want to keep this functionality?

**Comment by cjhendrix** [comment]
The issue description is proposing to eliminate the new tab.  So that would avoid the problem in Chrome, I think.  Unless I'm misunderstanding.

**Comment by mbellotti** [comment]
!!! Actually I was the one who misunderstood I think. I read this issue as the behavior should be consistent in both places (open in a new tab when file is not hosted on HDX), because my understanding was this feature was requested by Sarah https://github.com/OCHA-DAP/hdx-ckan/issues/2882

So.... are we getting rid of this completely now?

**Comment by cjhendrix** [comment]
Thanks for finding that original issue.  I knew we had some history with this one. I think we'll have to talk to Sarah to nail it down.

**Comment by cjhendrix** [comment]
So, here is the summary of the current behavior of our download button **on the dataset view page**
1. External links open in a new tab.  This is fine when it [goes to a webpage](https://data.hdx.rwlabs.org/dataset/ebola-geonode), but looks kind of awkward [when it is a download](https://data.hdx.rwlabs.org/dataset/syria-border-crossings) (try downloading the zipped shapefile resource).  
2. [filestore (and presumably datastore) downloads do not open a new tab](https://data.hdx.rwlabs.org/dataset/nepal-health-facilities-cod), which seems sensible

As best I can tell, the same rules apply to the download button on preview page **except** for remote resources, which do not open in a new tab.  But that's probably a good thing, because the only remote resources with previews are actual files, for which it doesn't make sense to open a new tab. 

So, all that said.  It's messy, but it seems to be what was specified.  Closing.
