### ISSUE TITLE
Dataset View: Preview button not showing for previewable files (at least for txt and csv)

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3080]
![image](https://cloud.githubusercontent.com/assets/1654485/8650019/cef360ee-296f-11e5-993c-b80a7539196c.png)

**Comment by danmihaila** [comment]
this has to do with latest changes. this is an external url to a csv file.
assigned to @alexandru-m-g

**Comment by alexandru-m-g** [comment]
A related problem is that sometimes when previewing a CSV there  is a javascript exception while recline is running the sanitizeFieldName() function: `Uncaught Error: Syntax error, unrecognized expression: (Chose one ID per assessment report)` 

A fix is committed below.

**Comment by alexandru-m-g** [comment]
@teodorescuserban IT seems that we do need to run the following command: `paster views create recline_view text_view -c /srv/prod.ini` on the server. I know you tried it on staging and it was giving some error. Let's try together to debug it. On my local computer it seems to work fine.

**Comment by alexandru-m-g** [comment]
Tested with @teodorescuserban on staging and it works. Closing.
