### ISSUE TITLE
Filestore: OFS

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3081]
Go to: https://test-data.hdx.rwlabs.org/dataset/json-repository
you will see a bunch of existing files that will display the OFS link: http://data.hdx.rwlabs.org/storage/f/2015-06-16T21%3A22%3A52.437Z/mli-idps-region-2015-may.csv
If you update an existing resource, the download link will be the new format.
We should display only one type of for downloading resources (the new one) even for OFS stored files. We could use the previous action/url we had.
@mbellotti pls share any thoughts or ideas pros or cons.

**Comment by mbellotti** [comment]
Oh no, I don't think this is a good idea. The two different URLs very easily tell CKAN where to find the file (OFS or new filestore), making maintaining two systems for now pretty clean and simple. I'm not sure what if any bugs might come up if we do this. Is there any advantage to having downloads come through the same route other than the superficial? Most users are not going to notice one way or another and both urls are permalinks.

**Comment by danmihaila** [comment]
1.
Actually, if I remember correct @cjhendrix this was one main request to get rid of url like "...storage/f/2015-06-16T21%3A22%3A52.437Z..." and have permalinks.
We could try to use something that we had before "...dataset/2dc23901-20b6-41b9-871b-e1b2801fc7c9/resource/b7046604-5318-4b99-8bc0-8139b4a2298c/download"
2. What about private resources? if we are going to expose "...storage/f/2015-06-16T21%3A22%3A52.437Z..." is it going to display or not the private resources?

**Comment by mbellotti** [comment]
This is kind of the problem we were having with the migration script, the storage/f/ url is actually stored in the db as the url of the file and yet when the migration script updates both the url on the resource table and the url on the resource_revision page, CKAN still displays that storage/f/ route. I was in the middle of trying to figure out what was going on here.

As for private resources, I thought we had fixed that problem long ago?

Anyway I will give it a shot and report back.

**Comment by danmihaila** [comment]
ok. Please let us know what you find. Also, I suggest to take a look over our old code for permalinks.

**Comment by cjhendrix** [comment]
On the point I was tagged in above, the requirement was to have permalinks for resource downloads. Beyond that I don't recall any specification about how we get that done.

**Comment by alexandru-m-g** [comment]
Does this mean we want to keep both OFS and the new 2.3 way of storing files for now ? 
Why can't we completely migrate to the new one? IMHO, trying to maintain 2 storage system will only cause headaches in the future.

**Comment by danmihaila** [comment]
I checked and private resources are fixed. Lets chat during our SPAR call about permalink and migration script.
