### ISSUE TITLE
Organization List: for the "+" is missing from "Add Organization

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3082]
The button is only visible to sysadmins, which is the desired behavior.

On stag v0.10.0: 
![image](https://cloud.githubusercontent.com/assets/1654485/8650312/30de9ff6-2972-11e5-927f-22a31c0af088.png)

On prod v0.9.8
![image](https://cloud.githubusercontent.com/assets/1654485/8650334/4e8d7874-2972-11e5-9dd7-8c166ed21323.png)

**Comment by mbellotti** [comment]
The problem is that bootstrap isn't using font awesome anymore. In my original fix I just included font awesome into hdx_theme, restoring the icons. However @aalecs and @yumiendo think it's better just to get rid of the icons altogether, so that's what we'll do.
