### ISSUE TITLE
less recompile over and over again

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#3093]
Even if `hdx.less_compile.onstartup = False` on ckan restart less compile is run.

This delays the actual startup of ckan with more than 30 seconds (on staging). Might be less on production - hopefully we didn't needed restart on prod.

tagging @danmihaila to assign and prioritize.

**Comment by alexandru-m-g** [comment]
@teodorescuserban: let's look at this more closely on staging. I looked on my local machine and this doesn't seem to happen.

**Comment by teodorescuserban** [comment]
might be still related with build cache on startup = True?

**Comment by teodorescuserban** [comment]
It was just a leftover in startup script.
Fixed and closing.
