### ISSUE TITLE
Add ".shp.zip" as a geo preview triggering extension

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3094]
Reminder for cj:  update the faq text to reflect this change.

**Comment by alexandru-m-g** [comment]
@cjhendrix The code is committed . How should I change the FAQ text ?

**Comment by cjhendrix** [comment]
Tagging @ochadataproject for approval of change to FAQ text.   It's ok for this commit to be deployed without the FAQ change, if approval is still pending.

Change this paragraph:

![image](https://cloud.githubusercontent.com/assets/1654485/9607364/05b02c2c-50c9-11e5-9583-b3164fc77762.png)

to

`The HDX system will attempt to create a map, or geographic preview, from geodata formats that it recognizes. For a geographic preview to be generated, your data needs to be in either a zipped shapefile, kml or geojson format. Ensure that the 'format' field on the resource creation form also specifies "zipped shapefile", "kml" or "geojson". Pro tip: HDX will automatically add the correct format if the file extension is ".shp.zip", ".kml", or ".geojson". Here are examples of geodata points, lines, and polygons that show the preview feature.`

Please be sure to retain the hrefs in the last sentence.

**Comment by ochadataproject** [comment]
Looks fine thanks

**Comment by cjhendrix** [comment]
FYI @ochadataproject :  We changed the text a bit above to capture a subtlety about how this works. I think it's fine, but let us know if you want changes.  Thanks @alexandru-m-g for catching it.
