### ISSUE TITLE
Problem when an uploaded resource is updated to a "link to url" resource

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#3098]
There seems to be a bug when you switch from an uploaded resource to a "Link to url" it still gets treated as uploaded and the download link is weird, like: http://test-data.hdx.rwlabs.org/dataset/413d5f86-9c91-47ea-994c-71c435ec6bb5/resource/47079c73-a4c5-44e4-82a6-13291ee0aec6/download/ucid0B9V0hbx2cV31elJLNmZCSm8xZncexportdownload

**Comment by danmihaila** [comment]
Assigned to @mbellotti as she made the changes regarding OFS and initial updates of UI
