### ISSUE TITLE
Filestore downloading seems broken

### ISSUE THREAD

**Issue by reubano** [OCHA-DAP/hdx-ckan#3104]
I uploaded a [file](https://test-data.hdx.rwlabs.org/dataset/json-repository/resource/3333793a-041a-4ec8-a2c6-10ef71e4abec) via the browser to `json-repository` but get a `404` error when trying to download it.

**Comment by danmihaila** [comment]
@reubano can you retest this issue?

**Comment by reubano** [comment]
trying to... having internet issues.

**Comment by reubano** [comment]
Direct downloading works but now an issue with the [3w](https://test-data.hdx.rwlabs.org/organization/ocha-mali). It is trying to download the [geojson](https://test-data.hdx.rwlabs.org/dataset/json-repository/resource/c393a6a2-aa66-4f33-94cc-ce7d32fcdd27) from 

[json-repository](https://test-data.hdx.rwlabs.org/dataset/json-repository/resource_download/c393a6a2-aa66-4f33-94cc-ce7d32fcdd27) (and gets 500 error) but the download url is [this](http://test-data.hdx.rwlabs.org/dataset/e66dbc70-17fe-4230-b9d6-855d192fc05c/resource/c393a6a2-aa66-4f33-94cc-ce7d32fcdd27/download/maliadmnbndaAdm1Gov.geojson). Note this is via uploading from the website and not via the api as in #3044.

**Comment by teodorescuserban** [comment]
the filestore has been migrated off of old ofs, hence the url change.
3w maintainer needs to update the thing.

**Comment by reubano** [comment]
@teodorescuserban Gotcha.

**Comment by cjhendrix** [comment]
@teodorescuserban  it sounds like you are saying all our old filestore resources will have to be updated after we migrate.    I'm sure that's not the case, right?

**Comment by teodorescuserban** [comment]
the ofs migration will move the most recent version of a resource in a different folder and change the url.

We will keep all resource files but the url to get them will change in the form:

``` https://data.hdx.rwlabs.org/dataset/<dataset-id>/resource/<resource-id>/download/<file-name>```

```
