### ISSUE TITLE
Dataset download: the last few kb are very slow to arrive for recently added resources

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3106]
When I download resources (whether large or small), I get almost all of the file, but the last few kb take more than a minute. 

For example, [this one](https://test-data.hdx.rwlabs.org/dataset/mali-3w), got to 35.1kb (of 36kb) in less than a second, but took another 1.5 minutes to complete. 

It seems this is only happening to recently added resources.  Older resources download normally.

**Comment by danmihaila** [comment]
@cjhendrix can you confirm this is still an issue on staging?

**Comment by cjhendrix** [comment]
Yes, still an issue.  Just tried it here: https://test-data.hdx.rwlabs.org/dataset/testingtesting

**Comment by teodorescuserban** [comment]
can you please try on demo stack ?
thank you.

**Comment by danmihaila** [comment]
duplicated by another issue, closing this one
