### ISSUE TITLE
Misbehaving gallery items

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3107]
Dev team is probably already aware of this, but just in case.  Seems to be happening on all gallery items (with large thumbnails at least).

![image](https://cloud.githubusercontent.com/assets/1654485/8715231/ba92bee0-2b7e-11e5-84af-f106a5222fdf.png)

**Comment by danmihaila** [comment]
duplicated, already assigned in current sprint. closing it
