### ISSUE TITLE
Geo Preview: kml, kmz

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3108]
These were working before (if format was forced to geojson or zipped shapefile).   They are not working now.  Not sure what changed, since ogr2ogr should be processing them.

Note, I'm making this a medium priority since we don't want to delay deployment for these secondary formats.

**Comment by danmihaila** [comment]
@alexandru-m-g what is the status/solution of this issue?

**Comment by alexandru-m-g** [comment]
@cjhendrix is this still an issue ?

**Comment by cjhendrix** [comment]
We ruled out KMZ, but I haven't had time to test KML yet.  So not sure. I'll close this one and reopen if I find a problem.
