### ISSUE TITLE
Dataset View:  "make it public" modal styling

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3109]
![image](https://cloud.githubusercontent.com/assets/1654485/8715640/9cb09436-2b85-11e5-9906-f80d9a455a4e.png)

**Comment by cjhendrix** [comment]
Also note that the "make public" link doesn't appear to work.

**Comment by danmihaila** [comment]
assigned to @mbellotti as she did the initial version of this code. Please note that this is for sprint 60, and it needs to go to prod.
