### ISSUE TITLE
Geo Preview: difficult to click point data

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3112]
- [ ] change hand icon to a pointer
- [ ] see if we can tweak the click location to make it easier to click on a point

**Comment by cjhendrix** [comment]
Mentioned by @pjdufour as well.

**Comment by cjhendrix** [comment]
+1  - Another request on this one to our feedback email from a user in Yemen.

**Comment by aalecs** [comment]
ex: https://data.hdx.rwlabs.org/dataset/nepal-health-facilities-cod

**Comment by cjhendrix** [comment]
After conversation with @alexandru-m-g, we will leave the cursor change out for now until we can discuss the best design solution (via another issue).

**Comment by alexandru-m-g** [comment]
@cjhendrix as discussed I opened a related ticket that deals with the onhover functionality research:

https://github.com/OCHA-DAP/hdx-ckan/issues/3503
