### ISSUE TITLE
Global Search / Country

### ISSUE THREAD

**Issue by pjdufour** [OCHA-DAP/hdx-ckan#3116]
When you use the global search (site-wide search field) to search for `ebola` it automatically takes you to the Ebola crisis page (https://data.hdx.rwlabs.org/ebola).  When searching "yemen", even though there is a nice Yemen country page, it takes you to https://data.hdx.rwlabs.org/search?q=yemen.  When a search term is a `case-insensitive contains` match for a country name, add a small section about the indicators and datasets results that says something like: `Go to country page for Yemen`.

A suggestion bar could be useful for other use cases as well, such as minor mispellings.  Distance calculation against all tags (pre-sorted into treeset in-memory if needed for performance).  If only 3 characters off and matches only one tag, prompt suggestion.  For example, when mispelling boundaries as boundries (https://data.hdx.rwlabs.org/search?q=boundries), prompt: `Did you mean boundaries?`

**Comment by danmihaila** [comment]
@pjdufour The search for ebola is a redirect we are doing as a special case. We are currently working on a module to improve our search results and when searching for a country (e.g yemen as in your example) it will surface out the country page.
The second iteration of improving our search will be related to suggestion and predictive search (e.g boundries).
Thank you for your useful feedback and will be back to you when we have some good results.

**Comment by danmihaila** [comment]
@pjdufour can you check now https://data.hdx.rwlabs.org/search?q=yemen ?
