### ISSUE TITLE
Search: recommendations for users

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3137]
When a user is performing a search inside HDX, there is a need to display and highlight other key pages together with datasets. Base document can be found here: https://docs.google.com/document/d/1qVUS05rc-q88u4k5NqTtCzcrjOSM8a94h1YbbEwf-3Q/edit#
- [ ] include in search recommendations Crises, Organizations, Locations, 
- [ ] maximum 5 recommendations for the moment with a mix of entities
- [ ] remove "All" tab, and move "Datasets" tab on first position with default focus on it
- [ ] Check section "Details on actual search results" from google doc for three scenarios related to search terms
- [ ] Check screenshot to see how to display the results
  ![screen shot 2015-07-20 at 11 16 44](https://cloud.githubusercontent.com/assets/3865844/8772055/20005918-2ed1-11e5-9652-eff0e9971f15.png)

**Comment by mbellotti** [comment]
Adding instructions here for future reference:

There's a console script to set up the index. So when you're ready deploy, run python setup.py develop in hdx_search and then run the paster command paster hdx- feature-search build. That will write the js file that lunr uses to build it's index

**Comment by danmihaila** [comment]
@mbellotti please write the exact commands for @teodorescuserban to run in order to have the process easier and faster. thanks

**Comment by mbellotti** [comment]
Sure:
- "python setup.py develop" in hdx_search extension
- "paster hdx-feature-search build --config=...." in that same folder

Better?

**Comment by danmihaila** [comment]
yes, much better. I saw in our previous comment a typo (then run the paster command paster hdx- feature-search build) and i wanted to be sure Serban has the instructions to do it alone.
thanks

**Comment by teodorescuserban** [comment]
"python setup.py develop" in hdx_search extension  == hdxckantool plugins dev

**Comment by danmihaila** [comment]
trying to run again the reindex on staging raises this error:
root@ckan:/srv/ckan/ckanext-hdx_search/ckanext/hdx_search# paster hdx-feature-search build -c /srv/prod.ini                                               Collecting Feature Pages...                                                  Traceback (most recent call last):                                             File "/usr/local/bin/paster", line 9, in <module>                              load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()      File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 104, in run                                                                     invoke(command, command_name, options, args[1:])
 File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 143, in invoke
   exit_code = runner.run(args)                                               File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 238, in run                                                                     result = self.command()
 File "/srv/ckan/ckanext-hdx_search/ckanext/hdx_search/command.py", line 31, in command
   self.buildIndex()
 File "/srv/ckan/ckanext-hdx_search/ckanext/hdx_search/command.py", line 43, in buildIndex
   crises = config.get('hdx.crises').split(", ")
NameError: global name 'config' is not defined                               root@ckan:/srv/ckan/ckanext-hdx_search/ckanext/hdx_search# paster hdx-feature-search build -c /srv/prod.ini
Collecting Feature Pages...                                                  Traceback (most recent call last):                                             File "/usr/local/bin/paster", line 9, in <module>                              load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()      File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 104, in run                                                                     invoke(command, command_name, options, args[1:])                           File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 143, in invoke
   exit_code = runner.run(args)                                               File "/usr/local/lib/python2.7/dist-packages/paste/script/command.py", line 238, in run                                                                     result = self.command()
 File "/srv/ckan/ckanext-hdx_search/ckanext/hdx_search/command.py", line 31, in command
   self.buildIndex()
 File "/srv/ckan/ckanext-hdx_search/ckanext/hdx_search/command.py", line 43, in buildIndex
   crises = config.get('hdx.crises').split(", ")
NameError: global name 'config' is not defined                               root@ckan:/srv/ckan/ckanext-hdx_search/ckanext/hdx_search#

**Comment by mbellotti** [comment]
Oh damn, that's a stupid mistake on my part. Sorry, pushing fix right now

**Comment by danmihaila** [comment]
@mbellotti when typing or searching "nepal" the nepal earthquake is not visible. I think crises page should have a better score. pinging @yumiendo and attaching screenshots
![screen shot 2015-08-04 at 16 37 56](https://cloud.githubusercontent.com/assets/3865844/9061876/5d8fd9fa-3ac7-11e5-9a77-7d90280f63e1.png)
![screen shot 2015-08-04 at 16 37 50](https://cloud.githubusercontent.com/assets/3865844/9061877/5d924c80-3ac7-11e5-8408-1b016c5b86a1.png)

**Comment by danmihaila** [comment]
country to be change to location

**Comment by mbellotti** [comment]
Also double check that it's Organisation while we're at it ;)
