### ISSUE TITLE
Search: predictive search

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3139]
When a user is typing into the search bar/box in HDX, there is a need suggest key pages (locations, crises, organizations) to user. Base document can be found here: https://docs.google.com/document/d/1qVUS05rc-q88u4k5NqTtCzcrjOSM8a94h1YbbEwf-3Q/edit#
- [ ] include in predictive search: Crises, Organizations, Locations
- [ ] maximum 5 recommendations for the moment with a mix of entities
- [ ] Check section "Details on actual search results" from google doc for three scenarios related to search terms
- [ ] Check screenshot to see how to display the results
  ![screen shot 2015-07-20 at 11 24 44](https://cloud.githubusercontent.com/assets/3865844/8772135/f68aeb88-2ed1-11e5-8e3d-70d0e32d503c.png)

**Comment by mbellotti** [comment]
Do we want this effect on the home page as well? Or just on the pages where the search bar is in the header?
