### ISSUE TITLE
Org edit page: no space between buttons for sysadmins

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3141]
This problem is only visible to sysadmins.

![image](https://cloud.githubusercontent.com/assets/1654485/8772259/f4f3dcbe-2eca-11e5-861c-94daf232a050.png)

On ckan 2.2 the delete button is at bottom left and update is on bottom right.

**Comment by danmihaila** [comment]
related to #3142
