### ISSUE TITLE
On login, green message can't be cleared

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3145]
This has been true on prod for a while now.  I thought we had an old issue about it, but I don't see it. 

![image](https://cloud.githubusercontent.com/assets/1654485/8772874/e69b75be-2ecf-11e5-81b4-b92903be5551.png)

**Comment by danmihaila** [comment]
there are some javascript errors. moving to sprint 61, check screenshot
![screen shot 2015-07-20 at 12 13 06](https://cloud.githubusercontent.com/assets/3865844/8772926/cccc7a30-2ed8-11e5-9932-22d9db41c615.png)
