### ISSUE TITLE
Login: bad login reverts to last remembered user

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3146]
This is only an issue for users with multiple accounts.
1. login as some user (user a)
2. logout, click login
3. click "not you"
4. enter a different username/pwd (user b)  **but make an error in the password**
5. ckan loads a "login failed" modal, but reverts to user a

**Comment by danmihaila** [comment]
I think this is new behaviour. The new module is storing a cookie for the last user that logged in with success in HDX which in your scenario was user a.
We can do the change to save user b, but as he is just a trying user I don't see the reason
Another solution is to think how to handle this special case...

**Comment by cjhendrix** [comment]
In case of a login failure, you could just load the same window as you get when you click "not you".

**Comment by teodorescuserban** [comment]
So remove user specific cookie when logout.

**Comment by cjhendrix** [comment]
behavior is the same for me (in an incognito window, chrome)

**Comment by cjhendrix** [comment]
Oops!  Was testing on prod.  Sorry.  Closing.
