### ISSUE TITLE
Resource previews not working

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3147]
I've tested the following datasets:
https://test-data.hdx.rwlabs.org/dataset/idp/resource/df2e1def-1804-48da-b2f6-d6bd09fac3a4 (filestore)
https://test-data.hdx.rwlabs.org/dataset/sidih-secuestro-simple/resource/55473640-351b-49fa-b059-f592151d81fa (filestore)
https://test-data.hdx.rwlabs.org/dataset/ourairports-zmb/resource/f436ec4e-9545-441a-b3f9-03c93c64d44d (remote resource)
https://test-data.hdx.rwlabs.org/dataset/mortality_rate_adult_male/resource/942a2f65-1902-4f57-831e-6e83088b0ab1 (CPS resource)

**Comment by danmihaila** [comment]
assigned to @alexandru-m-g

**Comment by cjhendrix** [comment]
Also XLSX and XLS preview not working.

**Comment by cjhendrix** [comment]
TXT also.  Maybe something with the dataproxy container?

**Comment by danmihaila** [comment]
@cjhendrix did you test with fresh uploaded files?

**Comment by cjhendrix** [comment]
No, just existing ones, but I just tested with a fresh filstore csv.  Still no preview.

**Comment by alexandru-m-g** [comment]
Even locally I get the following errors:

```
TypeError: $.url is undefined
TypeError: recline.Backend.DataProxy is undefined
```

This was surely working last week so it's kinda weird. Will investigate more today.

**Comment by alexandru-m-g** [comment]
Fixed.
