### ISSUE TITLE
Dataset Edit: tab styling is missing

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3150]
![image](https://cloud.githubusercontent.com/assets/1654485/8805119/ca329f50-2fcf-11e5-947c-23dda9f817a9.png)

**Comment by danmihaila** [comment]
@cjhendrix can you add please a screenshot or another url ?

**Comment by cjhendrix** [comment]
Oops, that was supposed to be a screenshot I was pasting in.   Fixed.

**Comment by danmihaila** [comment]
@cjhendrix I think this is the way it looks on production right now...

**Comment by cjhendrix** [comment]
You are so right. Doesn't look nice, but isn't a 2.3 problem.  Removing that label and putting into backlog.

**Comment by danmihaila** [comment]
assigned to @yumiendo for comments
How should we show the selected tab? grey background with red underline?
![add_member copy](https://cloud.githubusercontent.com/assets/3865844/9605037/eab52328-50c3-11e5-9cdb-603f7efa3b05.png)

**Comment by yumiendo** [comment]
lets do the same as what we have currently for dataset / indicators https://data.hdx.rwlabs.org/dataset?sort=metadata_modified+desc 
selected / hover in red.

**Comment by danmihaila** [comment]
ok, agreed.
![screen shot 2015-09-01 at 17 46 42](https://cloud.githubusercontent.com/assets/3865844/9607378/79a2d032-50d1-11e5-8f89-b4ff162ca27f.png)

**Comment by cjhendrix** [comment]
zoomed to 90% in chrome the red line is misaligned, but not really a big deal.  Marking as tested.

![image](https://cloud.githubusercontent.com/assets/1654485/10019717/29ea1fb8-613f-11e5-9539-66b16e944142.png)
