### ISSUE TITLE
Resource create/edit: Change the file format help text

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3153]
Change the indicated text to be: 

`HDX will allow previews of certain formats, like CSV, TXT, XLS, and JSON.  Map previews are also possible if you set the resource format to “zipped shapefile”, “geojson”, or “kml”. Map previews may take a few minutes to appear.`

![image](https://cloud.githubusercontent.com/assets/1654485/8777165/925a57f0-2ef6-11e5-992f-e2fb71177b78.png)

**Comment by danmihaila** [comment]
I like the idea. Pinging @yumiendo for a feedback

**Comment by yumiendo** [comment]
This is perfect.

**Comment by danmihaila** [comment]
@cjhendrix please provide the final text for
"HDX will allow previews of certain formats, like CSV, TXT, XLS, and JSON. Map previews are also possible if you set the file format to “zipped shapefile”, “geojson”, or “kml”. Map previews may take a few minutes to appear."

**Comment by cjhendrix** [comment]
Updated above.  Thanks.
