### ISSUE TITLE
Dashboard: icon for private datasets is broken

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3165]
![image](https://cloud.githubusercontent.com/assets/1654485/8800133/81f56fd4-2fb0-11e5-8d52-f9af085bdbc1.png)

**Comment by danmihaila** [comment]
@aalecs I think this damaged the search listing like mali page
![screen shot 2015-08-13 at 16 55 15](https://cloud.githubusercontent.com/assets/3865844/9251480/188a47c0-41dc-11e5-8d8b-c9aa477266b3.png)

**Comment by aalecs** [comment]
Yeah ... Why did we prefix all the dataset lists with "search-list" in order to fix an icon?
I think we should revert changes
