### ISSUE TITLE
Custom org page: WFP

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3167]
The HDX Logo is not visible
![screen shot 2015-07-21 at 15 08 49](https://cloud.githubusercontent.com/assets/3865844/8800322/6f9417e6-2fba-11e5-8119-f09e7e914888.png)

**Comment by danmihaila** [comment]
assigned to @alexandru-m-g

**Comment by alexandru-m-g** [comment]
This is caused by the following line in the custom styling section ( when you edit an organization ):
`@hdxLogoUrl: "@{imagePath}/homepage-new/logo-beta.svg";`

Not sure why this was added but it points to an old url that is not valid anymore. I've removed in on staging and now the URL appears ok.
