### ISSUE TITLE
Dealing with incompatibility in notify.js after upgrading to bootstrap 3

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#3181]
We've made a 1 line change to core ckan because of #3067 and #3145, more precisely to resource.config. 
The problem was this line `return element.append(jQuery('<a class="close" href="#">&times;</a>')).alert();` from the initialize() function. The alert() seems to cause problems with bootstrap 3 and is no longer necessary. 

The quick fix was to load a modified hdx_notify.js. We need to investigate if we can solve this without modifying ckan core.

**Comment by alexandru-m-g** [comment]
We could avoid loading the "main" bundle from "base/javascript/resource.config" and create our own bundle in the 'hdx_theme' plugin and change page.html to load that one. 

This would avoid modifying the 1 line in CKAN core but not sure it's worth the change as it doesn't help us with the goal of having an easier CKAN upgrade process and ensuring new features from new CKAN versions are part of HDX.

**Comment by danmihaila** [comment]
Did you try this solution? I like it...

**Comment by alexandru-m-g** [comment]
@danmihaila  As I said, I'm not sure we're gaining anything by going this route. Let's talk.
