### ISSUE TITLE
Search icon not showing up in the search bar on the Blog (WordPress) site. 

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#3208]
When I am trying to use the search bar in the WordPress site (i.e. blog) the search icon is not showing, but something weird shows up in its place. Here's the screenshot:

![screenshot from 2015-07-22 10 37 07](https://cloud.githubusercontent.com/assets/953118/8828002/dee4d9f2-305d-11e5-894b-adb0214f18f8.png)

Here is what it is supposed to show:

![screenshot from 2015-07-22 10 37 54](https://cloud.githubusercontent.com/assets/953118/8828006/e8232186-305d-11e5-98dc-94d209ef7f66.png)

I'm in Chrome + Ubuntu 14.04

**Comment by danmihaila** [comment]
@teodorescuserban any hint?

**Comment by teodorescuserban** [comment]
@luiscape is this still an issue?

**Comment by luiscape** [comment]
@teodorescuserban issue seems to be solved. I see a magnifying icon on both Ubuntu and Mac OS.

**Comment by danmihaila** [comment]
ok, closing it.
thanks @teodorescuserban and @luiscape
