### ISSUE TITLE
Large (280mb) geojson file was previewing before but isn't previewing now

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3213]
![image](https://cloud.githubusercontent.com/assets/1654485/8829971/eee167b2-3099-11e5-828e-d425526397fc.png)

https://test-data.hdx.rwlabs.org/dataset/geotest01

I'm hoping this is just some wrinkle due to bug fixing.

**Comment by danmihaila** [comment]
@alexandru-m-g ping

**Comment by cjhendrix** [comment]
Note that I've just reuploaded the file, so it's probably in the processing queue now.

**Comment by alexandru-m-g** [comment]
I think that for some reason stag is really slow at the moment and we have a timeout of 5 minutes per task.

**Comment by cjhendrix** [comment]
This is happening now for two datasets that I used in a demo yesterday and were working fine.  These files are much smaller. 

https://test-data.hdx.rwlabs.org/dataset/lsib-lines-global-simplified (4.5MB)
https://test-data.hdx.rwlabs.org/dataset/lsib-polygons-africa-and-americas-simplified (15MB)
https://test-data.hdx.rwlabs.org/dataset/test-resource-create (corno-line.geojson is only 66KB)

**Comment by teodorescuserban** [comment]
Ater restarting stag vm, keeping demo stack off and starting only the test stack, things appear to work well.
Closing.
