### ISSUE TITLE
Resource View: remove embed button

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3228]
We haven't really tested this and don't quite know it's limitations with respect to the changes we have made to 2.3's resource views.  Let's hide/remove the embed button for now. 

![image](https://cloud.githubusercontent.com/assets/1654485/8845693/7f74a1f4-3121-11e5-9fd5-94779dea0b86.png)

**Comment by danmihaila** [comment]
In Firefox the icons on Embed and Data Explorer are broken

**Comment by danmihaila** [comment]
We will hide it, but it is good to keep it there because we will enable it soon.
