### ISSUE TITLE
Indicator Datasets: previews not working

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3229]
On test, CSV previews (both filestore and remote) are working, but not the ones generated from CPS.  

This may be related to the test setup only (I notice the download URLs all point to production), but I wanted to be sure. 

https://test-data.hdx.rwlabs.org/dataset/proportion_of_the_population_using_improved_sanitation_facilities

**Comment by teodorescuserban** [comment]
Dataproxy could not reach the prod cps (dns resolution issue).
I have corrected that and now it should work.
Please reopen it if neded.
Closing.
