### ISSUE TITLE
Resource Preview: XLSX preview not working

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3231]
I've tried a few different XLSX files (all in filestore).  None are previewing and all are giving the same error:

![image](https://cloud.githubusercontent.com/assets/1654485/8846623/0a02d168-3129-11e5-92c4-cd35cd31b666.png)

**Comment by danmihaila** [comment]
@cjhendrix  On prod we are not supporting "xlsx" viewing. only xls. If it is difficult to implement we should disable "preview" link for xlsx.

**Comment by cjhendrix** [comment]
Agreed.

**Comment by alexandru-m-g** [comment]
I disabled for now the preview for xlsx files. I think we should try to see if it's worth upgrading the dataproxy that we have on prod.

**Comment by cjhendrix** [comment]
Interestingly, we actually did have xlsx preview enabled on prod.  But it wasn't showing up for all datasets.  Maybe just recently added ones?  Anyway, it wasn't working so I'm glad we've disabled it. 

![image](https://cloud.githubusercontent.com/assets/1654485/8868973/f7c98af8-31de-11e5-873d-a8fa410e3741.png)
