### ISSUE TITLE
Resource Create: add a spinner or some other notification while upload is ongoing

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3236]
Can @yumiendo give ideas on how this should look?

**Comment by yumiendo** [comment]
Can I bother you for a screen shot of the page? (I remember it looked slightly different from the submit data page...)

**Comment by cjhendrix** [comment]
![image](https://cloud.githubusercontent.com/assets/1654485/8854736/bbc87bae-3161-11e5-8e2c-bae211b73ae4.png)

**Comment by yumiendo** [comment]
can we add a loading state while the file is being uploaded (centered on screen, screenshot attached)? The copy is a suggestion. Please feel free to change...but some indication of how long it might take is helpful.
I don't remember if we used a loading animation somewhere else on the site. perhaps we can use this http://tobiasahlin.com/spinkit/ (6th in carousel)

(In 2.3 - it wont start uploading till you click on "Add" or "Save&add another" right? it was my understanding that user cannot do anything while the file is being uploaded...thus ive used a modal state = black screen with opacity)
<img width="1407" alt="screen shot 2015-07-29 at 12 56 44 pm" src="https://cloud.githubusercontent.com/assets/8006323/8963810/0a0fa5a2-35f0-11e5-9fbf-552a42475951.png">
