### ISSUE TITLE
User List: search text not visible

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3246]
Text typed in the search box is not visible.  

![image](https://cloud.githubusercontent.com/assets/1654485/8870938/0d9faab6-31f2-11e5-9773-da59bb9f917a.png)

**Comment by danmihaila** [comment]
the commit closes the initial description of the issue, but there are 2 more items to align:
- searching icon
- all users link
  Check screenshot
  ![screen shot 2015-08-10 at 16 06 51](https://cloud.githubusercontent.com/assets/3865844/9172141/0989a6da-3f7a-11e5-8b9e-e0f94eb3fad9.png)

**Comment by danmihaila** [comment]
if it is not easy to be done today, we can move it to Sprint 63...
