### ISSUE TITLE
Geopreview: non-geographic SRS

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3253]
OGR assumes geodatasets to be in lat-long wgs84 (srid 4326).  Datasets that are not do not display correctly. 

Example resources (both zips): https://data.hdx.rwlabs.org/dataset/region-de-desarrollo-03-honduras

**Comment by cjhendrix** [comment]
Alex has committed a fix for this.

**Comment by alexandru-m-g** [comment]
Commit: https://bitbucket.org/agartner/gisrestlayer/commits/e59914ade5526361b59347e9152172dc3dc73dfd

**Comment by danmihaila** [comment]
@cj can you please test this issue on stag and marked with "testedSTAG" if it is ok?

**Comment by cjhendrix** [comment]
Working and executed on prod for the example dataset.
