### ISSUE TITLE
Geo Preview: ogr unable to transform if no SRS is specified

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3254]
Some datasets have no SRS defined.  OGR then cannot transform to the requested 4326. 

Proposed solution: catch error (which is quite specifc) and resubmit with the assign SRS command assuming 4326.  Most of the time, if a dataset doesn't have an SRS, it will be 4326. 

Example dataset: https://data.hdx.rwlabs.org/dataset/multi-hazard-average-annual-loss

**Comment by cjhendrix** [comment]
This shapefile also has no CRS defined (no prj file with the shp file and QGIS gives a warning).  However it was processed successfully and a bounding box returned.  But no geometry shows. 
https://test-data.hdx.rwlabs.org/dataset/guinea-capitale-of-region-district-and-sub-district

**Comment by alexandru-m-g** [comment]
This was done here: https://bitbucket.org/agartner/gisrestlayer/commits/2d42fc36928d50ce492a74bb346830249a1e5036
Should be part of the next redeploy

**Comment by danmihaila** [comment]
@cj can you please test this issue on stag and marked with "testedSTAG" if it is ok?
