### ISSUE TITLE
Geo Preview: zipped shapefiles with accented characters in the filenames (inside the zip) fail to process

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3255]
The python library handling the unzip balks at accented characters.  Research needed to determine how to fix. 

Example dataset: https://data.hdx.rwlabs.org/dataset/vegetacion-riberena-de-la-comunidad-isla-de-leon-en-cartagena

**Comment by alexandru-m-g** [comment]
Fix for this was committed here: https://bitbucket.org/agartner/gisrestlayer/commits/1a6ce48b7427557ec1f569364904b48ac9259b8f

**Comment by danmihaila** [comment]
@cj can you please test this issue on stag and marked with "testedSTAG" if it is ok?

**Comment by cjhendrix** [comment]
Tested on stag, but still not working.  However stag seems very slow at the moment, so maybe we are running into a timeout.

**Comment by cjhendrix** [comment]
On feature, still getting the error:

shape_info: "{"error_class": "UnicodeDecodeError", "layer_id": "pre_4de82360_c8ce_41f4_b165_fc25aa628523", "error_type": "None", "state": "failure", "message": "'ascii' codec can't decode byte 0xa2 in position 14: ordinal not in range(128)", "type": "unknown"}",

**Comment by cjhendrix** [comment]
Working on staging.  Closing.
