### ISSUE TITLE
Geo Preview: zip files with .ZIP in caps not handled

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3256]
Fix has been committed.  

https://data.hdx.rwlabs.org/dataset/somalia-health-facilities/resource_edit/447228c4-606f-4fc8-94af-19c3b3500a5a

**Comment by danmihaila** [comment]
@cj can you please test this issue on stag and marked with "testedSTAG" if it is ok?

**Comment by cjhendrix** [comment]
Not fixed on feature.  

![image](https://cloud.githubusercontent.com/assets/1654485/9081582/e82f11ca-3b5d-11e5-903c-70236a72ad96.png)

**Comment by cjhendrix** [comment]
working now on stag.  Closing.
