### ISSUE TITLE
Geo Preview: getting reources from geonode fails 

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3262]
"message": "CKAN resource filename could not be deduced"

This has been true with both USG and WFP geonodes.  

Example:
https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=global-logistics

**Comment by jj0hns0n** [comment]
@cjhendrix I think @tomkralidis should be able to help with this one.

**Comment by tomkralidis** [comment]
What are the steps to reproduce the issue?  I am not able to access the example link.

**Comment by cjhendrix** [comment]
Hi @tomkralidis Thanks for jumping in.  I believe this one is going to be on our side.  @alexandru-m-g may correct me, but I think the issue here is that our geo preview generation code is expecting a file name in the url of a remote resource, which is not how geonode is providing the download.

**Comment by alexandru-m-g** [comment]
Indeed, this was a small issue on our side with some parameters not being urlencoded.

**Comment by alexandru-m-g** [comment]
@teodorescuserban Once this is deployed to production we will need to do a small change in prod.ini.
`hdx.gis.layer_import_url = http://localhost:1234/api/add-layer/dataset/{dataset_id}/resource/{resource_id}?resource_download_url={resource_download_url}&url_type={url_type}`

Please note the _url_type_ at the end.

**Comment by danmihaila** [comment]
@teodorescuserban can you please confirm the change is made in prod.ini ?

**Comment by teodorescuserban** [comment]
There are no changes yet.
I was expecting to be announced when i shoud change.

**Comment by danmihaila** [comment]
@cjhendrix this is deployed on staging, please test it

**Comment by teodorescuserban** [comment]
I changed the prod.ini on staging. 
After testing, when deploying to prod, pretty please remind me of this. 
Do no close yet.

**Comment by cjhendrix** [comment]
Just tested.  Beautiful.  Working on 2different geonodes and 3 different formats:
http://test-data.hdx.rwlabs.org/dataset/global-logistics
http://test-data.hdx.rwlabs.org/dataset/lsib-lines-africa-and-americas-detailed

**Comment by danmihaila** [comment]
@cjhendrix can we close it?

**Comment by teodorescuserban** [comment]
Don't, please.
Lets close this after we deploy to prod.

În Lun, 10 aug. 2015 la 14:23, danmihaila notifications@github.com a
scris:

**Comment by danmihaila** [comment]
@cjhendrix confirmed this is ok. closing it
