### ISSUE TITLE
Hide interactive data section on custom org pages when there is no data viz configured for the custom org page

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#3268]
![image](https://cloud.githubusercontent.com/assets/6885303/8923007/d65bb184-34b8-11e5-88f3-00eb0956cb5f.png)

**Comment by cjhendrix** [comment]
The visualization is hidden, but the datasets not showing. Reopening, but could also be a new issue. 

![image](https://cloud.githubusercontent.com/assets/1654485/9765286/cbf04b6a-5713-11e5-941c-4abda5002235.png)

**Comment by danmihaila** [comment]
the code is good, but I found that in custom org at less part there is
#content > div.container.mainContent > div > div > div > div > div > div > div:nth-child(4) { display:NONE !important;}
which makes that part to be hidden. Pinging @luiscape and @takavarasha to be aware, that now the section can be hidden if there is no visualization selected and for organizations that have the custom selector, we should remove it.

**Comment by danmihaila** [comment]
fixed on staging, will do it on production after redeploy or maybe it is better for data team to check and remove.
