### ISSUE TITLE
Dataset View: "make it public" modal confirmation text is wrong

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3274]
The same text appears regardless of whether the user is making the dataset public or private. 

![image](https://cloud.githubusercontent.com/assets/1654485/8930612/a0a0965a-352f-11e5-8078-f9b15cf02b92.png)

**Comment by danmihaila** [comment]
@mbellotti could be a translation issue?

**Comment by mbellotti** [comment]
I've tried a bunch of different things here, but (probably because this is javascript here) it doesn't look like the modal text can be changed on the fly. So I just updated the copy to work for both.

**Comment by danmihaila** [comment]
@mbellotti I have to reopen this one. I tested on stag. After I click confirm on modal, the private/public is never changing/saving in db
@cjhendrix pls confirm the text from modal is ok now

**Comment by danmihaila** [comment]
I was wrong, I think it was something wrong with staging. @mbellotti the action is ok.
still need a feedback from @cjhendrix about message.
closing this one

**Comment by cjhendrix** [comment]
Sorry, Dan, it's not my call on the text.  It looks reasonable to me, but someone else would need to approve if you don't feel comfortable approving it.  Tagging @amcguire62 

for convenience, the text Marianne applied is: 
`Are you sure? This will affect whether this data is visible to everyone`

**Comment by danmihaila** [comment]
Text is ok, but on large screens the popup is very very large. @mbellotti could we do it to fit the text?
check screenshot
![screen shot 2015-08-04 at 15 16 20](https://cloud.githubusercontent.com/assets/3865844/9060372/ca2a0484-3abb-11e5-9e8d-1d771b4ffd6d.png)

**Comment by mbellotti** [comment]
The modal is sized in relation to the window, not the text. I've made that ratio a bit smaller, so hopefully that works well.

**Comment by danmihaila** [comment]
I tested on stag vs prod and in my case there are 672px, no difference. I am using FF

**Comment by mbellotti** [comment]
![screen shot 2015-08-10 at 10 08 23 pm](https://cloud.githubusercontent.com/assets/489152/9188647/6835d55a-3fac-11e5-9e22-25f3abc0459b.png)
This is the size I get on both Chrome and FF :/

**Comment by danmihaila** [comment]
I think it is about the display. can we make a fix size? On large displays it looks bad
![screen shot 2015-08-11 at 10 49 59](https://cloud.githubusercontent.com/assets/3865844/9192798/d867051e-4016-11e5-93fd-86edf42583ed.png)

**Comment by mbellotti** [comment]
Sure. How large would you like it to be?

**Comment by teodorescuserban** [comment]
Why not centering the message too?

În Mar, 11 aug. 2015 la 17:14, mbellotti notifications@github.com a scris:

**Comment by danmihaila** [comment]
@mbellotti i think the size from your screenshot looks good, i don't know how many px. Maybe u can set something like max width.

**Comment by danmihaila** [comment]
If not working well, i think we coudl ask @yumiendo for an opinion related to header and popin width

**Comment by aalecs** [comment]
Just an idea ... can't we reuse the information popups from the onboarding? We already have components for them, eg.:

<img width="868" alt="screen shot 2015-08-12 at 11 05 33" src="https://cloud.githubusercontent.com/assets/5638491/9219260/2cc653aa-40e2-11e5-8784-1177f0781ee4.png">

**Comment by yumiendo** [comment]
will provide mockups. we can reuse the onboarding conf windows as per arti's suggestion.

**Comment by danmihaila** [comment]
until we have the final mockups, I will move this issue to sprint 63 as it is not enough time to fix. 
ping @mbellotti and @aalecs to follow this

**Comment by mbellotti** [comment]
We didn't have feedback in time so we're using the styles from onboarding
