### ISSUE TITLE
Request Membership Modal not visible

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3276]
![image](https://cloud.githubusercontent.com/assets/1654485/8931387/3626cc66-3536-11e5-9302-54777facde62.png)

**Comment by danmihaila** [comment]
@alexandru-m-g is it complicated to be done? I know you worked on add member modal. we will probably need a hotfix

**Comment by alexandru-m-g** [comment]
No, it's a simple bug.
