### ISSUE TITLE
Reordering search results with multiword searches gets a bad URL 

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3285]
1. Open this search: https://data.hdx.rwlabs.org/search?q=kenya+open+data+initiative&ext_indicator=0
2. Reorder to Last Modified
3. URL becomes https://data.hdx.rwlabs.org/search?q=kenya%2Bopen%2Bdata%2Binitiative&ext_indicator=0&sort=metadata_modified+desc and matches many more results.

**Comment by danmihaila** [comment]
this is still an issue on staging server. reopening
ping @mbellotti

**Comment by danmihaila** [comment]
this is back! reopening and moving to Sprint 62

**Comment by mbellotti** [comment]
It's working on staging right now :/

**Comment by danmihaila** [comment]
I was checking /dataset which is basically the issue https://github.com/OCHA-DAP/hdx-ckan/issues/3285 from next sprint. I removed my previous comment.
I still see a bug on staging related to /search . I made the following steps:
1. http://test-data.hdx.rwlabs.org/search?q=  (2248 results)
2. filter by "zipped shapefile": http://test-data.hdx.rwlabs.org/search?q=&res_format=zipped+shapefile (250 results)
3. order by "last modified": http://test-data.hdx.rwlabs.org/search?q=&res_format=zipped%2Bshapefile&sort=metadata_modified+desc -> ERROR 0 results

**Comment by danmihaila** [comment]
my last comment will be fixed by #3014
closing this one
