### ISSUE TITLE
Series of page alerts when requesting a new org

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3287]
Login as a non sysadmin and create an org request.  On submitting the request: 

![image](https://cloud.githubusercontent.com/assets/1654485/8975363/aaa04642-367d-11e5-9420-83318c633966.png)
Click ok
![image](https://cloud.githubusercontent.com/assets/1654485/8975367/b8aba16e-367d-11e5-831a-2d83bb2ca1bb.png)
Click ok
![image](https://cloud.githubusercontent.com/assets/1654485/8975374/ca58345e-367d-11e5-9c2d-a90338209026.png)

**Comment by alexandru-m-g** [comment]
This seems to be particular to Chrome

**Comment by danmihaila** [comment]
The submit button is outside the form and it submits all the forms from the page...It is a bug...
