### ISSUE TITLE
Remote request to datastore failing.  Header problem?

### ISSUE THREAD

**Issue by SimonbJohnson** [OCHA-DAP/hdx-ckan#3302]
http://simonbjohnson.github.io/Ebola-Guinea-3W/ is failing to call data from HDX datastore.  Cross origin request header not there?

<img width="1261" alt="screen shot 2015-07-31 at 18 14 48" src="https://cloud.githubusercontent.com/assets/2110742/9012858/13c28be8-37b0-11e5-98e6-aa2999630558.png">

**Comment by teodorescuserban** [comment]
Fixed.
