### ISSUE TITLE
disk gets full after some time on the rqworker machine

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#3303]
After a batch about 200 geo-enabled datasets were updated I see this error in some of them. 

```
"shape_info": "{\"error_class\": \"FolderCreationException\", \"layer_id\": \"pre_2e893679_f802_4c5d_a245_0045d1105cfd\", \"error_type\": \"None\", \"state\": \"failure\", \"message\": \"A problem occured while creating folder /tmp/pre_2e893679_f802_4c5d_a245_0045d1105cfd: [Errno 28] No space left on device: '/tmp/pre_2e893679_f802_4c5d_a245_0045d1105cfd'\", \"type\": \"folder-creation-problem\"}",
```

The problem is that all these files get downloaded to /tmp but are not deleted and we run out of disk space. Either @teodorescuserban should create a script to regularly delete them or I can change the gislayer to delete them after they are being processed. 

Pinging @danmihaila and @cjhendrix so that they are aware of the problem

**Comment by luiscape** [comment]
@alexandru-m-g Just to point out that this operation may not happen all that often -- i.e. once a month maybe.

**Comment by teodorescuserban** [comment]
Once a month gis disabled is sad. We will take more care of this guy :)

**Comment by teodorescuserban** [comment]
@alexandru-m-g: let's do both.
You change it so in normal run mode the file will be removed after proccessing.
I make a cron that would take care of the leftovers (from errors, crashes etc)

While we are at it, would you also be able to make the folder used to store the files as a configure option?
I might want to map a host volume to that at some point.

**Comment by teodorescuserban** [comment]
I created the script.
The script is only hosted in one container on staging to test it out properly.

Current settings are:
scripts is running every 10 minutes.
removes all files / folders starting with 'pre_' that are older than 48 hours.

Suggestions?
We might need to decrease massively the max age (currently at 48 hours).

**Comment by teodorescuserban** [comment]
I will change the max age to 2 hours.

**Comment by teodorescuserban** [comment]
Just experienced another disk full on prod.
I have removed the current gisworker and create another one that has the script in it + the /tmp folder is mapped to a host volume (gistmp on gluster fs).

**Comment by alexandru-m-g** [comment]
Just a note, that there is already a fix for this on the gislayer side (basically removing all temp files when they are no longer needed). It's just not in production yet, still needs to be tested.

**Comment by teodorescuserban** [comment]
Gislayer? Who cares about gislayer? :)

Mar, 11 aug. 2015, 06:52, Alexandru Gartner notifications@github.com a
scris:

**Comment by alexandru-m-g** [comment]
@teodorescuserban Maybe I should've said gisworker. Gislayer and gisworker share the same codebase. :)

**Comment by teodorescuserban** [comment]
Yeah but gisworker does not run gislayer underneath, right?
So tmp cleaning might not be possible from gisworker with gislayer code?

Mar, 11 aug. 2015, 08:54, Alexandru Gartner notifications@github.com a
scris:

**Comment by alexandru-m-g** [comment]
gisworker downloads the file ( & writes it to disk ) so it can definitely also delete the file after the processing is done.

**Comment by teodorescuserban** [comment]
Let's convene to my garden tower after your snow-and-moose-and-maple-syrup
trip. :)

Mie, 12 aug. 2015, 09:03, Alexandru Gartner notifications@github.com a
scris:

**Comment by teodorescuserban** [comment]
To leave a clearer end of the discussion here, the script that cleans the folder is made and cronned every 10 minutes.
It cleans the files older than 1 hour that starts with `pre_` in the folder specified by the `$HDX_TMP_DIR` env var or fallbacks to cleanup the `/tmp` folder.

Changes have been propagated to the latest gisworker docker image.

**Comment by luiscape** [comment]
@teodorescuserban and @alexandru-m-g just to give some more information here. I believe some of the reasons that the disk is getting full before the scheduled cron job is that there is a script I have been running that registers about 300 datasets under UNOSAT at once. The running time of that script is about 3 ~ 5 minutes.

This scenario is somewhat unlikely to happen often in production -- although quite common in staging as I use it to test new features of the script. With that said, I really like @alexandru-m-g's idea of deleting files as soon as they are processed. :-)

**Comment by teodorescuserban** [comment]
@alexandru-m-g fixed his code - now the gisworker will remove the temp files related to a finished job.
I enabled the cron to clean up any other mess.
Also, we are now using host volume for the gisworker temp folder.
Closing.

**Comment by luiscape** [comment]
:+1:
