### ISSUE TITLE
CKAN changes file names

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3318]
See details here: 

https://github.com/OCHA-DAP/cod-migration/issues/40

This is problematic because users may have a file naming standard and having their published files renamed may not be welcome.  In the particular case of COD migration, OCHA has had a file naming standard for several years (although it is not universally used), and having CKAN alter that in a way that makes the file name unreadable should be fixed. 

I suggest this could be a PR back to ckan core.

**Comment by teodorescuserban** [comment]
Note that the file naming convention by url standards seems ok. 
People are already used to haev all kinds of limitations when choosing a username for an account, a email address, and so on.

**Comment by teodorescuserban** [comment]
See here:
https://github.com/ckan/ckan/issues/1820

**Comment by cjhendrix** [comment]
Yes but having an OCHA system break an OCHA standard is probably not good.  We just need to maintain "-" and "_" which are usually allowed and worked fine in ckan 2.1.

Of course if this would create some significant technical problem, then we shouldn't do it.  But if it's just a matter of removing "-" and "_" from ckan's file renaming and tolerating some ugly URLs, I think it's ok. @amcguire62 ?

**Comment by danmihaila** [comment]
@mbellotti first step is to find out why ckan is removing the special chars and find the reason.

**Comment by mbellotti** [comment]
So, yes, this is a problem with ckan core, although nothing to do with the issue Serban highlighted. Munge_filename does not allow underscores. There doesn't seem to be any real reason for this that I can think of ... it looks like someone just forgot to include underscores in the regex of acceptable characters.  I'm waiting on feedback from the core team just to be sure.

If they okay it I will submit a PR back to ckan core with a fix and test. Until then, if this a big concern I can modify our core with a comment.

**Comment by teodorescuserban** [comment]
The whole thing might start from what dns valid characters are (letters,
numbers, dash and dot).
Slugify usually strips out the dot too, as well as lower() all caps.

Lun, 24 aug. 2015, 23:15, mbellotti notifications@github.com a scris:

**Comment by danmihaila** [comment]
@teodorescuserban @cjhendrix can one of you confirm this is ok now on staging?

**Comment by cjhendrix** [comment]
Sorry, I know I'm quite late on this.  But yes working on stag and prod.
