### ISSUE TITLE
Resource Create:  the check mark is trying to escape again

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3333]
On feature  (v 0.10.3):

![image](https://cloud.githubusercontent.com/assets/1654485/9081527/4ab38b4c-3b5d-11e5-9382-77ddb1c24054.png)

**Comment by danmihaila** [comment]
I saw this one on staging and fixed yesterday. I will ask Serban to deploy feature with the latest version and it should be good.

**Comment by danmihaila** [comment]
i double check it and it looks it was a different problem:
if you upload a shapefile with a looong name without whitespaces it will break, but if you upload a short name of the file it will be ok.
I hope it fixed it well
