### ISSUE TITLE
Search: new tags exist, but not available in filter

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3340]
As part of COD migration, we are creating some (temporary) unique tags for each migrated dataset.  

These tags are available via URL:  http://feature-data.hdx.rwlabs.org/dataset?tags=nodeid4707
![image](https://cloud.githubusercontent.com/assets/1654485/9086485/0398ad32-3b85-11e5-98e5-6f0c8d5f6005.png)
But they are not available in the filter list:
![image](https://cloud.githubusercontent.com/assets/1654485/9086503/153bfb02-3b85-11e5-90d1-1b45387ceab5.png)

**Comment by danmihaila** [comment]
it looks that we somehow limit the number of tags in that dropdown. good catch
http://feature-data.hdx.rwlabs.org/api/3/action/tag_list - the full list of tags.
