### ISSUE TITLE
Make sure dataset tab shows 25

### ISSUE THREAD

**Issue by mbellotti** [OCHA-DAP/hdx-ckan#3342]
There are certain conditions under which the dataset tab shows five, instead of twenty-five in search. Hunt those down and kill them.

**Comment by danmihaila** [comment]
@mbellotti : any commit or reference? I don't know how to test or reproduce on prod/staging

**Comment by mbellotti** [comment]
https://github.com/OCHA-DAP/hdx-ckan/commit/a868f36829cb8ae71108311573260d617ae8e38e
