### ISSUE TITLE
CORS disallowed for DataStore API

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#3343]
At some point recently CORS have been disallowed on the DataStore API (they are still allowed on the regular metadata API). This is causing issues on visualizations hosted on third-party domains (i.e. GitHub) that pull data directly from the DataStore API.

``` console
XMLHttpRequest cannot load 
https://data.hdx.rwlabs.org/api/action/datastore_search?resource_id=b8b5670f-ce85-
4c50-bb30-aa6003e29f2e;limit=2000. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://luiscape.github.io' is therefore not allowed access.
```

And here is a live example from a previously-working visualization hosted on GitHub pages: http://luiscape.github.io/hdx-datstore-example/

**Comment by teodorescuserban** [comment]
Fixed.

**Comment by luiscape** [comment]
Thank you, Sir! (**THAT WAS FAST!**)

**Comment by teodorescuserban** [comment]
:)

În Joi, 6 aug. 2015 la 00:35, Luis Capelo notifications@github.com a
scris:
