### ISSUE TITLE
API allows creation of datasets with no group

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3366]
Discovered this while testing the COD migration.

**Comment by danmihaila** [comment]
can u specify what is the api call you are using?

**Comment by cjhendrix** [comment]
whichever one serban is using in gospawn    :)

**Comment by danmihaila** [comment]
@cjhendrix can you run the script and test this one. code looks good now

**Comment by cjhendrix** [comment]
Looks good.  Seems to be (correctly) failing if any of the required parameters are missing from the json passed to the API.
