### ISSUE TITLE
Share button rendering offscreen

### ISSUE THREAD

**Issue by davidmegginson** [OCHA-DAP/hdx-ckan#3369]
When I click on the "Share" button for a dataset in Chrome, it renders a popup dialogue mostly off the left side of the screen.  Screenshot: http://www.clipular.com/c/6521137465917440.png?k=hfed9aJHiDqp1GAYIXRPDTJbNm8

Assigned to Dan for triage.

**Comment by danmihaila** [comment]
related to #3273
