### ISSUE TITLE
Dataset List: autocomplete suggestions don't go away with click elsewhere on the page

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3371]
Found on chrome. 
To replicate: 
1. open /dataset and type something in the search bar
2. change your mind and decide to open the filter drawer
3. autocomplete suggestions remain visible

I'm not sure we necessarily want to fix this.  I found it a bit jarring, but I can also why maybe we want the suggestions to remain visible as long as there is text.  Pinging @yumiendo for decision.

**Comment by yumiendo** [comment]
i'd love to address this - not sure how hard it is. 
regardless of whether someone has filter drawer open - can we make it go away if you click outside the predictive dropdown?

(I also pressed "esc" but didnt do anything)

**Comment by danmihaila** [comment]
ok, moving it to sprint 63 and assigned to @mbellotti

**Comment by aalecs** [comment]
On staging if you click any option in the predictive dropdown it will just close the list and won't do anything. Initial functionality is lost, reopening issue...

**Comment by aalecs** [comment]
Please fix on a separate branch from dev so we can make a different pull request, thanks!

**Comment by mbellotti** [comment]
A separate branch from dev or a separate branch from marianne_sprint63? I'm
literally just about to push the fix O.o

On Wed, Aug 26, 2015 at 9:13 AM, Alexandru Artimon <notifications@github.com

**Comment by aalecs** [comment]
I meant a new branch out of dev just for this fix. Thanks

**Comment by aalecs** [comment]
Fixed, thanks!
