### ISSUE TITLE
COD Migration Geo Preview thingy

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3375]
Making a placeholder for this for discussion. 

We have closed the issue about triggering geopreview for datasets made from the API, but gospawn won't know when to apply the magic words (it won't know if a dataset is a zipped shapefile, zipped geodatabase, or zipped cat vidoes).   Which means that for most of the migrated CODs we would have to trigger it manually. 

Options (open to more ideas):
1. Add something to gospawn to inspect zip files for .shp and set file format to "zipped shapefile" if found.  KML (uncommon in CODs) and geojson (rare to nonexistant) should be triggered automatically by their file format (though this needs to be tested)

**Comment by teodorescuserban** [comment]
You idea is great!
Lets see how easily done it is.

**Comment by teodorescuserban** [comment]
Fixed on gospawn.
