### ISSUE TITLE
Locations list page: /group

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3377]
The locations list page (https://data.hdx.rwlabs.org/group) will be replaced by this new page. 
- Create a new clean controller to handle the list of locations (probably we could reuse browse_controller)

Coordinate with @aalecs , issue no #3378

Mockup:
![locations_spec](https://cloud.githubusercontent.com/assets/3865844/9168590/eb6a24fe-3f60-11e5-9b32-f3459b83563e.png)

**Comment by mbellotti** [comment]
We can close this one I think?
