### ISSUE TITLE
Search: not displaying the same number of options

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3382]
If I search "world", the dropdown displays 5 results but when hitting enter I am getting only 4 recommendations
![screen shot 2015-08-10 at 16 22 46](https://cloud.githubusercontent.com/assets/3865844/9172437/3ee11ffa-3f7c-11e5-874f-a0613396ab0d.png)
![screen shot 2015-08-10 at 16 22 40](https://cloud.githubusercontent.com/assets/3865844/9172436/3edeed48-3f7c-11e5-9fde-fe5c0091134b.png)

**Comment by mbellotti** [comment]
Yes this is deliberate. We discussed how many results to return and the
documentation I was given said five for predictive but only had about three
for recommendations. Why would you want the same number anyway? Visually
you can put more on predictive without ruining the design than you can with
recommendations

**Comment by danmihaila** [comment]
I don't understand why we would remove 1 result. As I see in screenshot the "recommendations" are already on 2 rows.
Pinging @yumiendo for more comments re this issue

**Comment by mbellotti** [comment]
Well I can make them even, I just don't know why you would necessarily want
that. Best thing in my opinion is to remove one from recommendations.

**Comment by yumiendo** [comment]
Hi guys, sorry it looks like my comp did not cover this issue. (i think my comp showed 3 "You might also like:")

if 5 results shows in the predictive dropdown (and if user just hit enter) - "You might also like:..." should also list 5.  it may run in 2 lines but it's ok.

**Comment by danmihaila** [comment]
ok, so, basically will be the same number, maximum 5. We will do it next sprint, in 63.
