### ISSUE TITLE
FAQ / Geodata Minor Typo 

### ISSUE THREAD

**Issue by pjdufour** [OCHA-DAP/hdx-ckan#3385]
Geodata section in FAQ is a great idea!  There's a minor typo in the FAQ for "Is HDX integrated with any GeoNodes?".  The "N" in GeoNode is generally capitalized.  A link to the main GeoNode website, http://geonode.org/, might also be useful.

![image](https://cloud.githubusercontent.com/assets/1438253/9174690/7922c718-3f4f-11e5-80f7-c902c0b31faf.png)

**Comment by danmihaila** [comment]
pinging @cjhendrix to provide the final text.

**Comment by cjhendrix** [comment]
Please replace the FAQ section with the following:

```
Is HDX integrated with any GeoNodes?
HDX has some datasets that are links to data stored on GeoNodes, such as the Ebola GeoNode, the Sala Humanitaria GeoNode, and the U.S. Department of State GeoNode. These links are currently maintained manually. Updates to downloadable resources on a GeoNode will be reflected in the download from HDX. Updates to metadata or descriptions are only captured if the dataset owner updates them manually on HDX.
```
