### ISSUE TITLE
Download resource, private dataset

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3390]
This is the only way to reproduce the issue:
1. create a private dataset
2. add a resource
3. same logged in user, try to download resource -> ERR redirects to login page, can not login, etc.
4. make dataset public
5. same logged in user, try to download resource -> success

For an existing public dataset:
1. try to download resource (as hdx user) -> success
2. make dataset private
3. try to download resource (as hdx user) -> success

**Comment by cjhendrix** [comment]
Serban fixed this by having me install the user agent switcher in Chrome.   But that's not a good solution for all users of test/feature /demo,  so he was going to look into it.

**Comment by danmihaila** [comment]
I will check this bug later this week

**Comment by danmihaila** [comment]
wrong assignment , i reassigned to me

**Comment by teodorescuserban** [comment]
No need, Dan. Assign it to me. I will see it done.

În Mar, 11 aug. 2015 la 15:03, danmihaila notifications@github.com a
scris:

**Comment by danmihaila** [comment]
@teodorescuserban , I was wrong I can not reproduce using the steps I was talking about. Assigned to you (probably not related to ckan)

**Comment by danmihaila** [comment]
@teodorescuserban you can test on 
https://test-data.hdx.rwlabs.org/dataset/json-repository
not working resource:
https://test-data.hdx.rwlabs.org/dataset/e66dbc70-17fe-4230-b9d6-855d192fc05c/resource/12e3bdb5-9ea9-460f-811d-03d134936823/download/Screen-Shot-2015-08-12-at-13.57.50.png

**Comment by teodorescuserban** [comment]
This has been a varnish misconfig fixed on prod by Steven.
We need to talk about this later.
I also fixed on test stack.

Mie, 12 aug. 2015, 15:14, danmihaila notifications@github.com a scris:

**Comment by teodorescuserban** [comment]
Closing.
