### ISSUE TITLE
Location admin page: delete

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3395]
1. When click on delete button it should show a confirmation screen for user...
2. Same for organizations
   ![screen shot 2015-08-12 at 13 58 23](https://cloud.githubusercontent.com/assets/3865844/9222409/4a0f981e-40fa-11e5-9cca-263de607b0f4.png)

**Comment by danmihaila** [comment]
I think we should postpone this until we have a confirmation box from @yumiendo . We might have it next week probably based on onboarding widgets

**Comment by yumiendo** [comment]
please refer to the javascript warning comps. 
![screen2 screen4](https://cloud.githubusercontent.com/assets/8006323/9584685/840b861e-4fe0-11e5-89fc-a784897a4644.png)

**Comment by danmihaila** [comment]
@alexandru-m-g I will move this issue for next sprint as it will be part of other changes regarding this messages and alerts

**Comment by danmihaila** [comment]
closing this one, duplicated by #3472
