### ISSUE TITLE
Group page: Sorting not working when select order by dropdown

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3402]
This is the third place where we found the error. Can we do a fix to apply every place we are using this dropdown?
![screen shot 2015-08-13 at 12 11 34](https://cloud.githubusercontent.com/assets/3865844/9246502/9ca6af94-41b4-11e5-9a29-3616018c6787.png)

**Comment by danmihaila** [comment]
Places to test&check:
- /dataset
- /search
- /organization/innago
- /organization/wfp  - custom org
- /group/mli - custom loc
- /group/afg 
- /ebola
- /dashboard - activity stream
- /dashboard/datasets
- /dashboard/organizations
- /dashboard/groups

**Comment by alexandru-m-g** [comment]
Tested:
- /dataset?sort=title_case_insensitive+asc -- works
- /search?q=health&sort=title_case_insensitive+desc -- works
- /organization/wfp?sort=title_case_insensitive+asc -- works 
- /organization/innago?sort=title_string+desc -- works 
- /group/mli - no sorting option for custom loc
- /group/afg?sort=title_case_insensitive+desc -- works
- /ebola - no sorting option
- /dashboard -> fixed filter in activity stream (check commit - problem with bootstrap version )
- /dashboard/datasets --works
- /dashboard/organizations --no sorting
- /dashboard/groups - no sorting
