### ISSUE TITLE
Add Member Modal:  part of frame missing from dropdown

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3412]
It's the same on the Role dropdown.    Same in both FF and Chrome.

![image](https://cloud.githubusercontent.com/assets/1654485/9270041/cd921c46-426e-11e5-915e-96dfd5caa78f.png)

**Comment by danmihaila** [comment]
this will be part of the refactoring related to all modals. I hope we will include in sprint 64 mockups from @yumiendo 
Pinging @aalecs to be aware

**Comment by yumiendo** [comment]
@danmihaila 
Can we address this with https://github.com/OCHA-DAP/hdx-ckan/issues/3472

**Comment by danmihaila** [comment]
Yes, we will do it.

**Comment by danmihaila** [comment]
this will be done via #3472 Added to @aalecs to have an eye on it
