### ISSUE TITLE
Create dataset update frequency field

### ISSUE THREAD

**Issue by aalecs** [OCHA-DAP/hdx-ckan#3419]
In order for the data team to be able to create the dashboards where they monitor datasets we need a field in which they can update via API the number of days in which a dataset is being updated.

More info here: https://docs.google.com/document/d/1g8hAwxZoqageggtJAdkTKwQIGHUDSajNfj85JkkTpEU/edit#

**Comment by alexandru-m-g** [comment]
A field with the name 'data_update_frequency'  was added.

A _POST_ request to the following API `/api/action/hdx_package_update_metadata` 
with `id=[dataset_id]` and `data_update_frequency=7` would update just this field of a specified dataset
