### ISSUE TITLE
Org page controller - featured items

### ISSUE THREAD

**Issue by aalecs** [OCHA-DAP/hdx-ckan#3428]
Basically for an MVP we need a way for the data team to be able to select the featured orgs and to modify the controller to pull that data into the page.

In the org edit page we need a checkbox to mark an org as featured and possibly other fields:
- either: upload field where we can put a preview screenshot of the org page
- either: text field or other way of specifying from where inside the org page we can get the container for the preview image

**Comment by danmihaila** [comment]
I will not go with a checkbox as we can face this situation:
- long list of organizations (200)
- data team will have 3 checkboxes already checked but for organizations found on different pages.
  I suggest we display the full list of organization and use 2 types of icons (featured/not featured). A sysadmin could click and enable an organization as featured but only if they is an empty slot.
  This is an idea, but I am open to discuss about the solution.
  pinging @yumiendo also as we need to decide asap about this

**Comment by mbellotti** [comment]
Why don't we go a little simpler and draw the pool of featured orgs from those marked as custom? Presumably these are the orgs we'd most like to feature anyway.

**Comment by yumiendo** [comment]
dan - would the 2 types of icons visible to all users or just to sys admin? does data team need to provide the thumbnail or is the dev team in charge? 

Im throwing another idea here -
assuming the data team has 1.make 3 selection 2. provide thumbnail and update these periodically. 

sketches attached below -
1. add "edit" button on the organisation list page (only visible to sys admin....thought about adding this in other locations but this may be most straight forward...at least for now)  
![1](https://cloud.githubusercontent.com/assets/8006323/9672196/677a99e4-5266-11e5-9a15-e3f6b1ca3444.png)
2. clicking on edit brings up a modal to make 3 selections using tabs/dropdowns.
Upload image function needs to be more detailed...but im not fully understanding the process of creating screenshot yet (its done programmatically right?) once I know better I can design the UI. 
![2](https://cloud.githubusercontent.com/assets/8006323/9672198/6aa5bf04-5266-11e5-949d-172623db3802.png)
3. "save" (or publish) update the featured orgs. 
(if it needs to be published at later date...maybe we can add some kind of calendar/timer here too)

let me know what you think -

**Comment by danmihaila** [comment]
hey @yumiendo, thank you for these mockups. I forgot to update this issue, but we decided at our last call with data team to manage the three featured organizations via a dataset from datastore.
We might still need these mockups in case we want to add this feature to allow data team to have an UI interface to manage them.
