### ISSUE TITLE
Org page - featured section ui

### ISSUE THREAD

**Issue by aalecs** [OCHA-DAP/hdx-ckan#3429]
Adapt UI of org page to include the featured section. Specs:

![org_withimage](https://cloud.githubusercontent.com/assets/5638491/9408176/d5dbb970-4818-11e5-920f-43652c02feba.png)

**Comment by yumiendo** [comment]
![org_02_spec](https://cloud.githubusercontent.com/assets/8006323/9581225/18e3879c-4fcc-11e5-975e-558a2a8196f8.png)

please use this one instead.
