### ISSUE TITLE
Backend solution to save part of a rendered page as an image

### ISSUE THREAD

**Issue by aalecs** [OCHA-DAP/hdx-ckan#3430]
Experiment with Phantom.JS and see if we can create a reliable solution that can save part of a rendered page, including visualisations made in JS, as an image.
This can be used to complete the "Save as image" feature of the embeddable visualisations and for the featured organisations section of the orgs page (#3428)

**Comment by aalecs** [comment]
To install CaptureJS: npm install -g capturejs
PhantomJS 1.9 can be installed using apt-get.

But 1.9 has an issue with rendering maps so we use a different repository that provides 2.0:
sudo add-apt-repository ppa:tanguy-patte/phantomjs
sudo apt-get update
sudo apt-get install phantomjs

**Comment by teodorescuserban** [comment]
Installed on staging.

**Comment by teodorescuserban** [comment]
Made its way to prod.
I had a strange issue today when deploying prod.
I got the following error on the new container:

```
root@ckan:/# capturejs --uri https://data.hdx.rwlabs.org/organization/wfp --output  gg.jpg
{ [Error: Cannot find module 'weak'] code: 'MODULE_NOT_FOUND' }
```

I solved it by reinstalling capturejs:

```
root@ckan:/# npm uninstall -g capturejs           
unbuild capturejs@0.2.1
root@ckan:/# npm install -g capturejs 
```
