### ISSUE TITLE
Layer metadata not updated by spatial server

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#3431]
Currently we take the list of fields ( properties ) that the geometries have via an API call to spatial.
But when a geo-file is updated and it's fields are changed spatial doesn't refresh this information (until it is restarted) so a call to the API returns the old values. This  can lead to errors.

**Comment by danmihaila** [comment]
@teodorescuserban pls chat with @alexandru-m-g and redeploy staging to test this issue. thanks

**Comment by alexandru-m-g** [comment]
@teodorescuserban a new configuration is need on gislayer for the db password: DB_PASS

Also the requirements changed so a `pip install -r requirements.txt` is needed

**Comment by teodorescuserban** [comment]
Still need to gather up with @alexandru-m-g to configure this.

**Comment by teodorescuserban** [comment]
Good brownbag session with @alexandru-m-g :)
In the brownbag was a bottle but still good session :)
