### ISSUE TITLE
Org admins can undo the settings of a custom organisations

### ISSUE THREAD

**Issue by aalecs** [OCHA-DAP/hdx-ckan#3432]
An org admin can undo the settings for a custom org. The following steps will reproduce this issue
1. Login as a sys admin and configure a custom org page for a chosen organisation
2. Add an ordinary user account (that you have the password for) as an admin of the chosen organisation
3. Open a new incognito window and log into HDX using the ordinary user account in step 2
4. Find the chosen organisation and click on edit
5. The organisation page goes into edit mode. The custom settings for the organisation are visible except for the "use custom settings" check box.
6. Click update. The custom settings for the organisation are lost and the organisation becomes an ordinary organisation.

**Comment by danmihaila** [comment]
Nosetest: check on page if there is any hidden input and what is the value. On server side check the action for update organizations.
ping @mbellotti to be aware of this comment
