### ISSUE TITLE
Setup Jenkins server for HDX

### ISSUE THREAD

**Issue by aalecs** [OCHA-DAP/hdx-ckan#3442]

**Comment by danmihaila** [comment]
this is high priority now for Sprint 65.

**Comment by teodorescuserban** [comment]
will be done today.

**Comment by teodorescuserban** [comment]
Well I was too confident. :)
I will do it in a few days, though.

**Comment by teodorescuserban** [comment]
I changed priority on this one, @danmihaila

**Comment by danmihaila** [comment]
@teodorescuserban i found the issue about Jenkins too  :) I hope we can have it done this sprint

**Comment by danmihaila** [comment]
done
