### ISSUE TITLE
Investigate more about initializing custom models

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#3450]
We should investigate more about initializing custom models like `validate_tokens` and `user_extra`. 
I'm referring here to how they are initialized in tests and cli. 

I'm providing a link to how it was done for ckan_pages extension: https://github.com/ckan/ckanext-pages/blob/master/ckanext/pages/db.py

This is to deal with errors like `InvalidRequestError: Table 'validation_tokens' is already defined for this MetaData instance.` that sometime appear in tests on model import: https://github.com/OCHA-DAP/hdx-ckan/commit/35631a2ec72914f99d0e55ed18a418043f4538c4

**Comment by mbellotti** [comment]
Having read over the example code, I have no objection to using this approach. I modeled our approach after ckan comments extension because it seemed to give greater flexibility concerning deploy procedures.

**Comment by danmihaila** [comment]
@alexandru-m-g do you want to make the migration of code? do we need a call for re this issue?
