### ISSUE TITLE
User: strange behaviour

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3453]
- [ ] How to reproduce 
  on staging there is a difference between:
  https://test-data.hdx.rwlabs.org/user/  -> profile of current user if logged in or 404 if not logged in
  and
  https://test-data.hdx.rwlabs.org/user  -> list of users
  Both should go to the list of users
- [ ] Nosetest: go to both urls and check the content.

**Comment by cjhendrix** [comment]
Loads the logged in user's profile page instead of the list of users when trailing / is included

![image](https://cloud.githubusercontent.com/assets/1654485/9736481/b336c608-5641-11e5-8363-05ff127cc771.png)
