### ISSUE TITLE
Range date of a dataset

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3457]
- [ ] how to reproduce it
- Given dataset with a range in "date of dataset"
  ![1](https://cloud.githubusercontent.com/assets/3865844/9515103/c99bbd5c-4ca7-11e5-8d77-cf752c33b015.jpg)
- I would like to edit one of the fields. In this case, lets assume I want to change the source of the dataset. I press, EDIT
  ![2](https://cloud.githubusercontent.com/assets/3865844/9515110/d78e6a90-4ca7-11e5-9b30-5a787ccc7699.jpg)
- Once you are in the edit mode, and you scroll down to choose the metadata field to be edited, you will notice that your range is gone and the date of dataset has automatically being changed to a rather random date. 
  ![3](https://cloud.githubusercontent.com/assets/3865844/9515115/e0a3190a-4ca7-11e5-8641-2ebcd580a433.gif)
- [ ] Nosetest: load the dataset page with the range and search inside the page for both dates.

**Comment by danmihaila** [comment]
@alexandru-m-g will do it as hotfix

**Comment by alexandru-m-g** [comment]
This is fixed, closing. Didn't add a nosetest as the bug was entirely js.
