### ISSUE TITLE
Organization edit: description is not checked for validation anymore

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3458]
- [ ] Try to edit an organization
  https://test-data.hdx.rwlabs.org/organization/edit/innago
  with an empty description.
  Organization will be saved with no warning even if description is emtpy.
- [ ] Nosetest: check all the fields for an organization that are mandatory.

**Comment by aalecs** [comment]
Also, just discovered on staging that the description field is not saved. Steps:
- edit INNAGO
- change description to "Test"
- save org
- check org page -> no "Test" as description
- edit org -> no "Test" in description field

**Comment by mbellotti** [comment]
So far I haven't been able to reproduce either of these problems. Temporary quirk in staging?

**Comment by danmihaila** [comment]
@mbellotti
1. first task in the initial description is still available. I reproduced it local. 
Steps:
- go to http://localhost:5000/organization/edit/innago
- check description which is empty field:
  ![screen shot 2015-09-02 at 15 22 39](https://cloud.githubusercontent.com/assets/3865844/9630985/7df82f64-5186-11e5-9675-69b211ec941f.png)
- leave description empty
- save organization
  Organization is saved even if description is mandatory.
- second comment from @aalecs I can not reproduce. I added "test" in description field and it is working, it is saving the value

**Comment by mbellotti** [comment]
Try this, go back to edit/innago. This time instead of just leaving the description box as is and saving it, focus on the textarea and hit backspace (or delete, it shouldn't matter). This time you will get a validation error... so I'm wondering if this is an issue with markdown?
