### ISSUE TITLE
Onboarding improvements

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3459]
Right now all the onboarding widgets are loading on all pages even if user is logged in or not. Same, they are retrieving data even if it is not needed.
Improve this by trigerring the load only when click on sign in, sign out or register.

**Comment by alexandru-m-g** [comment]
@danmihaila Can you please test this on stag. Not sure what I'm supposed to see/not see anymore

**Comment by danmihaila** [comment]
it is almost good. When login there is the action "onboarding_followee_list" called.
printscreen attached and ping @aalecs 
<img width="1118" alt="screen shot 2015-09-22 at 17 48 13" src="https://cloud.githubusercontent.com/assets/3865844/10021802/6fa6282c-6152-11e5-9cf6-9283f283d633.png">
