### ISSUE TITLE
the /monitor url needs to have authentication

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#3463]
Can we add HTTP authentication to /monitor . It's important. Should be done for all servers: prod, stag,feature,dev

**Comment by teodorescuserban** [comment]
We have the user agent auth. Dont we?

Vin, 28 aug. 2015, 14:04, Alexandru Gartner notifications@github.com a
scris:

**Comment by alexandru-m-g** [comment]
I seem to be able to connect to: data.hdx.rwlabs.org/monitor without any special user agent or http auth

**Comment by teodorescuserban** [comment]
Fixed on prod. I will propagate the changes.
Closing.
