### ISSUE TITLE
Remove deleted geo-resources from postgis

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#3466]
We need to identify and remove from postgis the resources that have been deleted from CKAN.

**Comment by teodorescuserban** [comment]
Lets talk.

Dum, 30 aug. 2015, 03:26, Alexandru Gartner notifications@github.com a
scris:

**Comment by alexandru-m-g** [comment]
@teodorescuserban there will be another config change needed for this on the gislayer side:

``` python
RESOURCE_ID_LIST_API = 'http://[CKAN_URL]/api/action/hdx_resource_id_list'
```

**Comment by teodorescuserban** [comment]
Why you don't use the already defined `CKAN_SERVER_URL` and just make `RESOURCE_ID_LIST_API` as a path?
Like:
`RESOURCE_ID_LIST_API='/api/action/hdx_resource_id_list'`

**Comment by teodorescuserban** [comment]
We could use that on `GIS_API_PATTERN` and `RESOURCE_UPDATE_API` as well.

**Comment by alexandru-m-g** [comment]
I meant to have the API endpoints as completely separate since it gives more flexibility. For example, if some API needs to be accessed via HTTP while another needs HTTPS. Or if some API endpoint gets moved out of the CKAN application. 

The CKAN_SERVER_URL was added as a quick fix for a completely different problem.

**Comment by teodorescuserban** [comment]
Ok. Understood. You are perfectly right.

Vin, 4 sept. 2015, 14:02, Alexandru Gartner notifications@github.com a
scris:
