### ISSUE TITLE
Geopreview processing starts but does not complete

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3471]
Another one: 

https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=afghanistan-admin-level-3-boundaries

**Comment by alexandru-m-g** [comment]
After investigating with @teodorescuserban, we came back to the following conclusion:
-  We can see in the logs that the geoprocessing takes places and actually ends succesfully
-  CKAN is notified about this via the API and returns _successful_
-  The status of the resource is then modified ( so the _successful_ state of the resource is overwritten ). How does this happen:
  -  The cod migration script has the following steps:
    1. Create/Update dataset
    2. Upload resource via `resource_update` API
    3. Update dataset to mark the import complete. This was done by removing a tag from the dataset via `package_show` (for reading the dataset) and `package_update` ( for writing the dataset back to the db without a specific tag )
  - Let's assume that in the middle of step (c), between the `package_show` and `package_update`, the geo-processing finishes. So there's a new resource revision created which indicates that the resource is _previewable_. But then the `package_update` creates a new resource revision with **old** information where the status of the resource is still "Processing"

Possible solutions:
-  remove step (c) from the script somehow
-  try using http://docs.ckan.org/en/ckan-2.3/api/index.html#ckan.logic.action.patch.package_patch to remove the tag
-  modify hdx_package_update_metadata() or create a new API

Won't do any code changes until we decide that one of the above is really necessary. Pinging @cjhendrix

**Comment by cjhendrix** [comment]
tested but it was an intermittent problem and therefore hard to replicate.  Seems to be fixed.
