### ISSUE TITLE
Javascript alerts

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3472]
We need to refactor the javascript alerts. 
- [ ]  make a dataset private/public. Similar to
  ![edit_membership](https://cloud.githubusercontent.com/assets/3865844/9600618/beef81e4-50a4-11e5-938f-4cabd18668f0.png)
- [x] add member 
  ![add_member](https://cloud.githubusercontent.com/assets/3865844/9600631/c8720714-50a4-11e5-963d-985f4b7e5719.png)
- [x] delete member
  ![delete_dataset](https://cloud.githubusercontent.com/assets/3865844/9600641/d8bbfe7c-50a4-11e5-8853-1eefb1ad7b1a.png)
- [x]  edit member
  ![edit_membership](https://cloud.githubusercontent.com/assets/3865844/9600669/fdd9a1b4-50a4-11e5-96d9-113cd837dff9.png)
- [x] delete location
  ![delete_dataset](https://cloud.githubusercontent.com/assets/3865844/9600641/d8bbfe7c-50a4-11e5-8853-1eefb1ad7b1a.png)
- [x] delete organization
  ![delete_dataset](https://cloud.githubusercontent.com/assets/3865844/9600641/d8bbfe7c-50a4-11e5-8853-1eefb1ad7b1a.png)
- [x] delete user
  ![delete_dataset](https://cloud.githubusercontent.com/assets/3865844/9600641/d8bbfe7c-50a4-11e5-8853-1eefb1ad7b1a.png)
- [x] delete dataset
  ![delete_dataset](https://cloud.githubusercontent.com/assets/3865844/9600641/d8bbfe7c-50a4-11e5-8853-1eefb1ad7b1a.png)
- [x] delete resource
  ![delete_dataset](https://cloud.githubusercontent.com/assets/3865844/9600641/d8bbfe7c-50a4-11e5-8853-1eefb1ad7b1a.png)

**Comment by alexandru-m-g** [comment]
@danmihaila 
This seems to work fine except I don't know how to delete groups and locations. Can you check or tell me where it's done ?

**Comment by danmihaila** [comment]
<img width="456" alt="screen shot 2015-09-22 at 16 49 19" src="https://cloud.githubusercontent.com/assets/3865844/10020146/f9c8d3dc-6149-11e5-8142-a89d75c4feea.png">
