### ISSUE TITLE
Onboarding: forgot password feature

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3476]
We need a mockup to integrate the forgot password in our onboarding. Assigning to @yumiendo for mockup
Right now we have: https://data.hdx.rwlabs.org/user/reset

**Comment by yumiendo** [comment]
2 comps attached - form field & confirmation
![forgot_password](https://cloud.githubusercontent.com/assets/8006323/9613413/2fb9a454-50b9-11e5-94e8-ab77cbec1b62.png)
![forgot_password2](https://cloud.githubusercontent.com/assets/8006323/9613414/2fba6eac-50b9-11e5-8444-3e50e412f192.png)

after the confirmation - can we take user back to the page they were on?
currently after password reset it goes to the old login page. 
<img width="1440" alt="screen shot 2015-09-01 at 2 56 19 pm" src="https://cloud.githubusercontent.com/assets/8006323/9613448/65f86f6e-50b9-11e5-9f07-af284cefa9af.png">

through the reset link provided in the email - does it take user back to the login screen?

**Comment by danmihaila** [comment]
ok, will see how we can do it.
thanks @yumiendo and assigned this task for next sprint

**Comment by alexandru-m-g** [comment]
I tried to reset the password by using the **email** but I get the below message:

![reset_password](https://cloud.githubusercontent.com/assets/6586348/10017493/6d2cddc2-6137-11e5-8b80-d62f4d674ec9.png)

I tried for my user with my main gmail address.

**Comment by alexandru-m-g** [comment]
Fixed by @danmihaila and tested on stag
