### ISSUE TITLE
ROEA page fixes

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3481]
@aalecs we need to do this as hotfix on prod. please work on this asap.
1."Coping" should be changed by " Lack of Coping Cap" or any abbreviation
2. The source that Sarah suggested is not "OCHA ROEA" but "OCHA, UNHCR,FEWSNET"

**Comment by aalecs** [comment]
1. fixed in the code
2. can be configured in the org edit page at the visualisation config section

**Comment by danmihaila** [comment]
ping @takavarasha and @luiscape. Please check Arti's comment.
