### ISSUE TITLE
Geopreview: OSM basemap not refreshing on chrome (win7)

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3482]
I've been seeing this problem over the last week.  Restarts haven't helped.  Happens only on chrome, not FF.   

When zooming in our out of the geo preview map, the OSM tiles are often not refreshed, though I have seen it work sometimes as well.  The tile requests are from (for example) https://data.hdx.rwlabs.org/crisis-tiles/8/149/131.png  and are stuck as "pending". 

![image](https://cloud.githubusercontent.com/assets/1654485/9656400/6b891890-5238-11e5-84f8-ed7207f31faf.png)

![image](https://cloud.githubusercontent.com/assets/1654485/9656409/733da9ac-5238-11e5-9095-f91795301525.png)

**Comment by teodorescuserban** [comment]
Assign it to me please.

Joi, 3 sept. 2015, 13:41, cjhendrix notifications@github.com a scris:

**Comment by cjhendrix** [comment]
I haven't seen this happening for the last week or so.  Closing for now.
