### ISSUE TITLE
Docker alignment with prod configuration

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3483]
This is an issue that should be assigned to all devs in order to be aligned with configurations made on server.
It will be also an advantage in order to have all the features installed on local machines, to be able to get snapshots of database easier, etc.

**Comment by teodorescuserban** [comment]
Please lets talk.
Reason 1: I'm in the middle of doing some major changes on how prod docker stack is created.
Reason 2: you should be very easily able to follow the same prod procedure to bring up parts of stack or the entire stack on your local env.

**Comment by alexandru-m-g** [comment]
Repo and documentation are here: https://bitbucket.org/agartner/hdxckan-dev-docker-compose 
If you don't have access to the repo please let me know.
