### ISSUE TITLE
Onboarding: followee list

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3486]
Improve the list of items that user can initially follows when during the onboarding.
Ping @yumiendo to be aware of this and comments

**Comment by yumiendo** [comment]
some running list of ideas:
- top country pages (popularity)
- curated country pages
- orgs with most datasets
- (if crises are happening) crises page
  etc

**Comment by danmihaila** [comment]
@yumiendo the most popular country means the country with the most datasets, then we add the custom pages, custom crises and orgs with most datasets.
What about HDX organization? it has the most datasets, should we skip it?
pinging @cjhendrix for comments or ideas too

**Comment by cjhendrix** [comment]
I'd suggest we get most popular datasets in there.  Dataset view pages are by far the most viewed pages (of course there are a lot more of them). 

![image](https://cloud.githubusercontent.com/assets/1654485/9900404/da9665b2-5c60-11e5-81cf-81f583874684.png)

**Comment by yumiendo** [comment]
@danmihaila I think having HDX there is going to help users...(being the top contributor) so let's include.
@cjhendrix sure ! how often should we refresh the list of datasets? (assuming we're using GA...)is there a way to set up so it refreshes every so often?

**Comment by cjhendrix** [comment]
Cool.  CKAN gives us a measure of popularity on datasets (I think it's number of views in the last 3 weeks).  It's what is used when you rank a search result by popularity, so no need to pull from GA.

**Comment by danmihaila** [comment]
from what I know only datasets and resources have popular views. For the moment we can not access the google analytics data.
I would say that the next improvement should be done based on Yumi's suggestion and next step to integrate with GA data.
ping @alexandru-m-g for more ideas
