### ISSUE TITLE
Geopreview:  enable support for KMZ

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3504]
This may require enabling a different kml driver.  Requested by @luiscape primarily for the UNOSAT datasets.

**Comment by alexandru-m-g** [comment]
This is a related commit: https://bitbucket.org/agartner/gisrestlayer/commits/433a393ffca4ae98b62de38499a1981dbcac51d6

**Comment by cjhendrix** [comment]
Tested with two different kmz files, both returning the same error. Reopening.

https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=geotest02

**Comment by teodorescuserban** [comment]
nobody tols me that I need to redeploy gis layer and worker containers with the new code. :)
@alexandru-m-g just told me and I did.

please try again.

ps: i will redeploy on prod as well after we confirm all green

**Comment by cjhendrix** [comment]
Working on stag.  Closing.

**Comment by teodorescuserban** [comment]
thanks @cjhendrix will deploy on prod now.

**Comment by teodorescuserban** [comment]
Deployed. 
Tagging @cjhendrix as he might want to test this on prod.
