### ISSUE TITLE
Have a CKAN health check page

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#3505]
Now that HDX has many components it's easy to loose track of them and it's hard to check if they're all working after a redeploy.

I think we should have CKAN ping the other services to see if they're operational and present the results in a health check page like: http://mylocalwebstop.com/wp-content/uploads/2015/02/screenshot-11.png. This would be easy to check by any sysadmin and could be indicative on whether things are up and running correctly. 

Things like: dataproxy, gisworker, gislayer, redis, thumbnail endpoint could all benefit from this.

Pinging @danmihaila and @teodorescuserban .

**Comment by danmihaila** [comment]
I will include here the email server. I know @teodorescuserban created a git issue to test the email server.

**Comment by teodorescuserban** [comment]
Not sure if ckan itself should test everything. I would rather have the
util container do that but lets talk

Mar, 8 sept. 2015, 15:10, danmihaila notifications@github.com a scris:

**Comment by alexandru-m-g** [comment]
I didn't go too much into detail above but basically each tool should test it's own dependencies ( like gislayer should test access to postgis, redis, spatial etc ). 

Just the page showing the status should be on CKAN. So CKAN centralizes the data since they all ultimately communicate with CKAN in one way or another.

**Comment by alexandru-m-g** [comment]
## Idea

These checks should test that the services are up and running on the expected host & port. They should not play the role of unit tests. 

The main goal is to see that our services are connected properly on the production server. 

The checks should be simple.

The results could at first be displayed as a JSON result (action / API ). HTML page could come later.

## What  ?
-  dataproxy
-  cps
-  gislayer - which should itself check the following
  -  redis
  -  rq worker
  -  spatial server
-  spatial server
-  ~~phantom js~~ ( this is not a network service, it's a command run inside the CKAN container )
-  mail server ( this needs to be investigated a bit more ) 
-  ~~solr~~ ( CKAN anyway doesn't start without a running solr instance )

## How ?

The simplest checks could be the equivalent of a _ping_. This will tell us: _There's something actually listening on the expected host:port_

Slightly more complex checks would assume that the service we want to check has ( or we can easily implement ) some sort of API for reporting its status. This would give us a bit more information: _The correct service is listening on the host:port and it seems to be configured correctly_

The report of a check should contain:
-  Name ( ex. Dataproxy check )
-  Description ( What does the check actually check )
-  Result: Passed / Failed
-  Error message ( empty if the check passed )
-  List of subchecks with the exact same structure -- for now this is just needed for the gislayer

``` javascript
{
  'name': 'Dataproxy check',
  'description': 'Calls the [URL/NAME] API of the dataproxy and checks that it gets http status code 200 and "some string" is part of the response',
  'result': 'Failed',
  'error_message': 'HTTP status was 401 instead of 200',
  'subchecks': [
    {
      'name': 'Subcheck 1',
      'description': '',
      'result': 'Passed',
      'error_message': ''
    }
  ]
}
```

**Comment by mbellotti** [comment]
solr? cps?

**Comment by alexandru-m-g** [comment]
After talking to @mbellotti and @teodorescuserban:
-  will create a separate ckan extension ( so that it could potentially be reused )
-  there will be different types of checks that can be configured to test different services, like: open port check, http status code check, etc . There should be an easy way to add new types of checks.
-  there will be a configuration file that will specify a list of checks that should be run. For each of the item in the list there should be something like `type: HttpStatusCodeChecker, port: 9013, host: 172.17.42.1, expected: 200`

**Comment by alexandru-m-g** [comment]
This commit is also related to this issue https://bitbucket.org/agartner/gisrestlayer/commits/909f4f027380d5c507b4bdcb697a7a6238421608

**Comment by alexandru-m-g** [comment]
@danmihaila @teodorescuserban 
This commit involves changes on both CKAN and gislayer. There is a new extension in CKAN called ckanext-hdx_service_checker. 

The following steps will be needed:
-  A `python setup.py develop` will probably be needed in the new extension. 
-  on CKAN, in prod.ini: `hdx.checks.config_path = /srv/ckan/ckanext-hdx_service_checker/ckanext/hdx_service_checker/config/config.json` (check path)
-  on gislayer / gisworker: `CHECKS_CONFIG_PATH = '/srv/gislayer/config/config.json'` (check path)
-  on gislayer / gisworker: `pip install -r requirements.txt`

**Comment by teodorescuserban** [comment]
why not adding hdx.checks.config_path to common-config.ini.txt?

În Lun, 28 sept. 2015 la 12:50, Alexandru Gartner notifications@github.com
a scris:

**Comment by teodorescuserban** [comment]
do we require an update on gislayer / gisworker code?

În Lun, 28 sept. 2015 la 13:38, Serban Teodorescu <
teodorescu.serban@gmail.com> a scris:

**Comment by alexandru-m-g** [comment]
@teodorescuserban 
1.  You're right. I'll make the change and add it to common config. 
2.  Yes gislayer / worker needs to be updated ( check my comment above )

**Comment by danmihaila** [comment]
The tool looks ok. @alexandru-m-g can you check if the errors are real on staging? Lookind forward to check on prod
<img width="1280" alt="screen shot 2015-10-08 at 15 46 56" src="https://cloud.githubusercontent.com/assets/3865844/10366564/fba3a772-6dd3-11e5-8f42-3177eff00b91.png">

**Comment by alexandru-m-g** [comment]
Made 2 changes that should help avoid the errors on the server.
