### ISSUE TITLE
Search.  Grrr.

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3508]
For COD migration, we have created (temporarily) tags in the form of `nodeid1234`.  Often, searching by that tag finds the dataset.  However sometimes it does not.  For example none of these searches return the single dataset having the tag:

https://data.hdx.rwlabs.org/search?q=nodeid3976+water
https://data.hdx.rwlabs.org/search?q=nodeid3976+ethiopia
https://data.hdx.rwlabs.org/search?q=nodeid3976

The dataset I want to find is https://data.hdx.rwlabs.org/dataset/ethiopia-water-courses

**Comment by teodorescuserban** [comment]
are we sure the search for nodeid is well performed if you dont specify
that is a tag?

În Mie, 9 sept. 2015 la 11:41, cjhendrix notifications@github.com a scris:

**Comment by cjhendrix** [comment]
It works in many cases.  I just can't understand why sometimes it doesn't.  I still think we need to privilege tags more in the search weighting.

**Comment by danmihaila** [comment]
@cjhendrix I found some issues:
- as you see in screenshot, nodeid3976 is not returned for the whole list of datasets
- the dataset you pasted is private and this might be the reason.
  I guess this issue should be close in case making this dataset public is still not showing.

**Comment by cjhendrix** [comment]
D'oh!

**Comment by alexandru-m-g** [comment]
Nothing to test here.
