### ISSUE TITLE
Make facet filtering UX clearer

### ISSUE THREAD

**Issue by mbellotti** [OCHA-DAP/hdx-ckan#3509]
Currently when users want to filter a search by a facet they click a small funnel icon in the search bar to pull down the filter window. However it is not clear what this icon is or what it should do. Let's find a better way to alert users to the possibility of filters.

**Comment by cjhendrix** [comment]
This is being worked on as part of #3555 and it's related issues.  Moved to epics and will close when the design and implementation are done.

**Comment by danmihaila** [comment]
this is done, closing it
