### ISSUE TITLE
Custom Org:  can't see difference between private and public datasets

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3532]
On custom org, private datasets are shown to authorized users, however there is no icon/badge to differentiate them.  This has been confusing to org admins.

Add the lock icon https://drive.google.com/open?id=0B24NBcgmV490VjFQMFRoZ3V3VXc to the search results similar to what is shown here:  
![image](https://cloud.githubusercontent.com/assets/1654485/9959819/059d539e-5e17-11e5-94f0-3e29910a8006.png)

That's a mockup for dashboard, so don't worry about anything other than placement of the lock icon.

**Comment by alexandru-m-g** [comment]
This was mostly already done by #3557 . I'm just changing the style a bit here.

Pinging @cjhendrix
