### ISSUE TITLE
Featured Organizations: missing thumbnail and large thumbnail sizes

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3533]
I think the dev team is aware of these issues already but I didn't find an issue for them.  Please close if duplicate.
- [x] thumbnail for AFG is missing (3W section)
- [ ] thumbnails are large 1170x500 px and 200 to 500KB.  I think something like 500 px wide is enough even when zooming in on the page to 200%. 

![image](https://cloud.githubusercontent.com/assets/1654485/9844334/9f900008-5ac2-11e5-8669-bb02a10243fa.png)

**Comment by danmihaila** [comment]
@cjhendrix i think we can close this one

**Comment by cjhendrix** [comment]
I still think we should fix the image size just to keep the site as light as possible.  Field bandwidths are often frustratingly slow.  I guess what would help would be to have some idea of what our target is for the size to load a given HDX page so we could know if these images are blowing the budget or not.  To me they seem big (and I see them loading slowly sometimes).  If you disagree, feel free to close.

**Comment by danmihaila** [comment]
maybe we could cache the images in browser

**Comment by danmihaila** [comment]
@aalecs you could check if there is a paramater to adjust the size of screenshot in px

**Comment by aalecs** [comment]
@teodorescuserban We need to install the imagemagick suite in the ckan container before being able to use the thumbnail generator ... the command is similar to: 
apt-get install imagemagick

**Comment by teodorescuserban** [comment]
@aalecs : imagemagick has been added to staging ckan container.

**Comment by teodorescuserban** [comment]
installed on staging, @aalecs
