### ISSUE TITLE
Dataset View: problems with share resource button

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3535]
Each of the 4 options in the share button on a --->**resource**<--- has "XXXX" as the URL component of the share link.  Compare to the links for the share button on the dataset to see the difference.

![image](https://cloud.githubusercontent.com/assets/1654485/9844882/2db07fda-5ac7-11e5-939f-68bf69df4a1f.png)

**Comment by danmihaila** [comment]
@alexandru-m-g can you work on this pls?

**Comment by alexandru-m-g** [comment]
Fix was committed.
