### ISSUE TITLE
Main Nav tweaks

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3538]
bring back FAQ on the same line as main nav(we might have to squeeze the space next to the HDX logo)  and put "Feedback" in the footer.

![nav_cleanup](https://cloud.githubusercontent.com/assets/3865844/9872083/aee9be9e-5b9f-11e5-90e1-a2630b90c044.png)

**Comment by alexandru-m-g** [comment]
@aalecs seems like Contact in the footer is the same as Feedback. Is that why this wasn't moved to the footer ( according to the description of this ticket ) ?

**Comment by danmihaila** [comment]
@yumiendo we need you to validate this issue. I checked  on https://test-data.hdx.rwlabs.org/dataset header and footer, are they ok?
<img width="1187" alt="screen shot 2015-10-08 at 16 37 37" src="https://cloud.githubusercontent.com/assets/3865844/10367820/386d7fa0-6ddb-11e5-96bc-dcb467ce5b2f.png">
<img width="1191" alt="screen shot 2015-10-08 at 16 37 35" src="https://cloud.githubusercontent.com/assets/3865844/10367821/3873ee6c-6ddb-11e5-9004-53231c1cf013.png">

**Comment by yumiendo** [comment]
We removed 'feedback' from the top bar so can we add it back into the footer? 
<img width="1383" alt="screen shot 2015-10-08 at 6 48 11 pm copy" src="https://cloud.githubusercontent.com/assets/8006323/10381765/6e6b686e-6deb-11e5-974c-d4dec41c64a1.png">

**Comment by yumiendo** [comment]
also once we implement the new filters...can we remove the funnel icon and shift the main navigation to the left (roughly 40px...) comp attached.
<img width="1323" alt="screen shot 2015-10-08 at 7 07 47 pm" src="https://cloud.githubusercontent.com/assets/8006323/10382024/c5585676-6ded-11e5-8f48-555e326c4f2f.png">

**Comment by danmihaila** [comment]
@aalecs lets made also the changes re Feedback and funnel icon in sprint 68. Thanks
