### ISSUE TITLE
FAQ feedback tweaks

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3539]
- [ ] shrink the question field(height) a little so all of the capcha is exposed ?
- [ ] is it possible to move the scroll bar to the side? (so it won’t overlap with the text fields)
- [x] can we make the capcha wider to match the rest of the text fields? 
  <img width="640" alt="screen shot 2015-09-08 at 10 16 28 am" src="https://cloud.githubusercontent.com/assets/3865844/9872201/57dea906-5ba0-11e5-8645-452f2f3535c0.png">

**Comment by aalecs** [comment]
In order to make it look like in the photo, I did the following:
      - hidden please fill out text so we can have more space 
      - no more scroll bar + captcha wider

**Comment by alexandru-m-g** [comment]
Still see some scrollbars but might be only on my machine: 

Chrome
![chrome](https://cloud.githubusercontent.com/assets/6586348/10017227/4828eb9e-6135-11e5-9e20-ff5c8217af7d.png)

Firefox
![ff](https://cloud.githubusercontent.com/assets/6586348/10017234/4cc1c48c-6135-11e5-8b3c-1e441e944462.png)
