### ISSUE TITLE
Resource Preview: data proxy not working

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3540]
I can't get preview of any datasets (tried some CSV, XLS, and geojson).

**Comment by teodorescuserban** [comment]
on staging?

**Comment by cjhendrix** [comment]
prod

**Comment by danmihaila** [comment]
@alexandru-m-g can you investigate? if it is easy to fix lets do it today, if not we move it to next sprint. thanks

**Comment by teodorescuserban** [comment]
fixed.
had a similar issue on staging as well. fixed.
closing.

**Comment by teodorescuserban** [comment]
fixed on demo and feature as well...

**Comment by danmihaila** [comment]
I think we still have a problem with json preview

**Comment by teodorescuserban** [comment]
example?

În Mar, 15 sept. 2015 la 12:28, danmihaila notifications@github.com a
scris:

**Comment by alexandru-m-g** [comment]
I don't think json ( as opposed to geojson ) was made to work after the upgrade to CKAN 2.3.

**Comment by teodorescuserban** [comment]
me neither

În Mar, 15 sept. 2015 la 13:16, Alexandru Gartner notifications@github.com
a scris:

**Comment by alexandru-m-g** [comment]
Tested on stag and prod.
