### ISSUE TITLE
User menu falling out of browser

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3551]
Chrome on Win 7.  Zoomed to 100%.  Chrome window maximized.

![image](https://cloud.githubusercontent.com/assets/1654485/9928075/9c55ec46-5d23-11e5-99ea-2ac5c2c71669.png)

On FF for comparison (working fine)
![image](https://cloud.githubusercontent.com/assets/1654485/9928178/a57104ae-5d24-11e5-9e5f-29d923218d24.png)

**Comment by danmihaila** [comment]
@cjhendrix is this still an issue? can you reproduce it?

**Comment by cjhendrix** [comment]
Can't reproduce now. Closing.

**Comment by cjhendrix** [comment]
You're right, but I think we need to assign it to the data team.  I don't think this should be on HDX.

**Comment by cjhendrix** [comment]
@JavierTeran  This "dataset" is just a link to a web page with no data.  Thought you might want to have a look at it.
