### ISSUE TITLE
Rationalize the different ways we display dataset search results

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3555]
We have at least 6 different ways of displaying search results.  It would be good to reduce that number and standardize:
1. Display of icons (popular, quality checked, subnational, deleted, private)
2. Interface for filters (we have two ways: left sidebar and top drawer)
3. Where private/deleted datasets are shown to authorized users (deleted datasts not shown in standard search result and custom org, but shown on default org and dashboard; private datasets not shown on standard search result, but shown on custom/default org and dashboard)
4. If an authorized user has buttons for edit/delete on each item in the list (they are there on the dashboard, but not on the org page, for example)
5. Make pagination consistent (where it makes sense to do so).

![image](https://cloud.githubusercontent.com/assets/1654485/9930141/f029526e-5d31-11e5-92f9-aba70a287cff.png)

**Comment by cjhendrix** [comment]
As this involves both dev and design, pinging @amcguire62 for prioritization.

**Comment by yumiendo** [comment]
@danmihaila @ochadataproject @amcguire62 @JavierTeran 

Hi all, attached is standardized header treatment/new filters.
- Data (showing header/all filters)
  ![data](https://cloud.githubusercontent.com/assets/8006323/10150302/c082c80e-660c-11e5-8e74-153a73f5e2ed.png)
- Custom location (mali - showing header/all filters - CJ pointed out some data contain multiple countries so please keep the location filter)
  ![custom_location](https://cloud.githubusercontent.com/assets/8006323/10251148/f5351b36-68fc-11e5-8d41-64cd5e1948b7.png)
- Default org (showing header/all filters minus “organization” with activity stream… - This will replace the old template https://data.hdx.rwlabs.org/organization/adra-vanuatu )
  ![default_org](https://cloud.githubusercontent.com/assets/8006323/10150304/c08ffbf0-660c-11e5-88ae-5dc357f1de60.png)

the rest of pages will follow similar pattern -
- Default location (same as custom location page)
- Custom org (all filters minus organisation + activity stream)
- Crisis (all filters + activity stream = combo of data page + default org page)

We also need to remember to remove the current advance filters(drawer & funnel icon) when implementing the above.

**Comment by yumiendo** [comment]
![data_searchrec](https://cloud.githubusercontent.com/assets/8006323/10227950/582c5e9e-683e-11e5-8b41-97802aa49314.png)
attached is a version with 'You might also like..." above the search results

**Comment by alexandru-m-g** [comment]
@danmihaila @teodorescuserban 
2 things will be needed on the next deploy (staging and prod):
1.  Run the following sql query on the database:
   
   ``` sql
   update package pp set creator_user_id = (
   
   select u.id
   from package p, package_role pr, user_object_role uor, "user" u
   where p.id = pr.package_id AND pr.user_object_role_id = uor.id  AND u.id = uor.user_id AND p.id = pp.id 
   AND p.state = 'active' and uor.role='admin' and p.creator_user_id IS NULL  ) 
   where pp.creator_user_id IS NULL and pp.state = 'active';
   ```
2.  Change the **solr schema** with the new one from here: https://github.com/OCHA-DAP/hdx-ckan/blob/18213f4b71d7e1c922d18c7a2faabfe7c960905c/ckanext-hdx_search/ckanext/hdx_search/hdx-solr/schema.xml

**Comment by teodorescuserban** [comment]
- reindex

**Comment by yumiendo** [comment]
ok - will respond later today

**Comment by teodorescuserban** [comment]
UPDATE 1119
