### ISSUE TITLE
Dashboard:  delete behavior different on stag and prod

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3556]
On the My Datasets page, when clicking the `Delete` link on a dataset in the list,  I get different delete behaviors between stag and prod.  

On stag, I get a the correct behavior (modal), however the delete button in the modal **doesn't** work (nothing happens on click). 
![image](https://cloud.githubusercontent.com/assets/1654485/9931122/31689486-5d39-11e5-830d-2911809c7af4.png)

On prod, I get redirected to a different page.  The confirm delete button **does** work, however. 
![image](https://cloud.githubusercontent.com/assets/1654485/9931140/5714e6f8-5d39-11e5-9a26-aa58e6e29a14.png)

**Comment by danmihaila** [comment]
On staging we have the new look. Pinging @aalecs for 'delete" action not working.
