### ISSUE TITLE
Changes to dashboard>my datasets

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3557]
**For all dashboard tabs (my datasets, my orgs, newsfeed, my locations)**
- [ ] Add "Dashboard" header at the top of all dashboard pages as shown in mockup below.  Tabs are below.  The text "Dashboard" does not change with selection of a different tab.

**For "My Datasets"**
- [ ] Do not display deleted datasets on My Datasets
- [ ] Change dataset list display to match HDX style as shown in mockup.
- [ ] Remove the "delete" link from those datasets (only "Edit this dataset" is available as shown in mockup)

Private dataset icon is here: https://drive.google.com/open?id=0B24NBcgmV490VjFQMFRoZ3V3VXc

![image](https://cloud.githubusercontent.com/assets/8006323/9907852/06bad512-5c5f-11e5-8c05-62c1bc3f88c9.png)

**Comment by alexandru-m-g** [comment]
This was mostly already done by #3557 . I'm just changing the style a bit here.

Pinging @cjhendrix
