### ISSUE TITLE
Text change on dataset deletion modal

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3558]
Change 

`You are deleting dataset` 

to

`You are deleting a dataset`

![image](https://cloud.githubusercontent.com/assets/1654485/9931278/9893dd86-5d3a-11e5-832a-d62870fe55ea.png)

**Comment by alexandru-m-g** [comment]
@cjhendrix @mbellotti I was trying to test this so I created a new dataset both as a normal user and as a sysadmin BUT I don't see the "Delete" link under the dataset. Check screenshot.
Is that normal ? 

![delete_not_appearing](https://cloud.githubusercontent.com/assets/6586348/10206112/edf0d69c-67cd-11e5-826e-abc76eb9e1b1.png)

**Comment by alexandru-m-g** [comment]
It seems like it is normal according to: https://github.com/OCHA-DAP/hdx-ckan/issues/3557 . Then this issue becomes irrelevant :)
