### ISSUE TITLE
visualization: loading icon

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3560]
when visualization is taking too long we should add a javascript "loading..." as we have for resource upload.
or try to display something until the whole data is download.
for 3w, wfp and roea dashboard.
ping @aalecs, @yumiendo  and @SimonbJohnson for ideas.

**Comment by yumiendo** [comment]
there is a loading state/screen for when uploading files (share data) <- this takes the whole screen but maybe we could use it for the visualization part of the page? 

previously: https://github.com/OCHA-DAP/hdx-ckan/issues/3236

**Comment by danmihaila** [comment]
do we want the whole page to be disabled or only the 3w visualization?

**Comment by yumiendo** [comment]
let's apply it for the visualization section of the page only (or whichever takes longest) and let users get to other sections of the page as needed.

**Comment by yumiendo** [comment]
the text should read "Loading...this might take a few seconds"
