### ISSUE TITLE
Research how to really really delete ckan datasets 

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3562]
We want to make deletions by users real.  Currently ckan's delete works about as well as Ashley Madison's. 

Note that permanent delete is already implemented at cli level in ckan (there is paster dataset purge DATASET_ID) and api level for orgs and groups [for example](http://docs.ckan.org/en/ckan-2.3/api/index.html#ckan.logic.action.delete.group_purge).

**Comment by teodorescuserban** [comment]
Package delete api call is [here](http://docs.ckan.org/en/ckan-2.3/api/index.html#ckan.logic.action.delete.package_delete)

**Comment by mbellotti** [comment]
So, I've implemented dataset delete as dataset purge which was easy, but there's a catch: dataset purge does not remove files that have been uploaded, just the database row for the dataset.

Obviously this is not what we want, but we should probably talk about how we want to modify this. Is it something we want to modify in core for the ckan community or not?
