### ISSUE TITLE
Investigate the flame icon : views vs downloads

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3567]

**Comment by mbellotti** [comment]
Sorry I keep meaning to ask @danmihaila about this, and keep forgetting. I know we discussed this, but I cannot remember what exactly I'm investigating here?

Will finish it off this weekend :)

**Comment by danmihaila** [comment]
When having datasets list, we see flame. What means the value?
On dataset view page, the flame is sync with the value from bottom, continous browsing(downloads)
Also, What is the timeframe we calculate views/downloads?

Dan Mihaila

**Comment by mbellotti** [comment]
There are indeed page views, but the object it uses to determine where or not to display the flame icon has two options ("recent", and "total"). It makes sense to use recents to determine popularity, but better to display the total. Committed a change to this effect

**Comment by danmihaila** [comment]
I think this is ok, but we need to call it "downloads". You can check https://github.com/OCHA-DAP/hdx-ckan/issues/2799 and the commit related to 2799.
thanks
