### ISSUE TITLE
Dataset View Page: Adding icons

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3568]
This summarizes and will close issues #1593 and #2297.  

Add icons for dataset status (private, deleted) and for dataset properties (subnational, gallery item, quality checked, comparable, popular).  The mockups below (and specs to come) give show how it should look in different situations and some related changes (adding lines, adjusting heights).

For the private icon, use https://drive.google.com/open?id=0B24NBcgmV490VjFQMFRoZ3V3VXc
For deleted icon, use the default ckan (we are making it hard to get to these datasets and will soon be making deletion permanent, so the ugly icon is ok for now).

If the dataset title is too long to fit the status icons (private and/or deleted), they can break to a second line. 

![image](https://cloud.githubusercontent.com/assets/8006323/9907689/5566df68-5c5e-11e5-8c53-32c29a931f16.png)

![image](https://cloud.githubusercontent.com/assets/8006323/9747805/fd278106-564d-11e5-8290-e85f2bd08a4d.png)

![image](https://cloud.githubusercontent.com/assets/8006323/9747806/fd28f3b0-564d-11e5-8a22-c93056b7c4e5.png)

![image](https://cloud.githubusercontent.com/assets/8006323/9747809/fd2b8558-564d-11e5-9c3a-989a88e79ebc.png)

**Comment by yumiendo** [comment]
@danmihaila @aalecs below is the spec for the icon group - let me know if you have any Q !
the icon is same size as what we used on the search result page (15px height)
<img width="1384" alt="screen shot 2015-09-20 at 6 00 23 pm" src="https://cloud.githubusercontent.com/assets/8006323/9983252/154be446-5fc4-11e5-88c3-adb20965d0e3.png">
<img width="1382" alt="screen shot 2015-09-20 at 6 29 55 pm" src="https://cloud.githubusercontent.com/assets/8006323/9983247/15465f08-5fc4-11e5-8b09-f85b3c4692c4.png">
<img width="1384" alt="screen shot 2015-09-20 at 6 26 48 pm" src="https://cloud.githubusercontent.com/assets/8006323/9983248/15476a9c-5fc4-11e5-9d18-4ac3bb69c505.png">
<img width="1383" alt="screen shot 2015-09-20 at 6 24 51 pm" src="https://cloud.githubusercontent.com/assets/8006323/9983249/15477eba-5fc4-11e5-8fe0-39db4a3cacc8.png">
<img width="1378" alt="screen shot 2015-09-20 at 6 19 27 pm" src="https://cloud.githubusercontent.com/assets/8006323/9983250/1547c6a4-5fc4-11e5-96ff-d04a42005cbf.png">
<img width="1363" alt="screen shot 2015-09-20 at 6 02 48 pm" src="https://cloud.githubusercontent.com/assets/8006323/9983251/154b7678-5fc4-11e5-8b78-49d20ed94cf0.png">

**Comment by alexandru-m-g** [comment]
The button group on the dataset page seem to appear twice. For example here: https://test-data.hdx.rwlabs.org/dataset/afghanistan-admin-level-2-boundaries-blah
Check screenshot:
![buttons](https://cloud.githubusercontent.com/assets/6586348/10205687/537b9536-67cb-11e5-97cb-d217a91c575d.png)

**Comment by danmihaila** [comment]
@alexandru-m-g I think this is a problem with COD import as it is treated as indicator. check breadcrumb and the whole list of COD datasests

**Comment by danmihaila** [comment]
pinging @cjhendrix and @teodorescuserban

**Comment by danmihaila** [comment]
i looks it is triggered not by COD, but only when we have a geopreview. It should be a problem in geopreview template.

**Comment by alexandru-m-g** [comment]
@danmihaila Ok, so maybe this actually belongs in another ticket as it's own separate bug. We need to decide how we treat indicators that have geopreview ?

**Comment by danmihaila** [comment]
I think it is not this. i think it is a but how we display templates. will digg into this now.
