### ISSUE TITLE
Show all attributes in geopreview.

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3583]
Once #3370 is resolved, we can display all attributes in the geopreview.  At the moment, we only display string fields.

**Comment by cjhendrix** [comment]
I think this may have already been done.   @alexandru-m-g @aalecs ?

**Comment by alexandru-m-g** [comment]
I was looking for this ticket but couldn't find it. It was done here https://github.com/OCHA-DAP/hdx-ckan/issues/2932

**Comment by cjhendrix** [comment]
Great!  Thanks.  Closing.

**Comment by cjhendrix** [comment]
The integer attribute is not showing, at least for this dataset: 
https://data.hdx.rwlabs.org/dataset/dr-congo-contour-lines

![image](https://cloud.githubusercontent.com/assets/1654485/10604945/3fcd6b88-7728-11e5-9b9e-6d78e3be6fe7.png)

![image](https://cloud.githubusercontent.com/assets/1654485/10604966/54ff1bf0-7728-11e5-89c3-44f06b4707ae.png)

I think maybe we miscommunicated about this issue.  It's not a duplicate of #2932.

**Comment by alexandru-m-g** [comment]
Was showing only strings, integers and floats ( floats are actually converted strings because of some parsing issues that we had with ogr2ogr ) as I didn't want to show some weird blobs for example. 

Added "numeric" to the list now.
