### ISSUE TITLE
reset thumbnails to be accessed only by sysadmin

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3593]

**Comment by alexandru-m-g** [comment]
@danmihaila How should I test this  ? I went to https://test-data.hdx.rwlabs.org/organization?reset_thumbnails=true as a normal user but I didn't get any message.

**Comment by teodorescuserban** [comment]
I can help you check the thumbnails timestamp.:)

Mie, 30 sept. 2015, 23:24, Alexandru Gartner notifications@github.com a
scris:

**Comment by danmihaila** [comment]
We can reopen it. Right now there is no error message. By default ckan allows adding parameters but it will not throw errors. We could try test the api call or ... Write a nosetest 😀

Dan Mihaila
