### ISSUE TITLE
Review and add to GA events and custom dimensions

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3601]
We need to add some additional google analytics events, but first we want to review what we have.  

This issue is to work with CJ to do the following:
- [ ] Confirm that the existing events are still used in all the cases where we think the should be
- [ ] Brainstorm an event and custom dimensions structure for we want to add (both now and what we anticipate adding in the future)
- [ ] Add the events in code (at least for CODs, indicators, and country-centric indicators)

The test problem we want to implement for in this sprint is the following:

We want GA to be able to report how many downloads (at resource and dataset level) of CODs vs Indicators vs country-centric indicators.  Additionally, we want to see which user did the download.

**Comment by cjhendrix** [comment]
Issue updated based on conversation with @amcguire62 .

**Comment by danmihaila** [comment]
closed
