### ISSUE TITLE
Security issues: ckanext-hdx_theme

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3626]
sub-issue under #3618 
- [ ] check all our custom actions/api calls if they have/need auth
- [ ]  nosetest for our custom action

**Comment by alexandru-m-g** [comment]
I'm commenting out the hdx_get_sysadmins. It doesn't seem to be used anymore
@danmihaila you added it so let me know if there's some reason why we should keep it.

**Comment by alexandru-m-g** [comment]
Also changed hdx_get_shape_info() to not be an action anymore. It doesn't make sense to be called by itself.
