### ISSUE TITLE
Organization List: going to page 2 of search result loses the query

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3629]
To replicate:
1. Go to /organization
2. Search the org list for "ocha" (correctly loads https://data.hdx.rwlabs.org/organization?q=ocha)
3. Go to page two of the results (**incorrectly** loads https://data.hdx.rwlabs.org/organization?sort=title+asc&limit=25&page=2)  
4. Also note that it doesn't contain an anchor to scroll down to the dataset list (as we do with other simlar pages).

**Comment by danmihaila** [comment]
@mbellotti item 4 [Also note that it doesn't contain an anchor to scroll down to the dataset list (as we do with other simlar pages] is not completed. reopened

**Comment by mbellotti** [comment]
It was (
https://github.com/OCHA-DAP/hdx-ckan/commit/8de036515febadaff5fedeb2117f3e3d843592ef),
but there was a merge conflict on the template file between my changes and
Arti's (I think it was Arti) so it might have gotten overwritten by
resolving that. Will restore.

**Comment by danmihaila** [comment]
Ok, np

Dan Mihaila

**Comment by danmihaila** [comment]
@mbellotti please let me know when you make a new PR for this. We want to deploy to prod this week. thanks

**Comment by mbellotti** [comment]
Sure, it's in my newest batch of commits. Should I break it off into a
separate branch or will you deploy with 68?

**Comment by danmihaila** [comment]
Yes, it should be only this commit (for sprint 67) as it will be merged
into stag and prod today. dmihaila@dginternational.org

**Comment by danmihaila** [comment]
this is done and tested on stag, closing it
