### ISSUE TITLE
Ebola hotfix adding an extra layer

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3637]
Get new cases from https://raw.githubusercontent.com/BrcMapsTeam/Ebola-Web-Map/master/data/data.js
var NewConfirms = {"GIN001001":"0",....
and add it as the 1st top layer, in total there willl be 7 layers
Label: New cases last week 
Please do it as hotfix.

**Comment by alexandru-m-g** [comment]
I looked both on staging and prod and I don't see any "New cases last week " layer. There's one called "New confirmed cases" at the bottom but it's not the 1st.  @aalecs are there some other details that are not mentioned in the ticket ?
