### ISSUE TITLE
Popular / downloads icon inside dataset shows different figure than the one at the bottom of datasets

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#3651]
When visiting a dataset ([ebola-cases-2014](https://data.hdx.rwlabs.org/dataset/ebola-cases-2014)) the user now finds an icon on the left-hand side that shows the number of downloads that dataset has. That figure is different than the figure shown at the bottom of the dataset.

Figure at the top:
![screen shot 2015-10-01 at 10 20 03 am](https://cloud.githubusercontent.com/assets/953118/10223250/2d8dee2c-6826-11e5-9206-4a098275a93e.png)

Figure at the bottom:
![screen shot 2015-10-01 at 10 20 10 am](https://cloud.githubusercontent.com/assets/953118/10223255/32916e08-6826-11e5-8e32-4d27ba0148b4.png)

**Comment by danmihaila** [comment]
@luiscape do we want to display downloads or views? I guess right now it is displayed the number of views, but we could correlate it with the total number of downloads
pinging @cjhendrix to be aware of this

**Comment by luiscape** [comment]
@danmihaila That's a good idea. At this point I am interested in consistency. That is, if we show "downloads" on the footer it would be nice to have "downloads" in the hover as well.

Personally, I like the way it is: flame icon is about views and the footer is about downloads. I would just change the text of the hover to "views" instead of "downloads". Does that make sense?
