### ISSUE TITLE
Onboarding: reset password

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3667]
For users which are not validated, when doing the reset password it should send again the validation token.
For users which are valid, it should reset the password (current process).
Question: what about the deleted users?

**Comment by danmihaila** [comment]
@mbellotti requirement no 1 is not done. Reopening it

**Comment by danmihaila** [comment]
in tokens.py:57 there is missing an import for "hdx_mailer"
can you please fix it asap? tnx

**Comment by mbellotti** [comment]
Done

**Comment by danmihaila** [comment]
Reopened. When user is not valided and I am trying to perform a password reset:You have not yet validated your email.
