### ISSUE TITLE
custom org: uploading the two logos fails

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3678]
Same on stag and prod v0.11.15.11
1. Create a new org
2. Make it custom
3. Set both logos to upload a file
4. Save
5. Logo is not displayed (see screen cap below)
6. Edit the org
7. Set both logos to upload a file (again)
8. Save
9. Server error returned.

![image](https://cloud.githubusercontent.com/assets/1654485/10306590/6d45ec8a-6c28-11e5-8d14-6e57e8ac8763.png)

**Comment by cjhendrix** [comment]
Note that uploading the logos one at a time works normally.

**Comment by danmihaila** [comment]
assigned to @mbellotti for current sprint

**Comment by danmihaila** [comment]
I am trying to click on "upload" button and javascript popup is not working. Reopening it.

**Comment by danmihaila** [comment]
@alexandru-m-g can you fix this asap?
