### ISSUE TITLE
Add Members:  difficult to find user unless username is known or obvious

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3679]
When adding an existing user to an org, you have to either know or guess the username.  Perhaps we should also display user names (and possibly emails?)to make it easier to select the user?  

This comes from a real-world case of trying to add someone named "Djimadji Constant Djimet Sou" to an org.  Her (his?) username is "djims".  If I hadn't known about the search bar on /user (which we don't advertise anywhere on the site), I wouldn't have been able to add him.  Searching by email in the "add existing user" modal doesn't work.

**Comment by mbellotti** [comment]
@cjhendrix How often do we get new users now? The feature you're suggesting is best implemented with a new Solr core, or in a pinch we can use the same trick we used with lunr.js for predictive search. But that wouldn't be ideal if we expected to see a larger number of users joining.

**Comment by cjhendrix** [comment]
Organisations and members seem to be a relatively popular feature (anecdotally), but I haven't heard specific user complaints about this. 

I wouldn't expect a massive increase in users joining, so maybe the lunr.js fix would be ok.  @amcguire62 @danmihaila ?

**Comment by cjhendrix** [comment]
This did come up at the IMPACT training in Cape Town.  Here are my notes about it: 

When adding a member to an organization, a few users tried the emails first.  However this field doesn’t search for emails, only display name and user name.   Because they were logging in with email, email seemed the natural thing to search for them.  Most were able to solve this on their own by searching for the person's name.  But in one case (that I noticed), the user’s display name was obscure, meaning that they couldn’t be found.

**Comment by cjhendrix** [comment]
I'm running into this again managing two collaboration orgs.  The user request email comes to me with the email, but not the user name.  However the add user dialog only works with user names.  

A quick fix would be to add the user name to the email we send when a new request is made.

**Comment by cjhendrix** [comment]
Ok, I see the name now (thanks @alexandru-m-g).  I still find the format a bit messy, but the important info is there if a user reads through it.  Closing.
