### ISSUE TITLE
capture js test is failing on travis

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#3688]
I tested and the file is indeed created. The only problem is that the test is occurring faster than capturejs can complete.
There needs to be a pause between the capturejs task and the test itself.
We didn't had problems running it outside of travis.
This is a blocker for #3664 
Assigning @danmihaila to decide what to do.

**Comment by danmihaila** [comment]
we will probably need to change the test to run method sync or to add a delay.
pinging @mbellotti as she wrote the code and test.
