### ISSUE TITLE
Not all private datasets get lock icon

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3691]
I just added two new datasets to staging (via api).  Both are private, however only one gets the lock icon.

Icon: https://test-data.hdx.rwlabs.org/dataset/chad-roads
No icon: https://test-data.hdx.rwlabs.org/dataset/chad-administrative-boundaries

**Comment by danmihaila** [comment]
I think one has geo preview, and one is only dataset. I will add it to current sprint with high priority.
