### ISSUE TITLE
Some files download, some files redirect to log in

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3694]
On stag (works normally on prod):
1. Login as a sysadmin
2. go to https://test-data.hdx.rwlabs.org/dataset/a-test-dataset-with-large-files
3. try to download each file

Resources 1-4 and 7 work for me
Resources 5 and 6 redirect to login.

Note that all these were present on production and brought over with the database. 

I'm seeing similar behavior on newly created datasets with filestore resources also.

**Comment by teodorescuserban** [comment]
Only zip files, right?

Lun, 12 oct. 2015, 16:53, cjhendrix notifications@github.com a scris:

**Comment by cjhendrix** [comment]
the fifth resource is a text file.

**Comment by teodorescuserban** [comment]
All redirects to login when trying to download private zip or images are related to a misconfig in varnish container that has been fixed on production but not on staging.

Fixed & closing.

**Comment by danmihaila** [comment]
@teodorescuserban I see again this issue on staging
https://test-data.hdx.rwlabs.org/dataset/a-test-dataset-with-large-files
try a zip one:
http://test-data.hdx.rwlabs.org/dataset/2be86412-ed82-41a4-8606-7994453e4de5/resource/960152e1-bfbe-4e08-b429-5b732e797333/download/africa-adm2-multipoly-gadm-shp.zip

**Comment by teodorescuserban** [comment]
please confirm it works now.
closing.
