### ISSUE TITLE
Performance: Organizations with Lots of Datasets Take a Long time to Load

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#3704]
When visiting the following organizations:
- [HDX](http://data.hdx.rwlabs.org/organization/hdx)
- [OurAirports](https://data.hdx.rwlabs.org/organization/ourairports)
- [UNOSAT](https://data.hdx.rwlabs.org/organization/un-operational-satellite-appplications-programme-unosat)

I have noticed serious response times -- on the magnitude of 20 seconds. The browser hangs waiting a response from the server for that long. HDX is the one with the longest wait times from the list above. 

I am not sure if issues are related to my network infrastructure, but the comparison between the HDX organization and other organizations is happening under different circumstances (i.e. different machines, different networks). 

I just wanted to report the issue.

**Comment by danmihaila** [comment]
great feedback. we will check it to see how it loads on different aspects. HDX has many datasets, but OurAirports and UNOSAT took about 3-4 secs to load. Anyway, we will check this
