### ISSUE TITLE
HDX views: create the CHART (bar,line) view

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3718]
Access allowed to sysadmin (for the moment)
A sysadmin will be allowed to add a hdx CHART view for a resource. First iteration will be to display a simple chart with only one source.
Admin fields needed:
Title, 
Data Type (bar chart, line chart), 
X Axis Label, 
X Column,
Y Axis Label, 
Y Column,
Source, 
Data Link URL, 
Label

**Comment by alexandru-m-g** [comment]
AS discussed with @danmihaila this should be similar to the Mali page.
