### ISSUE TITLE
Test load after changes re filters

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3731]
url to be tested:
http://test-data.hdx.rwlabs.org/dataset/
http://test-data.hdx.rwlabs.org/organization/wfp
http://test-data.hdx.rwlabs.org/search
http://test-data.hdx.rwlabs.org/search?q=&tags=cod
http://test-data.hdx.rwlabs.org/group/mli
http://test-data.hdx.rwlabs.org/group/nepal-earthquake

Same for prod

**Comment by danmihaila** [comment]
@teodorescuserban any feedback on this one?

**Comment by teodorescuserban** [comment]
@danmihaila actually it looks a bit better or the same.
You should be abel to notice the difference between prod and stag - both are underloaded at the moment.

**Comment by teodorescuserban** [comment]
Closing. You are welcome to reopen or comment.
