### ISSUE TITLE
Geopreview: geojson service not previewing

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3747]
The resource here https://data.hdx.rwlabs.org/dataset/mexico-volcanes-activos is a geojson service.  Downloed, the data looks fine (in qgis), but with the "geojson" file type, it doesn't preview. 

I noticed that the service delivers a file called simply "geojson", so maybe the naming is a problem?

**Comment by danmihaila** [comment]
@cjhendrix I changed the type to geojson on staging and it looks good: https://test-data.hdx.rwlabs.org/dataset/mexico-volcanes-activos
I am not sure this is an issue anymore if we change resource type from json to geojson
