### ISSUE TITLE
Should this file have exceeded our upload limits?

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3748]
https://data.hdx.rwlabs.org/dataset/mexico-continuo-de-elevaciones-mexicano

It is a zip file containing several rar files.

**Comment by danmihaila** [comment]
@cjhendrix do we have an update on this file? it looks like a broken external link right now.

**Comment by cjhendrix** [comment]
Yes, file is broken.  Closing for now.
