### ISSUE TITLE
Feature server showing up in Google Rankings

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3754]
![image](https://cloud.githubusercontent.com/assets/1654485/10787461/627cd674-7d71-11e5-994d-22a97c4ded5b.png)

**Comment by teodorescuserban** [comment]
It looks like a bug in the default container configuration that would disable http basic auth.

I will fix it today.

I would also create a default `robots.txt` file with the following content:

```
User-agent: *
Disallow: /
```

In the end, by default, you will need a password to enter test sites (again) + bots would be prevented anyway from crawling the site.

Special care must be taken to replace `robots.txt` with the current customized vesion when deploying to prod (we kinda want robots to index our site - not all but some areas)

maybe we should also revisit the current `robots.txt` site on our hdx-ckan to make sure the indexing robots access is done as we want to:

```
User-agent: *
Disallow: /dataset/rate/
Disallow: /revision/
Disallow: /dataset/*/history
Disallow: /api/

User-Agent: *
Crawl-Delay: 10
```

**Comment by danmihaila** [comment]
@teodorescuserban can you please check if you add your changes. I think for our prod server we should NOT have the reject of user-agents.
@cjhendrix can you please check if feature-data is still on google? I tried and don't see it anymore

**Comment by cjhendrix** [comment]
No, I don't see it.

**Comment by danmihaila** [comment]
closing it
