### ISSUE TITLE
Layout errors on Preview Page

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3755]
![image](https://cloud.githubusercontent.com/assets/1654485/10787484/8d2839d6-7d71-11e5-8ffd-ab1b3f2354c5.png)

**Comment by danmihaila** [comment]
@cjhendrix I think this is fixed. can you confirm and close this one?

**Comment by cjhendrix** [comment]
Yep,  fixed.
