### ISSUE TITLE
Caching improvements

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3756]
Lets see how we can improve some pages. Brainstorm with dev team needed and to compare with other websites.

**Comment by teodorescuserban** [comment]
It has been decided to enable the following:
1. /fanstatic cached in the browser for 1 month and on nginx for 6 hours.
2. /fonts same as above
3. /images 1 day and 1 day on server cache

On staging I will just make them all 5 minutes for client and 10 minutes for server to test.

**Comment by danmihaila** [comment]
@teodorescuserban can you please update the status of this issue? we should have a call when this is complete to check the improvements.

**Comment by teodorescuserban** [comment]
in testing. will notify you when all good.

**Comment by teodorescuserban** [comment]
On staging (test stack) you can test against the following files:

```
/fonts/Gotham_OTF/Gotham-Bold.otf
/fanstatic/hdx_theme/:version:2015-12-14T13:52:05.47/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff
/images/homepage/logo-ocha.png
```

The expire is set to 7 minutes (just to make it strange enough). 
One you test it and confirm all green, I will change the duration as specified in this ticket and commit to a new nginx image.

Tag @danmihaila

**Comment by danmihaila** [comment]
this is done and will be deployed to prod
