### ISSUE TITLE
Edit dataset: tags and locations are displayed ugly

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3768]
![screen shot 2015-11-03 at 12 40 57](https://cloud.githubusercontent.com/assets/3865844/10906223/66065110-8228-11e5-8d2c-cd718783cfac.png)
@yumiendo @amcguire62 do we plan to also change the edit datasets? if yes, maybe it doesn't make sense to fix this issue.

**Comment by yumiendo** [comment]
those location tags are reused in the new contribute flow - so maybe if we fix it we'll be able to reuse? 
- add margin-bottom 20px. 
- the location name shouldnt be broken up into 2 lines (not sure how you call this fixes...)
