### ISSUE TITLE
Share url

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3771]
Sharing via our buttons(for a dataset) is working for google+ and twitter but not working for Facebook and email. It is sharing the homepage (or the old xxxx string)

**Comment by alexandru-m-g** [comment]
@danmihaila I have committed a fix for this but this part actually needs to be rewritten. 

We need to change the shortening process because right now there are a few race conditions. Best to be included in the next sprint.
