### ISSUE TITLE
Dataset Preview: Text preview window has become very small

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3787]
![image](https://cloud.githubusercontent.com/assets/1654485/10944203/4bdbd008-8318-11e5-944c-1784c8e356dc.png)

**Comment by danmihaila** [comment]
moving this one to next sprint (low priority)

**Comment by danmihaila** [comment]
not an issue anymore. @cjhendrix please reopen if you can reproduce it.
<img width="1440" alt="screen shot 2016-05-04 at 13 27 04" src="https://cloud.githubusercontent.com/assets/3865844/15011697/f26c43cc-11fb-11e6-9b82-ad1f03e92dec.png">
