### ISSUE TITLE
Freaky!  Seeing different membership info in an org depending on login

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3789]
![image](https://cloud.githubusercontent.com/assets/1654485/10944952/d3e3a112-831b-11e5-8e44-05e94e2810fa.png)

**Comment by danmihaila** [comment]
i think there were 2 different url checked: https://test-data.hdx.rwlabs.org/organization/members/ocha-bgss and https://test-data.hdx.rwlabs.org/organization/members/ocha-bgss1 :)
ping @cjhendrix  I think we can close this

**Comment by cjhendrix** [comment]
D'oh!
