### ISSUE TITLE
Custom pages: pages module

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3803]

**Comment by alexandru-m-g** [comment]
@teodorescuserban @danmihaila 
There will be a new table for custom pages that can be created like this:
`paster hdx_pages initdb -c /srv/prod.ini` from within the hdx_pages folder/extension

**Comment by teodorescuserban** [comment]
Ok.

Joi, 12 nov. 2015, 19:57, Alexandru Gartner notifications@github.com a
scris:
