### ISSUE TITLE
Resource download fails due to too many redirects

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#3812]
A download did not work because of too many redirects (Chrome ERR_TOO_MANY_REDIRECTS)
Notice the http instead of https in the url field in the output from the resource_show api for the resource below. This is an issue on prod.
{
help: "https://data.hdx.rwlabs.org/api/3/action/help_show?name=resource_show",
success: true,
result: {
resource_uploader: "marindi",
cache_last_updated: null,
package_id: "3a755454-a3c8-49ed-a30a-0cf2c658fd69",
webstore_last_updated: null,
datastore_active: false,
id: "1913313e-0417-488d-98c2-adf90e47c542",
size: null,
state: "active",
shape_info: "{"error_class": "TooManyRedirects", "layer_id": "pre_1913313e_0417_488d_98c2_adf90e47c542", "error_type": "None", "state": "failure", "message": "Exceeded 30 redirects.", "type": "unknown"}",
hash: "",
description: "Admin COD datasets for BFA endorsed by RO on October 2015; see metadata for description of cleaning and processing performed by ITOS.",
format: "Zipped shapefile",
tracking_summary: {
total: 0,
recent: 0
},
last_modified: null,
url_type: "api",
mimetype: null,
cache_url: null,
name: "bfa_pplp_nga.zip",
created: "2015-11-10T13:05:16.756681",
url: "http://data.hdx.rwlabs.org/dataset/3a755454-a3c8-49ed-a30a-0cf2c658fd69/resource/1913313e-0417-488d-98c2-adf90e47c542/download/bfa_pplp_nga.zip",
webstore_url: null,
mimetype_inner: null,
position: 0,
revision_id: "47ab1b28-140b-4d1c-ab66-c3a4b6e181f6",
resource_type: "file.upload"
}
}

**Comment by danmihaila** [comment]
will check it

**Comment by takavarasha** [comment]
We had another occurance of this issue today, affecting another dataset and was resolved by re-uploading the file. https://data.hdx.rwlabs.org/dataset/mrt-settlements

**Comment by danmihaila** [comment]
Now it is working. as I said, but probably we need more tests, the file
might have a lock (it can not be used) until it is fully uploaded &
unlocked by gis worker/bot

_Dan Mihaila_, IT Consultant
(M) +40 722 502 304 • (GTalk) dan.mihaila@gmail.com • (Skype) carcotelul
• (Twitter) dan_mihaila • (Yahoo) carcotelul
  dmihaila@dginternational.org

**Comment by takavarasha** [comment]
Thanks. I will ask user not to fix if it happens again but just to make the
dataset private so you guys can have a look.

**Comment by danmihaila** [comment]
excellent, thanks

_Dan Mihaila_, IT Consultant
(M) +40 722 502 304 • (GTalk) dan.mihaila@gmail.com • (Skype) carcotelul
• (Twitter) dan_mihaila • (Yahoo) carcotelul
  dmihaila@dginternational.org
