### ISSUE TITLE
organization/wfp shows me logged out even when I'm logged in

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#3815]
Steps to reproduce ( tried in Firefox - both Linux and Mac ):
1.  Make sure you are logged out of hdx
2.  Go to https://data.hdx.rwlabs.org/organization/wfp
3.  Click on `log in` and enter username and password. You'll see the dashboard and you are logged in.
4.  Then type again in the URL bar: https://data.hdx.rwlabs.org/organization/wfp

**Comment by alexandru-m-g** [comment]
@teodorescuserban I was thinking that it might be some server configuration issue so I added the following screenshot. Maybe it's helpful.
![wfp](https://cloud.githubusercontent.com/assets/6586348/11094149/c42e22da-8896-11e5-984e-67926f326109.png)

**Comment by teodorescuserban** [comment]
I am having hard time to find out when and what was the ticket number, but there is a specific caching configuration for `/organization/wfp` and `/group/nepal-earthquake` that cache the pages at nginx level for 5 minutes.
You can also check out your nginx docker in `/etc/nginx/includes/ckan-cache-adjust.conf`

**Comment by teodorescuserban** [comment]
@alexandru-m-g, @danmihaila we can change it, tune it etc. :)
just let me know.

**Comment by teodorescuserban** [comment]
I will decrease the caching time to 1 minute, as per @danmihaila recommendation.
