### ISSUE TITLE
Recover password input is case sensitive

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3824]
We probably don't want it to be case sensitive, at least for emails.

**Comment by brew** [comment]
The local part of an email address _can_ be case sensitive [1], though many email providers and services choose not to allow it.

CKAN (and HDX-CKAN) however, does allow case sensitivity in emails when registering. So, MyEmail@example.com and myemail@example.com can both be registered as different accounts. 

Has there been a problem for users with the password recovery form?

If we were to do something about this here, we'd also want to ensure a case insensitive unique check was performed on newly registered emails.

[1] https://en.wikipedia.org/wiki/Email_address#Local_part

**Comment by cjhendrix** [comment]
It's only happened once as far as I know, and the user (me) figured it out immediately.  So I don't think it's a big problem.  

I only raised it as an issue because it seemed unusual for an email to be case sensitive. But now that you've educated me on that one, I guess we should keep to the standard and retain case-sensitivity on the local part.  

I'll close, but we can reopen if someone disagrees.

**Comment by danmihaila** [comment]
lets reopen it, I just had a call with Brook and he will fix it.

**Comment by brew** [comment]
I think I understand now...

Because email is being used as a unique identifier, we need to ensure email is unique in a case insensitive way through-out the application. So I need to check new user registration, edit user profile, current user values, and also user input for login and password recovery. All of these should be transformed to lowercase.

**Comment by amcguire62** [comment]
Once we decide on how we fix this - can we also incl some "on hover" text to support the user by explaining what we are doing here.

**Comment by danmihaila** [comment]
yes, basically the any uppercase letter is transformed into lowercase as any email address is working in other live systems. 
@yumiendo where can we add such an explanation ?

**Comment by brew** [comment]
Do we need an explanation? We're handling the transformation and are not expecting the user to do anything.
