### ISSUE TITLE
Custom org: upload of organisation logo not working on production

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#3830]
The logo upload for custom org logos is not working on production.
No error message is generated.
After the upload, image_rect and image_sq fields in the organization's customization extra are blank. We would expect to see a value like timestamp+image_file_name in those fields.

{value: "{"use_org_color": "true", "image_rect": "", "image_sq": "", "topline_resource": "", "highlight_color": "#ff6600"}",
state: "active",
key: "customization",
revision_id: "de24307c-f47f-42f7-99eb-5246c81ba7ac",
group_id: "dea2e027-6227-474e-aaef-78f121d3e677",
id: "6cf0502f-8d4a-4361-8b2d-3ea45cc01d8a"}

**Comment by danmihaila** [comment]
@takavarasha this is done by @alexandru-m-g . Will be pushed as hotfix on prod today I hope
