### ISSUE TITLE
Popular/downloads/views - align the terminology and dispay consistent results

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3839]
related to #3826 and #3684
![2](https://cloud.githubusercontent.com/assets/3865844/11332561/5db6648a-91cf-11e5-8997-a50590b3b580.gif)
![1](https://cloud.githubusercontent.com/assets/3865844/11332562/5db74e72-91cf-11e5-8910-22cb95401be3.gif)

**Comment by brew** [comment]
Fixed in #3872.
