### ISSUE TITLE
Zoom issue with filters

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3842]
This is on production in Chrome, Win8, zoom 125%

![image](https://cloud.githubusercontent.com/assets/1654485/11342716/0ab1a396-9209-11e5-99cf-31aca897f535.png)

**Comment by danmihaila** [comment]
@cjhendrix can you please test this on staging and mark it with TestedSTAG ? From my computer looks good, but I wanted to double check with you.

**Comment by cjhendrix** [comment]
working!
