### ISSUE TITLE
Change /cod to use the filter checkbox instead of tag

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3843]
The /cod redirect currently filters by tag, but it might be help educate users to have it use the checkbox instead.

**Comment by teodorescuserban** [comment]
I need the exact url to redirect to.

**Comment by danmihaila** [comment]
@cjhendrix pls correct me if I am wrong but link should be
https://data.hdx.rwlabs.org/search?q=&ext_cod=1

**Comment by cjhendrix** [comment]
Yes, that's it.  However with that link the filter panel isn't open.  Could we have that open as well?  I think that's what @yumiendo would want since that is the current behavior.

**Comment by yumiendo** [comment]
agree with CJ -
the link you pasted https://data.hdx.rwlabs.org/search?q=&ext_cod=1 is technically a filtered view - so can we expose the filters with COD checkbox checked?

**Comment by danmihaila** [comment]
no, because it will be 2 search boxes displayed :)

**Comment by yumiendo** [comment]
spoke with sarah briefly - 

(proposed fix)
when user goes to /cod 
- change COD tag to checkbox (checked)
- with filter exposed (so users are aware its filtered view, sarah is ok with 2 search bars exposed)

(in the future - not top priority but in the list of future development)
- we might do a special page for /cod that includes interactive map/key figures.

@amcguire62 including aidan so he is in the loop.

**Comment by danmihaila** [comment]
/cod is going to filter but the checbox is not checked!
@teodorescuserban can you check the redirect url
https://data.hdx.rwlabs.org/search?q=&ext_page_size=25&sort=title_case_insensitive+asc&tags=cod&ext_cod=1#dataset-filter-start

**Comment by teodorescuserban** [comment]
closing
