### ISSUE TITLE
Dataset Lists: Styling problem on filter drop downs

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3848]
I would swear we have an issue for this already, but I couldn't find it.

![image](https://cloud.githubusercontent.com/assets/1654485/11364290/bd07cf84-929f-11e5-9d91-03f0fd9d1efd.png)

**Comment by danmihaila** [comment]
yes, and it was fixed at a moment. we tested with locations and organizations. it was on windows only I think or non-mac systems

**Comment by danmihaila** [comment]
this will have to be tested in a non MacoS env

**Comment by danmihaila** [comment]
@cjhendrix can you please test this as well . for me is ok

**Comment by cjhendrix** [comment]
Working for me.
