### ISSUE TITLE
Organization Search: organizations not found

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3893]
On demo, these 4 organizations exist: 
- Demo - Cluster A
- Demo - Cluster B
- Demo - Cluster C
- Demo - Cluster D

However, in the organization search bar on /organization,  searching for them by name doesn't find them.  Searching "demo"  or "cluster" works, but searching "demo cluster a" or "demo - cluster a" does not. 

Searching for other multi-word orgs like "ocha dr congo" for example, works.   Maybe something to do with the hyphen?

**Comment by danmihaila** [comment]
Did you check if they show in filters?

**Comment by cjhendrix** [comment]
They are all there, but some of them disappear as you type more: A and D disappear

![image](https://cloud.githubusercontent.com/assets/1654485/11527508/1e378e98-98ea-11e5-8040-af1a96ad12fe.png)

**Comment by aalecs** [comment]
@cjhendrix Can you give me a link to the demo server? I can't find the orgs on prod/stag.

**Comment by aalecs** [comment]
@cjhendrix - it might have to do with the fact that the datasets assigned to cluster A and D are not pulbic.
I did a test with 3 orgs named as you suggested and it works in all cases and the search isn't case sensitive.

Unless you can still reproduce the issue, we can close this ticket.

**Comment by cjhendrix** [comment]
D'oh!  That private-not-in-search thing keeps catching me out.  I hate that!  I'm sure it's just as confusing to our users with private data, but we already have an issue for that somewhere. Closing this one.
