### ISSUE TITLE
Dataset Edit:  confusion between "edit" and "update" buttons

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3905]
It’s difficult to find how to add an additional resource.  Everyone went to the update button on the first resource which led them to overwrite the existing resource rather than add a new one.   Many didn’t think the “edit” button was part of the dataset, but part of something “higher” in the hierarchy.  Even once on the edit page, it’s not obvious to go to the resources tab to add a resource.  

The latter problem is resolved by the new contribute flow. However, I also suggest:
1. adding a "add more" button underneath the resources on dataset view, perhaps vertically aligned with the "update" buttons.

**Comment by cjhendrix** [comment]
I'm adding this to sprint candidates since it may make sense to consider it along with the contribute/edit flow work that is ongoing.

**Comment by danmihaila** [comment]
@cjhendrix is this a valid issue? i am closing it
