### ISSUE TITLE
New Contribute Flow: Loading images & icons

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3928]
Show animated loading image during upload & icons for file type

**Comment by alexandru-m-g** [comment]
Things that still need to be done here: 
-  [x] icons for file types
-  [ ] there's a moment when the page turns gray before the contribute flow starts loading after click on edit/add dataset. This is a new req but we should probably show something there as well.

**Comment by alexandru-m-g** [comment]
Closing this after discussion with @danmihaila
