### ISSUE TITLE
New Contribute Flow: Reorder the resources and Drag&Drop [Research]

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3930]
Research about how to reorder resources, drag&drop. If it is easy lets implement it, if not lets write down the result of the research and we will implement in the next sprint
In default CKAN the reordering is enabled and is working well. Maybe this should be a starting point.

**Comment by danmihaila** [comment]
@aalecs i think there is a bug in FF (macos) when dragging: the dragged resource is previewed far in the right side. Maybe it is only a FF issue

**Comment by brew** [comment]
Syncing drag n drop reordering with the server is done as part of #3980 and #3970.
