### ISSUE TITLE
New Contribute Flow: validate the labels&text of the form

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3931]
Check all form labels for mistakes and update the full text on left column

**Comment by aalecs** [comment]
@danmihaila while working on this I found a set of missing items, mostly texts. I made a list in the format "section - item - reason":
- Dataset title & description -  "Dataset's quality has been confirmed" - tooltip missing
- Metadata - section description missing
- Metadata - Maintainer - placeholder missing
- Metadata - Location - placeholder missing
- Metadata - License - placeholder missing
- Metadata - Update frequency - tooltip missing - is there any ?
