### ISSUE TITLE
New Contribute Flow: Resource name appears twice

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3976]
Resource name appears twice (for uploaded file). 
For files (as opposed to URLs) the URL should be hidden as in mockup

**Comment by brew** [comment]
For clarity: For uploaded files, the filepath should be hidden, but for URLs the URL is visible.

**Comment by brew** [comment]
URLs from cloud services shouldn't be hidden when adding them.
