### ISSUE TITLE
New Contribute Flow: resource numbering is not working well

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#3980]
when deleting and reordering the numbers of resources are not updating/refreshing
![screen shot 2016-01-05 at 11 20 22](https://cloud.githubusercontent.com/assets/3865844/12111497/71209d6a-b39e-11e5-87f0-e224d0febcf9.png)

**Comment by brew** [comment]
Check reordered position numbers are being saved to the server.
