### ISSUE TITLE
Org membership request emails use org id instead of title

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3982]
This is an email from a real org on production.  

Links to the org (both work):
http://data.hdx.rwlabs.org/organization/cfc78fd0-4a2c-4338-a68f-49e4635ee335
http://data.hdx.rwlabs.org/organization/rimwg-e

![image](https://cloud.githubusercontent.com/assets/1654485/12112430/cdb1da6e-b39c-11e5-923b-3bf68e8f7e21.png)

**Comment by alexandru-m-g** [comment]
This was changed in #3948 .
