### ISSUE TITLE
New Contribute Flow: Update frequency list should specify that the number is in days

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#4003]
From @cjhendrix 
Update frequency list could be a bit more human friendly.  At least we should specifiy that it is in days.  At best we could use days/weeks/months as appropriate.
@takavarasha @luiscape can you comment re this issue?
![screen shot 2016-01-20 at 11 17 46](https://cloud.githubusercontent.com/assets/3865844/12444402/7adcbf08-bf67-11e5-8bbb-34dd91be4d96.png)

**Comment by takavarasha** [comment]
My understanding is that the user should be presented with the following 9 options:
Never
Every day
Every week
Every two weeks
Every month
Every three months
Every six months
Every year
Other

Below are the values that should be saved based on what the user has selected:
Never ==> Save the value 0
Every day ==> Save the value 1
Every week ==> Save the value 7
Every two weeks ==> Save the value 14
Every month ==> Save the value 30
Every three months ==> Save the value 90
Every six months ==> Save the value 180
Every year ==> Save the value 365
Other ==> Save the value entered by the user

When the user selects the "Other" option, they are presented with a text box to enter the frequency in number of whole days greater than or equal to zero. A maximum value had not been discussed and should not be enforced at this time.

**Comment by danmihaila** [comment]
ok. I will implement the values as they were now except Other as this is a new request. My advice is to use the predefined values otherwise we will end with user writing "two weeks and half" and we need to translate what user is entering in other option into values as he/she currently sees some text and not numbers.

**Comment by takavarasha** [comment]
The value entered in other must be a whole number greater than 0.
