### ISSUE TITLE
New Contribute Flow: Resource validation

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4022]
Screenshot attached.
- [x] The validation string numbering is starting from 0 and the errors are displayed for a different resource. It should say error resource 3 instead of 2

![screen shot 2016-02-01 at 11 11 48](https://cloud.githubusercontent.com/assets/3865844/12712995/d2b45b48-c8d4-11e5-8111-f7bc97c401e5.png)
- [ ] In case user is clicking on add more resource button, but it is not entering anything in form the system will trigger an error. is it ok?

**Comment by alexandru-m-g** [comment]
If a resource form is empty the server side validation of that resource will fail. Let me know if this needs to be changed.
