### ISSUE TITLE
New Contribute Flow: Resources issues

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4023]
- [x] When adding a new resources of type "url" there are 2 fields called "File name" and user doesn't know where to place the "url"
- [ ] Trying to not put a format for an url and I am getting an error saying format is missing. 
  Pls note that the error message is for resource x+1
  ![screen shot 2016-02-01 at 11 19 17](https://cloud.githubusercontent.com/assets/3865844/12713234/17676950-c8d6-11e5-9016-aaefb9daa7fa.png)

**Comment by alexandru-m-g** [comment]
Usually the server manages to guess the format if the format field is empty. You'll get a validation error if that didn't succeed.
