### ISSUE TITLE
HDX Views and Downloads: dataset list page

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4030]
We decided  to split “Popular” into “Trending”(short-term traction) and “Most downloads” (long-term traction) to make sure new/old datasets are treated fairly. 
- Hover on flame icon for “Trending" (measured by recent views without showing the number which confuses everyone)
- Next to flame icon - display rounded up/significant number of downloads (i.e. 10000+ downloads, 5000+ downloads, 1000+ downloads, etc. this can be determined by the team). Values could be: 10,100, 200, 500, 1000, 2000, 5000, 10000.

<img width="1280" alt="datasetlist" src="https://cloud.githubusercontent.com/assets/3865844/12746143/de672e26-c9a5-11e5-92a8-b207d9b06f59.png">

**Comment by alexandru-m-g** [comment]
@danmihaila @yumiendo So when should the trending icon appear ? What's the threshold ( in dataset views ) ?

**Comment by yumiendo** [comment]
I learned from @danmihaila that 10 views of dataset page makes it 'trending' - so lets keep that the same.

**Comment by alexandru-m-g** [comment]
The commit https://github.com/OCHA-DAP/hdx-ckan/commit/6d9724ca14c35bddc668db31c109f18bc702e1c4 is actually related to this ticket. Wrong commit message.
