### ISSUE TITLE
HDX Views and Downloads: dataset view page

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4031]
We decided to split “Popular” into “Trending”(short-term traction) and “Most downloads” (long-term traction).
- hover on flame logo for “Trending” (without showing number)
- (next to the flame/trending icon) display rounded up/significant number of downloads (i.e. 1000+ downloads, 100+ downloads etc) 
- total number of downloads will be displayed at the bottom in the continuous browse. 
  ![dataset_popular](https://cloud.githubusercontent.com/assets/3865844/12746270/6817abaa-c9a6-11e5-99b7-00f784a435fc.png)

**Comment by alexandru-m-g** [comment]
I've committed the change for this. Isn't it weird that on the same page the user can see both something like 200+ and the real number which can be like 999 ?

Ex in screenshot below:
![1](https://cloud.githubusercontent.com/assets/6586348/12977562/18d0678c-d0d4-11e5-9c88-53081ec37d03.png)
![2](https://cloud.githubusercontent.com/assets/6586348/12977563/18d86bd0-d0d4-11e5-8a0a-782731deebb5.png)

@yumiendo @danmihaila what do you think  ?

**Comment by yumiendo** [comment]
Hi alex, why is the total roundup number(in this case 200+) much smaller than the actual downloads (447)?? shouldn't the round up number be 400+?

**Comment by alexandru-m-g** [comment]
@yumiendo i thought the thresholds are the ones specified in #4030. If I should use other ones please let me know.

**Comment by yumiendo** [comment]
oh im sorry... Iooks like I didn't call out all numbers(threshold) in the example and caused confusion.
can we include all the in-between numbers...
10,20,30,40,50,60,70,80,90,
100, 200, 300, 400, 500, 600,700,800, 900
1000,1100, 1200,1300,1400, 1500,1600,1700,1800,1900,
2000, 2100, 2200,2300,2400,2500,2600,2700,2800,2900,
same goes for 3000....9900
10000, 11000,12000.....

**Comment by alexandru-m-g** [comment]
commit https://github.com/OCHA-DAP/hdx-ckan/commit/cc2f502a24f9a67a2555fea303ff57b60155b4c2 is actually related to #4067  (sorry)
