### ISSUE TITLE
New contribute flow: Horizontal scrollbar showing

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#4038]
I tested in Linux - Firefox and Chrome in FullHD, and in Windows in Firefox:
![scrollbar](https://cloud.githubusercontent.com/assets/6586348/12813794/0d469918-cb43-11e5-8988-e077686ae36b.png)
Notice the scrollbar at the bottom

**Comment by danmihaila** [comment]
ref https://github.com/OCHA-DAP/hdx-ckan/commit/0d2f6315c9102031fd57ad0f2fc7acad2a8ee42b
