### ISSUE TITLE
New Contribute Flow: Multi-line text/textarea field scroll not working in Chrome

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4041]
When trying to scroll up to the top of text field (after adding lengthy description or caveat etc) the whole page scrolls up instead of text field.
write a long paragraph in text field > try to scroll up to the top of text field > the page moves
<img width="622" alt="screen shot 2016-02-04 at 14 29 25" src="https://cloud.githubusercontent.com/assets/3865844/12814963/c80c6b12-cb4b-11e5-8172-634a5cadfc68.png">

**Comment by aalecs** [comment]
Seems the problem is because the whole content is inside an iframe. I didn't find a solution in a short time, should we spend more time on this?

**Comment by danmihaila** [comment]
I think we can leave it like this for the moment as it is only on Chrome and not all the time. I will move it to sprint candidates and we will return to this one later.
Pinging @yumiendo to be aware. thanks, @aalecs

**Comment by danmihaila** [comment]
I double tested in chrome and FF and for me now it is working well. I will close this one and reopened if it is the case
