### ISSUE TITLE
New Contribute Flow: change the header to “Edit Details” in edit mode

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4043]
Once dataset is submitted and user clicks on edit > change the header to “Edit Details”
To distinguish “add data” from “edit” - 1. change the header to “Edit Details” 2. change bg color to #888 and 3. “x” to #fff

**Comment by alexandru-m-g** [comment]
Here is how it would look after the change. 
@danmihaila @yumiendo 
![new_in_form](https://cloud.githubusercontent.com/assets/6586348/12889993/46d2af56-ce8a-11e5-8e88-d9533564f75a.png)
![new_add_resource](https://cloud.githubusercontent.com/assets/6586348/12889992/46cfdcfe-ce8a-11e5-9ed8-d338df93bfb1.png)
![edit](https://cloud.githubusercontent.com/assets/6586348/12889994/46d40a54-ce8a-11e5-8c7e-f2dd469b110e.png)

**Comment by yumiendo** [comment]
Hi alex - thank you for these ! 
Two things - (both css)
1. on 'add detail' page header - can we change the 'x' (close button) to white
2. on the drag/drop page at the bottom - 'supported formats' and 'any common data' etc in bold. I know i made you change to #000000 but it looks too emphasized so can we tone them down to #888888 (and keep them as bold. screen attached) 
<img width="705" alt="screen shot 2016-02-09 at 9 12 54 am" src="https://cloud.githubusercontent.com/assets/8006323/12918498/7d7ba55c-cf0d-11e5-881b-d067b008d03f.png">

**Comment by danmihaila** [comment]
@yumiendo @alexandru-m-g number 2 is related to https://github.com/OCHA-DAP/hdx-ckan/issues/4046 which I've done.
I will work on item 2, no worries.

**Comment by yumiendo** [comment]
Im sorry if this is tied to another github issue - can we make sure to add \* to the fields under resource? 
<img width="648" alt="screen shot 2016-02-09 at 9 41 12 am" src="https://cloud.githubusercontent.com/assets/8006323/12919208/0e7eb8f2-cf11-11e5-9f6a-9d0231656a72.png">

**Comment by alexandru-m-g** [comment]
@yumiendo This is in #4051. 
Also added a comment there. Making the star red is actually the complicated part. Please advise on how important that is.

**Comment by alexandru-m-g** [comment]
@yumiendo, @danmihaila: 
I've made the changes to the (X) button to make it white. But check below how it looks when you scroll down:
![scroll](https://cloud.githubusercontent.com/assets/6586348/12929448/69c82788-cf7b-11e5-8e6e-d0260b075e52.png)
Let me know if that is ok.

**Comment by yumiendo** [comment]
this is great - thank you.
