### ISSUE TITLE
New Contribute Flow: When not logged in and click on “add data” > old login screen shows

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4044]
Can we update the screen below to the newer login screen?

**Comment by danmihaila** [comment]
message displayed: In order to add data, you need to login below or register on HDX

**Comment by yumiendo** [comment]
Thanks dan for the 2 screenshots. I prefer the longer message (because its more clear) - is it possible to add the height so the bottom is not cut off?

**Comment by danmihaila** [comment]
ok. this means we will have the login widget with height bigger. is this ok?
