### ISSUE TITLE
New Contribute: Geopreview not working on 2nd resource

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4050]
Works fine on Demo (current contribute flow):  https://demo-data.hdx.rwlabs.org/dataset/cod-admin-3-4

But on Feature (new cont. flow), the second resource never previewed: https://feature-data.hdx.rwlabs.org/dataset/burundi-adm-levels-3-4

**Comment by danmihaila** [comment]
@cjhendrix can you confirm this is still a valid issue?

**Comment by cjhendrix** [comment]
Seems to be fixed:  https://data.hdx.rwlabs.org/dataset/ljksldkfjslkj  Both previewed after being created at the same time (drag and drop method).
