### ISSUE TITLE
New Contribute Flow: On initial screen, faq link should point to "What are the recommended data formats?"

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4053]
In first screen (Drag & Drop) -  faq link at the bottom
description [mandatory] - is it possible to link to ‘What are the recommended data formats?” question(ideally drawer open like screen below) under FAQ?

**Comment by danmihaila** [comment]
@aalecs do you think we can make the following change to FAQ: when adding a full url to an FAQ item ( including #anchor_or_id_of_item) to display it expanded?

**Comment by aalecs** [comment]
I added this feature for the FAQ page, the only thing to remember is that the anchor has to be of the question title div and not of the question answer div :)

(referenced the commit in another issue - 1c85f1f)
