### ISSUE TITLE
HXL Proxy: research

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4061]
- [x] call with David, Alex and Dan about HXL Proxy
- [x] research about architecture and how can it be integrated with HDX
- [ ] try to build a simple chart with data fetched via HXL Proxy

**Comment by alexandru-m-g** [comment]
## What I did:
-  Played with the HXL proxy and HXL validation
-  Wrote a simple script that (tries to) import HXLized data into the CKAN datastore and tries to guess which columns are integers based on the HXL tags ( https://bitbucket.org/agartner/hxl-2-ckan-datastore )
-  Did a small speed comparison between HXL proxy and the datastore. Results and conclusions can be found here: https://docs.google.com/spreadsheets/d/1R2KhaIMonVYkTvJJy9RKyxmMaItvsSqq3deqwAoD7J8

## Going forward: how can HDX help users with HXL data ?
1.  Can we help users to add HXL tags to their spreadsheets ?
2.  For data that is already HXLated should we  add aditional features ?
   -  as explained by David here https://docs.google.com/document/d/1YfL9vOxZHfBfoSfoALj0r3-B_FZ9PGtEgjBFVzs2PXg
   -  create a new "HXL" view: 
     -  with links to HXL JSON endpoint 
     -  links to sample filtered JSON endpoints 
     -  links to HXL view 
     -  embed table / chart ?
3.  Import HXL data into the datastore ( is it still needed ? Many different APIs )
4.  Help the user validate their data ? Autogenerate (starter) validation schemas based on HXL tags
