### ISSUE TITLE
New contribute: change default text for the resource note field

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4066]
To make the distinction between the description of the dataset and the description of the resource, I suggest we change the default text from 
`Add description`
to
`Add a note about this resource`

This also will align better with the metadata guidance page. 

![image](https://cloud.githubusercontent.com/assets/1654485/13055901/3cf9151e-d412-11e5-9c6a-a1ad92015d23.png)

**Comment by cjhendrix** [comment]
tagging @yumiendo @JavierTeran

**Comment by yumiendo** [comment]
Perhaps we can change from "Add description" to "Note - add useful note about this file" ? @JavierTeran what do you think?
