### ISSUE TITLE
CKAN collection-editing permissions too lax

### ISSUE THREAD

**Issue by davidmegginson** [OCHA-DAP/hdx-ckan#41]
When I log in as a plain user (no special privileges), I'm able to edit any collection/dataset that doesn't belong to a specific team/organization.  If I belong to a team, I can edit any dataset that belongs to the team.

We'll need to add a hook to CKAN's permissions model so that editing permissions are a bit tighter; ideally, a collection outside a team should be editable only by the uploader or an admin user, and a collection inside the team should be editable by the whole team only if the uploader says so.

**Comment by cjhendrix** [comment]
Looks like I didn't close it as I said.  Closing now.
