### ISSUE TITLE
Travis failing

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4100]
Travis is still failing. I am not sure if it is from dev or a configuration.

**Comment by teodorescuserban** [comment]
will take a look.

În joi, 18 feb. 2016 la 15:22, danmihaila notifications@github.com a
scris:

**Comment by danmihaila** [comment]
@teodorescuserban any updates on this one?

**Comment by teodorescuserban** [comment]
Not yet.

**Comment by danmihaila** [comment]
@teodorescuserban can you make this issue high priority ? tnx
