### ISSUE TITLE
New Contribute Flow: improve speed for a dataset with several resources

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4106]
On testing, I edited https://test-data.hdx.rwlabs.org/dataset/refugee-and-returnee-data which contains 5 resources and took about 10-12 seconds. 
Also, when I changed from private to public to check the activity stream I noticed some strange records:
![screen shot 2016-02-23 at 12 59 56](https://cloud.githubusercontent.com/assets/3865844/13249534/9224ded0-da2d-11e5-9825-905eaec8d6ac.png)

**Comment by alexandru-m-g** [comment]
@danmihaila Can you explain a bit more about the strange records in the activity stream ? Also, analyzing and modifying the activity stream seems to be outside the scope of the issue. 
Can we have a new ticket ? Is it for this sprint ?

**Comment by danmihaila** [comment]
@alexandru-m-g you are right: we don't need to fix the activity stream in this issue, but I thought they might be related.
The issue to be done here is to improve the speed of saving dataset.
