### ISSUE TITLE
Contribute: Autocomplete not working for resource type after a space

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4143]
Typing "zipped" returns "zipped shapefile as a choice.  This is correct.  However, typing any of the characters after "zipped"  (i.e. " shapefile"), the autocomplete does not return the result and user cannot add a file type when no results are found.

![image](https://cloud.githubusercontent.com/assets/1654485/13494905/a1d3355e-e147-11e5-9fcf-5dc3d852c583.png)

**Comment by danmihaila** [comment]
I agree, it looks to work only with 1 word. nice catch
