### ISSUE TITLE
Location Page: when a group has no datasets, the message is not customized

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4146]
An edge case, for sure.  

![image](https://cloud.githubusercontent.com/assets/1654485/13522729/8e607f9a-e1f1-11e5-9816-d79e9e0e2342.png)

**Comment by danmihaila** [comment]
@cjhendrix what message should be displayed?

**Comment by cjhendrix** [comment]
"Sorry no datasets found"  would work.

**Comment by cjhendrix** [comment]
Or if it keeps the code more consistent, "Sorry no datasets found for "Foolandia""
