### ISSUE TITLE
Contribute: on smaller screens, horizontal scrollbar has no effect

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4152]
Only tested in Chome/Win7.  

![20160311-121756_capture](https://cloud.githubusercontent.com/assets/1654485/13700798/6f4ef05e-e783-11e5-8a34-52845564aaab.gif)

**Comment by alexandru-m-g** [comment]
This is the ticket that we were talking about ( related to the contribute flow being in full-width mode )
