### ISSUE TITLE
HDX visualizations: WFP indicators on hdx url

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4154]
We created a fork of https://github.com/SimonbJohnson/hdx-wfp-indicators here: https://github.com/OCHA-DAP/hdx-wfp-indicators
We need to have a public url on test-data for the moment for visualization, e.g:
https://test-data.hdx.rwlabs.org/visualization/wfp-indicators
Test to @aalecs and pinging @teodorescuserban to support on server side

**Comment by aalecs** [comment]
@teodorescuserban I've deployed the visualisation on github.io: http://ocha-dap.github.io/hdx-wfp-indicators
Can you do the setup in nginx for test-data? Thanks!

**Comment by teodorescuserban** [comment]
Done.
Thanks for help setting this up, @aalecs

**Comment by danmihaila** [comment]
this is done
