### ISSUE TITLE
On dataset page, it would be great if clicking on organisation logo would take user to the organisation page

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#4156]
On the dataset page, and if the organisation is branded (is a custom organisation with a logo), it would be great if the logo were a link to the organisation page of the organisation that owns the dataset. Users have been observed clicking on the logo with the expectation that they will be taken to the organisation page. There is currently no action associated with clicking the organisation's logo on the dataset page.

![image](https://cloud.githubusercontent.com/assets/6885303/14564785/1373152e-02f6-11e6-8399-8cd4f086beae.png)

**Comment by danmihaila** [comment]
@yumiendo pls advice

**Comment by takavarasha** [comment]
This was mentioned by @ochadataproject during demo with user

**Comment by yumiendo** [comment]
@danmihaila pls implement this change.

**Comment by ochadataproject** [comment]
Great glad this was done :)
