### ISSUE TITLE
Map Explorer CKAN: integrate powerview extension

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4159]
Integrate powerview extension (https://github.com/OCHA-DAP/ckanext-powerview) with HDX project and keep it easy to be updated (make a short doc how to keep it updated inside HDX)

**Comment by alexandru-m-g** [comment]
@teodorescuserban @danmihaila this ticket involves changes to the server configuration

**requirements.txt** was modified to include needed dependencies for powerviews. So a `pip install -r requirements.txt` will be needed.

Also, the database tables for powerviews need to be created. 
`hdx-ckan/ckanext-powerview# paster powerview init -c /srv/prod.ini`
