### ISSUE TITLE
Map Explorer CKAN: saving a powerview

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4160]
when user clicks on "save" button it will save a powerview in db. @yumiendo  to provide final flow

**Comment by alexandru-m-g** [comment]
This involved just a bit of testing on the CKAN side. The bulk of the work is here: https://github.com/OCHA-DAP/liverpool16/issues/51

**Comment by yumiendo** [comment]
Step 1: 
<img width="979" alt="screen shot 2016-05-04 at 5 21 54 pm" src="https://cloud.githubusercontent.com/assets/8006323/15029661/949e5ac0-121c-11e6-882f-d54f18656f49.png">

please include:
1. header bar "Lake Chad Basin Crisis" + "Explore data layers below to generate interactive visualisation"
2. Save button on the header bar

**Comment by yumiendo** [comment]
Step 2:
name the visualisation (reuse modal screens)
<img width="1440" alt="screen shot 2016-05-04 at 5 19 26 pm" src="https://cloud.githubusercontent.com/assets/8006323/15029674/a6a49766-121c-11e6-97b6-dbc7786a4f16.png">

**Comment by yumiendo** [comment]
after the step 2 - people click on save > which one of the following are we doing to MVP?
a. let people copy the direct link to share + message that says your visualisation is now saved under your dashboard. (also if we can send email with the link it'd be awesome)
b. a + people can also copy link to embed their visualisation
@danmihaila  @amcguire62 ?

**Comment by yumiendo** [comment]
step 3 - after user click on save > (the page in the bg refreshes to user's visualisation page with the customised header + description)

<img width="1440" alt="screen shot 2016-05-05 at 4 50 09 pm" src="https://cloud.githubusercontent.com/assets/8006323/15056747/478a6916-12e1-11e6-90c7-44eed7abf3ea.png">

text: 
"Copy the URL below to share your visualisation with your colleagues. Anyone with this link can access your visualisation."

"Where does my visualisation go once I save? 
Your saved visualisations will be stored in your dashboard under ‘My visualisations”."
