### ISSUE TITLE
MapExplorer:  add sort order and deduplication actions

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4162]
We need to be able to replicate this recipe in order to support "taking the latest" data from a dataset.

https://proxy.hxlstandard.org/data/edit?filter01=sort&sort-tags01=%23date%2Bend&sort-reverse01=on&filter02=dedup&dedup-tags02=%23country%2Bname&url=http%3A%2F%2Fdata.hdx.rwlabs.org%2Fdataset%2F6c4260fe-35b9-4dcd-b963-babb0d49d42a%2Fresource%2F3106b05f-e171-49ac-a353-d7b56aed918f%2Fdownload%2FFTS-Appeals_v2.csv&filter01=sort&sort-tags01=%23date%2Bend&sheet=&sort-reverse01=on

**Comment by cjhendrix** [comment]
I'm asking @davidmegginson for confirmation that the deduplication filter takes the first encountered.  In testing, it appears to be the case, but we want to be sure it's reliable.

**Comment by davidmegginson** [comment]
Confirmed. For good measure, I've added that to the class documentation in libhxl-python, to make it part of the interface contract (never trust a feature that's not in the contract :) ):

```
  Removes duplicate lines from a dataset, where "duplicate" is
  optionally defined by a set of keys specified by the user. As a
  result, not all values in duplicate rows will necessarily be
  identical. The filter will always return the *first* matching row
  of a set of duplicates.
```

**Comment by danmihaila** [comment]
moving this issue to ME repo
https://github.com/OCHA-DAP/liverpool16/issues/69
