### ISSUE TITLE
Problem with label not showing when code is used by WFP

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4163]
Tagging @amcguire62 

Label shows ok on HDX:
![image](https://cloud.githubusercontent.com/assets/1654485/14822608/9d4f708a-0bcf-11e6-9775-33ba06497ac2.png)

But doesn't show on WFP's site:
![image](https://cloud.githubusercontent.com/assets/1654485/14822656/cda63020-0bcf-11e6-9cc3-5a68714f4313.png)

The same is true in FF and Chrome.

**Comment by amcguire62** [comment]
Simon wonder any chance you could look at this - if its easy or hard or point them to the solution. We dont really want to be fixing their system so at this stage i think its reasonable we point them in the right direction.

**Comment by SimonbJohnson** [comment]
@cjhendrix do you have a link to the wfp viz in the screenshot.  The link in the screenshot takes me to another vis

http://vam.wfp.org/CountryPage_indicators.aspx?iso3=YEM

**Comment by cjhendrix** [comment]
I put Simon in touch with them by email.

**Comment by aalecs** [comment]
@danmihaila - can we have the link to the vis on the WFP site ?

**Comment by cjhendrix** [comment]
I typed it from the screen cap, but it doesn't seem to use our viz any more, even after you go through the data selection process.  http://vam.wfp.org/CountryPage_indicators.aspx?iso3=YEM

Perhaps we can ignore this one for now.

**Comment by aalecs** [comment]
Closing for now :)
