### ISSUE TITLE
 Tag line on mailchimp sign up needs to be updated to match new homepage tagline.

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4169]
When we deploy new homepage (or before):

http://unocha.us2.list-manage.com/subscribe?u=83487eb1105d72ff2427e4bd7&id=6fd988326c

**Comment by danmihaila** [comment]
@cjhendrix can you give more info re this?

**Comment by cjhendrix** [comment]
Done.
