### ISSUE TITLE
Dashboard sort menu display problem

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4171]
Similar problem on prod.  Win/Chrome/no zoom.

![image](https://cloud.githubusercontent.com/assets/1654485/15077661/bf1c7b62-13af-11e6-90ac-7ee14290a27b.png)

**Comment by aalecs** [comment]
@cjhendrix I can't reproduce the issue ... there's nothing

**Comment by cjhendrix** [comment]
I can't reproduce it either.  Gremlin.
