### ISSUE TITLE
WHS: Homepage redesign - mobile

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4175]
Design and implement the changes to do the mobile features for homepage. Please use this branch and coordinate with @aalecs .
https://github.com/OCHA-DAP/hdx-ckan/tree/dev-map-explorer
More details during our SPAR call.

![homepage_v4_mob](https://cloud.githubusercontent.com/assets/3865844/15114815/788305ca-1604-11e6-9a44-4dccadc02ff2.png)
![homepage_v4_mob_menu](https://cloud.githubusercontent.com/assets/3865844/15114817/78a822e2-1604-11e6-98d1-92af23802f34.png)

**Comment by baripembo** [comment]
@yumiendo can you please provide some annotations for the mobile view -- mainly font sizes. thank you!

**Comment by yumiendo** [comment]
here is the annotated one - let me know if you have any question
 ![homepage_v4_mob_spec](https://cloud.githubusercontent.com/assets/8006323/15188281/d51669de-1772-11e6-95a1-77e5524542ef.png)
![homepage_v4_mob_menu_spec](https://cloud.githubusercontent.com/assets/8006323/15188282/d51b5ec6-1772-11e6-834a-186bbe2cfb9b.png)

**Comment by danmihaila** [comment]
@baripembo I merged the code from @aalecs and you. can you please check the carousel for mobile? thank you.

**Comment by baripembo** [comment]
sent the code update to @aalecs to integrate

**Comment by danmihaila** [comment]
@aalecs can we close this one?
