### ISSUE TITLE
New logo: remove beta

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4177]
@yumiendo pls provide the link to google drive for asset. thanks.

**Comment by yumiendo** [comment]
https://drive.google.com/file/d/0B24NBcgmV490dGJ5NlEwWmd1Vmc/view?usp=sharing
<img width="413" alt="screen shot 2016-05-09 at 9 30 46 am" src="https://cloud.githubusercontent.com/assets/8006323/15114588/a5868b14-15c8-11e6-8ad4-81147b17a156.png">

**Comment by baripembo** [comment]
@yumiendo is there also mobile version? thanks!

**Comment by yumiendo** [comment]
@baripembo 
mob version here https://drive.google.com/file/d/0B24NBcgmV490dTd1MTVHVGhabmM/view?usp=sharing

**Comment by danmihaila** [comment]
@aalecs please update our logo.
