### ISSUE TITLE
Improve text justification on dataset description

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4181]
Short lines ending in a long URL justify awkwardly.  Adding a hard return (in fact two returns are required in markdown) creates too much space between the paragraphs.   The solution would be to left justify lines below a certain percentage of the width.

![image](https://cloud.githubusercontent.com/assets/1654485/15209172/f5ebb1a6-182f-11e6-8685-d40358449ce3.png)

**Comment by aalecs** [comment]
@cjhendrix we could change the url title to something shorter like "here" or "key figgures" and have the url set on that short text, like in this screenshot:
![screen shot 2016-05-24 at 14 05 32](https://cloud.githubusercontent.com/assets/5638491/15501861/bb16cc90-21b8-11e6-85c8-c05815a9bf1c.png)

**Comment by cjhendrix** [comment]
Of course, but I'm thinking of users who may not have any markdown-fu.

**Comment by danmihaila** [comment]
Until we found a nicer fix I think we are ok as it is now. I understand now the issue, and I think users could change their text a bit. We could make a FAQ entry with recommendations.
@cjhendrix pls reopen if you still think it is a big issue.
