### ISSUE TITLE
Edit Related Item

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#419]
I am not sure if we are going to use this section, but there is no refactor of the design and the fields has no validation.
For example, for url you can enter any string...
screenshot attached
![screen shot 2014-05-27 at 15 30 42](https://cloud.githubusercontent.com/assets/3865844/3091286/f5766fb4-e59a-11e3-9f52-ccdb990f2c39.png)

**Comment by cjhendrix** [comment]
We have validation on the main URL, but not on the image URL.  I think this is sufficient for now.  Closing.
