### ISSUE TITLE
Hard refresh required after login

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4190]
1. log out
2. view an org page for an org that has private datasets  for example: https://data.humdata.org/organization/wfp
3. private datasets will not be visible (as expected)
4. log in
5. navigate back to the org page (private datasets still not visible, which has always been the behavior).  
6. refresh.  In the past, this would recognize the login and private datasets would be visible.  Now however, it does not.
7. hard refresh.  Login is recognized.

**Comment by amcguire62** [comment]
Given all our other work i think this is a priority but in the sprint following WHS

**Comment by danmihaila** [comment]
You found it 😀 this is happening because wfp has a cache. Can you reproduce it with other org?

Dan Mihaila

**Comment by danmihaila** [comment]
ping @cjhendrix 
@teodorescuserban @alexandru-m-g pls confirm we have a cache on WFP org page.

**Comment by teodorescuserban** [comment]
Yes, wfp does have a cache.

```
    expires 1m;
    proxy_cache_valid 1m;
```

First line keeps the data in browsers' cache for 1 minute.
The second line keeps the data in nginx cache (to fater serve to other clients) for 1 minute.

**Comment by danmihaila** [comment]
@teodorescuserban can you remove the cache from wfp org page? thanks

**Comment by teodorescuserban** [comment]
I have disabled the one-minute cache for WFP.
Also, I disabled the one-minute cache for Nepal earthquake page.
