### ISSUE TITLE
new posts not showing on blog front page

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4211]
I don't think this is important until after WHS.   I think this is related to caching. 

The latest post (HDX 1.0) is visible here http://docs.humdata.org/blog/
but not visible here http://docs.humdata.org/

**Comment by cjhendrix** [comment]
I've tried hard refresh and incogntio, FYI

**Comment by danmihaila** [comment]
@teodorescuserban is it cache?

**Comment by cjhendrix** [comment]
Cache must have updated.  Showing now.  Closing.
