### ISSUE TITLE
Testing: UI

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#4212]
- [x] Research Selenium vs. other options
- [x] Setting up again Selenium for automated browser testing
- [ ] dev documentation how to run local
- [x] research if/how Selenium could be integrated with docker, stag/prod servers, etc.

**Comment by alexandru-m-g** [comment]
After discussions with @aalecs it seems that we have 2 options:
-  using Selenium as we did before
-  using Protractor: 
  -  might make it easier to test angular applications
  -  actually ( in the backend it uses the Selenium WebDriver )

About running the tests on the server side or Travis:
-  we could run them headless by using XVFB ( a virtual X server )
-  we could run them headless by using phantomJS
-  run the tests on other servers ( like a Selenium cloud ) and have Travis connect to the server to trigger the start of the tests

**Comment by alexandru-m-g** [comment]
Created a small test in Selenium for map explorer. It just loads a data slice, checks that map and chart are loaded and then removes it and checks that the map and chart have disappeared: https://github.com/OCHA-DAP/hdx-ckan-selenium/commit/e0ab9eb3ed3a02414cc151c697f4070aad1e7f8b
