### ISSUE TITLE
Contribute Flow: Import file options (Google Drive and Dropbox) not working

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#4224]
The import file option for google drive and dropbox on the contribute flow are currently broken. When a user clicks on the dropbox link, a modal with following text is shown: {error: "Origin does not match any app domain"}
![image](https://cloud.githubusercontent.com/assets/6885303/15689738/6e4b9288-274e-11e6-81dc-d06b375aa881.png)

For google drive, the following error is shown:
![image](https://cloud.githubusercontent.com/assets/6885303/15689858/d4f08a3e-274e-11e6-97ce-f0226994922c.png)

**Comment by mgalex** [comment]
This was related to some configs that needed to changed in the dropbox and google accounts related to the domain change. More info in #3889

**Comment by alexandru-m-g** [comment]
This was related to some configs that needed to be changed in the dropbox and google accounts related to the domain change. More info in #3889
@danmihaila @takavarasha can you please confirm it works ok now ?

**Comment by danmihaila** [comment]
it works for me (google drive). I don't have a dropbox account to test it.

**Comment by takavarasha** [comment]
It works for google drive.
