### ISSUE TITLE
Dropbox and Google Drive choosers not set up for demo-data.humdata.org

### ISSUE THREAD

**Issue by davidmegginson** [OCHA-DAP/hdx-ckan#4231]
This is not essential for IMPACT-WCA, but if it's an easy configuration change, it would be nice to set up authorisation in the Google Drive and Dropbox APIs so that the new demo-data.humdata.org domain is accepted.  Here's what I get right now ...

Dropbox chooser: `{"error": "Origin does not match any app domain"}`

Google Drive chooser: `Error: origin_mismatch`

**Comment by teodorescuserban** [comment]
I don't know who authorised it in the first place. If it's a configuration that needs to be updated on Google and Dropbox side, I am unaware of the settings required.
ping @davidmegginson

**Comment by alexandru-m-g** [comment]
I made the changes and it now works for me. The changes are detailed in this ticket #3889. 
Please confirm that it is fixed.

**Comment by davidmegginson** [comment]
Confirmed that it now works -- thanks, @alexandru-m-g !
