### ISSUE TITLE
api/action/user_list times out on production

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#4240]
Calls to /api/action/user_list are timing out on production server.

**Comment by danmihaila** [comment]
@teodorescuserban any hint?

**Comment by teodorescuserban** [comment]
yes, nginx 60 seconds timeout.

**Comment by teodorescuserban** [comment]
On staging it takes 51 seconds so it doesn't timeout.

Too many users? no solr index? no pagination on user list?

**Comment by teodorescuserban** [comment]
The same call with a query (/api/action/user_list?q=tes) works great.

**Comment by teodorescuserban** [comment]
If you ask me, that call should not be allowed unauthenticated. Look what wealth of info delivers...

**Comment by danmihaila** [comment]
@teodorescuserban this is the default ckan api call. I will make an issue to review it and to optimize if it is ok the case.
Basically for sysadmin user it displays more information (like email).

**Comment by teodorescuserban** [comment]
Yes but it is not auth.

**Comment by danmihaila** [comment]
assigned to @teodorescuserban  to increase timeout on prod

**Comment by teodorescuserban** [comment]
Fixed as per https://github.com/OCHA-DAP/hdx-dockers/pull/8
Increasing timeout to 120 for all requests.

This fix is in prod, but NOT on staging.
New nginx image building is under way.

**Comment by teodorescuserban** [comment]
New nginx image has been generated.

**Comment by danmihaila** [comment]
@takavarasha / @mcarans  please test it on production server. it is working for me
