### ISSUE TITLE
FAQ:  last categories are not selected

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4242]
In FF on linux and Chrome on Win
1. Remove any zoom 
2. Go to FAQ.
3. Click one of the last two categories in the list at left (contact or data policy).  
4. Page scrolls but the category is not highlighted.

It seems that the first category visible on the page is what is highlighted, and for the last two categories (depending on your screen size and zoom) it is one of the earlier categories that is the first visible on the page.

![image](https://cloud.githubusercontent.com/assets/1654485/16082231/f0cf0866-3310-11e6-9a3e-c589b6a2fe99.png)

**Comment by aalecs** [comment]
@danmihaila & @cjhendrix - to fix this issue we need to add a large space at the end of the FAQ section, after the contact item, that should have a height of 80-90% of the users browser window. That's necessary so the scroll will position the last items on the top of the screen and the menu-heighlight script would function properly.
Is that acceptable? 😃

**Comment by danmihaila** [comment]
@aalecs can we have a screenshot?

**Comment by aalecs** [comment]
![screen shot 2016-06-22 at 16 38 11](https://cloud.githubusercontent.com/assets/5638491/16268607/c32c0aa8-3897-11e6-8918-47cbc84b3ac0.png)

![screen shot 2016-06-22 at 16 37 46](https://cloud.githubusercontent.com/assets/5638491/16268609/c633d686-3897-11e6-9c44-cf08f60575a5.png)

**Comment by danmihaila** [comment]
I think it looks good.
@cjhendrix @yumiendo any comments?

**Comment by danmihaila** [comment]
@aalecs what is the minimum % that is going to work well?

**Comment by aalecs** [comment]
I checked and it's about 75% for a "tall" screen :) I have 1440px height on my screen and it's ok. For smaller screens there's not a problem since the footer will be larger compared to the screen height ;)
