### ISSUE TITLE
Multiple scrollbars on contribute page

### ISSUE THREAD

**Issue by davidmegginson** [OCHA-DAP/hdx-ckan#4244]
Under Ubuntu 16.04, using Chrome Version 51.0.2704.79 (64-bit):

![Screenshot](http://www.clipular.com/c/6220009359015936.png?k=n5buYt7xk2OufJz2dkHloXO7ELo)

**Comment by davidmegginson** [comment]
Also spotted under the MS Edge browser in Win10.

**Comment by davidmegginson** [comment]
_Not_ on the demo server, so it must be a fairly-recent introduction.

**Comment by danmihaila** [comment]
@aalecs can you double check this issue? Might be related with the full page change.
