### ISSUE TITLE
How to process new organization requests?

### ISSUE THREAD

**Issue by rainorsun** [OCHA-DAP/hdx-ckan#5841]
So I have finally managed to get HDX setup for my organisation. And I am able to get onboarding emails in dev via Mailhog. My challenge is, the flow for requesting a new organisation stops at the sending an email to the Data team with details of the new organisation. 

Maybe I missed something. But I am stuck. I need an organisation to create datasets. But I can't do this unless, I setup an organisation. 

How are new requests for organisations processed? Or how can I get at least one organisation setup for my sysadmin to do more testing. 

P.S: I have tried directly editing the database and adding to the group table with "is_organization" set to true but no dice. 

I believe @takavarasha has a guide on this that is closed-source (https://humanitarian.atlassian.net/wiki/spaces/HDX/pages/42437752/How+to+Process+New+Organisation+Requests) but still waiting for access.

**Comment by takavarasha** [comment]
Please send email to hdx@un.org so we can arrange a call to better understand this issue.
