### ISSUE TITLE
Do we want to add the ability to truly delete datasets?

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#694]
Datasets are only flagged as deleted.  The URL remains unavailable and they are visible to the org/user that owns them.

**Comment by pjdufour** [comment]
Yes.  If needed to prevent accidential deletion, it could be a two step process (like termination protection in Amazon Web Services).  Permanent deletion is necessary if an organization wants to reuse a dataset url or another org wants to use the url.

**Comment by pjdufour** [comment]
+1

**Comment by danmihaila** [comment]
this is implemented: delete forever done :)
