### ISSUE TITLE
Dataset creation: long list of selected countries obscures form

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#836]
Let's discuss the preferred solution.  Probably a scroll bar.

**Comment by cjhendrix** [comment]
No one is complaining and we may be redoing this workflow.  Archiving.

**Comment by cjhendrix** [comment]
we seem to never get around to redoing this workflow, so I'm putting this back in the backlog.  We still have it with v0.10.0

**Comment by danmihaila** [comment]
not an issue anymore
