### ISSUE TITLE
Intelligent button for "Download", "Visit Page"

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#87]
The buttons for accessing a resource appear to switch depending on the type of resource.  
- Download - for files, even if linking to a file on a different site
- Visit Page - for links to external websites that are not downloadable files

We still would want the _Preview_ button to be available for files that support it. 

See http://catalog.data.gov/dataset/e3-economyenergyenvironment-introductory-video-revitalizing-american-manufacturing for an example.

**Comment by xiaoyinghu** [comment]
I have uploaded a zip file, the format is "zip". However, button is showed up as "Go to resource".

The button show as "Download" for "csv" or "xlsx" though. 

Any one has idea what's the difference?

**Comment by xiaoyinghu** [comment]
Sorry, just realized this is an closed issue. I'm going to open a new issue.
