### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by BonnieRobinson** [OCHA-DAP/hdx-ckan#92]
Recommendation to remove Help from top-level navigation (Issue #91), requires adding a help button or icon to each page, in order to implement page-specific help.

**Comment by danmihaila** [comment]
@cjhendrix do you think this is still an issue with our latest changes and FAQ page?

**Comment by cjhendrix** [comment]
Wow, that one really is ancient history.  And we did add page-specific help.  And we have faq.  Closing.
