### ISSUE TITLE
Activity Stream and Newsfeed: change to text

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#982]
Could we remove "the extra" where indicated below?  Or perhaps change it to "metadata item"?  We just need to think through everywhere it occurs to be sure it makes sense everywhere.

![image](https://cloud.githubusercontent.com/assets/1654485/3569097/d54b9632-0b39-11e4-81dd-a9ce282d2a78.png)

**Comment by danmihaila** [comment]
not an issue anymore, closing it
<img width="1440" alt="screen shot 2016-04-26 at 14 28 19" src="https://cloud.githubusercontent.com/assets/3865844/14816720/27b55cae-0bbb-11e6-8395-a475626e1af7.png">
