### ISSUE TITLE
slight difference in height (1 px) between the edit and delete buttons on org member page

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#988]
Go to the org member page for an organization in which you are "admin".
There is a slight difference in height (1 px) between the edit and delete buttons.

**Comment by cjhendrix** [comment]
No one is complaining except Alex. :) Archiving.

**Comment by danmihaila** [comment]
issue is fixed. @alexandru-m-g pls reopen if you still think it is an issue
<img width="375" alt="screen shot 2016-04-26 at 14 29 34" src="https://cloud.githubusercontent.com/assets/3865844/14816766/66d3b3e0-0bbb-11e6-879e-c8ff7749a417.png">
<img width="1440" alt="screen shot 2016-04-26 at 14 29 37" src="https://cloud.githubusercontent.com/assets/3865844/14816765/66d27c5a-0bbb-11e6-9fb0-0790f8b2e901.png">
